processed 21 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 13-40:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 15618000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 42:
//# create-checkpoint
Checkpoint created: 1

task 3, lines 44-46:
//# programmable --sender A --inputs object(1,5) 100000 object(1,1)
//> 0: iota::coin::mint<P0::fake::FAKE>(Input(0), Input(1));
//> MergeCoins(Input(2), [Result(0)]);
mutated: object(0,0), object(1,1), object(1,5)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3990000,  storage_rebate: 3990000, non_refundable_storage_fee: 0

task 4, line 48:
//# create-checkpoint
Checkpoint created: 2

task 5, lines 50-91:
//# run-graphql
Response: {
  "data": {
    "queryCoinsAtLatest": {
      "edges": [
        {
          "cursor": "IEfLYjNGkxfK3tomwA29D80kpDwgGlte7cswTZsLcM89AgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IEfLYjNGkxfK3tomwA29D80kpDwgGlte7cswTZsLcM89AgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x47cb6233469317cadeda26c00dbd0fcd24a43c201a5b5eedcb304d9b0b70cf3d",
                            "balance": {
                              "value": "100100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IH5aInS9Te5Y4hTb/coUfmfmzWe613L/d9wgP/5bi8QJAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x7e5a2274bd4dee58e214dbfdca147e67e6cd67bad772ff77dc203ffe5b8bc409",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "INDY5gvH0tPVDzkOaX7KjlrHwJKQ8+rf3PxLB8l2G0WXAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xd0d8e60bc7d2d3d50f390e697eca8e5ac7c09290f3eadfdcfc4b07c9761b4597",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x47cb6233469317cadeda26c00dbd0fcd24a43c201a5b5eedcb304d9b0b70cf3d",
                "balance": {
                  "value": "100100"
                }
              }
            }
          }
        },
        {
          "cursor": "IH5aInS9Te5Y4hTb/coUfmfmzWe613L/d9wgP/5bi8QJAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IEfLYjNGkxfK3tomwA29D80kpDwgGlte7cswTZsLcM89AgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x47cb6233469317cadeda26c00dbd0fcd24a43c201a5b5eedcb304d9b0b70cf3d",
                            "balance": {
                              "value": "100100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IH5aInS9Te5Y4hTb/coUfmfmzWe613L/d9wgP/5bi8QJAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x7e5a2274bd4dee58e214dbfdca147e67e6cd67bad772ff77dc203ffe5b8bc409",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "INDY5gvH0tPVDzkOaX7KjlrHwJKQ8+rf3PxLB8l2G0WXAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xd0d8e60bc7d2d3d50f390e697eca8e5ac7c09290f3eadfdcfc4b07c9761b4597",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x7e5a2274bd4dee58e214dbfdca147e67e6cd67bad772ff77dc203ffe5b8bc409",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        },
        {
          "cursor": "INDY5gvH0tPVDzkOaX7KjlrHwJKQ8+rf3PxLB8l2G0WXAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IEfLYjNGkxfK3tomwA29D80kpDwgGlte7cswTZsLcM89AgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x47cb6233469317cadeda26c00dbd0fcd24a43c201a5b5eedcb304d9b0b70cf3d",
                            "balance": {
                              "value": "100100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IH5aInS9Te5Y4hTb/coUfmfmzWe613L/d9wgP/5bi8QJAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x7e5a2274bd4dee58e214dbfdca147e67e6cd67bad772ff77dc203ffe5b8bc409",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "INDY5gvH0tPVDzkOaX7KjlrHwJKQ8+rf3PxLB8l2G0WXAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xd0d8e60bc7d2d3d50f390e697eca8e5ac7c09290f3eadfdcfc4b07c9761b4597",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xd0d8e60bc7d2d3d50f390e697eca8e5ac7c09290f3eadfdcfc4b07c9761b4597",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoins": {
      "coins": {
        "edges": [
          {
            "cursor": "IEfLYjNGkxfK3tomwA29D80kpDwgGlte7cswTZsLcM89AgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x47cb6233469317cadeda26c00dbd0fcd24a43c201a5b5eedcb304d9b0b70cf3d",
                  "balance": {
                    "value": "100100"
                  }
                }
              }
            }
          },
          {
            "cursor": "IH5aInS9Te5Y4hTb/coUfmfmzWe613L/d9wgP/5bi8QJAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x7e5a2274bd4dee58e214dbfdca147e67e6cd67bad772ff77dc203ffe5b8bc409",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          },
          {
            "cursor": "INDY5gvH0tPVDzkOaX7KjlrHwJKQ8+rf3PxLB8l2G0WXAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xd0d8e60bc7d2d3d50f390e697eca8e5ac7c09290f3eadfdcfc4b07c9761b4597",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 6, lines 93-134:
//# run-graphql --cursors @{obj_1_3,1}
Response: {
  "data": {
    "queryCoinsAtChkpt1": {
      "edges": [
        {
          "cursor": "IEfLYjNGkxfK3tomwA29D80kpDwgGlte7cswTZsLcM89AQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IEfLYjNGkxfK3tomwA29D80kpDwgGlte7cswTZsLcM89AQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x47cb6233469317cadeda26c00dbd0fcd24a43c201a5b5eedcb304d9b0b70cf3d",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IH5aInS9Te5Y4hTb/coUfmfmzWe613L/d9wgP/5bi8QJAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x7e5a2274bd4dee58e214dbfdca147e67e6cd67bad772ff77dc203ffe5b8bc409",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "INDY5gvH0tPVDzkOaX7KjlrHwJKQ8+rf3PxLB8l2G0WXAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xd0d8e60bc7d2d3d50f390e697eca8e5ac7c09290f3eadfdcfc4b07c9761b4597",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x47cb6233469317cadeda26c00dbd0fcd24a43c201a5b5eedcb304d9b0b70cf3d",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        },
        {
          "cursor": "IH5aInS9Te5Y4hTb/coUfmfmzWe613L/d9wgP/5bi8QJAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IEfLYjNGkxfK3tomwA29D80kpDwgGlte7cswTZsLcM89AQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x47cb6233469317cadeda26c00dbd0fcd24a43c201a5b5eedcb304d9b0b70cf3d",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IH5aInS9Te5Y4hTb/coUfmfmzWe613L/d9wgP/5bi8QJAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x7e5a2274bd4dee58e214dbfdca147e67e6cd67bad772ff77dc203ffe5b8bc409",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "INDY5gvH0tPVDzkOaX7KjlrHwJKQ8+rf3PxLB8l2G0WXAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xd0d8e60bc7d2d3d50f390e697eca8e5ac7c09290f3eadfdcfc4b07c9761b4597",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x7e5a2274bd4dee58e214dbfdca147e67e6cd67bad772ff77dc203ffe5b8bc409",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1": {
      "coins": {
        "edges": [
          {
            "cursor": "IEfLYjNGkxfK3tomwA29D80kpDwgGlte7cswTZsLcM89AQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x47cb6233469317cadeda26c00dbd0fcd24a43c201a5b5eedcb304d9b0b70cf3d",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          },
          {
            "cursor": "IH5aInS9Te5Y4hTb/coUfmfmzWe613L/d9wgP/5bi8QJAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x7e5a2274bd4dee58e214dbfdca147e67e6cd67bad772ff77dc203ffe5b8bc409",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 7, line 136:
//# transfer-object 1,2 --sender A --recipient B
mutated: object(0,0), object(1,2)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2295200,  storage_rebate: 2295200, non_refundable_storage_fee: 0

task 8, line 138:
//# transfer-object 1,3 --sender A --recipient B
mutated: object(0,0), object(1,3)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2295200,  storage_rebate: 2295200, non_refundable_storage_fee: 0

task 9, line 140:
//# create-checkpoint
Checkpoint created: 3

task 10, lines 142-195:
//# run-graphql
Response: {
  "data": {
    "queryCoins": {
      "edges": [
        {
          "cursor": "IEfLYjNGkxfK3tomwA29D80kpDwgGlte7cswTZsLcM89AwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IEfLYjNGkxfK3tomwA29D80kpDwgGlte7cswTZsLcM89AwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x47cb6233469317cadeda26c00dbd0fcd24a43c201a5b5eedcb304d9b0b70cf3d",
                            "balance": {
                              "value": "100100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x47cb6233469317cadeda26c00dbd0fcd24a43c201a5b5eedcb304d9b0b70cf3d",
                "balance": {
                  "value": "100100"
                }
              }
            }
          }
        },
        {
          "cursor": "IH5aInS9Te5Y4hTb/coUfmfmzWe613L/d9wgP/5bi8QJAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IH5aInS9Te5Y4hTb/coUfmfmzWe613L/d9wgP/5bi8QJAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x7e5a2274bd4dee58e214dbfdca147e67e6cd67bad772ff77dc203ffe5b8bc409",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "INDY5gvH0tPVDzkOaX7KjlrHwJKQ8+rf3PxLB8l2G0WXAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xd0d8e60bc7d2d3d50f390e697eca8e5ac7c09290f3eadfdcfc4b07c9761b4597",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x7e5a2274bd4dee58e214dbfdca147e67e6cd67bad772ff77dc203ffe5b8bc409",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        },
        {
          "cursor": "INDY5gvH0tPVDzkOaX7KjlrHwJKQ8+rf3PxLB8l2G0WXAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IH5aInS9Te5Y4hTb/coUfmfmzWe613L/d9wgP/5bi8QJAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x7e5a2274bd4dee58e214dbfdca147e67e6cd67bad772ff77dc203ffe5b8bc409",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "INDY5gvH0tPVDzkOaX7KjlrHwJKQ8+rf3PxLB8l2G0WXAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xd0d8e60bc7d2d3d50f390e697eca8e5ac7c09290f3eadfdcfc4b07c9761b4597",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xd0d8e60bc7d2d3d50f390e697eca8e5ac7c09290f3eadfdcfc4b07c9761b4597",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoinsA": {
      "coins": {
        "edges": [
          {
            "cursor": "IEfLYjNGkxfK3tomwA29D80kpDwgGlte7cswTZsLcM89AwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x47cb6233469317cadeda26c00dbd0fcd24a43c201a5b5eedcb304d9b0b70cf3d",
                  "balance": {
                    "value": "100100"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "addressCoinsB": {
      "coins": {
        "edges": [
          {
            "cursor": "IH5aInS9Te5Y4hTb/coUfmfmzWe613L/d9wgP/5bi8QJAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x7e5a2274bd4dee58e214dbfdca147e67e6cd67bad772ff77dc203ffe5b8bc409",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          },
          {
            "cursor": "INDY5gvH0tPVDzkOaX7KjlrHwJKQ8+rf3PxLB8l2G0WXAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xd0d8e60bc7d2d3d50f390e697eca8e5ac7c09290f3eadfdcfc4b07c9761b4597",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 12, line 199:
//# create-checkpoint
Checkpoint created: 4

task 14, line 203:
//# create-checkpoint
Checkpoint created: 5

task 16, line 207:
//# create-checkpoint
Checkpoint created: 6

task 17, lines 209-250:
//# run-graphql --cursors @{obj_1_3,1}
Response: {
  "data": {
    "queryCoinsAtChkpt1BeforeSnapshotCatchup": {
      "edges": [
        {
          "cursor": "IEfLYjNGkxfK3tomwA29D80kpDwgGlte7cswTZsLcM89AQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IEfLYjNGkxfK3tomwA29D80kpDwgGlte7cswTZsLcM89AQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x47cb6233469317cadeda26c00dbd0fcd24a43c201a5b5eedcb304d9b0b70cf3d",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IH5aInS9Te5Y4hTb/coUfmfmzWe613L/d9wgP/5bi8QJAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x7e5a2274bd4dee58e214dbfdca147e67e6cd67bad772ff77dc203ffe5b8bc409",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "INDY5gvH0tPVDzkOaX7KjlrHwJKQ8+rf3PxLB8l2G0WXAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xd0d8e60bc7d2d3d50f390e697eca8e5ac7c09290f3eadfdcfc4b07c9761b4597",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x47cb6233469317cadeda26c00dbd0fcd24a43c201a5b5eedcb304d9b0b70cf3d",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        },
        {
          "cursor": "IH5aInS9Te5Y4hTb/coUfmfmzWe613L/d9wgP/5bi8QJAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IEfLYjNGkxfK3tomwA29D80kpDwgGlte7cswTZsLcM89AQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x47cb6233469317cadeda26c00dbd0fcd24a43c201a5b5eedcb304d9b0b70cf3d",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IH5aInS9Te5Y4hTb/coUfmfmzWe613L/d9wgP/5bi8QJAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x7e5a2274bd4dee58e214dbfdca147e67e6cd67bad772ff77dc203ffe5b8bc409",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "INDY5gvH0tPVDzkOaX7KjlrHwJKQ8+rf3PxLB8l2G0WXAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xd0d8e60bc7d2d3d50f390e697eca8e5ac7c09290f3eadfdcfc4b07c9761b4597",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x7e5a2274bd4dee58e214dbfdca147e67e6cd67bad772ff77dc203ffe5b8bc409",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1BeforeSnapshotCatchup": {
      "coins": {
        "edges": [
          {
            "cursor": "IEfLYjNGkxfK3tomwA29D80kpDwgGlte7cswTZsLcM89AQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x47cb6233469317cadeda26c00dbd0fcd24a43c201a5b5eedcb304d9b0b70cf3d",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          },
          {
            "cursor": "IH5aInS9Te5Y4hTb/coUfmfmzWe613L/d9wgP/5bi8QJAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x7e5a2274bd4dee58e214dbfdca147e67e6cd67bad772ff77dc203ffe5b8bc409",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 18, line 252:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 4
Objects snapshot updated to [0 to 4)

task 19, line 254:
//# create-checkpoint
Checkpoint created: 7

task 20, lines 256-285:
//# run-graphql --cursors @{obj_1_3,1}
Response: {
  "data": null,
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "queryCoinsAtChkpt1AfterSnapshotCatchup"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
