processed 21 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 13-40:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 15618000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 42:
//# create-checkpoint
Checkpoint created: 1

task 3, lines 44-46:
//# programmable --sender A --inputs object(1,5) 100000 object(1,1)
//> 0: iota::coin::mint<P0::fake::FAKE>(Input(0), Input(1));
//> MergeCoins(Input(2), [Result(0)]);
mutated: object(0,0), object(1,1), object(1,5)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3990000,  storage_rebate: 3990000, non_refundable_storage_fee: 0

task 4, line 48:
//# create-checkpoint
Checkpoint created: 2

task 5, lines 50-91:
//# run-graphql
Response: {
  "data": {
    "queryCoinsAtLatest": {
      "edges": [
        {
          "cursor": "IDsZKzLbcXAh3RmstyQOnIXqA/Yj/BW0aQ6r2gDliBShAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDsZKzLbcXAh3RmstyQOnIXqA/Yj/BW0aQ6r2gDliBShAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3b192b32db717021dd19acb7240e9c85ea03f623fc15b4690eabda00e58814a1",
                            "balance": {
                              "value": "100300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IGQga9g7xOuVUVEoKHCTAywa/Z7AkN9NsVxeUm94niIIAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x64206bd83bc4eb95515128287093032c1afd9ec090df4db15c5e526f789e2208",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMhu1lIcewaBw6PyElD1KYy/70s4EJQmtDbbjU9+RO1PAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc86ed6521c7b0681c3a3f21250f5298cbfef4b38109426b436db8d4f7e44ed4f",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x3b192b32db717021dd19acb7240e9c85ea03f623fc15b4690eabda00e58814a1",
                "balance": {
                  "value": "100300"
                }
              }
            }
          }
        },
        {
          "cursor": "IGQga9g7xOuVUVEoKHCTAywa/Z7AkN9NsVxeUm94niIIAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDsZKzLbcXAh3RmstyQOnIXqA/Yj/BW0aQ6r2gDliBShAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3b192b32db717021dd19acb7240e9c85ea03f623fc15b4690eabda00e58814a1",
                            "balance": {
                              "value": "100300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IGQga9g7xOuVUVEoKHCTAywa/Z7AkN9NsVxeUm94niIIAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x64206bd83bc4eb95515128287093032c1afd9ec090df4db15c5e526f789e2208",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMhu1lIcewaBw6PyElD1KYy/70s4EJQmtDbbjU9+RO1PAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc86ed6521c7b0681c3a3f21250f5298cbfef4b38109426b436db8d4f7e44ed4f",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x64206bd83bc4eb95515128287093032c1afd9ec090df4db15c5e526f789e2208",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        },
        {
          "cursor": "IMhu1lIcewaBw6PyElD1KYy/70s4EJQmtDbbjU9+RO1PAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDsZKzLbcXAh3RmstyQOnIXqA/Yj/BW0aQ6r2gDliBShAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3b192b32db717021dd19acb7240e9c85ea03f623fc15b4690eabda00e58814a1",
                            "balance": {
                              "value": "100300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IGQga9g7xOuVUVEoKHCTAywa/Z7AkN9NsVxeUm94niIIAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x64206bd83bc4eb95515128287093032c1afd9ec090df4db15c5e526f789e2208",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMhu1lIcewaBw6PyElD1KYy/70s4EJQmtDbbjU9+RO1PAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc86ed6521c7b0681c3a3f21250f5298cbfef4b38109426b436db8d4f7e44ed4f",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xc86ed6521c7b0681c3a3f21250f5298cbfef4b38109426b436db8d4f7e44ed4f",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoins": {
      "coins": {
        "edges": [
          {
            "cursor": "IDsZKzLbcXAh3RmstyQOnIXqA/Yj/BW0aQ6r2gDliBShAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x3b192b32db717021dd19acb7240e9c85ea03f623fc15b4690eabda00e58814a1",
                  "balance": {
                    "value": "100300"
                  }
                }
              }
            }
          },
          {
            "cursor": "IGQga9g7xOuVUVEoKHCTAywa/Z7AkN9NsVxeUm94niIIAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x64206bd83bc4eb95515128287093032c1afd9ec090df4db15c5e526f789e2208",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          },
          {
            "cursor": "IMhu1lIcewaBw6PyElD1KYy/70s4EJQmtDbbjU9+RO1PAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xc86ed6521c7b0681c3a3f21250f5298cbfef4b38109426b436db8d4f7e44ed4f",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 6, lines 93-134:
//# run-graphql --cursors @{obj_1_3,1}
Response: {
  "data": {
    "queryCoinsAtChkpt1": {
      "edges": [
        {
          "cursor": "IDsZKzLbcXAh3RmstyQOnIXqA/Yj/BW0aQ6r2gDliBShAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDsZKzLbcXAh3RmstyQOnIXqA/Yj/BW0aQ6r2gDliBShAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3b192b32db717021dd19acb7240e9c85ea03f623fc15b4690eabda00e58814a1",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IGQga9g7xOuVUVEoKHCTAywa/Z7AkN9NsVxeUm94niIIAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x64206bd83bc4eb95515128287093032c1afd9ec090df4db15c5e526f789e2208",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMhu1lIcewaBw6PyElD1KYy/70s4EJQmtDbbjU9+RO1PAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc86ed6521c7b0681c3a3f21250f5298cbfef4b38109426b436db8d4f7e44ed4f",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x3b192b32db717021dd19acb7240e9c85ea03f623fc15b4690eabda00e58814a1",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        },
        {
          "cursor": "IGQga9g7xOuVUVEoKHCTAywa/Z7AkN9NsVxeUm94niIIAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDsZKzLbcXAh3RmstyQOnIXqA/Yj/BW0aQ6r2gDliBShAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3b192b32db717021dd19acb7240e9c85ea03f623fc15b4690eabda00e58814a1",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IGQga9g7xOuVUVEoKHCTAywa/Z7AkN9NsVxeUm94niIIAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x64206bd83bc4eb95515128287093032c1afd9ec090df4db15c5e526f789e2208",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMhu1lIcewaBw6PyElD1KYy/70s4EJQmtDbbjU9+RO1PAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc86ed6521c7b0681c3a3f21250f5298cbfef4b38109426b436db8d4f7e44ed4f",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x64206bd83bc4eb95515128287093032c1afd9ec090df4db15c5e526f789e2208",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1": {
      "coins": {
        "edges": [
          {
            "cursor": "IDsZKzLbcXAh3RmstyQOnIXqA/Yj/BW0aQ6r2gDliBShAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x3b192b32db717021dd19acb7240e9c85ea03f623fc15b4690eabda00e58814a1",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          },
          {
            "cursor": "IGQga9g7xOuVUVEoKHCTAywa/Z7AkN9NsVxeUm94niIIAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x64206bd83bc4eb95515128287093032c1afd9ec090df4db15c5e526f789e2208",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 7, line 136:
//# transfer-object 1,2 --sender A --recipient B
mutated: object(0,0), object(1,2)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2295200,  storage_rebate: 2295200, non_refundable_storage_fee: 0

task 8, line 138:
//# transfer-object 1,3 --sender A --recipient B
mutated: object(0,0), object(1,3)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2295200,  storage_rebate: 2295200, non_refundable_storage_fee: 0

task 9, line 140:
//# create-checkpoint
Checkpoint created: 3

task 10, lines 142-195:
//# run-graphql
Response: {
  "data": {
    "queryCoins": {
      "edges": [
        {
          "cursor": "IDsZKzLbcXAh3RmstyQOnIXqA/Yj/BW0aQ6r2gDliBShAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDsZKzLbcXAh3RmstyQOnIXqA/Yj/BW0aQ6r2gDliBShAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3b192b32db717021dd19acb7240e9c85ea03f623fc15b4690eabda00e58814a1",
                            "balance": {
                              "value": "100300"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x3b192b32db717021dd19acb7240e9c85ea03f623fc15b4690eabda00e58814a1",
                "balance": {
                  "value": "100300"
                }
              }
            }
          }
        },
        {
          "cursor": "IGQga9g7xOuVUVEoKHCTAywa/Z7AkN9NsVxeUm94niIIAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IGQga9g7xOuVUVEoKHCTAywa/Z7AkN9NsVxeUm94niIIAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x64206bd83bc4eb95515128287093032c1afd9ec090df4db15c5e526f789e2208",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMhu1lIcewaBw6PyElD1KYy/70s4EJQmtDbbjU9+RO1PAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc86ed6521c7b0681c3a3f21250f5298cbfef4b38109426b436db8d4f7e44ed4f",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x64206bd83bc4eb95515128287093032c1afd9ec090df4db15c5e526f789e2208",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        },
        {
          "cursor": "IMhu1lIcewaBw6PyElD1KYy/70s4EJQmtDbbjU9+RO1PAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IGQga9g7xOuVUVEoKHCTAywa/Z7AkN9NsVxeUm94niIIAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x64206bd83bc4eb95515128287093032c1afd9ec090df4db15c5e526f789e2208",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMhu1lIcewaBw6PyElD1KYy/70s4EJQmtDbbjU9+RO1PAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc86ed6521c7b0681c3a3f21250f5298cbfef4b38109426b436db8d4f7e44ed4f",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xc86ed6521c7b0681c3a3f21250f5298cbfef4b38109426b436db8d4f7e44ed4f",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoinsA": {
      "coins": {
        "edges": [
          {
            "cursor": "IDsZKzLbcXAh3RmstyQOnIXqA/Yj/BW0aQ6r2gDliBShAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x3b192b32db717021dd19acb7240e9c85ea03f623fc15b4690eabda00e58814a1",
                  "balance": {
                    "value": "100300"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "addressCoinsB": {
      "coins": {
        "edges": [
          {
            "cursor": "IGQga9g7xOuVUVEoKHCTAywa/Z7AkN9NsVxeUm94niIIAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x64206bd83bc4eb95515128287093032c1afd9ec090df4db15c5e526f789e2208",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          },
          {
            "cursor": "IMhu1lIcewaBw6PyElD1KYy/70s4EJQmtDbbjU9+RO1PAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xc86ed6521c7b0681c3a3f21250f5298cbfef4b38109426b436db8d4f7e44ed4f",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 12, line 199:
//# create-checkpoint
Checkpoint created: 4

task 14, line 203:
//# create-checkpoint
Checkpoint created: 5

task 16, line 207:
//# create-checkpoint
Checkpoint created: 6

task 17, lines 209-250:
//# run-graphql --cursors @{obj_1_3,1}
Response: {
  "data": {
    "queryCoinsAtChkpt1BeforeSnapshotCatchup": {
      "edges": [
        {
          "cursor": "IDsZKzLbcXAh3RmstyQOnIXqA/Yj/BW0aQ6r2gDliBShAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDsZKzLbcXAh3RmstyQOnIXqA/Yj/BW0aQ6r2gDliBShAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3b192b32db717021dd19acb7240e9c85ea03f623fc15b4690eabda00e58814a1",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IGQga9g7xOuVUVEoKHCTAywa/Z7AkN9NsVxeUm94niIIAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x64206bd83bc4eb95515128287093032c1afd9ec090df4db15c5e526f789e2208",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMhu1lIcewaBw6PyElD1KYy/70s4EJQmtDbbjU9+RO1PAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc86ed6521c7b0681c3a3f21250f5298cbfef4b38109426b436db8d4f7e44ed4f",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x3b192b32db717021dd19acb7240e9c85ea03f623fc15b4690eabda00e58814a1",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        },
        {
          "cursor": "IGQga9g7xOuVUVEoKHCTAywa/Z7AkN9NsVxeUm94niIIAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDsZKzLbcXAh3RmstyQOnIXqA/Yj/BW0aQ6r2gDliBShAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3b192b32db717021dd19acb7240e9c85ea03f623fc15b4690eabda00e58814a1",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IGQga9g7xOuVUVEoKHCTAywa/Z7AkN9NsVxeUm94niIIAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x64206bd83bc4eb95515128287093032c1afd9ec090df4db15c5e526f789e2208",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMhu1lIcewaBw6PyElD1KYy/70s4EJQmtDbbjU9+RO1PAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc86ed6521c7b0681c3a3f21250f5298cbfef4b38109426b436db8d4f7e44ed4f",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x64206bd83bc4eb95515128287093032c1afd9ec090df4db15c5e526f789e2208",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1BeforeSnapshotCatchup": {
      "coins": {
        "edges": [
          {
            "cursor": "IDsZKzLbcXAh3RmstyQOnIXqA/Yj/BW0aQ6r2gDliBShAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x3b192b32db717021dd19acb7240e9c85ea03f623fc15b4690eabda00e58814a1",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          },
          {
            "cursor": "IGQga9g7xOuVUVEoKHCTAywa/Z7AkN9NsVxeUm94niIIAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x64206bd83bc4eb95515128287093032c1afd9ec090df4db15c5e526f789e2208",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 18, line 252:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 4
Objects snapshot updated to [0 to 4)

task 19, line 254:
//# create-checkpoint
Checkpoint created: 7

task 20, lines 256-285:
//# run-graphql --cursors @{obj_1_3,1}
Response: {
  "data": null,
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "queryCoinsAtChkpt1AfterSnapshotCatchup"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
