processed 21 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 13-40:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 15618000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 42:
//# create-checkpoint
Checkpoint created: 1

task 3, lines 44-46:
//# programmable --sender A --inputs object(1,5) 100000 object(1,1)
//> 0: iota::coin::mint<P0::fake::FAKE>(Input(0), Input(1));
//> MergeCoins(Input(2), [Result(0)]);
mutated: object(0,0), object(1,1), object(1,5)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3990000,  storage_rebate: 3990000, non_refundable_storage_fee: 0

task 4, line 48:
//# create-checkpoint
Checkpoint created: 2

task 5, lines 50-91:
//# run-graphql
Response: {
  "data": {
    "queryCoinsAtLatest": {
      "edges": [
        {
          "cursor": "IApniwe7Z2bjgyFQCb0B9CXz4dET8IjzA12i9bRMR7/CAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IApniwe7Z2bjgyFQCb0B9CXz4dET8IjzA12i9bRMR7/CAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x0a678b07bb6766e383215009bd01f425f3e1d113f088f3035da2f5b44c47bfc2",
                            "balance": {
                              "value": "100200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKvInbcjeUbNXxlsZmlaw02PXhlQ+UuIUGdLXk9hi5gJAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xabc89db7237946cd5f196c66695ac34d8f5e1950f94b8850674b5e4f618b9809",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPSGBTtl6PcfooWqNntlxy0bgSKaP1vrFtTbW1TbPtLtAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf486053b65e8f71fa285aa367b65c72d1b81229a3f5beb16d4db5b54db3ed2ed",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x0a678b07bb6766e383215009bd01f425f3e1d113f088f3035da2f5b44c47bfc2",
                "balance": {
                  "value": "100200"
                }
              }
            }
          }
        },
        {
          "cursor": "IKvInbcjeUbNXxlsZmlaw02PXhlQ+UuIUGdLXk9hi5gJAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IApniwe7Z2bjgyFQCb0B9CXz4dET8IjzA12i9bRMR7/CAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x0a678b07bb6766e383215009bd01f425f3e1d113f088f3035da2f5b44c47bfc2",
                            "balance": {
                              "value": "100200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKvInbcjeUbNXxlsZmlaw02PXhlQ+UuIUGdLXk9hi5gJAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xabc89db7237946cd5f196c66695ac34d8f5e1950f94b8850674b5e4f618b9809",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPSGBTtl6PcfooWqNntlxy0bgSKaP1vrFtTbW1TbPtLtAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf486053b65e8f71fa285aa367b65c72d1b81229a3f5beb16d4db5b54db3ed2ed",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xabc89db7237946cd5f196c66695ac34d8f5e1950f94b8850674b5e4f618b9809",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        },
        {
          "cursor": "IPSGBTtl6PcfooWqNntlxy0bgSKaP1vrFtTbW1TbPtLtAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IApniwe7Z2bjgyFQCb0B9CXz4dET8IjzA12i9bRMR7/CAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x0a678b07bb6766e383215009bd01f425f3e1d113f088f3035da2f5b44c47bfc2",
                            "balance": {
                              "value": "100200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKvInbcjeUbNXxlsZmlaw02PXhlQ+UuIUGdLXk9hi5gJAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xabc89db7237946cd5f196c66695ac34d8f5e1950f94b8850674b5e4f618b9809",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPSGBTtl6PcfooWqNntlxy0bgSKaP1vrFtTbW1TbPtLtAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf486053b65e8f71fa285aa367b65c72d1b81229a3f5beb16d4db5b54db3ed2ed",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xf486053b65e8f71fa285aa367b65c72d1b81229a3f5beb16d4db5b54db3ed2ed",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoins": {
      "coins": {
        "edges": [
          {
            "cursor": "IApniwe7Z2bjgyFQCb0B9CXz4dET8IjzA12i9bRMR7/CAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x0a678b07bb6766e383215009bd01f425f3e1d113f088f3035da2f5b44c47bfc2",
                  "balance": {
                    "value": "100200"
                  }
                }
              }
            }
          },
          {
            "cursor": "IKvInbcjeUbNXxlsZmlaw02PXhlQ+UuIUGdLXk9hi5gJAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xabc89db7237946cd5f196c66695ac34d8f5e1950f94b8850674b5e4f618b9809",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          },
          {
            "cursor": "IPSGBTtl6PcfooWqNntlxy0bgSKaP1vrFtTbW1TbPtLtAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xf486053b65e8f71fa285aa367b65c72d1b81229a3f5beb16d4db5b54db3ed2ed",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 6, lines 93-134:
//# run-graphql --cursors @{obj_1_3,1}
Response: {
  "data": {
    "queryCoinsAtChkpt1": {
      "edges": [
        {
          "cursor": "IApniwe7Z2bjgyFQCb0B9CXz4dET8IjzA12i9bRMR7/CAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IApniwe7Z2bjgyFQCb0B9CXz4dET8IjzA12i9bRMR7/CAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x0a678b07bb6766e383215009bd01f425f3e1d113f088f3035da2f5b44c47bfc2",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKvInbcjeUbNXxlsZmlaw02PXhlQ+UuIUGdLXk9hi5gJAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xabc89db7237946cd5f196c66695ac34d8f5e1950f94b8850674b5e4f618b9809",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPSGBTtl6PcfooWqNntlxy0bgSKaP1vrFtTbW1TbPtLtAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf486053b65e8f71fa285aa367b65c72d1b81229a3f5beb16d4db5b54db3ed2ed",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x0a678b07bb6766e383215009bd01f425f3e1d113f088f3035da2f5b44c47bfc2",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        },
        {
          "cursor": "IKvInbcjeUbNXxlsZmlaw02PXhlQ+UuIUGdLXk9hi5gJAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IApniwe7Z2bjgyFQCb0B9CXz4dET8IjzA12i9bRMR7/CAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x0a678b07bb6766e383215009bd01f425f3e1d113f088f3035da2f5b44c47bfc2",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKvInbcjeUbNXxlsZmlaw02PXhlQ+UuIUGdLXk9hi5gJAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xabc89db7237946cd5f196c66695ac34d8f5e1950f94b8850674b5e4f618b9809",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPSGBTtl6PcfooWqNntlxy0bgSKaP1vrFtTbW1TbPtLtAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf486053b65e8f71fa285aa367b65c72d1b81229a3f5beb16d4db5b54db3ed2ed",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xabc89db7237946cd5f196c66695ac34d8f5e1950f94b8850674b5e4f618b9809",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1": {
      "coins": {
        "edges": [
          {
            "cursor": "IApniwe7Z2bjgyFQCb0B9CXz4dET8IjzA12i9bRMR7/CAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x0a678b07bb6766e383215009bd01f425f3e1d113f088f3035da2f5b44c47bfc2",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          },
          {
            "cursor": "IKvInbcjeUbNXxlsZmlaw02PXhlQ+UuIUGdLXk9hi5gJAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xabc89db7237946cd5f196c66695ac34d8f5e1950f94b8850674b5e4f618b9809",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 7, line 136:
//# transfer-object 1,2 --sender A --recipient B
mutated: object(0,0), object(1,2)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2295200,  storage_rebate: 2295200, non_refundable_storage_fee: 0

task 8, line 138:
//# transfer-object 1,3 --sender A --recipient B
mutated: object(0,0), object(1,3)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2295200,  storage_rebate: 2295200, non_refundable_storage_fee: 0

task 9, line 140:
//# create-checkpoint
Checkpoint created: 3

task 10, lines 142-195:
//# run-graphql
Response: {
  "data": {
    "queryCoins": {
      "edges": [
        {
          "cursor": "IApniwe7Z2bjgyFQCb0B9CXz4dET8IjzA12i9bRMR7/CAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IApniwe7Z2bjgyFQCb0B9CXz4dET8IjzA12i9bRMR7/CAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x0a678b07bb6766e383215009bd01f425f3e1d113f088f3035da2f5b44c47bfc2",
                            "balance": {
                              "value": "100200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x0a678b07bb6766e383215009bd01f425f3e1d113f088f3035da2f5b44c47bfc2",
                "balance": {
                  "value": "100200"
                }
              }
            }
          }
        },
        {
          "cursor": "IKvInbcjeUbNXxlsZmlaw02PXhlQ+UuIUGdLXk9hi5gJAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IKvInbcjeUbNXxlsZmlaw02PXhlQ+UuIUGdLXk9hi5gJAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xabc89db7237946cd5f196c66695ac34d8f5e1950f94b8850674b5e4f618b9809",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPSGBTtl6PcfooWqNntlxy0bgSKaP1vrFtTbW1TbPtLtAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf486053b65e8f71fa285aa367b65c72d1b81229a3f5beb16d4db5b54db3ed2ed",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xabc89db7237946cd5f196c66695ac34d8f5e1950f94b8850674b5e4f618b9809",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        },
        {
          "cursor": "IPSGBTtl6PcfooWqNntlxy0bgSKaP1vrFtTbW1TbPtLtAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IKvInbcjeUbNXxlsZmlaw02PXhlQ+UuIUGdLXk9hi5gJAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xabc89db7237946cd5f196c66695ac34d8f5e1950f94b8850674b5e4f618b9809",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPSGBTtl6PcfooWqNntlxy0bgSKaP1vrFtTbW1TbPtLtAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf486053b65e8f71fa285aa367b65c72d1b81229a3f5beb16d4db5b54db3ed2ed",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xf486053b65e8f71fa285aa367b65c72d1b81229a3f5beb16d4db5b54db3ed2ed",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoinsA": {
      "coins": {
        "edges": [
          {
            "cursor": "IApniwe7Z2bjgyFQCb0B9CXz4dET8IjzA12i9bRMR7/CAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x0a678b07bb6766e383215009bd01f425f3e1d113f088f3035da2f5b44c47bfc2",
                  "balance": {
                    "value": "100200"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "addressCoinsB": {
      "coins": {
        "edges": [
          {
            "cursor": "IKvInbcjeUbNXxlsZmlaw02PXhlQ+UuIUGdLXk9hi5gJAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xabc89db7237946cd5f196c66695ac34d8f5e1950f94b8850674b5e4f618b9809",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          },
          {
            "cursor": "IPSGBTtl6PcfooWqNntlxy0bgSKaP1vrFtTbW1TbPtLtAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xf486053b65e8f71fa285aa367b65c72d1b81229a3f5beb16d4db5b54db3ed2ed",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 12, line 199:
//# create-checkpoint
Checkpoint created: 4

task 14, line 203:
//# create-checkpoint
Checkpoint created: 5

task 16, line 207:
//# create-checkpoint
Checkpoint created: 6

task 17, lines 209-250:
//# run-graphql --cursors @{obj_1_3,1}
Response: {
  "data": {
    "queryCoinsAtChkpt1BeforeSnapshotCatchup": {
      "edges": [
        {
          "cursor": "IApniwe7Z2bjgyFQCb0B9CXz4dET8IjzA12i9bRMR7/CAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IApniwe7Z2bjgyFQCb0B9CXz4dET8IjzA12i9bRMR7/CAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x0a678b07bb6766e383215009bd01f425f3e1d113f088f3035da2f5b44c47bfc2",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKvInbcjeUbNXxlsZmlaw02PXhlQ+UuIUGdLXk9hi5gJAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xabc89db7237946cd5f196c66695ac34d8f5e1950f94b8850674b5e4f618b9809",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPSGBTtl6PcfooWqNntlxy0bgSKaP1vrFtTbW1TbPtLtAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf486053b65e8f71fa285aa367b65c72d1b81229a3f5beb16d4db5b54db3ed2ed",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x0a678b07bb6766e383215009bd01f425f3e1d113f088f3035da2f5b44c47bfc2",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        },
        {
          "cursor": "IKvInbcjeUbNXxlsZmlaw02PXhlQ+UuIUGdLXk9hi5gJAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IApniwe7Z2bjgyFQCb0B9CXz4dET8IjzA12i9bRMR7/CAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x0a678b07bb6766e383215009bd01f425f3e1d113f088f3035da2f5b44c47bfc2",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKvInbcjeUbNXxlsZmlaw02PXhlQ+UuIUGdLXk9hi5gJAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xabc89db7237946cd5f196c66695ac34d8f5e1950f94b8850674b5e4f618b9809",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPSGBTtl6PcfooWqNntlxy0bgSKaP1vrFtTbW1TbPtLtAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf486053b65e8f71fa285aa367b65c72d1b81229a3f5beb16d4db5b54db3ed2ed",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xabc89db7237946cd5f196c66695ac34d8f5e1950f94b8850674b5e4f618b9809",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1BeforeSnapshotCatchup": {
      "coins": {
        "edges": [
          {
            "cursor": "IApniwe7Z2bjgyFQCb0B9CXz4dET8IjzA12i9bRMR7/CAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x0a678b07bb6766e383215009bd01f425f3e1d113f088f3035da2f5b44c47bfc2",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          },
          {
            "cursor": "IKvInbcjeUbNXxlsZmlaw02PXhlQ+UuIUGdLXk9hi5gJAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xabc89db7237946cd5f196c66695ac34d8f5e1950f94b8850674b5e4f618b9809",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 18, line 252:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 4
Objects snapshot updated to [0 to 4)

task 19, line 254:
//# create-checkpoint
Checkpoint created: 7

task 20, lines 256-285:
//# run-graphql --cursors @{obj_1_3,1}
Response: {
  "data": null,
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "queryCoinsAtChkpt1AfterSnapshotCatchup"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
