processed 24 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 16-29:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 5168000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 31:
//# run Test::M1::create --args 0 @A
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 3, line 33:
//# run Test::M1::create --args 1 @A
created: object(3,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 4, line 35:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 37-65:
//# run-graphql --cursors @{obj_2_0} @{obj_3_0}
Response: {
  "data": {
    "one_of_these_will_yield_an_object": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
              },
              "json": {
                "id": "0x8bb4a0c9c0d047672fd5c53a78e33fd3b956b0c965785afd675e6e3c5673c44a",
                "value": "1"
              }
            }
          }
        ]
      }
    },
    "if_the_other_does_not": {
      "nodes": []
    }
  }
}

task 6, line 67:
//# run Test::M1::create --args 2 @A
created: object(6,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 7, line 69:
//# run Test::M1::create --args 3 @A
created: object(7,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 8, line 71:
//# create-checkpoint
Checkpoint created: 2

task 9, lines 73-101:
//# run-graphql --cursors @{obj_2_0,1} @{obj_3_0,1}
Response: {
  "data": {
    "paginating_on_checkpoint_1": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
              },
              "json": {
                "id": "0x8bb4a0c9c0d047672fd5c53a78e33fd3b956b0c965785afd675e6e3c5673c44a",
                "value": "1"
              }
            }
          }
        ]
      }
    },
    "should_not_have_more_than_one_result": {
      "nodes": []
    }
  }
}

task 10, lines 103-118:
//# run-graphql
Response: {
  "data": {
    "four_objects": {
      "objects": {
        "nodes": [
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
              },
              "json": {
                "id": "0x35bfeebbbec01a7bad7196240c9f4d9ab5fd64ac8f10a748c46b2e2ec7f1f879",
                "value": "0"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
              },
              "json": {
                "id": "0x56f099d1bcf5f3b1bbe76f20bee3921ce787fac495adec2dc3263bd1a4586a78",
                "value": "3"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
              },
              "json": {
                "id": "0x854f411f7ca63a93b00d49e2ede8dff0d25351c92a7eb931c8002f03d54b2586",
                "value": "2"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
              },
              "json": {
                "id": "0x8bb4a0c9c0d047672fd5c53a78e33fd3b956b0c965785afd675e6e3c5673c44a",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}

task 11, lines 120-145:
//# run-graphql
Response: {
  "data": {
    "objects_at_version": {
      "objects": {
        "nodes": [
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
              },
              "json": {
                "id": "0x35bfeebbbec01a7bad7196240c9f4d9ab5fd64ac8f10a748c46b2e2ec7f1f879",
                "value": "0"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
              },
              "json": {
                "id": "0x56f099d1bcf5f3b1bbe76f20bee3921ce787fac495adec2dc3263bd1a4586a78",
                "value": "3"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
              },
              "json": {
                "id": "0x854f411f7ca63a93b00d49e2ede8dff0d25351c92a7eb931c8002f03d54b2586",
                "value": "2"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
              },
              "json": {
                "id": "0x8bb4a0c9c0d047672fd5c53a78e33fd3b956b0c965785afd675e6e3c5673c44a",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}

task 12, lines 147-148:
//# programmable --sender A --inputs object(2,0) object(3,0) object(6,0) object(7,0) @B
//> TransferObjects([Input(0), Input(1), Input(2), Input(3)], Input(4))
mutated: object(0,0), object(2,0), object(3,0), object(6,0), object(7,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 6209200,  storage_rebate: 5228800, non_refundable_storage_fee: 0

task 13, line 150:
//# create-checkpoint
Checkpoint created: 3

task 14, lines 152-214:
//# run-graphql --cursors @{obj_6_0,2}
Response: {
  "data": {
    "after_obj_6_0_at_checkpoint_2": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
              },
              "json": {
                "id": "0x8bb4a0c9c0d047672fd5c53a78e33fd3b956b0c965785afd675e6e3c5673c44a",
                "value": "1"
              }
            },
            "owner_at_latest_state_has_iota_only": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x2f5a472c79ff619ce92034eb44048469551d0bf36d61cb635555fb54ef7d28e9",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
                        },
                        "json": {
                          "id": "0x35bfeebbbec01a7bad7196240c9f4d9ab5fd64ac8f10a748c46b2e2ec7f1f879",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
                        },
                        "json": {
                          "id": "0x56f099d1bcf5f3b1bbe76f20bee3921ce787fac495adec2dc3263bd1a4586a78",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
                        },
                        "json": {
                          "id": "0x854f411f7ca63a93b00d49e2ede8dff0d25351c92a7eb931c8002f03d54b2586",
                          "value": "2"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
                        },
                        "json": {
                          "id": "0x8bb4a0c9c0d047672fd5c53a78e33fd3b956b0c965785afd675e6e3c5673c44a",
                          "value": "1"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "before_obj_6_0_at_checkpoint_2": {
      "nodes": [
        {
          "version": 3,
          "asMoveObject": {
            "contents": {
              "type": {
                "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
              },
              "json": {
                "id": "0x35bfeebbbec01a7bad7196240c9f4d9ab5fd64ac8f10a748c46b2e2ec7f1f879",
                "value": "0"
              }
            },
            "note_that_owner_result_should_reflect_latest_state": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x2f5a472c79ff619ce92034eb44048469551d0bf36d61cb635555fb54ef7d28e9",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
                        },
                        "json": {
                          "id": "0x35bfeebbbec01a7bad7196240c9f4d9ab5fd64ac8f10a748c46b2e2ec7f1f879",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
                        },
                        "json": {
                          "id": "0x56f099d1bcf5f3b1bbe76f20bee3921ce787fac495adec2dc3263bd1a4586a78",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
                        },
                        "json": {
                          "id": "0x854f411f7ca63a93b00d49e2ede8dff0d25351c92a7eb931c8002f03d54b2586",
                          "value": "2"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
                        },
                        "json": {
                          "id": "0x8bb4a0c9c0d047672fd5c53a78e33fd3b956b0c965785afd675e6e3c5673c44a",
                          "value": "1"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        {
          "version": 6,
          "asMoveObject": {
            "contents": {
              "type": {
                "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
              },
              "json": {
                "id": "0x56f099d1bcf5f3b1bbe76f20bee3921ce787fac495adec2dc3263bd1a4586a78",
                "value": "3"
              }
            },
            "note_that_owner_result_should_reflect_latest_state": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x2f5a472c79ff619ce92034eb44048469551d0bf36d61cb635555fb54ef7d28e9",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
                        },
                        "json": {
                          "id": "0x35bfeebbbec01a7bad7196240c9f4d9ab5fd64ac8f10a748c46b2e2ec7f1f879",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
                        },
                        "json": {
                          "id": "0x56f099d1bcf5f3b1bbe76f20bee3921ce787fac495adec2dc3263bd1a4586a78",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
                        },
                        "json": {
                          "id": "0x854f411f7ca63a93b00d49e2ede8dff0d25351c92a7eb931c8002f03d54b2586",
                          "value": "2"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
                        },
                        "json": {
                          "id": "0x8bb4a0c9c0d047672fd5c53a78e33fd3b956b0c965785afd675e6e3c5673c44a",
                          "value": "1"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      ]
    }
  }
}

task 16, line 218:
//# create-checkpoint
Checkpoint created: 4

task 18, line 222:
//# create-checkpoint
Checkpoint created: 5

task 19, line 224:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 4
Objects snapshot updated to [0 to 4)

task 20, line 226:
//# create-checkpoint
Checkpoint created: 6

task 21, lines 228-243:
//# run-graphql --cursors @{obj_6_0,2}
Response: {
  "data": null,
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "before_obj_6_0_at_checkpoint_2"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 22, lines 245-261:
//# run-graphql
Response: {
  "data": {
    "owned_by_address_b_latest": {
      "objects": {
        "nodes": [
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
              },
              "json": {
                "id": "0x35bfeebbbec01a7bad7196240c9f4d9ab5fd64ac8f10a748c46b2e2ec7f1f879",
                "value": "0"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
              },
              "json": {
                "id": "0x56f099d1bcf5f3b1bbe76f20bee3921ce787fac495adec2dc3263bd1a4586a78",
                "value": "3"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
              },
              "json": {
                "id": "0x854f411f7ca63a93b00d49e2ede8dff0d25351c92a7eb931c8002f03d54b2586",
                "value": "2"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
              },
              "json": {
                "id": "0x8bb4a0c9c0d047672fd5c53a78e33fd3b956b0c965785afd675e6e3c5673c44a",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}

task 23, lines 263-289:
//# run-graphql
Response: {
  "data": {
    "objects_at_version": {
      "objects": {
        "nodes": [
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
              },
              "json": {
                "id": "0x35bfeebbbec01a7bad7196240c9f4d9ab5fd64ac8f10a748c46b2e2ec7f1f879",
                "value": "0"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
              },
              "json": {
                "id": "0x56f099d1bcf5f3b1bbe76f20bee3921ce787fac495adec2dc3263bd1a4586a78",
                "value": "3"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
              },
              "json": {
                "id": "0x854f411f7ca63a93b00d49e2ede8dff0d25351c92a7eb931c8002f03d54b2586",
                "value": "2"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x10a7c5e744d9e2ab7868f8afb4caf6b0cc281fcedb4deb2a2a8916de0804b4b4::M1::Object"
              },
              "json": {
                "id": "0x8bb4a0c9c0d047672fd5c53a78e33fd3b956b0c965785afd675e6e3c5673c44a",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}
