processed 24 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 16-29:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 5168000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 31:
//# run Test::M1::create --args 0 @A
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 3, line 33:
//# run Test::M1::create --args 1 @A
created: object(3,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 4, line 35:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 37-65:
//# run-graphql --cursors @{obj_2_0} @{obj_3_0}
Response: {
  "data": {
    "one_of_these_will_yield_an_object": {
      "objects": {
        "nodes": []
      }
    },
    "if_the_other_does_not": {
      "nodes": [
        {
          "version": 3,
          "asMoveObject": {
            "contents": {
              "type": {
                "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
              },
              "json": {
                "id": "0xdd67e054858f57688c65b59242f068712d6694eb8c5ed268ee5e0e3eca87916c",
                "value": "0"
              }
            }
          }
        }
      ]
    }
  }
}

task 6, line 67:
//# run Test::M1::create --args 2 @A
created: object(6,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 7, line 69:
//# run Test::M1::create --args 3 @A
created: object(7,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 8, line 71:
//# create-checkpoint
Checkpoint created: 2

task 9, lines 73-101:
//# run-graphql --cursors @{obj_2_0,1} @{obj_3_0,1}
Response: {
  "data": {
    "paginating_on_checkpoint_1": {
      "objects": {
        "nodes": []
      }
    },
    "should_not_have_more_than_one_result": {
      "nodes": [
        {
          "version": 3,
          "asMoveObject": {
            "contents": {
              "type": {
                "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
              },
              "json": {
                "id": "0xdd67e054858f57688c65b59242f068712d6694eb8c5ed268ee5e0e3eca87916c",
                "value": "0"
              }
            }
          }
        }
      ]
    }
  }
}

task 10, lines 103-118:
//# run-graphql
Response: {
  "data": {
    "four_objects": {
      "objects": {
        "nodes": [
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
              },
              "json": {
                "id": "0x2d0328a478bd46eb9465e13518d000a8251099cd80401460c6b9368e02391c92",
                "value": "3"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
              },
              "json": {
                "id": "0xda7c39dd781c0a6360f059991e54653077b309bd90f8d6a64aebc6085d00fb6f",
                "value": "1"
              }
            }
          },
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
              },
              "json": {
                "id": "0xdd67e054858f57688c65b59242f068712d6694eb8c5ed268ee5e0e3eca87916c",
                "value": "0"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
              },
              "json": {
                "id": "0xf4b99dd80986192f93a818a90884b0e6847d089659242800a57ab8d37e2a3647",
                "value": "2"
              }
            }
          }
        ]
      }
    }
  }
}

task 11, lines 120-145:
//# run-graphql
Response: {
  "data": {
    "objects_at_version": {
      "objects": {
        "nodes": [
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
              },
              "json": {
                "id": "0x2d0328a478bd46eb9465e13518d000a8251099cd80401460c6b9368e02391c92",
                "value": "3"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
              },
              "json": {
                "id": "0xda7c39dd781c0a6360f059991e54653077b309bd90f8d6a64aebc6085d00fb6f",
                "value": "1"
              }
            }
          },
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
              },
              "json": {
                "id": "0xdd67e054858f57688c65b59242f068712d6694eb8c5ed268ee5e0e3eca87916c",
                "value": "0"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
              },
              "json": {
                "id": "0xf4b99dd80986192f93a818a90884b0e6847d089659242800a57ab8d37e2a3647",
                "value": "2"
              }
            }
          }
        ]
      }
    }
  }
}

task 12, lines 147-148:
//# programmable --sender A --inputs object(2,0) object(3,0) object(6,0) object(7,0) @B
//> TransferObjects([Input(0), Input(1), Input(2), Input(3)], Input(4))
mutated: object(0,0), object(2,0), object(3,0), object(6,0), object(7,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 6209200,  storage_rebate: 5228800, non_refundable_storage_fee: 0

task 13, line 150:
//# create-checkpoint
Checkpoint created: 3

task 14, lines 152-214:
//# run-graphql --cursors @{obj_6_0,2}
Response: {
  "data": {
    "after_obj_6_0_at_checkpoint_2": {
      "objects": {
        "nodes": []
      }
    },
    "before_obj_6_0_at_checkpoint_2": {
      "nodes": [
        {
          "version": 6,
          "asMoveObject": {
            "contents": {
              "type": {
                "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
              },
              "json": {
                "id": "0x2d0328a478bd46eb9465e13518d000a8251099cd80401460c6b9368e02391c92",
                "value": "3"
              }
            },
            "note_that_owner_result_should_reflect_latest_state": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
                        },
                        "json": {
                          "id": "0x2d0328a478bd46eb9465e13518d000a8251099cd80401460c6b9368e02391c92",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0xaa66189454be24a5b1fb153c611a2054fc24944c8c4c5302a61abd9693ef09ee",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
                        },
                        "json": {
                          "id": "0xda7c39dd781c0a6360f059991e54653077b309bd90f8d6a64aebc6085d00fb6f",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
                        },
                        "json": {
                          "id": "0xdd67e054858f57688c65b59242f068712d6694eb8c5ed268ee5e0e3eca87916c",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
                        },
                        "json": {
                          "id": "0xf4b99dd80986192f93a818a90884b0e6847d089659242800a57ab8d37e2a3647",
                          "value": "2"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        {
          "version": 4,
          "asMoveObject": {
            "contents": {
              "type": {
                "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
              },
              "json": {
                "id": "0xda7c39dd781c0a6360f059991e54653077b309bd90f8d6a64aebc6085d00fb6f",
                "value": "1"
              }
            },
            "note_that_owner_result_should_reflect_latest_state": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
                        },
                        "json": {
                          "id": "0x2d0328a478bd46eb9465e13518d000a8251099cd80401460c6b9368e02391c92",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0xaa66189454be24a5b1fb153c611a2054fc24944c8c4c5302a61abd9693ef09ee",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
                        },
                        "json": {
                          "id": "0xda7c39dd781c0a6360f059991e54653077b309bd90f8d6a64aebc6085d00fb6f",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
                        },
                        "json": {
                          "id": "0xdd67e054858f57688c65b59242f068712d6694eb8c5ed268ee5e0e3eca87916c",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
                        },
                        "json": {
                          "id": "0xf4b99dd80986192f93a818a90884b0e6847d089659242800a57ab8d37e2a3647",
                          "value": "2"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        {
          "version": 3,
          "asMoveObject": {
            "contents": {
              "type": {
                "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
              },
              "json": {
                "id": "0xdd67e054858f57688c65b59242f068712d6694eb8c5ed268ee5e0e3eca87916c",
                "value": "0"
              }
            },
            "note_that_owner_result_should_reflect_latest_state": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
                        },
                        "json": {
                          "id": "0x2d0328a478bd46eb9465e13518d000a8251099cd80401460c6b9368e02391c92",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0xaa66189454be24a5b1fb153c611a2054fc24944c8c4c5302a61abd9693ef09ee",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
                        },
                        "json": {
                          "id": "0xda7c39dd781c0a6360f059991e54653077b309bd90f8d6a64aebc6085d00fb6f",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
                        },
                        "json": {
                          "id": "0xdd67e054858f57688c65b59242f068712d6694eb8c5ed268ee5e0e3eca87916c",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
                        },
                        "json": {
                          "id": "0xf4b99dd80986192f93a818a90884b0e6847d089659242800a57ab8d37e2a3647",
                          "value": "2"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      ]
    }
  }
}

task 16, line 218:
//# create-checkpoint
Checkpoint created: 4

task 18, line 222:
//# create-checkpoint
Checkpoint created: 5

task 19, line 224:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 4
Objects snapshot updated to [0 to 4)

task 20, line 226:
//# create-checkpoint
Checkpoint created: 6

task 21, lines 228-243:
//# run-graphql --cursors @{obj_6_0,2}
Response: {
  "data": null,
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "before_obj_6_0_at_checkpoint_2"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 22, lines 245-261:
//# run-graphql
Response: {
  "data": {
    "owned_by_address_b_latest": {
      "objects": {
        "nodes": [
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
              },
              "json": {
                "id": "0x2d0328a478bd46eb9465e13518d000a8251099cd80401460c6b9368e02391c92",
                "value": "3"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
              },
              "json": {
                "id": "0xda7c39dd781c0a6360f059991e54653077b309bd90f8d6a64aebc6085d00fb6f",
                "value": "1"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
              },
              "json": {
                "id": "0xdd67e054858f57688c65b59242f068712d6694eb8c5ed268ee5e0e3eca87916c",
                "value": "0"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
              },
              "json": {
                "id": "0xf4b99dd80986192f93a818a90884b0e6847d089659242800a57ab8d37e2a3647",
                "value": "2"
              }
            }
          }
        ]
      }
    }
  }
}

task 23, lines 263-289:
//# run-graphql
Response: {
  "data": {
    "objects_at_version": {
      "objects": {
        "nodes": [
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
              },
              "json": {
                "id": "0x2d0328a478bd46eb9465e13518d000a8251099cd80401460c6b9368e02391c92",
                "value": "3"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
              },
              "json": {
                "id": "0xda7c39dd781c0a6360f059991e54653077b309bd90f8d6a64aebc6085d00fb6f",
                "value": "1"
              }
            }
          },
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
              },
              "json": {
                "id": "0xdd67e054858f57688c65b59242f068712d6694eb8c5ed268ee5e0e3eca87916c",
                "value": "0"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xe36e6d5323bc2639cf0ffe5824ea11c104760faf5923a942572a3b6059b0b59a::M1::Object"
              },
              "json": {
                "id": "0xf4b99dd80986192f93a818a90884b0e6847d089659242800a57ab8d37e2a3647",
                "value": "2"
              }
            }
          }
        ]
      }
    }
  }
}
