processed 15 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 11-28:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5456800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 30:
//# run Test::M1::create --args 0 @A
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 32:
//# run Test::M1::create --args 1 @A
created: object(3,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, line 34:
//# run Test::M1::update --sender A --args 100 object(2,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 1314800, non_refundable_storage_fee: 0

task 5, line 36:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 38-66:
//# run-graphql --cursors @{obj_3_0}
Response: {
  "data": {
    "after_obj_3_0": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xdbd3874f697cb23170911d06d51afbe2283a9f3a7913ff75efd0970739be23a5::M1::Object"
              },
              "json": {
                "id": "0x6a9b1e030a848ced050b917485d45f772a0db2fea720fd4b14a5b3efe1bfffc8",
                "value": "100"
              }
            }
          }
        ]
      }
    },
    "before_obj_3_0": {
      "objects": {
        "nodes": []
      }
    }
  }
}

task 7, line 68:
//# run Test::M1::update --sender A --args 200 object(2,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 8, line 70:
//# create-checkpoint
Checkpoint created: 2

task 9, lines 72-101:
//# run-graphql --cursors @{obj_3_0,1}
Response: {
  "data": {
    "after_obj_3_0_chkpt_1": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xdbd3874f697cb23170911d06d51afbe2283a9f3a7913ff75efd0970739be23a5::M1::Object"
              },
              "json": {
                "id": "0x6a9b1e030a848ced050b917485d45f772a0db2fea720fd4b14a5b3efe1bfffc8",
                "value": "100"
              }
            }
          }
        ]
      }
    },
    "before_obj_3_0_chkpt_1": {
      "objects": {
        "nodes": []
      }
    }
  }
}

task 10, lines 103-178:
//# run-graphql --cursors @{obj_3_0,2}
Response: {
  "data": {
    "address": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xdbd3874f697cb23170911d06d51afbe2283a9f3a7913ff75efd0970739be23a5::M1::Object"
              },
              "json": {
                "id": "0x5b0082f0f59dfc89c9d09e3f1099e1ee9b80e9e7c25192f97126ae36f30f4254",
                "value": "1"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xdbd3874f697cb23170911d06d51afbe2283a9f3a7913ff75efd0970739be23a5::M1::Object"
              },
              "json": {
                "id": "0x6a9b1e030a848ced050b917485d45f772a0db2fea720fd4b14a5b3efe1bfffc8",
                "value": "200"
              }
            }
          }
        ]
      }
    },
    "after_obj_3_0_chkpt_2": {
      "consistent_with_above": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xdbd3874f697cb23170911d06d51afbe2283a9f3a7913ff75efd0970739be23a5::M1::Object"
              },
              "json": {
                "id": "0x6a9b1e030a848ced050b917485d45f772a0db2fea720fd4b14a5b3efe1bfffc8",
                "value": "200"
              }
            },
            "owner": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xdbd3874f697cb23170911d06d51afbe2283a9f3a7913ff75efd0970739be23a5::M1::Object"
                        },
                        "json": {
                          "id": "0x5b0082f0f59dfc89c9d09e3f1099e1ee9b80e9e7c25192f97126ae36f30f4254",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xdbd3874f697cb23170911d06d51afbe2283a9f3a7913ff75efd0970739be23a5::M1::Object"
                        },
                        "json": {
                          "id": "0x6a9b1e030a848ced050b917485d45f772a0db2fea720fd4b14a5b3efe1bfffc8",
                          "value": "200"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "before_obj_3_0_chkpt_2": {
      "consistent_with_above": {
        "nodes": []
      }
    }
  }
}

task 11, line 180:
//# run Test::M1::update --sender A --args 300 object(3,0)
mutated: object(0,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 12, line 182:
//# create-checkpoint
Checkpoint created: 3

task 13, lines 184-247:
//# run-graphql --cursors @{obj_3_0,2}
Response: {
  "data": {
    "after_obj_3_0_chkpt_2": {
      "objects": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xdbd3874f697cb23170911d06d51afbe2283a9f3a7913ff75efd0970739be23a5::M1::Object"
              },
              "json": {
                "id": "0x6a9b1e030a848ced050b917485d45f772a0db2fea720fd4b14a5b3efe1bfffc8",
                "value": "200"
              }
            },
            "this_should_differ": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xdbd3874f697cb23170911d06d51afbe2283a9f3a7913ff75efd0970739be23a5::M1::Object"
                        },
                        "json": {
                          "id": "0x5b0082f0f59dfc89c9d09e3f1099e1ee9b80e9e7c25192f97126ae36f30f4254",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xdbd3874f697cb23170911d06d51afbe2283a9f3a7913ff75efd0970739be23a5::M1::Object"
                        },
                        "json": {
                          "id": "0x6a9b1e030a848ced050b917485d45f772a0db2fea720fd4b14a5b3efe1bfffc8",
                          "value": "200"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "before_obj_3_0_chkpt_2": {
      "objects": {
        "nodes": []
      }
    }
  }
}

task 14, lines 249-324:
//# run-graphql --cursors @{obj_3_0,3}
Response: {
  "data": {
    "address": {
      "objects": {
        "nodes": [
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xdbd3874f697cb23170911d06d51afbe2283a9f3a7913ff75efd0970739be23a5::M1::Object"
              },
              "json": {
                "id": "0x5b0082f0f59dfc89c9d09e3f1099e1ee9b80e9e7c25192f97126ae36f30f4254",
                "value": "300"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xdbd3874f697cb23170911d06d51afbe2283a9f3a7913ff75efd0970739be23a5::M1::Object"
              },
              "json": {
                "id": "0x6a9b1e030a848ced050b917485d45f772a0db2fea720fd4b14a5b3efe1bfffc8",
                "value": "200"
              }
            }
          }
        ]
      }
    },
    "after_obj_3_0_chkpt_3": {
      "consistent_with_above": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xdbd3874f697cb23170911d06d51afbe2283a9f3a7913ff75efd0970739be23a5::M1::Object"
              },
              "json": {
                "id": "0x6a9b1e030a848ced050b917485d45f772a0db2fea720fd4b14a5b3efe1bfffc8",
                "value": "200"
              }
            },
            "owner": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xdbd3874f697cb23170911d06d51afbe2283a9f3a7913ff75efd0970739be23a5::M1::Object"
                        },
                        "json": {
                          "id": "0x5b0082f0f59dfc89c9d09e3f1099e1ee9b80e9e7c25192f97126ae36f30f4254",
                          "value": "300"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xdbd3874f697cb23170911d06d51afbe2283a9f3a7913ff75efd0970739be23a5::M1::Object"
                        },
                        "json": {
                          "id": "0x6a9b1e030a848ced050b917485d45f772a0db2fea720fd4b14a5b3efe1bfffc8",
                          "value": "200"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "before_obj_3_0_chkpt_3": {
      "consistent_with_above": {
        "nodes": []
      }
    }
  }
}
