processed 17 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 18-35:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 5472000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 37-38:
//# programmable --sender A --inputs 0 1 @A
//> 0: Test::M1::create(Input(0), Input(2));
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 40:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 42-45:
//# programmable --sender A --inputs object(2,0) 100 2 3 @A
//> Test::M1::set_value(Input(0), Input(1));
//> Test::M1::create(Input(2), Input(4));
//> Test::M1::create(Input(3), Input(4));
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 4902000,  storage_rebate: 2287600, non_refundable_storage_fee: 0

task 5, line 47:
//# create-checkpoint
Checkpoint created: 2

task 6, lines 49-53:
//# programmable --sender A --inputs object(2,0) 200 4 5 6 @A
//> Test::M1::set_value(Input(0), Input(1));
//> Test::M1::create(Input(2), Input(5));
//> Test::M1::create(Input(3), Input(5));
//> Test::M1::create(Input(4), Input(5));
created: object(6,0), object(6,1), object(6,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 6209200,  storage_rebate: 2287600, non_refundable_storage_fee: 0

task 7, line 55:
//# create-checkpoint
Checkpoint created: 3

task 9, line 59:
//# create-checkpoint
Checkpoint created: 4

task 10, lines 61-135:
//# run-graphql
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x1457a25e59dd95037988d1623acefa4ea3ed3aeaaf5233566b32c6f20419a028",
                "value": "5"
              },
              "type": {
                "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x20e682e9bd64d57e2b9184ef69c11af67e1b92cb4295c51bf23ee9533f128cf7",
                "value": "200"
              },
              "type": {
                "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x2d8288b42428e037f480d70ac52b163a6431bc84858823cf18a40d05047cddb0",
                "value": "6"
              },
              "type": {
                "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xd4b20eb98f5c3714c708e35473bcee3e75ffc863d17fb0042915191624d76776",
                "value": "4"
              },
              "type": {
                "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xdc7a601e37bef86cb0009a0d5d2928aad82195410365760ce3af99ba796ccf93",
                "value": "2"
              },
              "type": {
                "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xffe2c100374e1a53f93cd6d37087ec6db3d95628912104be12dc2b63b95e31ea",
                "value": "3"
              },
              "type": {
                "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects_consistent_with_address_at_latest_checkpoint_4": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1457a25e59dd95037988d1623acefa4ea3ed3aeaaf5233566b32c6f20419a028",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x20e682e9bd64d57e2b9184ef69c11af67e1b92cb4295c51bf23ee9533f128cf7",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x2d8288b42428e037f480d70ac52b163a6431bc84858823cf18a40d05047cddb0",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd4b20eb98f5c3714c708e35473bcee3e75ffc863d17fb0042915191624d76776",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xdc7a601e37bef86cb0009a0d5d2928aad82195410365760ce3af99ba796ccf93",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xffe2c100374e1a53f93cd6d37087ec6db3d95628912104be12dc2b63b95e31ea",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1457a25e59dd95037988d1623acefa4ea3ed3aeaaf5233566b32c6f20419a028",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x20e682e9bd64d57e2b9184ef69c11af67e1b92cb4295c51bf23ee9533f128cf7",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x2d8288b42428e037f480d70ac52b163a6431bc84858823cf18a40d05047cddb0",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd4b20eb98f5c3714c708e35473bcee3e75ffc863d17fb0042915191624d76776",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xdc7a601e37bef86cb0009a0d5d2928aad82195410365760ce3af99ba796ccf93",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xffe2c100374e1a53f93cd6d37087ec6db3d95628912104be12dc2b63b95e31ea",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x9f6cd415c08be09b382dbcdc2471d69edd135d72693ada29700678293a249db6",
                        "balance": {
                          "value": "299999993098000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x1457a25e59dd95037988d1623acefa4ea3ed3aeaaf5233566b32c6f20419a028",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x20e682e9bd64d57e2b9184ef69c11af67e1b92cb4295c51bf23ee9533f128cf7",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x2d8288b42428e037f480d70ac52b163a6431bc84858823cf18a40d05047cddb0",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xd4b20eb98f5c3714c708e35473bcee3e75ffc863d17fb0042915191624d76776",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xdc7a601e37bef86cb0009a0d5d2928aad82195410365760ce3af99ba796ccf93",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xffe2c100374e1a53f93cd6d37087ec6db3d95628912104be12dc2b63b95e31ea",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 11, lines 137-181:
//# run-graphql
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1457a25e59dd95037988d1623acefa4ea3ed3aeaaf5233566b32c6f20419a028",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x20e682e9bd64d57e2b9184ef69c11af67e1b92cb4295c51bf23ee9533f128cf7",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x2d8288b42428e037f480d70ac52b163a6431bc84858823cf18a40d05047cddb0",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd4b20eb98f5c3714c708e35473bcee3e75ffc863d17fb0042915191624d76776",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xdc7a601e37bef86cb0009a0d5d2928aad82195410365760ce3af99ba796ccf93",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xffe2c100374e1a53f93cd6d37087ec6db3d95628912104be12dc2b63b95e31ea",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1457a25e59dd95037988d1623acefa4ea3ed3aeaaf5233566b32c6f20419a028",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x20e682e9bd64d57e2b9184ef69c11af67e1b92cb4295c51bf23ee9533f128cf7",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x2d8288b42428e037f480d70ac52b163a6431bc84858823cf18a40d05047cddb0",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd4b20eb98f5c3714c708e35473bcee3e75ffc863d17fb0042915191624d76776",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xdc7a601e37bef86cb0009a0d5d2928aad82195410365760ce3af99ba796ccf93",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xffe2c100374e1a53f93cd6d37087ec6db3d95628912104be12dc2b63b95e31ea",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x9f6cd415c08be09b382dbcdc2471d69edd135d72693ada29700678293a249db6",
                        "balance": {
                          "value": "300000000000000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1457a25e59dd95037988d1623acefa4ea3ed3aeaaf5233566b32c6f20419a028",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x20e682e9bd64d57e2b9184ef69c11af67e1b92cb4295c51bf23ee9533f128cf7",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x2d8288b42428e037f480d70ac52b163a6431bc84858823cf18a40d05047cddb0",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd4b20eb98f5c3714c708e35473bcee3e75ffc863d17fb0042915191624d76776",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xdc7a601e37bef86cb0009a0d5d2928aad82195410365760ce3af99ba796ccf93",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xffe2c100374e1a53f93cd6d37087ec6db3d95628912104be12dc2b63b95e31ea",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1457a25e59dd95037988d1623acefa4ea3ed3aeaaf5233566b32c6f20419a028",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x20e682e9bd64d57e2b9184ef69c11af67e1b92cb4295c51bf23ee9533f128cf7",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x2d8288b42428e037f480d70ac52b163a6431bc84858823cf18a40d05047cddb0",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd4b20eb98f5c3714c708e35473bcee3e75ffc863d17fb0042915191624d76776",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xdc7a601e37bef86cb0009a0d5d2928aad82195410365760ce3af99ba796ccf93",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xffe2c100374e1a53f93cd6d37087ec6db3d95628912104be12dc2b63b95e31ea",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x9f6cd415c08be09b382dbcdc2471d69edd135d72693ada29700678293a249db6",
                        "balance": {
                          "value": "299999996712400"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1457a25e59dd95037988d1623acefa4ea3ed3aeaaf5233566b32c6f20419a028",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x20e682e9bd64d57e2b9184ef69c11af67e1b92cb4295c51bf23ee9533f128cf7",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x2d8288b42428e037f480d70ac52b163a6431bc84858823cf18a40d05047cddb0",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd4b20eb98f5c3714c708e35473bcee3e75ffc863d17fb0042915191624d76776",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xdc7a601e37bef86cb0009a0d5d2928aad82195410365760ce3af99ba796ccf93",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xffe2c100374e1a53f93cd6d37087ec6db3d95628912104be12dc2b63b95e31ea",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1457a25e59dd95037988d1623acefa4ea3ed3aeaaf5233566b32c6f20419a028",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x20e682e9bd64d57e2b9184ef69c11af67e1b92cb4295c51bf23ee9533f128cf7",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x2d8288b42428e037f480d70ac52b163a6431bc84858823cf18a40d05047cddb0",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd4b20eb98f5c3714c708e35473bcee3e75ffc863d17fb0042915191624d76776",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xdc7a601e37bef86cb0009a0d5d2928aad82195410365760ce3af99ba796ccf93",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xffe2c100374e1a53f93cd6d37087ec6db3d95628912104be12dc2b63b95e31ea",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x9f6cd415c08be09b382dbcdc2471d69edd135d72693ada29700678293a249db6",
                        "balance": {
                          "value": "299999993098000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 12, line 183:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 3
Objects snapshot updated to [0 to 3)

task 13, line 185:
//# create-checkpoint
Checkpoint created: 5

task 14, lines 187-261:
//# run-graphql
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x1457a25e59dd95037988d1623acefa4ea3ed3aeaaf5233566b32c6f20419a028",
                "value": "5"
              },
              "type": {
                "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x20e682e9bd64d57e2b9184ef69c11af67e1b92cb4295c51bf23ee9533f128cf7",
                "value": "200"
              },
              "type": {
                "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x2d8288b42428e037f480d70ac52b163a6431bc84858823cf18a40d05047cddb0",
                "value": "6"
              },
              "type": {
                "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xd4b20eb98f5c3714c708e35473bcee3e75ffc863d17fb0042915191624d76776",
                "value": "4"
              },
              "type": {
                "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xdc7a601e37bef86cb0009a0d5d2928aad82195410365760ce3af99ba796ccf93",
                "value": "2"
              },
              "type": {
                "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xffe2c100374e1a53f93cd6d37087ec6db3d95628912104be12dc2b63b95e31ea",
                "value": "3"
              },
              "type": {
                "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1457a25e59dd95037988d1623acefa4ea3ed3aeaaf5233566b32c6f20419a028",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x20e682e9bd64d57e2b9184ef69c11af67e1b92cb4295c51bf23ee9533f128cf7",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x2d8288b42428e037f480d70ac52b163a6431bc84858823cf18a40d05047cddb0",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd4b20eb98f5c3714c708e35473bcee3e75ffc863d17fb0042915191624d76776",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xdc7a601e37bef86cb0009a0d5d2928aad82195410365760ce3af99ba796ccf93",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xffe2c100374e1a53f93cd6d37087ec6db3d95628912104be12dc2b63b95e31ea",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1457a25e59dd95037988d1623acefa4ea3ed3aeaaf5233566b32c6f20419a028",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x20e682e9bd64d57e2b9184ef69c11af67e1b92cb4295c51bf23ee9533f128cf7",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x2d8288b42428e037f480d70ac52b163a6431bc84858823cf18a40d05047cddb0",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd4b20eb98f5c3714c708e35473bcee3e75ffc863d17fb0042915191624d76776",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xdc7a601e37bef86cb0009a0d5d2928aad82195410365760ce3af99ba796ccf93",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xffe2c100374e1a53f93cd6d37087ec6db3d95628912104be12dc2b63b95e31ea",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x9f6cd415c08be09b382dbcdc2471d69edd135d72693ada29700678293a249db6",
                        "balance": {
                          "value": "299999993098000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x1457a25e59dd95037988d1623acefa4ea3ed3aeaaf5233566b32c6f20419a028",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x20e682e9bd64d57e2b9184ef69c11af67e1b92cb4295c51bf23ee9533f128cf7",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x2d8288b42428e037f480d70ac52b163a6431bc84858823cf18a40d05047cddb0",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xd4b20eb98f5c3714c708e35473bcee3e75ffc863d17fb0042915191624d76776",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xdc7a601e37bef86cb0009a0d5d2928aad82195410365760ce3af99ba796ccf93",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xffe2c100374e1a53f93cd6d37087ec6db3d95628912104be12dc2b63b95e31ea",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 15, line 263:
//# create-checkpoint
Checkpoint created: 6

task 16, lines 265-300:
//# run-graphql
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1457a25e59dd95037988d1623acefa4ea3ed3aeaaf5233566b32c6f20419a028",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x20e682e9bd64d57e2b9184ef69c11af67e1b92cb4295c51bf23ee9533f128cf7",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x2d8288b42428e037f480d70ac52b163a6431bc84858823cf18a40d05047cddb0",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd4b20eb98f5c3714c708e35473bcee3e75ffc863d17fb0042915191624d76776",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xdc7a601e37bef86cb0009a0d5d2928aad82195410365760ce3af99ba796ccf93",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xffe2c100374e1a53f93cd6d37087ec6db3d95628912104be12dc2b63b95e31ea",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1457a25e59dd95037988d1623acefa4ea3ed3aeaaf5233566b32c6f20419a028",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x20e682e9bd64d57e2b9184ef69c11af67e1b92cb4295c51bf23ee9533f128cf7",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x2d8288b42428e037f480d70ac52b163a6431bc84858823cf18a40d05047cddb0",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd4b20eb98f5c3714c708e35473bcee3e75ffc863d17fb0042915191624d76776",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xdc7a601e37bef86cb0009a0d5d2928aad82195410365760ce3af99ba796ccf93",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xffe2c100374e1a53f93cd6d37087ec6db3d95628912104be12dc2b63b95e31ea",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1457a25e59dd95037988d1623acefa4ea3ed3aeaaf5233566b32c6f20419a028",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x20e682e9bd64d57e2b9184ef69c11af67e1b92cb4295c51bf23ee9533f128cf7",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x2d8288b42428e037f480d70ac52b163a6431bc84858823cf18a40d05047cddb0",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd4b20eb98f5c3714c708e35473bcee3e75ffc863d17fb0042915191624d76776",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xdc7a601e37bef86cb0009a0d5d2928aad82195410365760ce3af99ba796ccf93",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xffe2c100374e1a53f93cd6d37087ec6db3d95628912104be12dc2b63b95e31ea",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1457a25e59dd95037988d1623acefa4ea3ed3aeaaf5233566b32c6f20419a028",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x20e682e9bd64d57e2b9184ef69c11af67e1b92cb4295c51bf23ee9533f128cf7",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x2d8288b42428e037f480d70ac52b163a6431bc84858823cf18a40d05047cddb0",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd4b20eb98f5c3714c708e35473bcee3e75ffc863d17fb0042915191624d76776",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xdc7a601e37bef86cb0009a0d5d2928aad82195410365760ce3af99ba796ccf93",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xffe2c100374e1a53f93cd6d37087ec6db3d95628912104be12dc2b63b95e31ea",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1457a25e59dd95037988d1623acefa4ea3ed3aeaaf5233566b32c6f20419a028",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x20e682e9bd64d57e2b9184ef69c11af67e1b92cb4295c51bf23ee9533f128cf7",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x2d8288b42428e037f480d70ac52b163a6431bc84858823cf18a40d05047cddb0",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd4b20eb98f5c3714c708e35473bcee3e75ffc863d17fb0042915191624d76776",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xdc7a601e37bef86cb0009a0d5d2928aad82195410365760ce3af99ba796ccf93",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xffe2c100374e1a53f93cd6d37087ec6db3d95628912104be12dc2b63b95e31ea",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1457a25e59dd95037988d1623acefa4ea3ed3aeaaf5233566b32c6f20419a028",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x20e682e9bd64d57e2b9184ef69c11af67e1b92cb4295c51bf23ee9533f128cf7",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x2d8288b42428e037f480d70ac52b163a6431bc84858823cf18a40d05047cddb0",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd4b20eb98f5c3714c708e35473bcee3e75ffc863d17fb0042915191624d76776",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xdc7a601e37bef86cb0009a0d5d2928aad82195410365760ce3af99ba796ccf93",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xffe2c100374e1a53f93cd6d37087ec6db3d95628912104be12dc2b63b95e31ea",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x89f4878c607cda08a8c7e8364507a8800574457a6101a928e5f731bdc4952962::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}
