processed 17 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 18-35:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5472000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 37-38:
//# programmable --sender A --inputs 0 1 @A
//> 0: Test::M1::create(Input(0), Input(2));
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 40:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 42-45:
//# programmable --sender A --inputs object(2,0) 100 2 3 @A
//> Test::M1::set_value(Input(0), Input(1));
//> Test::M1::create(Input(2), Input(4));
//> Test::M1::create(Input(3), Input(4));
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 4902000,  storage_rebate: 2287600, non_refundable_storage_fee: 0

task 5, line 47:
//# create-checkpoint
Checkpoint created: 2

task 6, lines 49-53:
//# programmable --sender A --inputs object(2,0) 200 4 5 6 @A
//> Test::M1::set_value(Input(0), Input(1));
//> Test::M1::create(Input(2), Input(5));
//> Test::M1::create(Input(3), Input(5));
//> Test::M1::create(Input(4), Input(5));
created: object(6,0), object(6,1), object(6,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6209200,  storage_rebate: 2287600, non_refundable_storage_fee: 0

task 7, line 55:
//# create-checkpoint
Checkpoint created: 3

task 9, line 59:
//# create-checkpoint
Checkpoint created: 4

task 10, lines 61-135:
//# run-graphql
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x14bc1e5036aa044b3590a0c09341dcd32f30e987a3ec91affdc6cfa680e99eb6",
                "value": "6"
              },
              "type": {
                "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x5c883187065c40e92b5fe0dd61c2304af04e9c4a488c9bfbb1f89d8c753ea3b7",
                "value": "200"
              },
              "type": {
                "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x6eb328790f1ef77b75c32bbde7abff6b9c93663d18b600205099427b1a7f2dfc",
                "value": "4"
              },
              "type": {
                "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xe3eb48f919c79555cf4b2b4ad06ee1894fc02854480456ef40862e1ea5279110",
                "value": "5"
              },
              "type": {
                "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xeb23e417185201e49fbde749f10866de6aa85410cc23f3d20045df50cd2f96f5",
                "value": "3"
              },
              "type": {
                "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xef64c2fde2bf43ec25f80eba4fbf15b6c91e47ba98fb34f7d8efc04b51f33607",
                "value": "2"
              },
              "type": {
                "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects_consistent_with_address_at_latest_checkpoint_4": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x14bc1e5036aa044b3590a0c09341dcd32f30e987a3ec91affdc6cfa680e99eb6",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5c883187065c40e92b5fe0dd61c2304af04e9c4a488c9bfbb1f89d8c753ea3b7",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6eb328790f1ef77b75c32bbde7abff6b9c93663d18b600205099427b1a7f2dfc",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xe3eb48f919c79555cf4b2b4ad06ee1894fc02854480456ef40862e1ea5279110",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xeb23e417185201e49fbde749f10866de6aa85410cc23f3d20045df50cd2f96f5",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xef64c2fde2bf43ec25f80eba4fbf15b6c91e47ba98fb34f7d8efc04b51f33607",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x14bc1e5036aa044b3590a0c09341dcd32f30e987a3ec91affdc6cfa680e99eb6",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5c883187065c40e92b5fe0dd61c2304af04e9c4a488c9bfbb1f89d8c753ea3b7",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6eb328790f1ef77b75c32bbde7abff6b9c93663d18b600205099427b1a7f2dfc",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xe3eb48f919c79555cf4b2b4ad06ee1894fc02854480456ef40862e1ea5279110",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xeb23e417185201e49fbde749f10866de6aa85410cc23f3d20045df50cd2f96f5",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xef64c2fde2bf43ec25f80eba4fbf15b6c91e47ba98fb34f7d8efc04b51f33607",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x8cc2a7bc18cb7b94bcd1dbd6e3acc7db8b447cfedbff284c230bf5c3423dafb8",
                        "balance": {
                          "value": "299999993098000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x14bc1e5036aa044b3590a0c09341dcd32f30e987a3ec91affdc6cfa680e99eb6",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x5c883187065c40e92b5fe0dd61c2304af04e9c4a488c9bfbb1f89d8c753ea3b7",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x6eb328790f1ef77b75c32bbde7abff6b9c93663d18b600205099427b1a7f2dfc",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xe3eb48f919c79555cf4b2b4ad06ee1894fc02854480456ef40862e1ea5279110",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xeb23e417185201e49fbde749f10866de6aa85410cc23f3d20045df50cd2f96f5",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xef64c2fde2bf43ec25f80eba4fbf15b6c91e47ba98fb34f7d8efc04b51f33607",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 11, lines 137-181:
//# run-graphql
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x14bc1e5036aa044b3590a0c09341dcd32f30e987a3ec91affdc6cfa680e99eb6",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5c883187065c40e92b5fe0dd61c2304af04e9c4a488c9bfbb1f89d8c753ea3b7",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6eb328790f1ef77b75c32bbde7abff6b9c93663d18b600205099427b1a7f2dfc",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xe3eb48f919c79555cf4b2b4ad06ee1894fc02854480456ef40862e1ea5279110",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xeb23e417185201e49fbde749f10866de6aa85410cc23f3d20045df50cd2f96f5",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xef64c2fde2bf43ec25f80eba4fbf15b6c91e47ba98fb34f7d8efc04b51f33607",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x14bc1e5036aa044b3590a0c09341dcd32f30e987a3ec91affdc6cfa680e99eb6",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5c883187065c40e92b5fe0dd61c2304af04e9c4a488c9bfbb1f89d8c753ea3b7",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6eb328790f1ef77b75c32bbde7abff6b9c93663d18b600205099427b1a7f2dfc",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xe3eb48f919c79555cf4b2b4ad06ee1894fc02854480456ef40862e1ea5279110",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xeb23e417185201e49fbde749f10866de6aa85410cc23f3d20045df50cd2f96f5",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xef64c2fde2bf43ec25f80eba4fbf15b6c91e47ba98fb34f7d8efc04b51f33607",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x8cc2a7bc18cb7b94bcd1dbd6e3acc7db8b447cfedbff284c230bf5c3423dafb8",
                        "balance": {
                          "value": "300000000000000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x14bc1e5036aa044b3590a0c09341dcd32f30e987a3ec91affdc6cfa680e99eb6",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5c883187065c40e92b5fe0dd61c2304af04e9c4a488c9bfbb1f89d8c753ea3b7",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6eb328790f1ef77b75c32bbde7abff6b9c93663d18b600205099427b1a7f2dfc",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xe3eb48f919c79555cf4b2b4ad06ee1894fc02854480456ef40862e1ea5279110",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xeb23e417185201e49fbde749f10866de6aa85410cc23f3d20045df50cd2f96f5",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xef64c2fde2bf43ec25f80eba4fbf15b6c91e47ba98fb34f7d8efc04b51f33607",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x14bc1e5036aa044b3590a0c09341dcd32f30e987a3ec91affdc6cfa680e99eb6",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5c883187065c40e92b5fe0dd61c2304af04e9c4a488c9bfbb1f89d8c753ea3b7",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6eb328790f1ef77b75c32bbde7abff6b9c93663d18b600205099427b1a7f2dfc",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xe3eb48f919c79555cf4b2b4ad06ee1894fc02854480456ef40862e1ea5279110",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xeb23e417185201e49fbde749f10866de6aa85410cc23f3d20045df50cd2f96f5",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xef64c2fde2bf43ec25f80eba4fbf15b6c91e47ba98fb34f7d8efc04b51f33607",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x8cc2a7bc18cb7b94bcd1dbd6e3acc7db8b447cfedbff284c230bf5c3423dafb8",
                        "balance": {
                          "value": "299999996712400"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x14bc1e5036aa044b3590a0c09341dcd32f30e987a3ec91affdc6cfa680e99eb6",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5c883187065c40e92b5fe0dd61c2304af04e9c4a488c9bfbb1f89d8c753ea3b7",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6eb328790f1ef77b75c32bbde7abff6b9c93663d18b600205099427b1a7f2dfc",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xe3eb48f919c79555cf4b2b4ad06ee1894fc02854480456ef40862e1ea5279110",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xeb23e417185201e49fbde749f10866de6aa85410cc23f3d20045df50cd2f96f5",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xef64c2fde2bf43ec25f80eba4fbf15b6c91e47ba98fb34f7d8efc04b51f33607",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x14bc1e5036aa044b3590a0c09341dcd32f30e987a3ec91affdc6cfa680e99eb6",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5c883187065c40e92b5fe0dd61c2304af04e9c4a488c9bfbb1f89d8c753ea3b7",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6eb328790f1ef77b75c32bbde7abff6b9c93663d18b600205099427b1a7f2dfc",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xe3eb48f919c79555cf4b2b4ad06ee1894fc02854480456ef40862e1ea5279110",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xeb23e417185201e49fbde749f10866de6aa85410cc23f3d20045df50cd2f96f5",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xef64c2fde2bf43ec25f80eba4fbf15b6c91e47ba98fb34f7d8efc04b51f33607",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x8cc2a7bc18cb7b94bcd1dbd6e3acc7db8b447cfedbff284c230bf5c3423dafb8",
                        "balance": {
                          "value": "299999993098000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 12, line 183:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 3
Objects snapshot updated to [0 to 3)

task 13, line 185:
//# create-checkpoint
Checkpoint created: 5

task 14, lines 187-261:
//# run-graphql
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x14bc1e5036aa044b3590a0c09341dcd32f30e987a3ec91affdc6cfa680e99eb6",
                "value": "6"
              },
              "type": {
                "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x5c883187065c40e92b5fe0dd61c2304af04e9c4a488c9bfbb1f89d8c753ea3b7",
                "value": "200"
              },
              "type": {
                "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x6eb328790f1ef77b75c32bbde7abff6b9c93663d18b600205099427b1a7f2dfc",
                "value": "4"
              },
              "type": {
                "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xe3eb48f919c79555cf4b2b4ad06ee1894fc02854480456ef40862e1ea5279110",
                "value": "5"
              },
              "type": {
                "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xeb23e417185201e49fbde749f10866de6aa85410cc23f3d20045df50cd2f96f5",
                "value": "3"
              },
              "type": {
                "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xef64c2fde2bf43ec25f80eba4fbf15b6c91e47ba98fb34f7d8efc04b51f33607",
                "value": "2"
              },
              "type": {
                "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x14bc1e5036aa044b3590a0c09341dcd32f30e987a3ec91affdc6cfa680e99eb6",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5c883187065c40e92b5fe0dd61c2304af04e9c4a488c9bfbb1f89d8c753ea3b7",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6eb328790f1ef77b75c32bbde7abff6b9c93663d18b600205099427b1a7f2dfc",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xe3eb48f919c79555cf4b2b4ad06ee1894fc02854480456ef40862e1ea5279110",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xeb23e417185201e49fbde749f10866de6aa85410cc23f3d20045df50cd2f96f5",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xef64c2fde2bf43ec25f80eba4fbf15b6c91e47ba98fb34f7d8efc04b51f33607",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x14bc1e5036aa044b3590a0c09341dcd32f30e987a3ec91affdc6cfa680e99eb6",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5c883187065c40e92b5fe0dd61c2304af04e9c4a488c9bfbb1f89d8c753ea3b7",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6eb328790f1ef77b75c32bbde7abff6b9c93663d18b600205099427b1a7f2dfc",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xe3eb48f919c79555cf4b2b4ad06ee1894fc02854480456ef40862e1ea5279110",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xeb23e417185201e49fbde749f10866de6aa85410cc23f3d20045df50cd2f96f5",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xef64c2fde2bf43ec25f80eba4fbf15b6c91e47ba98fb34f7d8efc04b51f33607",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x8cc2a7bc18cb7b94bcd1dbd6e3acc7db8b447cfedbff284c230bf5c3423dafb8",
                        "balance": {
                          "value": "299999993098000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x14bc1e5036aa044b3590a0c09341dcd32f30e987a3ec91affdc6cfa680e99eb6",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x5c883187065c40e92b5fe0dd61c2304af04e9c4a488c9bfbb1f89d8c753ea3b7",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x6eb328790f1ef77b75c32bbde7abff6b9c93663d18b600205099427b1a7f2dfc",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xe3eb48f919c79555cf4b2b4ad06ee1894fc02854480456ef40862e1ea5279110",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xeb23e417185201e49fbde749f10866de6aa85410cc23f3d20045df50cd2f96f5",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xef64c2fde2bf43ec25f80eba4fbf15b6c91e47ba98fb34f7d8efc04b51f33607",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 15, line 263:
//# create-checkpoint
Checkpoint created: 6

task 16, lines 265-300:
//# run-graphql
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x14bc1e5036aa044b3590a0c09341dcd32f30e987a3ec91affdc6cfa680e99eb6",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5c883187065c40e92b5fe0dd61c2304af04e9c4a488c9bfbb1f89d8c753ea3b7",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6eb328790f1ef77b75c32bbde7abff6b9c93663d18b600205099427b1a7f2dfc",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xe3eb48f919c79555cf4b2b4ad06ee1894fc02854480456ef40862e1ea5279110",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xeb23e417185201e49fbde749f10866de6aa85410cc23f3d20045df50cd2f96f5",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xef64c2fde2bf43ec25f80eba4fbf15b6c91e47ba98fb34f7d8efc04b51f33607",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x14bc1e5036aa044b3590a0c09341dcd32f30e987a3ec91affdc6cfa680e99eb6",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5c883187065c40e92b5fe0dd61c2304af04e9c4a488c9bfbb1f89d8c753ea3b7",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6eb328790f1ef77b75c32bbde7abff6b9c93663d18b600205099427b1a7f2dfc",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xe3eb48f919c79555cf4b2b4ad06ee1894fc02854480456ef40862e1ea5279110",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xeb23e417185201e49fbde749f10866de6aa85410cc23f3d20045df50cd2f96f5",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xef64c2fde2bf43ec25f80eba4fbf15b6c91e47ba98fb34f7d8efc04b51f33607",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x14bc1e5036aa044b3590a0c09341dcd32f30e987a3ec91affdc6cfa680e99eb6",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5c883187065c40e92b5fe0dd61c2304af04e9c4a488c9bfbb1f89d8c753ea3b7",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6eb328790f1ef77b75c32bbde7abff6b9c93663d18b600205099427b1a7f2dfc",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xe3eb48f919c79555cf4b2b4ad06ee1894fc02854480456ef40862e1ea5279110",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xeb23e417185201e49fbde749f10866de6aa85410cc23f3d20045df50cd2f96f5",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xef64c2fde2bf43ec25f80eba4fbf15b6c91e47ba98fb34f7d8efc04b51f33607",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x14bc1e5036aa044b3590a0c09341dcd32f30e987a3ec91affdc6cfa680e99eb6",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5c883187065c40e92b5fe0dd61c2304af04e9c4a488c9bfbb1f89d8c753ea3b7",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6eb328790f1ef77b75c32bbde7abff6b9c93663d18b600205099427b1a7f2dfc",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xe3eb48f919c79555cf4b2b4ad06ee1894fc02854480456ef40862e1ea5279110",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xeb23e417185201e49fbde749f10866de6aa85410cc23f3d20045df50cd2f96f5",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xef64c2fde2bf43ec25f80eba4fbf15b6c91e47ba98fb34f7d8efc04b51f33607",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x14bc1e5036aa044b3590a0c09341dcd32f30e987a3ec91affdc6cfa680e99eb6",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5c883187065c40e92b5fe0dd61c2304af04e9c4a488c9bfbb1f89d8c753ea3b7",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6eb328790f1ef77b75c32bbde7abff6b9c93663d18b600205099427b1a7f2dfc",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xe3eb48f919c79555cf4b2b4ad06ee1894fc02854480456ef40862e1ea5279110",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xeb23e417185201e49fbde749f10866de6aa85410cc23f3d20045df50cd2f96f5",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xef64c2fde2bf43ec25f80eba4fbf15b6c91e47ba98fb34f7d8efc04b51f33607",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x14bc1e5036aa044b3590a0c09341dcd32f30e987a3ec91affdc6cfa680e99eb6",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5c883187065c40e92b5fe0dd61c2304af04e9c4a488c9bfbb1f89d8c753ea3b7",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6eb328790f1ef77b75c32bbde7abff6b9c93663d18b600205099427b1a7f2dfc",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xe3eb48f919c79555cf4b2b4ad06ee1894fc02854480456ef40862e1ea5279110",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xeb23e417185201e49fbde749f10866de6aa85410cc23f3d20045df50cd2f96f5",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xef64c2fde2bf43ec25f80eba4fbf15b6c91e47ba98fb34f7d8efc04b51f33607",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x8ab51ad3c073bb1dba1f677d34a33768a2609bc3a436d5e938ea585068c6be39::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}
