processed 17 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 18-35:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 5472000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 37-38:
//# programmable --sender A --inputs 0 1 @A
//> 0: Test::M1::create(Input(0), Input(2));
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 40:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 42-45:
//# programmable --sender A --inputs object(2,0) 100 2 3 @A
//> Test::M1::set_value(Input(0), Input(1));
//> Test::M1::create(Input(2), Input(4));
//> Test::M1::create(Input(3), Input(4));
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 4902000,  storage_rebate: 2287600, non_refundable_storage_fee: 0

task 5, line 47:
//# create-checkpoint
Checkpoint created: 2

task 6, lines 49-53:
//# programmable --sender A --inputs object(2,0) 200 4 5 6 @A
//> Test::M1::set_value(Input(0), Input(1));
//> Test::M1::create(Input(2), Input(5));
//> Test::M1::create(Input(3), Input(5));
//> Test::M1::create(Input(4), Input(5));
created: object(6,0), object(6,1), object(6,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 6209200,  storage_rebate: 2287600, non_refundable_storage_fee: 0

task 7, line 55:
//# create-checkpoint
Checkpoint created: 3

task 9, line 59:
//# create-checkpoint
Checkpoint created: 4

task 10, lines 61-135:
//# run-graphql
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x051f15e7e12a0e680f0bc403d2d5125a4369179e3fb3256d1492661d4966bbe6",
                "value": "2"
              },
              "type": {
                "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x595b2ed1af2a32c880890647d3e212a9c923d735931ea3ad825e13988bbd3a5d",
                "value": "5"
              },
              "type": {
                "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x604602d3ea69836ce8c3853ae3b411058493ae97df1da58df14303d1bdd17c1d",
                "value": "3"
              },
              "type": {
                "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x74a2b330346be080ba35945b1c01b18f146c18fd7aaf7df95769cc13152b95ba",
                "value": "200"
              },
              "type": {
                "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xc0e64e1f8e84d7a123da1e330eee459e7fa214e9a3b9c9cd8bab236f15a247ce",
                "value": "6"
              },
              "type": {
                "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xfb4ed916e9c5074bd038c8508f187a94c2c649947cdf5b217871361793fd7768",
                "value": "4"
              },
              "type": {
                "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects_consistent_with_address_at_latest_checkpoint_4": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x051f15e7e12a0e680f0bc403d2d5125a4369179e3fb3256d1492661d4966bbe6",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x595b2ed1af2a32c880890647d3e212a9c923d735931ea3ad825e13988bbd3a5d",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x604602d3ea69836ce8c3853ae3b411058493ae97df1da58df14303d1bdd17c1d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x74a2b330346be080ba35945b1c01b18f146c18fd7aaf7df95769cc13152b95ba",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc0e64e1f8e84d7a123da1e330eee459e7fa214e9a3b9c9cd8bab236f15a247ce",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xfb4ed916e9c5074bd038c8508f187a94c2c649947cdf5b217871361793fd7768",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x051f15e7e12a0e680f0bc403d2d5125a4369179e3fb3256d1492661d4966bbe6",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x595b2ed1af2a32c880890647d3e212a9c923d735931ea3ad825e13988bbd3a5d",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x604602d3ea69836ce8c3853ae3b411058493ae97df1da58df14303d1bdd17c1d",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x74a2b330346be080ba35945b1c01b18f146c18fd7aaf7df95769cc13152b95ba",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc0e64e1f8e84d7a123da1e330eee459e7fa214e9a3b9c9cd8bab236f15a247ce",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xfb4ed916e9c5074bd038c8508f187a94c2c649947cdf5b217871361793fd7768",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x87e51e75eb63e04449579999c798027b7a8db435a1c122b28defda29027bb075",
                        "balance": {
                          "value": "299999993098000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x051f15e7e12a0e680f0bc403d2d5125a4369179e3fb3256d1492661d4966bbe6",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x595b2ed1af2a32c880890647d3e212a9c923d735931ea3ad825e13988bbd3a5d",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x604602d3ea69836ce8c3853ae3b411058493ae97df1da58df14303d1bdd17c1d",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x74a2b330346be080ba35945b1c01b18f146c18fd7aaf7df95769cc13152b95ba",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xc0e64e1f8e84d7a123da1e330eee459e7fa214e9a3b9c9cd8bab236f15a247ce",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xfb4ed916e9c5074bd038c8508f187a94c2c649947cdf5b217871361793fd7768",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 11, lines 137-181:
//# run-graphql
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x051f15e7e12a0e680f0bc403d2d5125a4369179e3fb3256d1492661d4966bbe6",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x595b2ed1af2a32c880890647d3e212a9c923d735931ea3ad825e13988bbd3a5d",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x604602d3ea69836ce8c3853ae3b411058493ae97df1da58df14303d1bdd17c1d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x74a2b330346be080ba35945b1c01b18f146c18fd7aaf7df95769cc13152b95ba",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc0e64e1f8e84d7a123da1e330eee459e7fa214e9a3b9c9cd8bab236f15a247ce",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xfb4ed916e9c5074bd038c8508f187a94c2c649947cdf5b217871361793fd7768",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x051f15e7e12a0e680f0bc403d2d5125a4369179e3fb3256d1492661d4966bbe6",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x595b2ed1af2a32c880890647d3e212a9c923d735931ea3ad825e13988bbd3a5d",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x604602d3ea69836ce8c3853ae3b411058493ae97df1da58df14303d1bdd17c1d",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x74a2b330346be080ba35945b1c01b18f146c18fd7aaf7df95769cc13152b95ba",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc0e64e1f8e84d7a123da1e330eee459e7fa214e9a3b9c9cd8bab236f15a247ce",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xfb4ed916e9c5074bd038c8508f187a94c2c649947cdf5b217871361793fd7768",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x87e51e75eb63e04449579999c798027b7a8db435a1c122b28defda29027bb075",
                        "balance": {
                          "value": "300000000000000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x051f15e7e12a0e680f0bc403d2d5125a4369179e3fb3256d1492661d4966bbe6",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x595b2ed1af2a32c880890647d3e212a9c923d735931ea3ad825e13988bbd3a5d",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x604602d3ea69836ce8c3853ae3b411058493ae97df1da58df14303d1bdd17c1d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x74a2b330346be080ba35945b1c01b18f146c18fd7aaf7df95769cc13152b95ba",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc0e64e1f8e84d7a123da1e330eee459e7fa214e9a3b9c9cd8bab236f15a247ce",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xfb4ed916e9c5074bd038c8508f187a94c2c649947cdf5b217871361793fd7768",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x051f15e7e12a0e680f0bc403d2d5125a4369179e3fb3256d1492661d4966bbe6",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x595b2ed1af2a32c880890647d3e212a9c923d735931ea3ad825e13988bbd3a5d",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x604602d3ea69836ce8c3853ae3b411058493ae97df1da58df14303d1bdd17c1d",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x74a2b330346be080ba35945b1c01b18f146c18fd7aaf7df95769cc13152b95ba",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc0e64e1f8e84d7a123da1e330eee459e7fa214e9a3b9c9cd8bab236f15a247ce",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xfb4ed916e9c5074bd038c8508f187a94c2c649947cdf5b217871361793fd7768",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x87e51e75eb63e04449579999c798027b7a8db435a1c122b28defda29027bb075",
                        "balance": {
                          "value": "299999996712400"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x051f15e7e12a0e680f0bc403d2d5125a4369179e3fb3256d1492661d4966bbe6",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x595b2ed1af2a32c880890647d3e212a9c923d735931ea3ad825e13988bbd3a5d",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x604602d3ea69836ce8c3853ae3b411058493ae97df1da58df14303d1bdd17c1d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x74a2b330346be080ba35945b1c01b18f146c18fd7aaf7df95769cc13152b95ba",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc0e64e1f8e84d7a123da1e330eee459e7fa214e9a3b9c9cd8bab236f15a247ce",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xfb4ed916e9c5074bd038c8508f187a94c2c649947cdf5b217871361793fd7768",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x051f15e7e12a0e680f0bc403d2d5125a4369179e3fb3256d1492661d4966bbe6",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x595b2ed1af2a32c880890647d3e212a9c923d735931ea3ad825e13988bbd3a5d",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x604602d3ea69836ce8c3853ae3b411058493ae97df1da58df14303d1bdd17c1d",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x74a2b330346be080ba35945b1c01b18f146c18fd7aaf7df95769cc13152b95ba",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc0e64e1f8e84d7a123da1e330eee459e7fa214e9a3b9c9cd8bab236f15a247ce",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xfb4ed916e9c5074bd038c8508f187a94c2c649947cdf5b217871361793fd7768",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x87e51e75eb63e04449579999c798027b7a8db435a1c122b28defda29027bb075",
                        "balance": {
                          "value": "299999993098000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 12, line 183:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 3
Objects snapshot updated to [0 to 3)

task 13, line 185:
//# create-checkpoint
Checkpoint created: 5

task 14, lines 187-261:
//# run-graphql
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x051f15e7e12a0e680f0bc403d2d5125a4369179e3fb3256d1492661d4966bbe6",
                "value": "2"
              },
              "type": {
                "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x595b2ed1af2a32c880890647d3e212a9c923d735931ea3ad825e13988bbd3a5d",
                "value": "5"
              },
              "type": {
                "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x604602d3ea69836ce8c3853ae3b411058493ae97df1da58df14303d1bdd17c1d",
                "value": "3"
              },
              "type": {
                "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x74a2b330346be080ba35945b1c01b18f146c18fd7aaf7df95769cc13152b95ba",
                "value": "200"
              },
              "type": {
                "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xc0e64e1f8e84d7a123da1e330eee459e7fa214e9a3b9c9cd8bab236f15a247ce",
                "value": "6"
              },
              "type": {
                "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xfb4ed916e9c5074bd038c8508f187a94c2c649947cdf5b217871361793fd7768",
                "value": "4"
              },
              "type": {
                "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x051f15e7e12a0e680f0bc403d2d5125a4369179e3fb3256d1492661d4966bbe6",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x595b2ed1af2a32c880890647d3e212a9c923d735931ea3ad825e13988bbd3a5d",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x604602d3ea69836ce8c3853ae3b411058493ae97df1da58df14303d1bdd17c1d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x74a2b330346be080ba35945b1c01b18f146c18fd7aaf7df95769cc13152b95ba",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc0e64e1f8e84d7a123da1e330eee459e7fa214e9a3b9c9cd8bab236f15a247ce",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xfb4ed916e9c5074bd038c8508f187a94c2c649947cdf5b217871361793fd7768",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x051f15e7e12a0e680f0bc403d2d5125a4369179e3fb3256d1492661d4966bbe6",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x595b2ed1af2a32c880890647d3e212a9c923d735931ea3ad825e13988bbd3a5d",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x604602d3ea69836ce8c3853ae3b411058493ae97df1da58df14303d1bdd17c1d",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x74a2b330346be080ba35945b1c01b18f146c18fd7aaf7df95769cc13152b95ba",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc0e64e1f8e84d7a123da1e330eee459e7fa214e9a3b9c9cd8bab236f15a247ce",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xfb4ed916e9c5074bd038c8508f187a94c2c649947cdf5b217871361793fd7768",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x87e51e75eb63e04449579999c798027b7a8db435a1c122b28defda29027bb075",
                        "balance": {
                          "value": "299999993098000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x051f15e7e12a0e680f0bc403d2d5125a4369179e3fb3256d1492661d4966bbe6",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x595b2ed1af2a32c880890647d3e212a9c923d735931ea3ad825e13988bbd3a5d",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x604602d3ea69836ce8c3853ae3b411058493ae97df1da58df14303d1bdd17c1d",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x74a2b330346be080ba35945b1c01b18f146c18fd7aaf7df95769cc13152b95ba",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xc0e64e1f8e84d7a123da1e330eee459e7fa214e9a3b9c9cd8bab236f15a247ce",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xfb4ed916e9c5074bd038c8508f187a94c2c649947cdf5b217871361793fd7768",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 15, line 263:
//# create-checkpoint
Checkpoint created: 6

task 16, lines 265-300:
//# run-graphql
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x051f15e7e12a0e680f0bc403d2d5125a4369179e3fb3256d1492661d4966bbe6",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x595b2ed1af2a32c880890647d3e212a9c923d735931ea3ad825e13988bbd3a5d",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x604602d3ea69836ce8c3853ae3b411058493ae97df1da58df14303d1bdd17c1d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x74a2b330346be080ba35945b1c01b18f146c18fd7aaf7df95769cc13152b95ba",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc0e64e1f8e84d7a123da1e330eee459e7fa214e9a3b9c9cd8bab236f15a247ce",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xfb4ed916e9c5074bd038c8508f187a94c2c649947cdf5b217871361793fd7768",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x051f15e7e12a0e680f0bc403d2d5125a4369179e3fb3256d1492661d4966bbe6",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x595b2ed1af2a32c880890647d3e212a9c923d735931ea3ad825e13988bbd3a5d",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x604602d3ea69836ce8c3853ae3b411058493ae97df1da58df14303d1bdd17c1d",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x74a2b330346be080ba35945b1c01b18f146c18fd7aaf7df95769cc13152b95ba",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc0e64e1f8e84d7a123da1e330eee459e7fa214e9a3b9c9cd8bab236f15a247ce",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xfb4ed916e9c5074bd038c8508f187a94c2c649947cdf5b217871361793fd7768",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x051f15e7e12a0e680f0bc403d2d5125a4369179e3fb3256d1492661d4966bbe6",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x595b2ed1af2a32c880890647d3e212a9c923d735931ea3ad825e13988bbd3a5d",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x604602d3ea69836ce8c3853ae3b411058493ae97df1da58df14303d1bdd17c1d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x74a2b330346be080ba35945b1c01b18f146c18fd7aaf7df95769cc13152b95ba",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc0e64e1f8e84d7a123da1e330eee459e7fa214e9a3b9c9cd8bab236f15a247ce",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xfb4ed916e9c5074bd038c8508f187a94c2c649947cdf5b217871361793fd7768",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x051f15e7e12a0e680f0bc403d2d5125a4369179e3fb3256d1492661d4966bbe6",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x595b2ed1af2a32c880890647d3e212a9c923d735931ea3ad825e13988bbd3a5d",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x604602d3ea69836ce8c3853ae3b411058493ae97df1da58df14303d1bdd17c1d",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x74a2b330346be080ba35945b1c01b18f146c18fd7aaf7df95769cc13152b95ba",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc0e64e1f8e84d7a123da1e330eee459e7fa214e9a3b9c9cd8bab236f15a247ce",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xfb4ed916e9c5074bd038c8508f187a94c2c649947cdf5b217871361793fd7768",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x051f15e7e12a0e680f0bc403d2d5125a4369179e3fb3256d1492661d4966bbe6",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x595b2ed1af2a32c880890647d3e212a9c923d735931ea3ad825e13988bbd3a5d",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x604602d3ea69836ce8c3853ae3b411058493ae97df1da58df14303d1bdd17c1d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x74a2b330346be080ba35945b1c01b18f146c18fd7aaf7df95769cc13152b95ba",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc0e64e1f8e84d7a123da1e330eee459e7fa214e9a3b9c9cd8bab236f15a247ce",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xfb4ed916e9c5074bd038c8508f187a94c2c649947cdf5b217871361793fd7768",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x051f15e7e12a0e680f0bc403d2d5125a4369179e3fb3256d1492661d4966bbe6",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x595b2ed1af2a32c880890647d3e212a9c923d735931ea3ad825e13988bbd3a5d",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x604602d3ea69836ce8c3853ae3b411058493ae97df1da58df14303d1bdd17c1d",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x74a2b330346be080ba35945b1c01b18f146c18fd7aaf7df95769cc13152b95ba",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc0e64e1f8e84d7a123da1e330eee459e7fa214e9a3b9c9cd8bab236f15a247ce",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xfb4ed916e9c5074bd038c8508f187a94c2c649947cdf5b217871361793fd7768",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xe948dcd4f659a16c65fe64364337eaa66a6a34f3e7ed84e9ba3259962a2883f6::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}
