// Copyright (c) 2024 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

import { lazy as _lazy } from 'react';
import { ReactComponent as AddIcon } from './icon-list/add.svg';

function lazy(
    importFunction: () => Promise<{
        ReactComponent: typeof AddIcon;
    }>,
) {
    return _lazy(async () => {
        const imported = await importFunction();
        return { default: imported.ReactComponent };
    });
}

function importIcon(iconFile: string) {
    return lazy(async () => import(`./icons/${iconFile}.svg`));
}

export enum IconEnum {
    Activity = 'Activity',
    Add = 'Add',
    Address = 'Address',
    Apps = 'Apps',
    ArrowBottomLeft = 'ArrowBottomLeft',
    ArrowTopRight = 'ArrowTopRight',
    Assets = 'Assets',
    Back = 'Back',
    Checkmark = 'Checkmark',
    Clock = 'Clock',
    Close = 'Close',
    CogGear = 'CogGear',
    Copy = 'Copy',
    DoubleLeft = 'DoubleLeft',
    DoubleRight = 'DoubleRight',
    Down = 'Down',
    Export = 'Export',
    Filter = 'Filter',
    Flag = 'Flag',
    Forward = 'Forward',
    Handler = 'Handler',
    Hide = 'Hide',
    Home = 'Home',
    Icon = 'Icon',
    ImportPass = 'ImportPass',
    Info = 'Info',
    IotaLogoMark = 'IotaLogoMark',
    IotaLogoSmall = 'IotaLogoSmall',
    Key = 'Key',
    Ledger = 'Ledger',
    Left = 'Left',
    ListViewLarge = 'ListViewLarge',
    ListViewMedium = 'ListViewMedium',
    ListViewSmall = 'ListViewSmall',
    LockLocked = 'LockLocked',
    LockUnlocked = 'LockUnlocked',
    LogOut = 'LogOut',
    Migration = 'Migration',
    MoreHoriz = 'MoreHoriz',
    MoreVert = 'MoreVert',
    NullIcon = 'NullIcon',
    OutboundLink = 'OutboundLink',
    Pencil = 'Pencil',
    QrCode = 'QrCode',
    RadionOff = 'RadionOff',
    RadionOn = 'RadionOn',
    Right = 'Right',
    Save = 'Save',
    Search = 'Search',
    Seed = 'Seed',
    Show = 'Show',
    SortByDefault = 'SortByDefault',
    SortByDown = 'SortByDown',
    SortByUp = 'SortByUp',
    Stack = 'Stack',
    Stake = 'Stake',
    SwapAccount = 'SwapAccount',
    ThumbUp = 'ThumbUp',
    TransactionBlock = 'TransactionBlock',
    Trash = 'Trash',
    TriangleBottom = 'TriangleBottom',
    TriangleTop = 'TriangleTop',
    Up = 'Up',
    User = 'User',
    Vest = 'Vest',
}

export const IconList: Record<IconEnum, ReturnType<typeof importIcon>> = {
    [IconEnum.Activity]: importIcon('activity'),
    [IconEnum.Add]: importIcon('add'),
    [IconEnum.Address]: importIcon('address'),
    [IconEnum.Apps]: importIcon('apps'),
    [IconEnum.ArrowBottomLeft]: importIcon('arrow_bottom_left'),
    [IconEnum.ArrowTopRight]: importIcon('arrow_top_right'),
    [IconEnum.Assets]: importIcon('assets'),
    [IconEnum.Back]: importIcon('back'),
    [IconEnum.Checkmark]: importIcon('checkmark'),
    [IconEnum.Clock]: importIcon('clock'),
    [IconEnum.Close]: importIcon('close'),
    [IconEnum.CogGear]: importIcon('cog_gear'),
    [IconEnum.Copy]: importIcon('copy'),
    [IconEnum.DoubleLeft]: importIcon('double_left'),
    [IconEnum.DoubleRight]: importIcon('double_right'),
    [IconEnum.Down]: importIcon('down'),
    [IconEnum.Export]: importIcon('export'),
    [IconEnum.Filter]: importIcon('filter'),
    [IconEnum.Flag]: importIcon('flag'),
    [IconEnum.Forward]: importIcon('forward'),
    [IconEnum.Handler]: importIcon('handler'),
    [IconEnum.Hide]: importIcon('hide'),
    [IconEnum.Home]: importIcon('home'),
    [IconEnum.Icon]: importIcon('icon'),
    [IconEnum.ImportPass]: importIcon('import_pass'),
    [IconEnum.Info]: importIcon('info'),
    [IconEnum.IotaLogoMark]: importIcon('iota_logo_mark'),
    [IconEnum.IotaLogoSmall]: importIcon('iota_logo_small'),
    [IconEnum.Key]: importIcon('key'),
    [IconEnum.Ledger]: importIcon('ledger'),
    [IconEnum.Left]: importIcon('left'),
    [IconEnum.ListViewLarge]: importIcon('list_view_large'),
    [IconEnum.ListViewMedium]: importIcon('list_view_medium'),
    [IconEnum.ListViewSmall]: importIcon('list_view_small'),
    [IconEnum.LockLocked]: importIcon('lock_locked'),
    [IconEnum.LockUnlocked]: importIcon('lock_unlocked'),
    [IconEnum.LogOut]: importIcon('log_out'),
    [IconEnum.Migration]: importIcon('migration'),
    [IconEnum.MoreHoriz]: importIcon('more_horiz'),
    [IconEnum.MoreVert]: importIcon('more_vert'),
    [IconEnum.NullIcon]: importIcon('null_icon'),
    [IconEnum.OutboundLink]: importIcon('outbound_link'),
    [IconEnum.Pencil]: importIcon('pencil'),
    [IconEnum.QrCode]: importIcon('qr_code'),
    [IconEnum.RadionOff]: importIcon('radion_off'),
    [IconEnum.RadionOn]: importIcon('radion_on'),
    [IconEnum.Right]: importIcon('right'),
    [IconEnum.Save]: importIcon('save'),
    [IconEnum.Search]: importIcon('search'),
    [IconEnum.Seed]: importIcon('seed'),
    [IconEnum.Show]: importIcon('show'),
    [IconEnum.SortByDefault]: importIcon('sort_by_default'),
    [IconEnum.SortByDown]: importIcon('sort_by_down'),
    [IconEnum.SortByUp]: importIcon('sort_by_up'),
    [IconEnum.Stack]: importIcon('stack'),
    [IconEnum.Stake]: importIcon('stake'),
    [IconEnum.SwapAccount]: importIcon('swap_account'),
    [IconEnum.ThumbUp]: importIcon('thumb_up'),
    [IconEnum.TransactionBlock]: importIcon('transaction_block'),
    [IconEnum.Trash]: importIcon('trash'),
    [IconEnum.TriangleBottom]: importIcon('triangle_bottom'),
    [IconEnum.TriangleTop]: importIcon('triangle_top'),
    [IconEnum.Up]: importIcon('up'),
    [IconEnum.User]: importIcon('user'),
    [IconEnum.Vest]: importIcon('vest'),
};
