[package]
name = "smart_account_allowed_authenticators"
edition = "2024"

[dependencies]
Iota = { local = "../../../../crates/iota-framework/packages/iota-framework" }

[addresses]
smart_account_allowed_authenticators = "0x0"

[dev-dependencies]

[dev-addresses]
