// Copyright (c) 2024 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Ampli - A strong typed wrapper for your Analytics
 *
 * This file is generated by Amplitude.
 * To update run 'ampli pull web'
 *
 * Required dependencies: @amplitude/analytics-browser@^1.3.0
 * Tracking Plan Version: 1
 * Build: 1.0.0
 * Runtime: browser:typescript-ampli-v2
 *
 * [View Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20EVM%20Bridge/events/main/latest)
 *
 * [Full Setup Instructions](https://data.eu.amplitude.com/iota-foundation/IOTA%20EVM%20Bridge/implementation/web)
 */

import * as amplitude from '@amplitude/analytics-browser';

export type Environment = 'iotaevmbridge';

export const ApiKey: Record<Environment, string> = {
    iotaevmbridge: 'placeholder-api-key',
};

export interface LoadOptions {
    environment?: Environment;
    disabled?: boolean;
    client?: {
        apiKey?: string;
        instance?: BrowserClient;
        configuration?: BrowserOptions;
    };
}

export type PromiseResult<T> = { promise: Promise<T | void> };

const getVoidPromiseResult = () => ({ promise: Promise.resolve() });

// prettier-ignore
export class Ampli {
    private disabled: boolean = false;
    private amplitude?: BrowserClient;

    get client(): BrowserClient {
        this.isInitializedAndEnabled();
        return this.amplitude!;
    }

    get isLoaded(): boolean {
        return this.amplitude != null;
    }

    private isInitializedAndEnabled(): boolean {
        if (!this.amplitude) {
            console.error('ERROR: Ampli is not yet initialized. Have you called ampli.load() on app start?');
            return false;
        }
        return !this.disabled;
    }

    /**
     * Initialize the Ampli SDK. Call once when your application starts.
     *
     * @param options Configuration options to initialize the Ampli SDK with.
     */
    load(options: LoadOptions): PromiseResult<void> {
        this.disabled = options.disabled ?? false;

        if (this.amplitude) {
            console.warn('WARNING: Ampli is already initialized. Ampli.load() should be called once at application startup.');
            return getVoidPromiseResult();
        }

        let apiKey: string | null = null;
        if (options.client && 'apiKey' in options.client) {
            apiKey = options.client.apiKey;
        } else if ('environment' in options) {
            apiKey = ApiKey[options.environment];
        }

        if (options.client && 'instance' in options.client) {
            this.amplitude = options.client.instance;
        } else if (apiKey) {
            this.amplitude = amplitude.createInstance();
            const configuration = (options.client && 'configuration' in options.client) ? options.client.configuration : {};
            return this.amplitude.init(apiKey, undefined, { ...DefaultConfiguration, ...configuration });
        } else {
            console.error("ERROR: ampli.load() requires 'environment', 'client.apiKey', or 'client.instance'");
        }

        return getVoidPromiseResult();
    }

    /**
     * Identify a user and set user properties.
     *
     * @param userId The user's id.
     * @param options Optional event options.
     */
    identify(
        userId: string | undefined,
        options?: EventOptions,
    ): PromiseResult<Result> {
        if (!this.isInitializedAndEnabled()) {
            return getVoidPromiseResult();
        }

        return this.amplitude!.identify(
            userId ? amplitude.Identify.identify().set('userId', userId) : amplitude.Identify.identify(),
            options,
        );
    }

    /**
     * Flush the event.
     */
    flush(): PromiseResult<Result> {
        if (!this.isInitializedAndEnabled()) {
            return getVoidPromiseResult();
        }

        return this.amplitude!.flush();
    }

    /**
     * Track event
     *
     * @param event The event to track.
     * @param options Optional event options.
     */
    track(event: Event, options?: EventOptions): PromiseResult<Result> {
        if (!this.isInitializedAndEnabled()) {
            return getVoidPromiseResult();
        }

        return this.amplitude!.track(event, undefined, options);
    }

    // Placeholder events will be generated here when running 'ampli pull web'
    // Example events based on our tracking plan:
    
    /**
     * bridge_direction_toggled
     * 
     * User toggles bridge direction (L1→L2 or L2→L1)
     */
    bridgeDirectionToggled(properties?: { fromDirection?: string; toDirection?: string }, options?: EventOptions) {
        // This will be implemented when pulling from Amplitude
        console.warn('bridgeDirectionToggled event not yet implemented. Run "pnpm pull-amplitude" to generate events.');
    }

    /**
     * l1_wallet_connected
     * 
     * L1 wallet successfully connected
     */
    l1WalletConnected(properties?: { walletType?: string; address?: string; connectionMethod?: string }, options?: EventOptions) {
        // This will be implemented when pulling from Amplitude
        console.warn('l1WalletConnected event not yet implemented. Run "pnpm pull-amplitude" to generate events.');
    }

    /**
     * bridge_transaction_initiated
     * 
     * User clicks "Bridge Assets" button
     */
    bridgeTransactionInitiated(properties?: { amount?: string; coinType?: string; bridgeDirection?: string; receivingAddress?: string }, options?: EventOptions) {
        // This will be implemented when pulling from Amplitude
        console.warn('bridgeTransactionInitiated event not yet implemented. Run "pnpm pull-amplitude" to generate events.');
    }
}

export const ampli = new Ampli();

// BASE TYPES
type BrowserOptions = amplitude.Types.BrowserOptions;

export type BrowserClient = amplitude.Types.BrowserClient;
export type BaseEvent = amplitude.Types.BaseEvent;
export type IdentifyEvent = amplitude.Types.IdentifyEvent;
export type GroupEvent = amplitude.Types.GroupIdentifyEvent;
export type Event = amplitude.Types.Event;
export type EventOptions = amplitude.Types.EventOptions;
export type Result = amplitude.Types.Result;

// DEFAULT CONFIGURATION
const DefaultConfiguration: BrowserOptions = {
    plan: {
        version: '1',
    },
    ingestionMetadata: {
        sourceName: 'browser-typescript-ampli',
        sourceVersion: '1.0.0',
    },
};