#
# Dependabot configuration file
#

version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/external-crates/move"
    schedule:
      interval: "daily"
    # Disable version update PRs, keep security alerts
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    # Disable version update PRs, keep security alerts
    open-pull-requests-limit: 0
