[default]
extend-ignore-identifiers-re = [
    # Digests
    "[a-zA-Z0-9]{43}?",
    # Identifiers
    "[a-zA-Z0-9]{44}?",
    # Base64
    "[a-zA-Z0-9_]{47}?"
]

[default.extend-words]
# accepted plurals
froms = "froms"
alls = "alls"
somes = "somes"
# ordinal numbers (2nd, ...)
nd = "nd"
# random identifiers, variables, functions, ...
bttr = "bttr"
dbe = "dbe"
thr = "thr"
fo = "fo"
BA = "BA"
DAA = "DAA"
UE = "UE"
tto = "tto"
ser = "ser"
pn = "pn"
noo = "noo"
Ot = "Ot"
Hel = "Hel"
numer = "numer"
ratatui = "ratatui"
groth = "groth"
strat = "strat"
mistic = "mistic"
transferer = "transferrer"
checkpoitn = "checkpoint"
# Identity
AAS = "AAS"
# actual typos purposely used in tests
assing = "assing"
tring = "tring"
Thi = "Thi"

[files]
extend-exclude = ["pnpm-lock.yaml", "external-crates/*", "*.snap", "*.exp", "config-patch"]
