[default]
extend-ignore-identifiers-re = [
  # Short git hashes
  "[a-z0-9]{7}?",
  # Digests
  "[a-zA-Z0-9]{43}?",
  # Identifiers
  "[a-zA-Z0-9]{44}?",
  # Base64
  "[a-zA-Z0-9_]{47}?",
]
# Truncated hex IDs (ex. "0x9...a9b")
extend-ignore-re = ["0x[a-z0-9]\\.{3}[a-z0-9]{3}"]

[type.hex-move]
extend-glob = ["hex.move"]
extend-words = { ba = "ba" }

[default.extend-words]
# ordinal numbers (2nd, ...)
nd = "nd"
# random identifiers, variables, functions, ...
tto = "tto"
ser = "ser"
groth = "groth"
transferer = "transferrer"
checkpoitn = "checkpoint"
# Identity
AAS = "AAS"
# actual typos purposely used in tests
assing = "assing"
tring = "tring"
Thi = "Thi"

[default.extend-identifiers]
numer = "numer"

[files]
extend-exclude = [
  "pnpm-lock.yaml",
  "external-crates/*",
  "*.snap",
  "*.exp",
  "config-patch",
  "*.patch",
  "*.svg",
]
