#!/usr/bin/env bash
# Run multiple stress.rs processes in parallel, each pinned to one fullnode.
# Works around iota-benchmark stress.rs's "random proxy chosen once per workload"
# behavior in bench_driver.rs:356.
#
# Outputs go to runs/multi-<utc-ts>/ — one parent dir per invocation, never overwritten.

set -uo pipefail

QPS_TOTAL="${QPS_TOTAL:-10000}"
DURATION="${DURATION:-300s}"
WORKERS="${WORKERS:-12}"
IN_FLIGHT_RATIO="${IN_FLIGHT_RATIO:-10}"
BURST_SIZE="${BURST_SIZE:-1}"
BARRIER_PERIOD_MS="${BARRIER_PERIOD_MS:-0}"
GAS_CHUNK_SIZE="${GAS_CHUNK_SIZE:-500}"
NUM_TRANSFER_ACCOUNTS="${NUM_TRANSFER_ACCOUNTS:-2}"
# Persistent gas-pool cache dir (survives across runs). Each subprocess gets
# its own cache file under this dir, keyed by primary_gas_owner index. To
# disable the cache, set GAS_POOL_CACHE_DIR="disable" (or any non-path that
# doesn't exist and can't be created).
# Default lives under the monorepo's runs/ (which is gitignored) so all
# sweep artifacts stay under one tree. Override with GAS_POOL_CACHE_DIR=...
# if you want a shared cross-clone cache, e.g. $HOME/.stress-gas-pool.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GAS_POOL_CACHE_DIR="${GAS_POOL_CACHE_DIR:-$SCRIPT_DIR/runs/.stress-gas-pool}"
FULLNODES="${FULLNODES:-http://127.0.0.1:9000}"
PROM_URL="${PROM_URL:-http://localhost:9090}"

IFS=',' read -ra FN_ARR <<< "$FULLNODES"
# Number of stress subprocesses. Defaults to the number of fullnode URLs (one
# proc primarily targets one fullnode), but can be overridden — e.g.
# NUM_PROCS=8 FULLNODES=<4 urls> ... gives 8 procs sharing 4 fullnodes (2:1),
# which preserves client-side concurrency (more independent RPC clients, more
# burst races at the gate) even with a slimmer validator network.
N="${NUM_PROCS:-${#FN_ARR[@]}}"

# Honest pool (Option B for the anti-spam fairness experiment described in
# graduated-benefits.md). When HONEST_PROC_COUNT > 0, the LAST
# HONEST_PROC_COUNT procs in this invocation use the honest configuration
# (low QPS, no burst), and the first (N - HONEST_PROC_COUNT) procs use the
# existing spammer-style config (QPS_TOTAL, BURST_SIZE, BARRIER_PERIOD_MS,
# IN_FLIGHT_RATIO, WORKERS). Default 0 keeps single-pool behavior so
# burst-sweep.sh and other callers are unaffected.
HONEST_PROC_COUNT="${HONEST_PROC_COUNT:-0}"
HONEST_QPS_PER_PROC="${HONEST_QPS_PER_PROC:-50}"
HONEST_BURST_SIZE="${HONEST_BURST_SIZE:-1}"
HONEST_BARRIER_PERIOD_MS="${HONEST_BARRIER_PERIOD_MS:-0}"
HONEST_IFR="${HONEST_IFR:-4}"
HONEST_WORKERS="${HONEST_WORKERS:-4}"

N_SPAMMER=$((N - HONEST_PROC_COUNT))
if [ "$N_SPAMMER" -le 0 ]; then
  echo "Error: HONEST_PROC_COUNT=$HONEST_PROC_COUNT >= NUM_PROCS=$N (no spammer procs left)" >&2
  exit 1
fi
# QPS_PER is the per-spammer-proc QPS. With HONEST_PROC_COUNT=0 this
# collapses to the original QPS_TOTAL / N.
QPS_PER=$((QPS_TOTAL / N_SPAMMER))

# Offset into the GAS_OWNERS array. Set GAS_OWNERS_OFFSET=4 on the second
# machine in a 2-machine setup so it uses gas owners 4-7 (avoiding contention
# with machine 1 using 0-3).
GAS_OWNERS_OFFSET="${GAS_OWNERS_OFFSET:-0}"

# Benchmark gas-owner addresses — read dynamically from the benchmark
# keystore generated by bootstrap.sh's print-benchmark-accounts helper.
# The keystore is sorted (FileBasedKeystore::save) so the address order
# is stable across runs even though it differs from the deterministic
# benchmark_gas_keys() generation order. Stable order is all we need:
# process i always gets the i-th address.
KEYSTORE_PATH="$SCRIPT_DIR/dev-tools/iota-private-network/configs/genesis/benchmark.keystore"
if [ ! -f "$KEYSTORE_PATH" ]; then
  echo "Error: benchmark keystore not found at $KEYSTORE_PATH — run bootstrap.sh first" >&2
  exit 1
fi
mapfile -t GAS_OWNERS < <(python3 -c "
import json, sys
data = json.load(open('$KEYSTORE_PATH'))
for k in data['keys']:
    print(k['address'])
")
if [ $((GAS_OWNERS_OFFSET + N)) -gt "${#GAS_OWNERS[@]}" ]; then
  echo "Error: GAS_OWNERS_OFFSET=$GAS_OWNERS_OFFSET + N=$N exceeds ${#GAS_OWNERS[@]} defined gas owners" >&2
  exit 1
fi

# Build stress.rs once before forking subprocesses. Each subprocess uses
# `cargo run --release` which will auto-rebuild if needed, but doing it serially
# here avoids 8 parallel cargo invocations racing on the build directory.
echo "=> Pre-building iota-benchmark (cargo build --release -p iota-benchmark)..."
cargo build --release -p iota-benchmark --bin stress || {
  echo "Error: build failed" >&2
  exit 1
}

# Master timestamp + parent dir under runs/ so each invocation is preserved.
MASTER_TS=$(date -u +"%Y-%m-%dT%H-%M-%SZ")
PARENT_DIR="runs/multi-${MASTER_TS}"
mkdir -p "$PARENT_DIR"

# Barrier files: each subprocess writes its READY_FILE after setup, then waits
# for START_FILE to appear. We touch START_FILE once all are ready, so all
# spam windows begin simultaneously.
BARRIER_DIR="$PARENT_DIR/barrier"
mkdir -p "$BARRIER_DIR"
START_FILE="$BARRIER_DIR/go"

if [ "$HONEST_PROC_COUNT" -gt 0 ]; then
  echo "=> Launching $N stress.rs processes in two pools:"
  echo "     spammer pool: $N_SPAMMER procs @ QPS=$QPS_PER each (total=$QPS_TOTAL)"
  echo "                   BURST_SIZE=$BURST_SIZE BARRIER_PERIOD_MS=$BARRIER_PERIOD_MS"
  echo "     honest pool:  $HONEST_PROC_COUNT proc(s) @ QPS=$HONEST_QPS_PER_PROC each"
  echo "                   BURST_SIZE=$HONEST_BURST_SIZE BARRIER_PERIOD_MS=$HONEST_BARRIER_PERIOD_MS"
else
  echo "=> Launching $N stress.rs processes, each at QPS=$QPS_PER (total=$QPS_TOTAL)"
fi
echo "=> Parent dir: $PARENT_DIR"
echo "=> Barrier: $BARRIER_DIR (start file: $START_FILE)"

pids=()
logs=()
runs_dirs=()
ready_files=()
pool_labels=()

# If this script is killed (Ctrl-C, SIGTERM, hangup), reap all subprocess
# groups so we don't leak orphan stress binaries holding their metrics ports.
cleanup_subprocesses() {
  local pid
  for pid in "${pids[@]}"; do kill -TERM -- -"$pid" 2>/dev/null || true; done
  sleep 1
  for pid in "${pids[@]}"; do kill -KILL -- -"$pid" 2>/dev/null || true; done
}
trap cleanup_subprocesses INT TERM HUP
for ((i=0; i<N; i++)); do
  # Round-robin primary fullnode assignment so N>len(FN_ARR) works
  # (e.g. NUM_PROCS=8 with 4 fullnodes → procs 0,4 share fn[0], etc.).
  fn="${FN_ARR[$((i % ${#FN_ARR[@]}))]}"
  log="$PARENT_DIR/process-$i.log"
  proc_runs="$PARENT_DIR/process-$i"
  ready_file="$BARRIER_DIR/process-$i.ready"
  logs+=("$log")
  runs_dirs+=("$proc_runs")
  ready_files+=("$ready_file")
  # Per-subprocess cache file (one per gas owner so they don't collide).
  cache_idx=$((GAS_OWNERS_OFFSET + i))
  if [ "$GAS_POOL_CACHE_DIR" = "disable" ] || [ -z "$GAS_POOL_CACHE_DIR" ]; then
    proc_cache=""
  else
    mkdir -p "$GAS_POOL_CACHE_DIR" 2>/dev/null
    proc_cache="$GAS_POOL_CACHE_DIR/owner-$cache_idx.json"
  fi
  # Pool dispatch: procs [N_SPAMMER..N-1] use the honest config when
  # HONEST_PROC_COUNT > 0. Procs [0..N_SPAMMER-1] always use the existing
  # spammer config. The two pools share the same barrier and fire their
  # first activity at the same instant once all N procs are ready.
  if [ "$HONEST_PROC_COUNT" -gt 0 ] && [ "$i" -ge "$N_SPAMMER" ]; then
    pool="honest"
    proc_qps=$HONEST_QPS_PER_PROC
    proc_burst=$HONEST_BURST_SIZE
    proc_barrier=$HONEST_BARRIER_PERIOD_MS
    proc_ifr=$HONEST_IFR
    proc_workers=$HONEST_WORKERS
  else
    pool="spammer"
    proc_qps=$QPS_PER
    proc_burst=$BURST_SIZE
    proc_barrier=$BARRIER_PERIOD_MS
    proc_ifr=$IN_FLIGHT_RATIO
    proc_workers=$WORKERS
  fi
  pool_labels+=("$pool")
  echo "   process $i [$pool] → $fn  (qps=$proc_qps burst=$proc_burst, log: $log, cache: ${proc_cache:-disabled})"
  QPS="$proc_qps" \
  DURATION="$DURATION" \
  WORKERS="$proc_workers" \
  IN_FLIGHT_RATIO="$proc_ifr" \
  BURST_SIZE="$proc_burst" \
  BARRIER_PERIOD_MS="$proc_barrier" \
  GAS_CHUNK_SIZE="$GAS_CHUNK_SIZE" \
  GAS_POOL_CACHE_PATH="$proc_cache" \
  NUM_TRANSFER_ACCOUNTS="$NUM_TRANSFER_ACCOUNTS" \
  NUM_VALIDATORS_TO_TARGET="${NUM_VALIDATORS_TO_TARGET:-0}" \
  FULLNODE_RPC="$fn" \
  FULLNODE_RPC_ALL="$FULLNODES" \
  USE_FULLNODE_FOR_EXECUTION="${USE_FULLNODE_FOR_EXECUTION:-false}" \
  USE_FULLNODE_FOR_RECONFIG="${USE_FULLNODE_FOR_RECONFIG:-false}" \
  CLIENT_METRIC_PORT="$((8081 + i))" \
  PRIMARY_GAS_OWNER="${GAS_OWNERS[$((GAS_OWNERS_OFFSET + i))]}" \
  RUNS_DIR="$proc_runs" \
  READY_FILE="$ready_file" \
  START_FILE="$START_FILE" \
  setsid ./stress-load-shedding.sh > "$log" 2>&1 &
  pids+=($!)
  # Stagger subprocess launches so their warmup pay_iota calls don't pile up
  # at the validator gate simultaneously (with TD path engaged, validators
  # see direct concurrent admissions from all procs — no fullnode buffer).
  # 500ms × N procs spreads setup over ~12s, plenty for the gate to drain
  # between proc warmup starts. Spam still syncs at the barrier post-ready.
  # Override with PROC_LAUNCH_STAGGER_MS=0 to disable.
  if [ "${PROC_LAUNCH_STAGGER_MS:-500}" -gt 0 ] && [ "$i" -lt "$((N - 1))" ]; then
    sleep "$(awk "BEGIN{print ${PROC_LAUNCH_STAGGER_MS:-500}/1000}")"
  fi
done

# Wait for all subprocesses to finish their setup (write their ready file).
# Bail after BARRIER_TIMEOUT seconds in case a subprocess crashes during setup.
BARRIER_TIMEOUT="${BARRIER_TIMEOUT:-1800}"  # 30 min default
echo "=> Waiting for all $N processes to finish setup (barrier sync, timeout=${BARRIER_TIMEOUT}s)..."
all_ready=0
elapsed=0
while [ $all_ready -eq 0 ]; do
  all_ready=1
  ready_count=0
  dead_without_ready=()
  for ((i=0; i<N; i++)); do
    rf="${ready_files[$i]}"
    if [ -f "$rf" ]; then
      ready_count=$((ready_count + 1))
    else
      all_ready=0
      # Fail-fast: if this subprocess's pid is no longer alive but it
      # never wrote a ready file, it crashed during setup. Bail out.
      if ! kill -0 "${pids[$i]}" 2>/dev/null; then
        dead_without_ready+=("$i")
      fi
    fi
  done
  echo "   [${elapsed}s] $ready_count/$N ready"
  if [ $all_ready -eq 1 ]; then break; fi
  if [ "${#dead_without_ready[@]}" -gt 0 ]; then
    echo
    echo "=> FAIL-FAST: ${#dead_without_ready[@]} subprocess(es) died during setup without writing ready file."
    for i in "${dead_without_ready[@]}"; do
      echo "--- process $i (log: ${logs[$i]}) ---"
      sed -r 's/\x1b\[[0-9;]*[mGKH]//g' "${logs[$i]}" 2>/dev/null \
        | grep -iE 'panic|insufficient|error|fail' \
        | grep -v 'compile\|^warning' \
        | tail -5
    done
    # Reap any remaining subprocesses so we don't leave orphans.
    # Each subprocess was launched via `setsid`, so its pid is the leader of
    # its own process group — kill the whole group (negative pid) to reach
    # the bash wrapper, the `script` fork, and the `target/release/stress`
    # grandchild. A plain `kill $pid` would only signal the bash wrapper and
    # leave the stress binary orphaned (which would hog its metrics port
    # 808N on the next run, causing AddrInUse panics).
    for pid in "${pids[@]}"; do kill -TERM -- -"$pid" 2>/dev/null || true; done
    # Release the start file so any still-waiting children unblock and exit.
    : > "$START_FILE" 2>/dev/null || true
    sleep 1
    # Anything still alive after SIGTERM gets SIGKILL.
    for pid in "${pids[@]}"; do kill -KILL -- -"$pid" 2>/dev/null || true; done
    for pid in "${pids[@]}"; do wait "$pid" 2>/dev/null || true; done
    echo "=> Exiting with code 1."
    exit 1
  fi
  if [ $elapsed -ge $BARRIER_TIMEOUT ]; then
    echo "=> Barrier timeout (${BARRIER_TIMEOUT}s). Releasing start anyway with $ready_count/$N ready."
    echo "   Missing: $(for ((i=0; i<N; i++)); do [ -f "${ready_files[$i]}" ] || echo "process-$i"; done)"
    break
  fi
  sleep 5
  elapsed=$((elapsed + 5))
done

# Cross-machine sync: when running stress-multi.sh on multiple machines in
# parallel, set WAIT_FOR_USER=1 on each. Both will pause after their local
# barrier here. Press Enter on both machines (roughly) simultaneously to
# release the spam phase.
if [ "${WAIT_FOR_USER:-0}" = "1" ]; then
  echo
  echo "================================================================"
  echo "  All $N processes finished setup on THIS machine."
  echo "  Press Enter to release the spam phase."
  echo "  (For multi-machine sync: press Enter on all machines at once.)"
  echo "================================================================"
  read -r _
fi

echo "=> Releasing start barrier."
# Write wall-clock epoch (ns) so workers in barrier mode can align ticks across
# processes (and across machines, if clocks are NTP-synced). Plain `touch` is
# preserved as a fallback for non-barrier runs since stress.rs only parses the
# content when --barrier-period-ms > 0.
date +%s%N > "$START_FILE"
SPAM_START_EPOCH=$(date +%s)
echo "=> Spam phase running (DURATION=$DURATION, BARRIER_PERIOD_MS=$BARRIER_PERIOD_MS)..."

echo "=> Waiting for all $N processes to finish (pids: ${pids[*]})"
exit_codes=()
for pid in "${pids[@]}"; do
  wait "$pid"
  exit_codes+=($?)
done
SPAM_END_EPOCH=$(date +%s)

# Helper to find the inner timestamped dir for a given process index.
inner_dir() {
  local i=$1
  ls -td "${runs_dirs[$i]}"/*/ 2>/dev/null | head -1
}

echo
echo "=> All processes done. Exit codes: ${exit_codes[*]}"

# Surface any panics / errors immediately so failures don't get buried in
# the per-process logs.
any_failed=0
for ((i=0; i<N; i++)); do
  if [ "${exit_codes[$i]}" -ne 0 ] 2>/dev/null; then
    any_failed=1
  fi
done
if [ "$any_failed" -ne 0 ]; then
  echo
  echo "=> Subprocess failures detected. Last error lines per process:"
  for ((i=0; i<N; i++)); do
    if [ "${exit_codes[$i]}" -ne 0 ] 2>/dev/null; then
      echo "--- process $i (exit=${exit_codes[$i]}, log=${logs[$i]}) ---"
      sed -r 's/\x1b\[[0-9;]*[mGKH]//g' "${logs[$i]}" 2>/dev/null \
        | grep -iE 'panic|error|fail|insufficient' \
        | grep -v 'compile\|warning:\|^warning\|note:' \
        | tail -5
    fi
  done
fi
echo "=> Per-process logs: ${logs[*]}"
echo
echo "=> Per-process run dirs:"
for ((i=0; i<N; i++)); do
  latest=$(inner_dir "$i")
  echo "   process $i → ${latest:-(no dir)}"
done
echo
echo "=> Per-process per-validator gauge peaks:"
for ((i=0; i<N; i++)); do
  echo "--- process $i → ${FN_ARR[$((i % ${#FN_ARR[@]}))]} ---"
  latest=$(inner_dir "$i")
  if [ -n "$latest" ] && [ -f "$latest/summary.txt" ]; then
    grep -A 9 '^\[gauge\] sum(sequencing_certificate_inflight)' "$latest/summary.txt" | head -10
  else
    echo "   (no summary)"
  fi
done

echo
echo "=> Aggregate rejections across all processes:"
total=0
for ((i=0; i<N; i++)); do
  latest=$(inner_dir "$i")
  if [ -n "$latest" ] && [ -f "$latest/summary.txt" ]; then
    n=$(grep -E '^[[:space:]]+TOTAL[[:space:]]+[0-9]+' "$latest/summary.txt" | head -1 | awk '{print $2}')
    echo "   process $i: $n"
    total=$((total + ${n:-0}))
  fi
done
echo "   GRAND TOTAL: $total"

echo
echo "=> TCP errors (EADDRNOTAVAIL) per subprocess:"
tcp_total=0
for ((i=0; i<N; i++)); do
  c=$(grep -c 'AddrNotAvailable\|code: 99' "${logs[$i]}" 2>/dev/null)
  c=${c:-0}
  echo "   process $i (${FN_ARR[$((i % ${#FN_ARR[@]}))]}): $c"
  tcp_total=$((tcp_total + c))
done
echo "   TOTAL: $tcp_total"

echo
echo "=> Peak num_inflight vs sem_cap (max across all process summaries; all see same network metrics):"
# Aggregate across all per-process summaries — some may have empty queries
# (Prometheus timing issues), so we take the max of whatever each captured.
sem_cap=0
peak_inflight=0
for ((i=0; i<N; i++)); do
  latest=$(inner_dir "$i")
  if [ -n "$latest" ] && [ -f "$latest/summary.txt" ]; then
    s=$(awk '/^\[gauge\] sequencing_in_flight_submissions/{f=1; next} /^$/{f=0} f && /peak=/{match($0, /peak=([0-9]+)/, a); print a[1]}' "$latest/summary.txt" | sort -n | tail -1)
    p=$(awk '/^\[gauge\] sum\(sequencing_certificate_inflight\)/{f=1; next} /^$/{f=0} f && /peak=/{match($0, /peak=([0-9]+)/, a); print a[1]}' "$latest/summary.txt" | sort -n | tail -1)
    [ -n "$s" ] && [ "$s" -gt "$sem_cap" ] && sem_cap=$s
    [ -n "$p" ] && [ "$p" -gt "$peak_inflight" ] && peak_inflight=$p
  fi
done
if [ "$sem_cap" -gt 0 ] && [ "$peak_inflight" -gt 0 ]; then
  ratio=$(awk -v p="$peak_inflight" -v s="$sem_cap" 'BEGIN{printf "%.2f", p/s}')
  echo "   sem_cap (max of post-permit peaks): $sem_cap"
  echo "   peak num_inflight (network max):    $peak_inflight"
  echo "   ratio peak/sem_cap:                 ${ratio}×"
else
  echo "   (couldn't compute — no process captured both metrics)"
fi

# Window: spam start → end + a small grace to capture the last scrape.
WINDOW=$(( SPAM_END_EPOCH - SPAM_START_EPOCH + 5 ))
if [ "$WINDOW" -lt 10 ]; then WINDOW=10; fi

# Helper: run an instant PromQL query and print the first sample's value
# as a float, or empty string on error / no result.
prom_scalar() {
  local query="$1"
  if ! command -v curl >/dev/null 2>&1 || ! command -v python3 >/dev/null 2>&1; then
    return
  fi
  curl -sfG --max-time 5 "$PROM_URL/api/v1/query" \
    --data-urlencode "query=$query" 2>/dev/null | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    rs = d.get('data', {}).get('result', [])
    if rs:
        v = float(rs[0]['value'][1])
        print(f'{v:.4f}')
except Exception:
    pass
" 2>/dev/null
}

# Helper: save a query_range time series to a JSON file for later
# cliff-vs-ramp analysis. Step 1s gives second-resolution detail.
prom_range() {
  local query="$1" outfile="$2"
  if ! command -v curl >/dev/null 2>&1; then return; fi
  curl -sfG --max-time 10 "$PROM_URL/api/v1/query_range" \
    --data-urlencode "query=$query" \
    --data-urlencode "start=$SPAM_START_EPOCH" \
    --data-urlencode "end=$SPAM_END_EPOCH" \
    --data-urlencode "step=1s" \
    >"$outfile" 2>/dev/null || rm -f "$outfile"
}

# Pull rejection counts per source from Prometheus over the spam window.
# The graduated check writes 4 distinct labels after the authority.rs split:
#   consensus_graduated_preventive  — num_inflight < max_pending, probabilistic drop
#   consensus_graduated_reactive    — num_inflight >= max_pending, 100% shed (graduated path)
#   consensus_max_pending_exceeded  — num_inflight >= max_pending detected by the
#                                     binary check after graduated passed (race window)
#   consensus_semaphore_no_permits  — submit_semaphore exhausted (independent limit)
declare -A REJECT
REJECT[consensus_graduated_preventive]=0
REJECT[consensus_graduated_reactive]=0
REJECT[consensus_max_pending_exceeded]=0
REJECT[consensus_semaphore_no_permits]=0

if command -v curl >/dev/null 2>&1 && command -v python3 >/dev/null 2>&1; then
  prom_query="sum by (source) (increase(transaction_overload_sources{host=~\"validator.*\"}[${WINDOW}s]))"
  prom_resp=$(curl -sfG --max-time 5 "$PROM_URL/api/v1/query" \
    --data-urlencode "query=$prom_query" 2>/dev/null || echo "")
  if [ -n "$prom_resp" ]; then
    while IFS=$'\t' read -r src val; do
      [ -z "$src" ] && continue
      REJECT[$src]=${val%.*}
    done < <(printf '%s' "$prom_resp" | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    for r in d.get('data', {}).get('result', []):
        s = r['metric'].get('source', '?')
        v = float(r['value'][1])
        print(f'{s}\t{v:.0f}')
except Exception:
    pass
")
  fi
fi

# Throughput, queue distribution, latency, rejection-rate metrics over the
# spam window. We aggregate across the whole committee rather than hardcode
# one host because `NUM_VALIDATORS_TO_TARGET=1` picks the target validator
# randomly per stress.rs run — it's not deterministically validator-1. For
# spam-attack metrics (queue depth, rejection rate), `max()` across hosts
# picks the targeted validator's value because the other validators see no
# spam and stay at 0. For network-wide metrics (TPS, latency) we aggregate
# similarly across hosts.

# Useful TPS: total executed transactions (= effects produced) per second.
# Max across validators — each validator executes the same finalised set
# (it's replicated state), so max() picks the one most up-to-date.
USEFUL_TPS=$(prom_scalar "max(increase(total_transaction_effects{host=~\"validator.*\"}[${WINDOW}s])) / ${WINDOW}")
[ -z "$USEFUL_TPS" ] && USEFUL_TPS=0

# Queue depth distribution during the spam window. `sequencing_certificate_inflight`
# is an IntGaugeVec with a `tx_type` label — sum across types per host
# first, then take max across hosts to surface the targeted validator's
# queue depth. Quantiles are then taken over time via a subquery.
QUEUE_P50=$(prom_scalar "quantile_over_time(0.50, max(sum by (host) (sequencing_certificate_inflight{host=~\"validator.*\"}))[${WINDOW}s:1s])")
QUEUE_P75=$(prom_scalar "quantile_over_time(0.75, max(sum by (host) (sequencing_certificate_inflight{host=~\"validator.*\"}))[${WINDOW}s:1s])")
QUEUE_P99=$(prom_scalar "quantile_over_time(0.99, max(sum by (host) (sequencing_certificate_inflight{host=~\"validator.*\"}))[${WINDOW}s:1s])")
[ -z "$QUEUE_P50" ] && QUEUE_P50=0
[ -z "$QUEUE_P75" ] && QUEUE_P75=0
[ -z "$QUEUE_P99" ] && QUEUE_P99=0

# Rejection rate distribution. `sum(rate(...))` aggregates across all
# `source` labels AND across hosts (the targeted validator's series
# dominates; other validators stay at 0). max_rate (rejs/sec peak across
# 5-sec windows) vs mean_rate characterises cliff vs ramp.
REJECT_RATE_MAX=$(prom_scalar "max_over_time((sum(rate(transaction_overload_sources{host=~\"validator.*\"}[5s])))[${WINDOW}s:5s])")
[ -z "$REJECT_RATE_MAX" ] && REJECT_RATE_MAX=0
TOTAL_REJ=$(( REJECT[consensus_graduated_preventive] + REJECT[consensus_graduated_reactive] + REJECT[consensus_max_pending_exceeded] + REJECT[consensus_semaphore_no_permits] ))
REJECT_RATE_MEAN=$(awk -v t="$TOTAL_REJ" -v w="$WINDOW" 'BEGIN{printf "%.2f", t/w}')

# Admission latency. The validator does not yet expose a full submit_tx
# RPC histogram; tx_verification_latency is the closest existing proxy
# (signature-verification step inside submit_tx_impl). Adding a proper
# end-to-end submit_tx histogram in authority_server/metrics.rs is a small
# follow-up that would give a more accurate number here.
ADMIT_LAT_P99=$(prom_scalar "histogram_quantile(0.99, sum by (le) (rate(validator_service_tx_verification_latency_bucket{host=~\"validator.*\"}[${WINDOW}s])))")
[ -z "$ADMIT_LAT_P99" ] && ADMIT_LAT_P99=0

# Time-series captures for post-hoc analysis (e.g. plotting cliff vs ramp,
# inspecting queue-depth shape during a burst). One JSON per metric, saved
# alongside summary.txt under the run directory. We aggregate across hosts
# so the dumps capture the targeted validator's behaviour without us
# having to know which one was picked.
prom_range "sum by (source) (rate(transaction_overload_sources{host=~\"validator.*\"}[5s]))" \
  "$PARENT_DIR/rejection_rate_by_source.json"
prom_range "max(sum by (host) (sequencing_certificate_inflight{host=~\"validator.*\"}))" \
  "$PARENT_DIR/queue_depth.json"

# Per-pool aggregation. Reads each per-process benchmark_stats.json (written
# by stress.rs to RUNS_DIR/<inner-ts>/benchmark_stats.json via the
# --benchmark-stats-path flag in stress-load-shedding.sh) and sums
# num_success_txes / num_error_txes grouped by pool. With HONEST_PROC_COUNT=0
# the honest pool is empty and the spammer pool equals the whole run.
SPAMMER_SUCCESS=0
SPAMMER_ERROR=0
HONEST_SUCCESS=0
HONEST_ERROR=0
for ((i=0; i<N; i++)); do
  stats_file=$(ls "${runs_dirs[$i]}"/*/benchmark_stats.json 2>/dev/null | head -1)
  if [ -z "$stats_file" ] || [ ! -f "$stats_file" ]; then continue; fi
  read -r succ err < <(python3 -c "
import json, sys
try:
    d = json.load(open('$stats_file'))
    print(d.get('num_success_txes', 0), d.get('num_error_txes', 0))
except Exception:
    print(0, 0)
" 2>/dev/null)
  succ=${succ:-0}
  err=${err:-0}
  if [ "${pool_labels[$i]}" = "honest" ]; then
    HONEST_SUCCESS=$((HONEST_SUCCESS + succ))
    HONEST_ERROR=$((HONEST_ERROR + err))
  else
    SPAMMER_SUCCESS=$((SPAMMER_SUCCESS + succ))
    SPAMMER_ERROR=$((SPAMMER_ERROR + err))
  fi
done
# Derive per-pool TPS and accept-rate. Uses DURATION-seconds field from the
# stats file via Prometheus WINDOW (close enough; the stress.rs duration
# field is the same span).
SPAMMER_TPS=$(awk -v s=$SPAMMER_SUCCESS -v w=$WINDOW 'BEGIN{if(w>0) printf "%.2f", s/w; else print 0}')
HONEST_TPS=$(awk -v s=$HONEST_SUCCESS -v w=$WINDOW 'BEGIN{if(w>0) printf "%.2f", s/w; else print 0}')
SPAMMER_TOTAL=$((SPAMMER_SUCCESS + SPAMMER_ERROR))
HONEST_TOTAL=$((HONEST_SUCCESS + HONEST_ERROR))
SPAMMER_ACCEPT_PCT=$(awk -v s=$SPAMMER_SUCCESS -v t=$SPAMMER_TOTAL 'BEGIN{if(t>0) printf "%.2f", 100.0*s/t; else print 0}')
HONEST_ACCEPT_PCT=$(awk -v s=$HONEST_SUCCESS -v t=$HONEST_TOTAL 'BEGIN{if(t>0) printf "%.2f", 100.0*s/t; else print 0}')

# Extract the targeted-validators line that stress.rs's TD prints at startup.
# All processes select identically (deterministic via sorted display names
# from genesis), so process-0 is representative. Strip tracing's ANSI color
# codes first so the summary line is greppable downstream.
TARGET_VALIDATOR=$(grep "Targeting [0-9]\+ of [0-9]\+ validators" "$PARENT_DIR/process-0.log" 2>/dev/null \
  | tail -1 | sed -r 's/\x1B\[[0-9;]*[mGKHF]//g' | grep -oE '\[[^]]*\]' | tail -1 || echo "?")

# Save a top-level summary so this run is self-contained
{
  echo "ts:           $MASTER_TS"
  echo "config:       QPS_TOTAL=$QPS_TOTAL DURATION=$DURATION WORKERS=$WORKERS IN_FLIGHT_RATIO=$IN_FLIGHT_RATIO BURST_SIZE=$BURST_SIZE BARRIER_PERIOD_MS=$BARRIER_PERIOD_MS GAS_CHUNK_SIZE=$GAS_CHUNK_SIZE NUM_TRANSFER_ACCOUNTS=$NUM_TRANSFER_ACCOUNTS"
  echo "fullnodes:    $FULLNODES"
  echo "target_validator: $TARGET_VALIDATOR"
  echo "exit codes:   ${exit_codes[*]}"
  echo "tcp errors:   $tcp_total"
  if [ "${peak_inflight:-0}" -gt 0 ] && [ "${sem_cap:-0}" -gt 0 ]; then
    echo "sem_cap:      $sem_cap"
    echo "peak inflight:$peak_inflight"
    echo "ratio:        ${ratio:-0}×"
  fi
  echo "reject_grad_preventive: ${REJECT[consensus_graduated_preventive]}"
  echo "reject_grad_reactive:   ${REJECT[consensus_graduated_reactive]}"
  echo "reject_max_pending:     ${REJECT[consensus_max_pending_exceeded]}"
  echo "reject_semaphore:       ${REJECT[consensus_semaphore_no_permits]}"
  echo "useful_tps:             $USEFUL_TPS"
  echo "queue_depth_p50:        $QUEUE_P50"
  echo "queue_depth_p75:        $QUEUE_P75"
  echo "queue_depth_p99:        $QUEUE_P99"
  echo "reject_rate_max:        $REJECT_RATE_MAX"
  echo "reject_rate_mean:       $REJECT_RATE_MEAN"
  echo "admit_lat_p99:          $ADMIT_LAT_P99"
  echo "spammer_proc_count:     $N_SPAMMER"
  echo "honest_proc_count:      $HONEST_PROC_COUNT"
  echo "spammer_success:        $SPAMMER_SUCCESS"
  echo "spammer_error:          $SPAMMER_ERROR"
  echo "spammer_tps:            $SPAMMER_TPS"
  echo "spammer_accept_pct:     $SPAMMER_ACCEPT_PCT"
  echo "honest_success:         $HONEST_SUCCESS"
  echo "honest_error:           $HONEST_ERROR"
  echo "honest_tps:             $HONEST_TPS"
  echo "honest_accept_pct:      $HONEST_ACCEPT_PCT"
} > "$PARENT_DIR/summary.txt"
echo
echo "=> Top-level summary: $PARENT_DIR/summary.txt"
