processed 7 tasks

init:
A: object(0,0)

task 1, lines 9-37:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7432800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 39:
//# run t::m::create --sender A
created: object(2,0), object(2,1), object(2,2), object(2,3)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 7797600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 41:
//# view-object 2,2
Owner: Object ID: ( fake(2,0) )
Version: 2
Contents: t::m::Obj {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,2),
        },
    },
}

task 4, line 43:
//# run t::m::share --args object(2,2) --sender A
Error: Error checking transaction input objects: InvalidChildObjectArgument { child_id: object(2,2), parent_id: object(2,0) }

task 5, line 45:
//# run t::m::share_wrapped --args object(2,2) --sender A
Error: Error checking transaction input objects: InvalidChildObjectArgument { child_id: object(2,2), parent_id: object(2,0) }

task 6, line 47:
//# run t::m::share_child --args object(2,2) --sender A
Error: Error checking transaction input objects: InvalidChildObjectArgument { child_id: object(2,2), parent_id: object(2,0) }
