processed 16 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 14-27:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 5168000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 29:
//# run Test::M1::create --args 0 @A --sender A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 31:
//# run Test::M1::create --args 0 @A --sender A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 4, line 33:
//# run Test::M1::create --args 0 @A --sender A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 5, line 35:
//# run Test::M1::create --args 0 @A --sender A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 6, line 37:
//# create-checkpoint
Checkpoint created: 1

task 7, line 39:
//# run Test::M1::create --args 0 @A --sender A
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 8, line 41:
//# run Test::M1::create --args 0 @A --sender A
created: object(8,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 9, line 43:
//# run Test::M1::create --args 0 @A --sender A
created: object(9,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 10, line 45:
//# create-checkpoint
Checkpoint created: 2

task 11, line 47:
//# run Test::M1::create --args 0 @A --sender A
created: object(11,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 12, line 49:
//# run Test::M1::create --args 0 @A --sender A
created: object(12,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 13, line 51:
//# create-checkpoint
Checkpoint created: 3

task 14, lines 53-77:
//# run-graphql
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "sequenceNumber": 0,
          "transactionBlocks": {
            "edges": []
          }
        },
        {
          "sequenceNumber": 1,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0IjoyLCJpIjpmYWxzZX0",
                "node": {
                  "digest": "7BPdUc3LpRmchBjPiSZ5Uju5yDZMbVhTQNYjDjmTXP5D",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOgqlyHReHTY5weyEZOqIFQo+bdy3dX6B6ZXq8EnpHkGAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0IjozLCJpIjpmYWxzZX0",
                "node": {
                  "digest": "3s48BKV1NGNPV5VRKFsAJKWiyUiWDLVxguSERpo8qRTV",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOgqlyHReHTY5weyEZOqIFQo+bdy3dX6B6ZXq8EnpHkGAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo0LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "6adEehTM2gxGKdumJXeKFwcaYhSB6RwGHbqg7Fv7JBmk",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOgqlyHReHTY5weyEZOqIFQo+bdy3dX6B6ZXq8EnpHkGAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo1LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "E4Lt2ME1UNXjXnuVzF9CMyrHnhdQWbWRXj3myqpzZMrP",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOgqlyHReHTY5weyEZOqIFQo+bdy3dX6B6ZXq8EnpHkGAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        },
        {
          "sequenceNumber": 2,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0Ijo2LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "DEYu7BBRqZyroncK1on7suMYzHy7GLJMoSsC6K8d14BR",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOgqlyHReHTY5weyEZOqIFQo+bdy3dX6B6ZXq8EnpHkGAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo3LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "32S1CoAgaGv7diFo2Bs7StnPB7Aakoma1JUT4k4cUpA7",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOgqlyHReHTY5weyEZOqIFQo+bdy3dX6B6ZXq8EnpHkGAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo4LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "3gEc6E6ypnwUqRtVBcF3ZwXPEQJaisXDDaK21p4sZyM8",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOgqlyHReHTY5weyEZOqIFQo+bdy3dX6B6ZXq8EnpHkGAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        },
        {
          "sequenceNumber": 3,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0Ijo5LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "6RpeYVhE2pRoKHE4yP99YreciLexUN7WtKDG3qrRpTpE",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOgqlyHReHTY5weyEZOqIFQo+bdy3dX6B6ZXq8EnpHkGAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0IjoxMCwiaSI6ZmFsc2V9",
                "node": {
                  "digest": "HFhCBUpVFLKMXW3GT7of6iyZJCnMerKdLNRsZE9KVR5C",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOgqlyHReHTY5weyEZOqIFQo+bdy3dX6B6ZXq8EnpHkGAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}

task 15, lines 79-96:
//# run-graphql
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "sequenceNumber": 0,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 1,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 2,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 3,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        }
      ]
    }
  }
}
