processed 16 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 14-27:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 5168000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 29:
//# run Test::M1::create --args 0 @A --sender A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 31:
//# run Test::M1::create --args 0 @A --sender A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 4, line 33:
//# run Test::M1::create --args 0 @A --sender A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 5, line 35:
//# run Test::M1::create --args 0 @A --sender A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 6, line 37:
//# create-checkpoint
Checkpoint created: 1

task 7, line 39:
//# run Test::M1::create --args 0 @A --sender A
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 8, line 41:
//# run Test::M1::create --args 0 @A --sender A
created: object(8,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 9, line 43:
//# run Test::M1::create --args 0 @A --sender A
created: object(9,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 10, line 45:
//# create-checkpoint
Checkpoint created: 2

task 11, line 47:
//# run Test::M1::create --args 0 @A --sender A
created: object(11,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 12, line 49:
//# run Test::M1::create --args 0 @A --sender A
created: object(12,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 13, line 51:
//# create-checkpoint
Checkpoint created: 3

task 14, lines 53-77:
//# run-graphql
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "sequenceNumber": 0,
          "transactionBlocks": {
            "edges": []
          }
        },
        {
          "sequenceNumber": 1,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0IjoyLCJpIjpmYWxzZX0",
                "node": {
                  "digest": "424aeEdunZxaA4t67RDP3AgJPK8AqRKwk8DT32729XQ2",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IP2qtaGuffpjrZ0U8hNfi/hoDvFrKgpoIzz8dFUVdC9DAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0IjozLCJpIjpmYWxzZX0",
                "node": {
                  "digest": "FJWVYP8B4ZxzT33reAXN1XLdTZJRQFafHf1rMEM7szAV",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IP2qtaGuffpjrZ0U8hNfi/hoDvFrKgpoIzz8dFUVdC9DAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo0LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "Csu5YAKSsZMPG5yUyWeKXJXUcBvC1yFeG7SEkeU2eadA",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IP2qtaGuffpjrZ0U8hNfi/hoDvFrKgpoIzz8dFUVdC9DAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo1LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "6MhFF74hrKhLDhS2iTj8eBbfD1QKeycDYoetbn4SeXvH",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IP2qtaGuffpjrZ0U8hNfi/hoDvFrKgpoIzz8dFUVdC9DAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        },
        {
          "sequenceNumber": 2,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0Ijo2LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "y5Doq1ScLBByfZyD5NVMe9earv7ctdG594SNN71ZRya",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IP2qtaGuffpjrZ0U8hNfi/hoDvFrKgpoIzz8dFUVdC9DAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo3LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "CbmAUd1Cp3PqQWALBbbjPts7geaXKTTGAwmSRzRu4kA4",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IP2qtaGuffpjrZ0U8hNfi/hoDvFrKgpoIzz8dFUVdC9DAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo4LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "8ZCZBGHxe5Cuvgq5FDLc8A4Gj3kEnHoyxef7MFeiKcNo",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IP2qtaGuffpjrZ0U8hNfi/hoDvFrKgpoIzz8dFUVdC9DAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        },
        {
          "sequenceNumber": 3,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0Ijo5LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "Axd1JSnBT4YT5JZsvD1k3HKvVEcgEgc1kR1mNGJLWnJ3",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IP2qtaGuffpjrZ0U8hNfi/hoDvFrKgpoIzz8dFUVdC9DAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0IjoxMCwiaSI6ZmFsc2V9",
                "node": {
                  "digest": "6eqwxyVPb8sGiP8zSUdPz1R5CVkHY5jJCyW9HBTM2yRN",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IP2qtaGuffpjrZ0U8hNfi/hoDvFrKgpoIzz8dFUVdC9DAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}

task 15, lines 79-96:
//# run-graphql
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "sequenceNumber": 0,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 1,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 2,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 3,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        }
      ]
    }
  }
}
