processed 26 tasks

init:
validator_0: object(0,0)

task 1, lines 7-26:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 5563200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 28:
//# run Test::M1::create --args 0 @A --gas-price 1000
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 3, line 30:
//# run Test::M1::create --args 0 @validator_0
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 4, line 32:
//# view-object 0,0
Owner: Account Address ( validator_0 )
Version: 1
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(0,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 300000000000000u64,
    },
}

task 5, line 34:
//# view-object 2,0
Owner: Account Address ( A )
Version: 3
Contents: Test::M1::Object {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    value: 0u64,
}

task 6, line 36:
//# view-object 3,0
Owner: Account Address ( validator_0 )
Version: 4
Contents: Test::M1::Object {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(3,0),
        },
    },
    value: 0u64,
}

task 7, line 38:
//# create-checkpoint 4
Checkpoint created: 4

task 8, line 40:
//# view-checkpoint
CheckpointSummary { epoch: 0, seq: 4, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 3000000, computation_cost_burned: 3000000, storage_cost: 10138400, storage_rebate: 1960800, non_refundable_storage_fee: 0 }}

task 9, line 42:
//# advance-epoch 6
Epoch advanced: 5

task 10, line 44:
//# view-checkpoint
CheckpointSummary { epoch: 5, seq: 10, content_digest: FAcXi2nPPF4jiTvbzWdPDfYJ6Tt6Z1VdcMivM2FWWu5W,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, computation_cost_burned: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 11, lines 46-51:
//# run-graphql
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    }
  }
}

task 12, line 53:
//# create-checkpoint
Checkpoint created: 11

task 13, line 55:
//# view-checkpoint
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, computation_cost_burned: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 14, lines 57-62:
//# run-graphql
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  }
}

task 15, lines 64-69:
//# run-graphql --show-usage --show-headers --show-service-version
Headers: {
    "content-type": "application/json",
    "content-length": "157",
    "x-iota-rpc-version": "0.9.0-testing-no-sha",
    "vary": "origin, access-control-request-method, access-control-request-headers",
    "access-control-allow-origin": "*",
}
Service version: 0.9.0-testing-no-sha
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 2,
      "outputNodes": 2,
      "depth": 2,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 41
    }
  }
}

task 16, line 71:
//# view-checkpoint
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, computation_cost_burned: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 17, lines 73-76:
//# advance-epoch
Epoch advanced: 6

task 18, lines 78-93:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x99135a7080d0b2a927284717a20c8bafce374f36dd8d5f4928e26c6433ba5ec6",
              "digest": "8kdRf7efUdbrQYA3ZFPUnxMhxkUqoUMecdXjqw7hgF6M",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    }
  }
}

task 19, lines 95-150:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": []
      }
    },
    "second": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x99135a7080d0b2a927284717a20c8bafce374f36dd8d5f4928e26c6433ba5ec6",
              "digest": "8kdRf7efUdbrQYA3ZFPUnxMhxkUqoUMecdXjqw7hgF6M",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    },
    "val_objs": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x1018b36a7497429904bc316d13943c2575e8b0b95e9fb78da173236033b9dcc8",
              "digest": "DJrwxDXFzxz1Tn7dttP7d3THZobBGz7HssdbMWVMsKaN",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x222a93adabcb62de4426070d385418753704b0d881cb5965923c0cdbab531e00",
              "digest": "614kBDnFrW5nbH4Fh2RQygBF3EiWAmy4cPC97EsLzq3Q",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x244d0ee8c2de7fba1464d1bb2c813a244196ec7c6ce8aa7d915d6bdc64c64217",
              "digest": "5RNHwbe6yN5diHr6s837tLwuv1LzNn9o9UoJrQRTpKR4",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x72e3c78b1a7949e55e291745f3e44c423fd6dcddeb00012dfa81b994647c552d",
              "digest": "2ipY4J5VkK1dXznqHHngPdWnT2zqtqhtqkaLWy3McW64",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x9448ced828b28e01e6ecea8827a5476c3ea65dda6384c2d2bad2427ea3848b5d",
              "digest": "HdXZYwxjaG6LtNaij1qodD5TmtbmgA9pAMrcVTX6Suwy",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x954705871e318ba8de121943084b47a25d42930d7471841971d73402e1e067a5",
              "digest": "7ACHuevnnrbKivHhah2mLJqT3oNzj8UFL3jESA3DqGT5",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xa75a0fca99b6b9c5bc8d318df60f7c1ab1328a82de0e2c2a6e4619b1627e6277",
              "digest": "6eKVj2NEGLFUeQBA3ibFSnJUAs2TtYSE5oCr5c5CYB2F",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xb0027d9b634e7d91f66eff316a097c92ae54ccc9a4f5081b8d5c076c6c0de10b",
              "digest": "GoXEwrQsNzH4KTtHH1qtDyXaANT9rBN9P6rrrwHjt7an",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xd70ac75a9489aa0a673a8f8ccd5d4e3e84ade6cf9d2c44d8ba1ce5acb042e02b",
              "digest": "6z2kE7MAKFf7KiGb9Z9YmDRvdqhGmKWvBm7ucYti1c1V",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xd98228affe398ab3bc22286d6b7b11da1442f113d0f2c298a7548c72c8483657",
              "digest": "7W9jXYAuxaTRKkXDq7P1oQc5yvX6GymBxnAc55DhtMXy",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xfba59abaf5940f30567b53f21a580203b3e5766f51cbeeab8f15de918bf14fb1",
              "digest": "BMLPLmewFqYTNc1gMh3Ynddc4THkWz78aFMwSDGDuaFN",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xfdbb048a42da963846f56edf3ce2c1adf991b5c2f6ed81c22e956a83ff14c16f",
              "digest": "3NwtLgi3VgSYQD4nrnCSUZGNHPHGKRfidG3GYNdVtWyK",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    },
    "object": {
      "version": 3,
      "owner": {
        "__typename": "AddressOwner",
        "owner": {
          "address": "0x0000000000000000000000000000000000000000000000000000000000000042"
        }
      }
    }
  }
}

task 20, lines 152-168:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "validatorSet": {
        "activeValidators": {
          "nodes": [
            {
              "address": {
                "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
              }
            }
          ]
        }
      }
    },
    "address": {
      "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
    }
  }
}

task 21, lines 170-176:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "referenceGasPrice": "234"
    }
  }
}

task 22, line 178:
//# run Test::M1::create --args 0 @A --gas-price 999
created: object(22,0)
mutated: object(0,1)
gas summary: computation_cost: 999000, computation_cost_burned: 999000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 23, line 180:
//# run Test::M1::create --args 0 @A --gas-price 1000
created: object(23,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 24, line 182:
//# run Test::M1::create --args 0 @A --gas-price 235
created: object(24,0)
mutated: object(0,1)
gas summary: computation_cost: 235000, computation_cost_burned: 235000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 25, lines 184-189:
//# run-graphql
Response: {
  "data": {
    "serviceConfig": {
      "availableVersions": [
        "0.9"
      ]
    }
  }
}
