processed 26 tasks

init:
validator_0: object(0,0)

task 1, lines 7-26:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 234000, storage_cost: 5563200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 28:
//# run Test::M1::create --args 0 @A --gas-price 1000
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 234000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 3, line 30:
//# run Test::M1::create --args 0 @validator_0
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 234000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 4, line 32:
//# view-object 0,0
Owner: Account Address ( validator_0 )
Version: 1
Contents: iota_system::staking_pool::StakedIota {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(0,0),
        },
    },
    pool_id: iota::object::ID {
        bytes: _,
    },
    stake_activation_epoch: 0u64,
    principal: iota::balance::Balance<iota::iota::IOTA> {
        value: 1500000000000000u64,
    },
}

task 5, line 34:
//# view-object 2,0
Owner: Account Address ( A )
Version: 3
Contents: Test::M1::Object {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    value: 0u64,
}

task 6, line 36:
//# view-object 3,0
Owner: Account Address ( validator_0 )
Version: 4
Contents: Test::M1::Object {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(3,0),
        },
    },
    value: 0u64,
}

task 7, line 38:
//# create-checkpoint 4
Checkpoint created: 4

task 8, line 40:
//# view-checkpoint
CheckpointSummary { epoch: 0, seq: 4, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 3000000, computation_cost_burned: 702000, storage_cost: 10138400, storage_rebate: 1960800, non_refundable_storage_fee: 0 }}

task 9, line 42:
//# advance-epoch 6
Epoch advanced: 5

task 10, line 44:
//# view-checkpoint
CheckpointSummary { epoch: 5, seq: 10, content_digest: FENGtPVwPw5vcptja5ykgfp92DMRu8SgpKuixgeHoHx4,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, computation_cost_burned: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 11, lines 46-51:
//# run-graphql
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    }
  }
}

task 12, line 53:
//# create-checkpoint
Checkpoint created: 11

task 13, line 55:
//# view-checkpoint
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, computation_cost_burned: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 14, lines 57-62:
//# run-graphql
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  }
}

task 15, lines 64-69:
//# run-graphql --show-usage --show-headers --show-service-version
Headers: {
    "content-type": "application/json",
    "content-length": "157",
    "x-iota-rpc-version": "0.11.0-testing-no-sha",
    "vary": "origin, access-control-request-method, access-control-request-headers",
    "access-control-allow-origin": "*",
}
Service version: 0.11.0-testing-no-sha
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 2,
      "outputNodes": 2,
      "depth": 2,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 41
    }
  }
}

task 16, line 71:
//# view-checkpoint
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, computation_cost_burned: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 17, lines 73-76:
//# advance-epoch
Epoch advanced: 6

task 18, lines 78-93:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x9d499da0d46d3b16d1558000f72bf19ab5494131150f6923e73634a4df9baac8",
              "digest": "HPGs84UynbgbQi7SZratrDxVxYyGmit2YnJ3XhAfncgw",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    }
  }
}

task 19, lines 95-150:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": []
      }
    },
    "second": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x9d499da0d46d3b16d1558000f72bf19ab5494131150f6923e73634a4df9baac8",
              "digest": "HPGs84UynbgbQi7SZratrDxVxYyGmit2YnJ3XhAfncgw",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    },
    "val_objs": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x122bee69d717e6e35f5da21ab6db6039527b90213fb370cf5d85baa98af57bfc",
              "digest": "7NxhhPjvfxWGNgaWoFKA8aE2yj3BqBY1kZAYzg4PQHpr",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x1b17d55f62475ecc5340dc637c24a492a60c75da3d00b2c33b5d58b2ece0be9a",
              "digest": "8Ecx9J882A8SQFmkGYFXhGjEViR32XFTcuqTXVagQ77b",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x2b82c1522d6f4ac762e34b2842ad25a0d18527465a3e8ac97e1b0b37fa8b1d1b",
              "digest": "GjHDD8pxe1MCH8i6ZDvCC7MnBV8Tes6ZYt5Zdsb8JVe",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x3ef26752db86a6c902f0bd74a5533147b2e0ade90fdc011b63c6857eb0185d03",
              "digest": "8tUZA4UMexZpDjF3nSw9KbpvdXjASLjbpNwv6Zor6sqq",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x4e8d6ddae7864680be2add5e44cb0c10fcac666b141103b9a6b5637694aa8f7c",
              "digest": "Ce3dPiw66KpFqo1xTd1E294Xf6KJGXExEM4S9n651Jat",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x6188230917472c4bdf281f7eade822598836d75443dd15bd68e941d5f3fb76aa",
              "digest": "8FZuVAFKXp35mw5xegdTuRjwRQbNc8y36WKD57b8dkdk",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x704fb07df8f2f7fb1640d26c066b66a8f2192ab0ca05aa12ebc489eec6635096",
              "digest": "BB4JeUfdm9sBqymTBzBdLQhyoScr2fgg7sU5gxHXGS51",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x80c5c249c4c846eff3a64a04289cc47c658e26a07ae9a2575ec5f5c66d25b90d",
              "digest": "3M7kPPT2PN487kozuxq2ck2G99h13twFQqaD9dr9i5ds",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x8e9d526e6e48948fec2e9c6e971b472fee7fb11eddc257c047a5fb7655c66dce",
              "digest": "784JQDjPMB3XXxomx9VUDsNX4naSMbjGT2XhQQZHEWqK",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x901de39f5f34a630f009047bc68d4783cb5bc15e1dacc4a24e19ed96049f531c",
              "digest": "4MeWC1rnfADttXmQpBpasDtujv3hmJdCe9XhR9FDyDCY",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xaf6cc809f167cc6461248e7361755ade86f07e2551444ddba313729d51e175bd",
              "digest": "AyeaLZGA3D3DmW6mJcXfeF3cFaTACiZSoFue24gsdyyk",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xd2e4d21dda191085edbdddcfbc138d04690a2751ebdfc38bbf30eb3fddbf6f9e",
              "digest": "9JVgMGG2r1B9WoD6ZUMU3X9YhJV2bXuW3SjfLGp61TA2",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    },
    "object": {
      "version": 3,
      "owner": {
        "__typename": "AddressOwner",
        "owner": {
          "address": "0x0000000000000000000000000000000000000000000000000000000000000042"
        }
      }
    }
  }
}

task 20, lines 152-168:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "validatorSet": {
        "activeValidators": {
          "nodes": [
            {
              "address": {
                "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
              }
            }
          ]
        }
      }
    },
    "address": {
      "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
    }
  }
}

task 21, lines 170-176:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "referenceGasPrice": "234"
    }
  }
}

task 22, line 178:
//# run Test::M1::create --args 0 @A --gas-price 999
created: object(22,0)
mutated: object(0,1)
gas summary: computation_cost: 999000, computation_cost_burned: 234000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 23, line 180:
//# run Test::M1::create --args 0 @A --gas-price 1000
created: object(23,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 234000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 24, line 182:
//# run Test::M1::create --args 0 @A --gas-price 235
created: object(24,0)
mutated: object(0,1)
gas summary: computation_cost: 235000, computation_cost_burned: 234000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 25, lines 184-189:
//# run-graphql
Response: {
  "data": {
    "serviceConfig": {
      "availableVersions": [
        "0.11"
      ]
    }
  }
}
