#!/usr/bin/env python3
"""make_calibration_table.py — render the calibration CSVs as markdown tables.

Writes results/calibration-tables.md: one per-machine table for each calibration
CSV that exists, plus a cross-machine comparison table when both are present.
These are the tables folded into probe-test.md. Pure stdlib; no venv.
"""

import csv
import glob
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "results")
OUT = os.path.join(RES, "calibration-tables.md")


def label_from(path):
    """calibration-<cpu-slug>.csv -> machine label (e.g. 'EPYC 9454P')."""
    slug = os.path.basename(path)[len("calibration-") : -len(".csv")]
    return slug.replace("-", " ").upper()


def load(path):
    return list(csv.DictReader(open(path)))


def cu(x):
    x = float(x)
    return f"{x:,.0f}" if x >= 1000 else f"{x:.0f}"


def order(rows):
    return sorted(rows, key=lambda r: (int(r["product"]), int(r["slow_n"])))


# Discover every machine's sweep: results/calibration-<cpu-slug>.csv. Nothing
# hardcoded — probe.sh names each file from the CPU it ran on.
paths = sorted(glob.glob(os.path.join(RES, "calibration-*.csv")))
present = [(label_from(p), load(p)) for p in paths]
if not present:
    raise SystemExit("no calibration-*.csv found in results/")

lines = ["# Calibration tables (generated by make_calibration_table.py)\n"]
for name, rows in present:
    lines.append(f"\n## {name} ({len(rows)} points)\n")
    lines.append(
        "| n | size | product | CU | exec mean (ms) | exec sem (ms) | samples |"
    )
    lines.append("| --- | --- | --- | --- | --- | --- | --- |")
    for r in order(rows):
        lines.append(
            f"| {r['slow_n']} | {r['slow_size']} | {int(r['product']):,} | "
            f"{cu(r['actual_cu'])} | {float(r['exec_mean_ms']):.3f} | "
            f"{float(r['exec_sem_ms']):.3f} | {r['n_samples']} |"
        )

# Cross-machine comparison, only if exactly two machines are present.
if len(present) == 2:
    (na, ra), (nb, rb) = present
    A = {(int(r["slow_n"]), int(r["slow_size"])): r for r in ra}
    B = {(int(r["slow_n"]), int(r["slow_size"])): r for r in rb}
    keys = sorted(set(A) & set(B), key=lambda k: (int(A[k]["product"]), k[0]))
    lines.append(f"\n## {na} vs {nb} ({len(keys)} shared points)\n")
    lines.append(f"| product | n×size | CU | {na} exec (ms) | {nb} exec (ms) | ratio |")
    lines.append("| --- | --- | --- | --- | --- | --- |")
    for k in keys:
        a, b = A[k], B[k]
        ea, eb = float(a["exec_mean_ms"]), float(b["exec_mean_ms"])
        lines.append(
            f"| {int(a['product']):,} | {k[0]}×{k[1]} | {cu(a['actual_cu'])} | "
            f"{ea:.3f} | {eb:.3f} | {eb / ea:.2f} |"
        )

with open(OUT, "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote", OUT)
