#!/usr/bin/env python3
"""make_calibration_table.py — render the calibration CSVs as markdown tables.

Writes results/probe/calibration-tables.md: one per-machine table for each
calibration CSV that exists, plus a cross-machine comparison table when more
than one is present, and for each groth16-<machine>.csv one table per curve
and function, plus a cross-machine groth16 comparison when more than one is
present. These are the tables folded into PROBE.md. Pure stdlib; no venv.
"""

import csv
import glob
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "results", "probe")
OUT = os.path.join(RES, "calibration-tables.md")

# Production runs TotalTxCount with these per-object, per-commit limits (config
# keys max_accumulated_txn_cost_per_object_in_mysticeti_commit and
# max_congestion_limit_overshoot_per_commit), counting each transaction as 1
# regardless of cost. Under TotalComputationUnits the same base/overshoot become
# CU limits scaled by the per-transaction cost — the mapping table below.
BASE_TXNS = 10
OVERSHOOT_TXNS = 100


def label_from(path, prefix="calibration-"):
    """<prefix><cpu-slug>.csv -> machine label (e.g. 'EPYC 9454P')."""
    slug = os.path.basename(path)[len(prefix) : -len(".csv")]
    return slug.replace("-", " ").upper()


def load(path):
    return list(csv.DictReader(open(path)))


def cu(x):
    x = float(x)
    return f"{x:,.0f}" if x >= 1000 else f"{x:.0f}"


def order(rows):
    return sorted(rows, key=lambda r: (int(r["product"]), int(r["slow_n"])))


# Discover every machine's sweep: results/probe/calibration-<cpu-slug>.csv.
# Nothing hardcoded — probe.sh names each file from the CPU it ran on. Sorted
# by machine label, so a machine's plain run comes before its "-turbo" run.
paths = sorted(glob.glob(os.path.join(RES, "calibration-*.csv")), key=label_from)
present = [(label_from(p), load(p)) for p in paths]
g16_paths = sorted(
    glob.glob(os.path.join(RES, "groth16-*.csv")),
    key=lambda p: label_from(p, "groth16-"),
)
if not present and not g16_paths:
    raise SystemExit("no calibration-*.csv or groth16-*.csv found in results/probe/")

lines = ["# Calibration tables (generated by make_calibration_table.py)\n"]
for name, rows in present:
    lines.append(f"\n## {name} ({len(rows)} points)\n")
    lines.append(
        "| n | size | product | CU | exec mean (ms) | exec sem (ms) | samples |"
    )
    lines.append("| --- | --- | --- | --- | --- | --- | --- |")
    for r in order(rows):
        lines.append(
            f"| {r['slow_n']} | {r['slow_size']} | {int(r['product']):,} | "
            f"{cu(r['actual_cu'])} | {float(r['exec_mean_ms']):.3f} | "
            f"{float(r['exec_sem_ms']):.3f} | {r['n_samples']} |"
        )

# Cross-machine comparison, when more than one machine is present: one
# execution-time column per machine, then each later machine's time divided by
# the first machine's.
if len(present) >= 2:
    keyed = [
        (name, {(int(r["slow_n"]), int(r["slow_size"])): r for r in rows})
        for name, rows in present
    ]
    first_name, first = keyed[0]
    keys = sorted(
        set.intersection(*(set(d) for _, d in keyed)),
        key=lambda k: (int(first[k]["product"]), k[0]),
    )
    lines.append(f"\n## Across machines ({len(keys)} shared points)\n")
    lines.append(
        "| product | n×size | CU | "
        + " | ".join(f"{name} exec (ms)" for name, _ in keyed)
        + " | "
        + " | ".join(f"{name} / {first_name}" for name, _ in keyed[1:])
        + " |"
    )
    lines.append("| " + " | ".join(["---"] * (2 * len(keyed) + 2)) + " |")
    for k in keys:
        rows_k = [d[k] for _, d in keyed]
        execs = [float(r["exec_mean_ms"]) for r in rows_k]
        # CU is machine-independent and measured exactly per transaction, so
        # every machine reports the same value; max() is just defensive
        # against a stale CSV.
        true_cu = max(float(r["actual_cu"]) for r in rows_k)
        lines.append(
            f"| {int(rows_k[0]['product']):,} | {k[0]}×{k[1]} | {cu(true_cu)} | "
            + " | ".join(f"{e:.3f}" for e in execs)
            + " | "
            + " | ".join(f"{e / execs[0]:.2f}" for e in execs[1:])
            + " |"
        )

# TotalTxCount -> TotalComputationUnits limit mapping (machine-independent: CU
# is protocol-defined). Each distinct per-tx CU maps the production count limits
# to CU limits — base = BASE_TXNS × CU, overshoot = OVERSHOOT_TXNS × CU.
cu_values = sorted({float(r["actual_cu"]) for _, rows in present for r in rows})
if cu_values:
    lines.append(
        f"\n## TotalTxCount (base {BASE_TXNS}, overshoot {OVERSHOOT_TXNS}) "
        "→ TotalComputationUnits limits\n"
    )
    lines.append(
        f"| CU per tx | base limit (×{BASE_TXNS}) | overshoot (×{OVERSHOOT_TXNS}) |"
    )
    lines.append("| --- | --- | --- |")
    for v in cu_values:
        lines.append(f"| {cu(v)} | {cu(v * BASE_TXNS)} | {cu(v * OVERSHOOT_TXNS)} |")

# groth16 (W8) points: results/probe/groth16-<cpu-slug>.csv, written by
# `probe.sh` with WORKLOAD=groth16. One table per machine, curve and function.
G16_ORDER = {"bn254": 0, "bls12381": 1, "verify": 0, "prepare": 1}


def g16_workloads(rows):
    return sorted(
        {(r["curve"], r["function"]) for r in rows},
        key=lambda w: (G16_ORDER.get(w[0], 9), w[0], G16_ORDER.get(w[1], 9), w[1]),
    )


g16_present = [(label_from(p, "groth16-"), load(p)) for p in g16_paths]
for name, rows in g16_present:
    for curve, function in g16_workloads(rows):
        sel = sorted(
            (r for r in rows if (r["curve"], r["function"]) == (curve, function)),
            key=lambda r: (int(r["calls"]), int(r["start_epoch"])),
        )
        lines.append(f"\n## {name}: groth16 {curve} {function} ({len(sel)} points)\n")
        lines.append("| calls | CU | exec mean (ms) | exec sem (ms) | samples |")
        lines.append("| --- | --- | --- | --- | --- |")
        for r in sel:
            lines.append(
                f"| {r['calls']} | {cu(r['actual_cu'])} | "
                f"{float(r['exec_mean_ms']):.3f} | {float(r['exec_sem_ms']):.3f} | "
                f"{r['n_samples']} |"
            )

# groth16 cross-machine comparison, when more than one machine is present: one
# table per workload, over the calls every machine measured, laid out like the
# slow comparison above.
if len(g16_present) >= 2:
    first_name = g16_present[0][0]
    for curve, function in g16_workloads([r for _, rows in g16_present for r in rows]):
        keyed = [
            (
                name,
                {
                    int(r["calls"]): r
                    for r in rows
                    if (r["curve"], r["function"]) == (curve, function)
                },
            )
            for name, rows in g16_present
        ]
        calls = sorted(set.intersection(*(set(d) for _, d in keyed)))
        if not calls:
            continue
        lines.append(
            f"\n## Across machines: groth16 {curve} {function} "
            f"({len(calls)} shared points)\n"
        )
        lines.append(
            "| calls | CU | "
            + " | ".join(f"{name} exec (ms)" for name, _ in keyed)
            + " | "
            + " | ".join(f"{name} / {first_name}" for name, _ in keyed[1:])
            + " |"
        )
        lines.append("| " + " | ".join(["---"] * (2 * len(keyed) + 1)) + " |")
        for k in calls:
            rows_k = [d[k] for _, d in keyed]
            execs = [float(r["exec_mean_ms"]) for r in rows_k]
            # As for slow: CU is protocol-defined, so every machine reports the
            # same value; max() is only defensive.
            true_cu = max(float(r["actual_cu"]) for r in rows_k)
            lines.append(
                f"| {k} | {cu(true_cu)} | "
                + " | ".join(f"{e:.3f}" for e in execs)
                + " | "
                + " | ".join(f"{e / execs[0]:.2f}" for e in execs[1:])
                + " |"
            )

with open(OUT, "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote", OUT)
