#!/usr/bin/env python3
"""make_calibration_table.py — render the calibration CSVs as markdown tables.

Writes results/probe/calibration-tables.md: one per-machine table for each
calibration CSV that exists, plus a cross-machine comparison table when both
are present, and for each groth16-<machine>.csv one table per curve and
function, plus a cross-machine groth16 comparison when both are present.
These are the tables folded into probe-test.md. Pure stdlib; no venv.
"""

import csv
import glob
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "results", "probe")
OUT = os.path.join(RES, "calibration-tables.md")

# Production runs TotalTxCount with these per-object, per-commit limits (config
# keys max_accumulated_txn_cost_per_object_in_mysticeti_commit and
# max_congestion_limit_overshoot_per_commit), counting each transaction as 1
# regardless of cost. Under TotalComputationUnits the same base/overshoot become
# CU limits scaled by the per-transaction cost — the mapping table below.
BASE_TXNS = 10
OVERSHOOT_TXNS = 100


def label_from(path, prefix="calibration-"):
    """<prefix><cpu-slug>.csv -> machine label (e.g. 'EPYC 9454P')."""
    slug = os.path.basename(path)[len(prefix) : -len(".csv")]
    return slug.replace("-", " ").upper()


def load(path):
    return list(csv.DictReader(open(path)))


def cu(x):
    x = float(x)
    return f"{x:,.0f}" if x >= 1000 else f"{x:.0f}"


def order(rows):
    return sorted(rows, key=lambda r: (int(r["product"]), int(r["slow_n"])))


# Discover every machine's sweep: results/probe/calibration-<cpu-slug>.csv.
# Nothing hardcoded — probe.sh names each file from the CPU it ran on.
paths = sorted(glob.glob(os.path.join(RES, "calibration-*.csv")))
present = [(label_from(p), load(p)) for p in paths]
g16_paths = sorted(glob.glob(os.path.join(RES, "groth16-*.csv")))
if not present and not g16_paths:
    raise SystemExit("no calibration-*.csv or groth16-*.csv found in results/probe/")

lines = ["# Calibration tables (generated by make_calibration_table.py)\n"]
for name, rows in present:
    lines.append(f"\n## {name} ({len(rows)} points)\n")
    lines.append(
        "| n | size | product | CU | exec mean (ms) | exec sem (ms) | samples |"
    )
    lines.append("| --- | --- | --- | --- | --- | --- | --- |")
    for r in order(rows):
        lines.append(
            f"| {r['slow_n']} | {r['slow_size']} | {int(r['product']):,} | "
            f"{cu(r['actual_cu'])} | {float(r['exec_mean_ms']):.3f} | "
            f"{float(r['exec_sem_ms']):.3f} | {r['n_samples']} |"
        )

# Cross-machine comparison, only if exactly two machines are present.
if len(present) == 2:
    (na, ra), (nb, rb) = present
    A = {(int(r["slow_n"]), int(r["slow_size"])): r for r in ra}
    B = {(int(r["slow_n"]), int(r["slow_size"])): r for r in rb}
    keys = sorted(set(A) & set(B), key=lambda k: (int(A[k]["product"]), k[0]))
    lines.append(f"\n## {na} vs {nb} ({len(keys)} shared points)\n")
    lines.append(f"| product | n×size | CU | {na} exec (ms) | {nb} exec (ms) | ratio |")
    lines.append("| --- | --- | --- | --- | --- | --- |")
    for k in keys:
        a, b = A[k], B[k]
        ea, eb = float(a["exec_mean_ms"]), float(b["exec_mean_ms"])
        # CU is machine-independent and measured exactly per transaction, so both
        # machines report the same value; max() is just defensive against a stale
        # CSV.
        true_cu = max(float(a["actual_cu"]), float(b["actual_cu"]))
        lines.append(
            f"| {int(a['product']):,} | {k[0]}×{k[1]} | {cu(true_cu)} | "
            f"{ea:.3f} | {eb:.3f} | {eb / ea:.2f} |"
        )

# TotalTxCount -> TotalComputationUnits limit mapping (machine-independent: CU
# is protocol-defined). Each distinct per-tx CU maps the production count limits
# to CU limits — base = BASE_TXNS × CU, overshoot = OVERSHOOT_TXNS × CU.
cu_values = sorted({float(r["actual_cu"]) for _, rows in present for r in rows})
if cu_values:
    lines.append(
        f"\n## TotalTxCount (base {BASE_TXNS}, overshoot {OVERSHOOT_TXNS}) "
        "→ TotalComputationUnits limits\n"
    )
    lines.append(
        f"| CU per tx | base limit (×{BASE_TXNS}) | overshoot (×{OVERSHOOT_TXNS}) |"
    )
    lines.append("| --- | --- | --- |")
    for v in cu_values:
        lines.append(f"| {cu(v)} | {cu(v * BASE_TXNS)} | {cu(v * OVERSHOOT_TXNS)} |")

# groth16 (W8) points: results/probe/groth16-<cpu-slug>.csv, written by
# `probe.sh` with WORKLOAD=groth16. One table per machine, curve and function.
G16_ORDER = {"bn254": 0, "bls12381": 1, "verify": 0, "prepare": 1}


def g16_workloads(rows):
    return sorted(
        {(r["curve"], r["function"]) for r in rows},
        key=lambda w: (G16_ORDER.get(w[0], 9), w[0], G16_ORDER.get(w[1], 9), w[1]),
    )


g16_present = [(label_from(p, "groth16-"), load(p)) for p in g16_paths]
for name, rows in g16_present:
    for curve, function in g16_workloads(rows):
        sel = sorted(
            (r for r in rows if (r["curve"], r["function"]) == (curve, function)),
            key=lambda r: (int(r["calls"]), int(r["start_epoch"])),
        )
        lines.append(f"\n## {name}: groth16 {curve} {function} ({len(sel)} points)\n")
        lines.append("| calls | CU | exec mean (ms) | exec sem (ms) | samples |")
        lines.append("| --- | --- | --- | --- | --- |")
        for r in sel:
            lines.append(
                f"| {r['calls']} | {cu(r['actual_cu'])} | "
                f"{float(r['exec_mean_ms']):.3f} | {float(r['exec_sem_ms']):.3f} | "
                f"{r['n_samples']} |"
            )

# groth16 cross-machine comparison, only if exactly two machines are present:
# one table per workload, over the calls both machines measured.
if len(g16_present) == 2:
    (na, ra), (nb, rb) = g16_present
    for curve, function in g16_workloads(ra + rb):
        A = {
            int(r["calls"]): r
            for r in ra
            if (r["curve"], r["function"]) == (curve, function)
        }
        B = {
            int(r["calls"]): r
            for r in rb
            if (r["curve"], r["function"]) == (curve, function)
        }
        calls = sorted(set(A) & set(B))
        if not calls:
            continue
        lines.append(
            f"\n## {na} vs {nb}: groth16 {curve} {function} "
            f"({len(calls)} shared points)\n"
        )
        lines.append(f"| calls | CU | {na} exec (ms) | {nb} exec (ms) | ratio |")
        lines.append("| --- | --- | --- | --- | --- |")
        for k in calls:
            a, b = A[k], B[k]
            ea, eb = float(a["exec_mean_ms"]), float(b["exec_mean_ms"])
            # As for slow: CU is protocol-defined, so both machines report the
            # same value; max() is only defensive.
            true_cu = max(float(a["actual_cu"]), float(b["actual_cu"]))
            lines.append(
                f"| {k} | {cu(true_cu)} | {ea:.3f} | {eb:.3f} | {eb / ea:.2f} |"
            )

with open(OUT, "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote", OUT)
