processed 17 tasks

init:
A: object(0,0)

task 1, lines 7-87:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 10579200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 89-90:
//# run P0::M::new_o
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2249600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 3, lines 92-93:
//# run P0::M::new_w
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2242000,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 4, lines 95-96:
//# run P0::M::new_dof
created: object(4,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2257200,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 5, lines 98-99:
//# run P0::M::new_dof
created: object(5,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2257200,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 6, lines 102-105:
//# run P0::M::connect --args object(2,0) object(3,0) object(4,0) object(5,0)
created: object(6,0), object(6,1)
mutated: object(0,1), object(2,0), object(4,0), object(5,0)
wrapped: object(3,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 9895200,  storage_rebate: 6064800, non_refundable_storage_fee: 0

task 7, lines 107-109:
//# view-object 2,0
Owner: Account Address ( _ )
Version: 7
Contents: P0::M::O {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 0u64,
    wrapped: std::option::Option<P0::M::W> {
        vec: vector[
            P0::M::W {
                id: iota::object::UID {
                    id: iota::object::ID {
                        bytes: fake(3,0),
                    },
                },
                count: 0u64,
            },
        ],
    },
}

task 8, lines 111-112:
//# run P0::M::touch_root --args object(2,0)
mutated: object(0,1), object(2,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2553600,  storage_rebate: 2553600, non_refundable_storage_fee: 0

task 9, lines 114-115:
//# run P0::M::touch_wrapped --args object(2,0)
mutated: object(0,1), object(2,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2553600,  storage_rebate: 2553600, non_refundable_storage_fee: 0

task 10, lines 117-118:
//# run P0::M::touch_inner --args object(2,0)
mutated: object(0,1), object(2,0), object(4,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3830400,  storage_rebate: 3830400, non_refundable_storage_fee: 0

task 11, lines 120-121:
//# run P0::M::touch_outer --args object(2,0)
mutated: object(0,1), object(2,0), object(5,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3830400,  storage_rebate: 3830400, non_refundable_storage_fee: 0

task 12, line 123:
//# view-object 2,0
Owner: Account Address ( _ )
Version: 11
Contents: P0::M::O {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 1u64,
    wrapped: std::option::Option<P0::M::W> {
        vec: vector[
            P0::M::W {
                id: iota::object::UID {
                    id: iota::object::ID {
                        bytes: fake(3,0),
                    },
                },
                count: 1u64,
            },
        ],
    },
}

task 13, line 125:
//# create-checkpoint
Checkpoint created: 1

task 14, lines 127-142:
//# run-graphql
Response: {
  "data": {
    "latest": {
      "asObject": {
        "asMoveObject": {
          "version": 11,
          "contents": {
            "json": {
              "id": "0x4e2eb4ff25f0bf308ef0b032ba93a4c17f50d6333b55d50c8f6a336a26781a26",
              "count": "1",
              "wrapped": {
                "id": "0xedd75c5b4691eac9bf5f986f58098a8583912d09cc9fefb3810bff61d1b3b1f5",
                "count": "1"
              }
            }
          }
        }
      }
    },
    "versioned": {
      "asObject": {
        "asMoveObject": {
          "version": 10,
          "contents": {
            "json": {
              "id": "0x4e2eb4ff25f0bf308ef0b032ba93a4c17f50d6333b55d50c8f6a336a26781a26",
              "count": "1",
              "wrapped": {
                "id": "0xedd75c5b4691eac9bf5f986f58098a8583912d09cc9fefb3810bff61d1b3b1f5",
                "count": "1"
              }
            }
          }
        }
      }
    },
    "beforeWrappedBump": {
      "asObject": {
        "asMoveObject": {
          "version": 8,
          "contents": {
            "json": {
              "id": "0x4e2eb4ff25f0bf308ef0b032ba93a4c17f50d6333b55d50c8f6a336a26781a26",
              "count": "1",
              "wrapped": {
                "id": "0xedd75c5b4691eac9bf5f986f58098a8583912d09cc9fefb3810bff61d1b3b1f5",
                "count": "0"
              }
            }
          }
        }
      }
    },
    "beforeBump": {
      "asObject": {
        "asMoveObject": {
          "version": 7,
          "contents": {
            "json": {
              "id": "0x4e2eb4ff25f0bf308ef0b032ba93a4c17f50d6333b55d50c8f6a336a26781a26",
              "count": "0",
              "wrapped": {
                "id": "0xedd75c5b4691eac9bf5f986f58098a8583912d09cc9fefb3810bff61d1b3b1f5",
                "count": "0"
              }
            }
          }
        }
      }
    }
  }
}

task 15, lines 144-172:
//# run-graphql
Response: {
  "data": {
    "unversioned": {
      "dynamicObjectField": {
        "value": {
          "version": 7,
          "contents": {
            "json": {
              "id": "0x83ce2f1b5214c74b93c0f540fb88c9b83351a74938f33b57d9aa77de0c6cbd34",
              "count": "0"
            }
          }
        }
      }
    },
    "latest": {
      "dynamicObjectField": {
        "value": {
          "version": 10,
          "contents": {
            "json": {
              "id": "0x83ce2f1b5214c74b93c0f540fb88c9b83351a74938f33b57d9aa77de0c6cbd34",
              "count": "1"
            }
          }
        }
      }
    },
    "afterFirstInnerBump": {
      "dynamicObjectField": {
        "value": {
          "version": 10,
          "contents": {
            "json": {
              "id": "0x83ce2f1b5214c74b93c0f540fb88c9b83351a74938f33b57d9aa77de0c6cbd34",
              "count": "1"
            }
          }
        }
      }
    },
    "beforeFirstInnerBump": {
      "dynamicObjectField": {
        "value": {
          "version": 7,
          "contents": {
            "json": {
              "id": "0x83ce2f1b5214c74b93c0f540fb88c9b83351a74938f33b57d9aa77de0c6cbd34",
              "count": "0"
            }
          }
        }
      }
    },
    "beforeBumps": {
      "dynamicObjectField": {
        "value": {
          "version": 7,
          "contents": {
            "json": {
              "id": "0x83ce2f1b5214c74b93c0f540fb88c9b83351a74938f33b57d9aa77de0c6cbd34",
              "count": "0"
            }
          }
        }
      }
    }
  }
}

task 16, lines 174-195:
//# run-graphql
Response: {
  "data": {
    "unversioned": {
      "dynamicObjectField": {
        "value": {
          "version": 7,
          "contents": {
            "json": {
              "id": "0xc80897cd3a556d87c0768f8ec3fcea03b8099bd762bcc9847af2aaf7422dff38",
              "count": "0"
            }
          }
        }
      }
    },
    "latest": {
      "dynamicObjectField": {
        "value": {
          "version": 11,
          "contents": {
            "json": {
              "id": "0xc80897cd3a556d87c0768f8ec3fcea03b8099bd762bcc9847af2aaf7422dff38",
              "count": "1"
            }
          }
        }
      }
    },
    "beforeInnerBump": {
      "dynamicObjectField": {
        "value": {
          "version": 7,
          "contents": {
            "json": {
              "id": "0xc80897cd3a556d87c0768f8ec3fcea03b8099bd762bcc9847af2aaf7422dff38",
              "count": "0"
            }
          }
        }
      }
    }
  }
}
