[package]
name = "abstract_account"
version = "0.0.1"
edition = "2024"

[dependencies]
Iota = { local = "../../../crates/iota-framework/packages/iota-framework" }

[addresses]
abstract_account = "0x0"
