#!/bin/bash

# Copyright (c) 2024 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0

set -e

ROOT=$(git rev-parse --show-toplevel || realpath "$(dirname "$0")/../..")
PRIVNET_DIR="$(realpath "$(dirname "$0")" || echo "$ROOT/dev-tools/iota-private-network")"

TEMP_EXPORT_DIR="${TEMP_EXPORT_DIR-"$PRIVNET_DIR/configs/temp"}"
VALIDATOR_CONFIGS_DIR="$PRIVNET_DIR/configs/validators"
GENESIS_DIR="$PRIVNET_DIR/configs/genesis"
OVERLAY_PATH="$PRIVNET_DIR/configs/validator-common.yaml"
# Parse `-n` for number of validators (default 4), `-e` for epoch duration (default 1200000),
# and `-b` to include deterministic benchmark gas accounts for use with the stress tool.
NUM_VALIDATORS=4
EPOCH_DURATION_MS=1200000
FLAG_SPECIFIED=false
BENCHMARK_MODE=false
# Number of deterministic benchmark gas accounts to generate when -b is set.
# Each account becomes a `--primary-gas-owner-id` for one stress subprocess,
# so this should be >= the maximum NUM_PROCS used by stress-multi.sh.
# Per-account gas amount is sized to fit u64 total supply at this count.
NUM_BENCHMARK_ACCOUNTS="${NUM_BENCHMARK_ACCOUNTS:-96}"
BENCHMARK_GAS_PER_ACCOUNT="${BENCHMARK_GAS_PER_ACCOUNT:-150000000000000000}"
while getopts "n:e:b" opt; do
  case "$opt" in
    n) NUM_VALIDATORS="$OPTARG"; FLAG_SPECIFIED=true ;;
    e) EPOCH_DURATION_MS="$OPTARG"; FLAG_SPECIFIED=true ;;
    b) BENCHMARK_MODE=true; FLAG_SPECIFIED=true ;;
    *) echo "Usage: $0 [-n num_validators] [-e epoch_duration_ms] [-b]"; exit 1 ;;
  esac
done

generate_genesis_template_if_missing() {
    mkdir -p "$PRIVNET_DIR/configs"
    GENESIS_TEMPLATE="$PRIVNET_DIR/configs/genesis-template-${NUM_VALIDATORS}.yaml"
    GENESIS_BLOB="$GENESIS_DIR/genesis.blob"

    if [[ -f "$GENESIS_TEMPLATE" ]] && [[ -f "$GENESIS_BLOB" ]] && [[ "$FLAG_SPECIFIED" == "false" ]]; then
        echo "Genesis template already exists: $GENESIS_TEMPLATE"
    else
        echo "Generating genesis template for $NUM_VALIDATORS validators (epoch: ${EPOCH_DURATION_MS}ms)..."
        cat > "$GENESIS_TEMPLATE" <<EOF
accounts:
  - address: "0xd59d79516a4ed5b6825e80826c075a12bdd2759aaeb901df2f427f5f880c8f60"
    gas_amounts:
      - 750000000000000000
      - 750000000000000000
  - address: "0x160ef6ce4f395208a12119c5011bf8d8ceb760e3159307c819bd0197d154d384"
    gas_amounts:
      - 20000000000000000
      - 20000000000000000
      - 20000000000000000
      - 20000000000000000
      - 20000000000000000
  - address: "0x7cc6ff19b379d305b8363d9549269e388b8c1515772253ed4c868ee80b149ca0"
    gas_amounts:
      - 750000000000000000
EOF

        if [[ "$BENCHMARK_MODE" == "true" ]]; then
            # Deterministic benchmark gas accounts generated by
            # GenesisConfig::benchmark_gas_keys() with the BENCHMARKS_RNG_SEED.
            # The helper writes both the keystore (consumed by the validators)
            # and emits the YAML account block (appended to the genesis
            # template). Addresses and keys stay in sync because both derive
            # from the same seeded RNG.
            HELPER_BIN="$ROOT/target/release/print-benchmark-accounts"
            if [[ ! -x "$HELPER_BIN" ]]; then
                echo "Building helper: cargo build --release -p iota-localnet --bin print-benchmark-accounts"
                (cd "$ROOT" && cargo build --release -p iota-localnet --bin print-benchmark-accounts)
            fi
            "$HELPER_BIN" \
                --count "$NUM_BENCHMARK_ACCOUNTS" \
                --gas-per-account "$BENCHMARK_GAS_PER_ACCOUNT" \
                --keystore-path "$GENESIS_DIR/benchmark.keystore" \
                >> "$GENESIS_TEMPLATE"
            echo "Benchmark gas accounts added to genesis template (${NUM_BENCHMARK_ACCOUNTS} stress owners @ ${BENCHMARK_GAS_PER_ACCOUNT} each)"
        fi

        cat >> "$GENESIS_TEMPLATE" <<EOF
parameters:
  allow_insertion_of_extra_objects: false
  epoch_duration_ms: $EPOCH_DURATION_MS
validator_config_info:
EOF

        for i in $(seq 1 $NUM_VALIDATORS); do
            cat >> "$GENESIS_TEMPLATE" <<EOF
  - commission_rate: 0
    gas_price: 1000
    name: validator-${i}
    primary_address: /dns/validator-${i}/udp/8081
    network_address: /dns/validator-${i}/tcp/8080/http
    p2p_address: /dns/validator-${i}/udp/8084
    stake: 20000000000000000
EOF
        done

        cat >> "$GENESIS_TEMPLATE" <<EOF
migration_sources: []
EOF
        echo "Genesis template generated: $GENESIS_TEMPLATE"
    fi
}


shift $((OPTIND-1))

# Select the matching genesis template
GENESIS_TEMPLATE="$PRIVNET_DIR/configs/genesis-template-${NUM_VALIDATORS}.yaml"

PRIVATE_DATA_DIR="$PRIVNET_DIR/data"

check_docker_image_exist() {
  if ! docker image inspect "$1" >/dev/null 2>&1; then
    echo "Error: Docker image $1 not found."
    exit 1
  fi
}

check_configs_exist() {
  if [ ! -f "$1" ]; then
    echo "Error: $(basename "$1") not found at "$1""
    exit 1
  fi
}

generate_genesis_files() {
  mkdir -p "$TEMP_EXPORT_DIR"

  # Generate genesis using the selected template
  TMP_GENESIS_TEMPLATE="$(basename "$GENESIS_TEMPLATE")"
  docker run --rm \
    -v "$PRIVNET_DIR:/iota" \
    -v "$TEMP_EXPORT_DIR:/iota/configs/temp" \
    -w /iota \
    iotaledger/iota-tools \
    /usr/local/bin/iota-localnet genesis \
      --from-config "/iota/configs/$TMP_GENESIS_TEMPLATE" \
      --working-dir "/iota/configs/temp" -f

  for file in "$TEMP_EXPORT_DIR"/validator*.yaml; do
    if [ -f "$file" ]; then
      yq eval-all '
        select(fileIndex == 1).validator as $overlay |
        select(fileIndex == 0) |
        .network-address = $overlay.network-address |
        .metrics-address = $overlay.metrics-address |
        .json-rpc-address = $overlay.json-rpc-address |
        .admin-interface-address = $overlay.admin-interface-address |
        .genesis.genesis-file-location = $overlay.genesis.genesis-file-location |
        .db-path = $overlay.db-path |
        .consensus-config.db-path = $overlay.consensus-config.db-path |
        .consensus-config.max-pending-transactions = $overlay.consensus-config.max-pending-transactions |
        .consensus-config.max-pending-local-submissions = $overlay.consensus-config.max-pending-local-submissions |
        .consensus-config.graduated-load-shedding-soft-limit-pct = $overlay.consensus-config.graduated-load-shedding-soft-limit-pct |
        .expensive-safety-check-config = $overlay.expensive-safety-check-config |
        .epoch_duration_ms = $overlay.epoch_duration_ms
      ' "$file" "$OVERLAY_PATH" >"${file}.tmp" && mv "${file}.tmp" "$file"
    fi
  done

  # copy generated validator configs
  for src_validator_config_filepath in "$TEMP_EXPORT_DIR"/validator*; do
    src_filename=$(basename -- "$src_validator_config_filepath")
    dest_filepath="$VALIDATOR_CONFIGS_DIR/$src_filename"

    # delete if directory (happens if docker-compose was started without the file being present)
    if [ -d "$dest_filepath" ] && [ -n "$dest_filepath" ] && (echo "$dest_filepath" | grep -q "configs/validators/validator-"); then
      rm -rf "$dest_filepath"
    fi
    if [ -e "$src_validator_config_filepath" ]; then
      mv "$src_validator_config_filepath" "$VALIDATOR_CONFIGS_DIR/"
    fi
  done

  genesis_dest_filepath="$GENESIS_DIR/genesis.blob"
  echo "$genesis_dest_filepath"
  # delete if directory (happens if docker-compose was started without the file being present)
  if [ -d "$genesis_dest_filepath" ] && [ -n "$genesis_dest_filepath" ] && (echo "$genesis_dest_filepath" | grep -q "iota-private-network/configs/genesis/genesis.blob"); then
    rm -rf "$genesis_dest_filepath"
  fi
  mv "$TEMP_EXPORT_DIR/genesis.blob" "$GENESIS_DIR/"

  rm -rf "$TEMP_EXPORT_DIR"
}

generate_benchmark_keystore() {
  echo "Generating benchmark keystore..."
  local BENCH_TEMP_DIR
  BENCH_TEMP_DIR="$(mktemp -d)"
  # Generate a temporary benchmark genesis to extract the keystore.
  # The dummy IPs don't matter — only the deterministic keys are needed.
  local DUMMY_IPS
  DUMMY_IPS=$(printf '127.0.0.1%.0s,' $(seq 1 "$NUM_VALIDATORS") | sed 's/,$//')
  docker run --rm \
    -v "$BENCH_TEMP_DIR:/bench" \
    iotaledger/iota-tools \
    /usr/local/bin/iota-localnet genesis \
      --benchmark-ips "$DUMMY_IPS" \
      --working-dir /bench \
      --force

  if [[ -f "$BENCH_TEMP_DIR/benchmark.keystore" ]]; then
    # Merge the auto-generated 4 deterministic keys with 20 additional stress-5..24
    # keys we use for multi-fullnode stress tests (one gas owner per subprocess).
    # 24 owners → NUM_PROCS up to 24.
    python3 -c "
import json, sys
auto = json.load(open('$BENCH_TEMP_DIR/benchmark.keystore'))
extra = [
    {'alias': 'stress-5', 'address': '0x9d7e87c7519b31853f3c3cc471cff15e4dd910c55588acb0c3b8237847e04134',
     'key': {'type': 'key_pair', 'value': 'iotaprivkey1qz3gu28qyn293d07zwcm9y7perswzfgfl536nt9f2yqpmz06kez768nx3dp'}},
    {'alias': 'stress-6', 'address': '0x4380e818ee8f001795742ad87be2dcd6eebf0624884a8871557f3be997aca35b',
     'key': {'type': 'key_pair', 'value': 'iotaprivkey1qrtl7ltkqrtcdcwzkpstuyfpq93ljyrykschwxw7re2fll2kkwkfcd345ct'}},
    {'alias': 'stress-7', 'address': '0x9fa4e43c1bebd3d787b44022e7e4c96ff5977456099842cf464d707dde02328d',
     'key': {'type': 'key_pair', 'value': 'iotaprivkey1qzkq848hz9yddrzu6v44kraxhzzcyd9cmhdjxly9qszty4pulyhnupmfv46'}},
    {'alias': 'stress-8', 'address': '0x6ab84f85ea9c40b3eb6841b66c7baaf63b271c3f198a5b2260b74d007c8c71f5',
     'key': {'type': 'key_pair', 'value': 'iotaprivkey1qpwjhf8qamd6naargjtxfd09n9ssy7uwkputw0gqykluf6al22psg3vpmz0'}},
    {'alias': 'stress-9', 'address': '0x5bbc757c117d79fe27533af0c3d112b85299385e8935be0f167b5184222afd12',
     'key': {'type': 'key_pair', 'value': 'iotaprivkey1qpvnjvksgm7k0u2y6qxmv4wfyeagssexph5w84p6xs74py3x0dp7gm9nssh'}},
    {'alias': 'stress-10', 'address': '0xccc9e62219640cd2c0f48ef49daf8c9755e74c03f649a3ecd2d576b9b03a135f',
     'key': {'type': 'key_pair', 'value': 'iotaprivkey1qp0jcgaxkk3kahnvp9wmjlehk7uhgy94ntmjzettyu2mlzjm2zws65zlw46'}},
    {'alias': 'stress-11', 'address': '0x88d4be6e3236eee110de5c592c90615ddbe6999688ad91c766609f03ad64f6e4',
     'key': {'type': 'key_pair', 'value': 'iotaprivkey1qpqxv5dvfq7zdsaa8v5rwnw40qku0sqac6p706mlhx5aklc728vekw3qfpu'}},
    {'alias': 'stress-12', 'address': '0x0aad9e9dadacdee74a393efeec28ed60090750a7f6d63343ff1cadf280144402',
     'key': {'type': 'key_pair', 'value': 'iotaprivkey1qp276zva7yskmzpv8hg9hewsr2cfddyu9l2kcnee5jjlkcupdlakjuhzece'}},
    {'alias': 'stress-13', 'address': '0xb2dc6c370b5f475c281c6a7b15f5974acf7fbd331ace6b3f38c9c42c48ba6031',
     'key': {'type': 'key_pair', 'value': 'iotaprivkey1qryusx2g5awhqgg0f56d9l6aceqgjn3pp9ca3dclr36vet6qzme4vey6rfu'}},
    {'alias': 'stress-14', 'address': '0xde7b523dafefc8695cc117e168324bfd01b60be7dda1d173177f699feafde734',
     'key': {'type': 'key_pair', 'value': 'iotaprivkey1qr3h66v39cc83c0j9dm9n6q9964hs3ysshphw6tq0c0r07u0h4tu7zje6z9'}},
    {'alias': 'stress-15', 'address': '0x450451005bf6cf8ec46424ba399e020528dcc3cd3f945edd9551ffb3cd309d56',
     'key': {'type': 'key_pair', 'value': 'iotaprivkey1qqdcflh0w7al6psl8jagdgllxxm7a0c49x3w09set4rjw9f8hjqhugqtm5p'}},
    {'alias': 'stress-16', 'address': '0x293210fa0f212e3bdb988a2b413b0579a0f74ca6cf6ca46fa73c801552ea2e52',
     'key': {'type': 'key_pair', 'value': 'iotaprivkey1qzlc6dj9032xect84n4xjmjvcghcjhdxkskcs4fpsf620s87ncakgxy74ym'}},
    {'alias': 'stress-17', 'address': '0xa45fe7c6081c17266a26f7e2cd3da78d5363a88d3d0358a2365f291ff3a52208',
     'key': {'type': 'key_pair', 'value': 'iotaprivkey1qpf4cu6lcn3kvyy28pwp86ey5q9psgup004kkqra3raa3zvgpt986vzcct8'}},
    {'alias': 'stress-18', 'address': '0x0fff519f4245be4ceb3015f0fa863d97c54f733386e2f72ee294160157b5017f',
     'key': {'type': 'key_pair', 'value': 'iotaprivkey1qprx0gtxqquv55z0zx39l46hw9y3etuuzxpeuj5r8qnm8eclqr55673znm3'}},
    {'alias': 'stress-19', 'address': '0x11c8aa01f82e52aa8200f8c9b4662937bf4ad7a67b066a610a38db38d8343055',
     'key': {'type': 'key_pair', 'value': 'iotaprivkey1qrvazg0kxhysg9q5a2hly3gw0lldlqjtgdtfhhfzp0hkkul4lw4m5h6u6wz'}},
    {'alias': 'stress-20', 'address': '0xf0ff2adeb165d77035bc76f656200929d4675bc83e72815fae3895fc1a6efa1a',
     'key': {'type': 'key_pair', 'value': 'iotaprivkey1qpf640f8f3g04fnw53dtc4u93yg9cygm8xvzkjsaekkjckmms3r8vm6mhgu'}},
    {'alias': 'stress-21', 'address': '0x0d488eda069891f1c4025edd9ed1dfc5af77ad317713366fc13f17515a2503b2',
     'key': {'type': 'key_pair', 'value': 'iotaprivkey1qped20pgvlygckxsawhzx4qjedqxpd8eu652yv8fhyudaxuncp5y5z0gmy7'}},
    {'alias': 'stress-22', 'address': '0x9b0f7453fe23ee5908edf08fa16b708077ad8ba6c85e9f812bec43871d7aabb3',
     'key': {'type': 'key_pair', 'value': 'iotaprivkey1qzakf8g6zgv430kzqdrq825qhydmmtvp2dl4jkss4aa4g58duhpq7ca5rfe'}},
    {'alias': 'stress-23', 'address': '0xbdf67fb29e2fb7052a063fbf3d7ee4491171fb9c7dff8c832c87a38eb011ef2d',
     'key': {'type': 'key_pair', 'value': 'iotaprivkey1qzpy3mzfkv4qe8cugtxcl50k3h0t5frv7vutx080w3f5w8s6wuuzvfw67fz'}},
    {'alias': 'stress-24', 'address': '0x7fbb8146800a060450e0ae653c34d147e5301b1b2bbd056980da5e4fa72b19e8',
     'key': {'type': 'key_pair', 'value': 'iotaprivkey1qz5d78kfxpvqs3sztwttf6x2es6lrae43etlgjumpn09uft093dfypnrg57'}},
]
auto['keys'].extend(extra)
with open('$GENESIS_DIR/benchmark.keystore', 'w') as f:
    json.dump(auto, f, indent=2)
print('Appended 20 stress-5..24 keys')
"
    echo "Benchmark keystore saved to $GENESIS_DIR/benchmark.keystore"
    echo ""
    echo "To run the stress tool against this network:"
    echo "  cargo run --release -p iota-benchmark --bin stress -- \\"
    echo "    --local false \\"
    echo "    --fullnode-rpc-addresses http://127.0.0.1:9000 \\"
    echo "    --use-fullnode-for-execution true \\"
    echo "    --use-fullnode-for-reconfig true \\"
    echo "    --genesis-blob-path $GENESIS_DIR/genesis.blob \\"
    echo "    --keystore-path $GENESIS_DIR/benchmark.keystore \\"
    echo "    --primary-gas-owner-id 0xf479d29837d22943aba6afc401f518a36521b990874eca784886185bd26bf681 \\"
    echo "    --num-client-threads 4 --num-transfer-accounts 10 --run-duration 120s \\"
    echo "    bench --target-qps 500 --in-flight-ratio 5 --num-workers 12 \\"
    echo "    --transfer-object 100 --shared-counter 0"
  else
    echo "Warning: benchmark.keystore was not generated"
  fi
  rm -rf "$BENCH_TEMP_DIR"
}

create_folder_for_postgres() {
  mkdir -p "$PRIVATE_DATA_DIR/primary" "$PRIVATE_DATA_DIR/replica"
  if [ "$(uname -s)" == "Linux" ]; then
    chown -R 999:999 "$PRIVATE_DATA_DIR/primary" "$PRIVATE_DATA_DIR/replica"
  fi
  chmod 0755 "$PRIVATE_DATA_DIR/primary" "$PRIVATE_DATA_DIR/replica"
}

main() {
  if [[ "$OSTYPE" != "darwin"* && "$EUID" -ne 0 ]]; then
      echo "Please run as root or with sudo"
      exit 1
    fi
  
  [ -d "$TEMP_EXPORT_DIR" ] && rm -rf "$TEMP_EXPORT_DIR"

  [ -d "$PRIVATE_DATA_DIR" ] && ./cleanup.sh

  # Generate genesis template if missing
  generate_genesis_template_if_missing

  # Only check overlay file existence
  check_configs_exist "$OVERLAY_PATH"

  for image in "iotaledger/iota-tools" "iotaledger/iota-node" "iotaledger/iota-indexer"; do
    check_docker_image_exist "$image"
  done

  generate_genesis_files

  # Re-write the benchmark keystore after generate_genesis_files. The
  # `iota-localnet genesis --from-config` step (running inside the cached
  # iota-tools image) writes its own benchmark.keystore with random keys
  # via the --from-config code path. Re-running our helper here restores
  # the deterministic keys that match the YAML addresses.
  if [[ "$BENCHMARK_MODE" == "true" ]]; then
    HELPER_BIN="$ROOT/target/release/print-benchmark-accounts"
    if [[ -x "$HELPER_BIN" ]]; then
      "$HELPER_BIN" \
        --count "$NUM_BENCHMARK_ACCOUNTS" \
        --gas-per-account "$BENCHMARK_GAS_PER_ACCOUNT" \
        --keystore-path "$GENESIS_DIR/benchmark.keystore" \
        >/dev/null
      echo "Restored deterministic benchmark.keystore (${NUM_BENCHMARK_ACCOUNTS} keys)"
    fi
  fi

  create_folder_for_postgres

  echo "Done"
}

main
