// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2024 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

use std::{
    collections::{BTreeMap, HashSet},
    fmt::{self, Debug, Display, Formatter, Write},
    fs,
    path::PathBuf,
};

use anyhow::{Result, anyhow, bail};
use clap::*;
use colored::Colorize;
use fastcrypto::{
    encoding::{Base64, Encoding},
    traits::{KeyPair, ToFromBytes},
};
use iota_genesis_builder::validator_info::GenesisValidatorInfo;
use iota_grpc_client::{Client, ReadMask, read_mask_fields::EpochField};
use iota_json_rpc_types::IotaTransactionBlockResponse;
use iota_keys::{
    key_derive::generate_new_key,
    keypair_file::{
        read_authority_keypair_from_file, read_network_keypair_from_file,
        write_authority_keypair_to_file, write_keypair_to_file,
    },
    keystore::{AccountKeystore, StoredKey},
};
use iota_sdk::wallet_context::WalletContext;
use iota_sdk_types::{
    Address, Identifier, ObjectId, Owner, TypeTag,
    crypto::{Intent, IntentMessage, IntentScope},
};
use iota_types::{
    base_types::ObjectRef,
    crypto::{
        AuthorityKeyPair, AuthorityPublicKey, AuthorityPublicKeyBytes, DEFAULT_EPOCH_ID,
        IotaKeyPair, NetworkKeyPair, NetworkPublicKey, Signable, SignatureScheme,
        generate_proof_of_possession, get_authority_key_pair,
    },
    dynamic_field::{Field, derive_dynamic_field_id},
    iota_system_state::{
        IotaSystemState, IotaSystemStateTrait, Validator,
        iota_system_state_inner_v1::{UnverifiedValidatorOperationCap, ValidatorV1},
        iota_system_state_summary::{IotaSystemStateSummary, IotaValidatorSummary},
    },
    multiaddr::Multiaddr,
    object::Object,
    transaction::{CallArg, Transaction, TransactionData, TransactionDataAPI},
};
use serde::Serialize;
use tabled::{
    builder::Builder,
    settings::{
        Alignment, Modify, Style,
        object::{Column, Columns},
    },
};

use crate::{PrintableResult, signing::sign_transaction};

#[path = "unit_tests/validator_tests.rs"]
#[cfg(test)]
mod validator_tests;

const DEFAULT_GAS_BUDGET: u64 = 200_000_000; // 0.2 IOTA

#[derive(Parser)]
pub enum IotaValidatorCommand {
    /// Generate a `validator.info` file and 4 key pair files (account, network,
    /// authority, protocol).
    MakeValidatorInfo {
        name: String,
        description: String,
        image_url: String,
        project_url: String,
        host_name: String,
    },
    /// Submit an on-chain transaction to become a validator candidate. The
    /// parameter is the file path to the `validator.info` generated by
    /// `MakeValidatorInfo`.
    BecomeCandidate {
        #[arg(name = "validator-info-path")]
        file: PathBuf,
        #[arg(name = "gas-budget", long)]
        gas_budget: Option<u64>,
    },
    /// Once you collect enough staking amount, run this command to become an
    /// active validator. It will become active and eligible to join the
    /// committee starting from next epoch.
    JoinValidators {
        /// Gas budget for this transaction.
        #[arg(name = "gas-budget", long)]
        gas_budget: Option<u64>,
    },
    /// Leave active validators (and possibly the committee) starting with the
    /// next epoch.
    LeaveValidators {
        /// Gas budget for this transaction.
        #[arg(name = "gas-budget", long)]
        gas_budget: Option<u64>,
    },
    /// Display metadata about the validator.
    DisplayMetadata {
        #[arg(name = "validator-address")]
        validator_address: Option<Address>,
    },
    /// Update the validator metadata.
    UpdateMetadata {
        #[command(subcommand)]
        metadata: MetadataUpdate,
        /// Gas budget for this transaction.
        #[arg(name = "gas-budget", long)]
        gas_budget: Option<u64>,
    },
    /// Report or un-report a validator as bad or non-performant.
    ReportValidator {
        /// Optional when sender is reporter validator itself and it holds the
        /// Cap object. Required when sender is not the reporter
        /// validator itself. Validator's OperationCap ID can be found
        /// by using the `display-metadata` subcommand.
        #[arg(name = "operation-cap-id", long)]
        operation_cap_id: Option<ObjectId>,
        /// The IOTA Address of the validator is being reported or un-reported
        #[arg(name = "reportee-address")]
        reportee_address: Address,
        /// If true, undo an existing report.
        #[arg(name = "undo-report", long)]
        undo_report: Option<bool>,
        /// Gas budget for this transaction.
        #[arg(name = "gas-budget", long)]
        gas_budget: Option<u64>,
    },
    /// Serialize the payload that is used to generate Proof of Possession.
    /// This is useful to take the payload offline for an Authority protocol
    /// keypair to sign.
    #[command(name = "serialize-payload-pop")]
    SerializePayloadForPoP {
        /// Authority account address encoded in hex with 0x prefix.
        #[arg(name = "account-address", long)]
        account_address: Address,
        /// Authority public key encoded in hex.
        #[arg(name = "authority-public-key", long)]
        authority_public_key: AuthorityPublicKeyBytes,
    },
    /// Get a list of the validators in the network. Use the `display-metadata`
    /// command to see the complete data for a validator.
    List,
}

#[derive(Serialize)]
#[serde(untagged)]
pub enum IotaValidatorCommandResponse {
    MakeValidatorInfo,
    DisplayMetadata(String),
    BecomeCandidate(IotaTransactionBlockResponse),
    JoinValidators(IotaTransactionBlockResponse),
    LeaveValidators(IotaTransactionBlockResponse),
    UpdateMetadata(IotaTransactionBlockResponse),
    ReportValidator(IotaTransactionBlockResponse),
    SerializedPayload(String),
    List(String),
}

fn make_key_files(
    file_name: PathBuf,
    is_authority_key: bool,
    key: Option<IotaKeyPair>,
) -> Result<()> {
    if file_name.exists() {
        println!("Use existing {file_name:?} key file.");
        return Ok(());
    } else if is_authority_key {
        let (_, keypair) = get_authority_key_pair();
        write_authority_keypair_to_file(&keypair, file_name.clone())?;
        println!("Generated new key file: {file_name:?}.");
    } else {
        let kp = match key {
            Some(key) => {
                println!("Generated new key file {file_name:?} based on iota.keystore file.");
                key
            }
            None => {
                let (_, kp, _, _) = generate_new_key(SignatureScheme::ED25519, None, None)?;
                println!("Generated new key file: {file_name:?}.");
                kp
            }
        };
        write_keypair_to_file(&kp, &file_name)?;
    }
    Ok(())
}

impl IotaValidatorCommand {
    pub async fn execute(
        self,
        context: &mut WalletContext,
        json: bool,
    ) -> Result<IotaValidatorCommandResponse, anyhow::Error> {
        let iota_address = context.active_address()?;

        let ret = Ok(match self {
            IotaValidatorCommand::MakeValidatorInfo {
                name,
                description,
                image_url,
                project_url,
                host_name,
            } => {
                let dir = std::env::current_dir()?;
                let authority_key_file_name = dir.join("authority.key");

                let account_key = context.config().keystore().get_key(&iota_address)?;

                if account_key.public().scheme() != SignatureScheme::ED25519 {
                    bail!("Only Ed25519 accounts are supported, please use Ed25519 keys for now.");
                }

                if let StoredKey::KeyPair(keypair) = account_key {
                    let account_key_file_name = dir.join("account.key");
                    make_key_files(account_key_file_name, false, Some(keypair.clone()))?;
                }

                let network_key_file_name = dir.join("network.key");
                let protocol_key_file_name = dir.join("protocol.key");
                make_key_files(authority_key_file_name.clone(), true, None)?;
                make_key_files(network_key_file_name.clone(), false, None)?;
                make_key_files(protocol_key_file_name.clone(), false, None)?;

                let authority_keypair: AuthorityKeyPair =
                    read_authority_keypair_from_file(authority_key_file_name)?;
                let protocol_keypair: NetworkKeyPair =
                    read_network_keypair_from_file(protocol_key_file_name)?;
                let network_keypair: NetworkKeyPair =
                    read_network_keypair_from_file(network_key_file_name)?;

                let account_address = Address::from(&account_key.public());

                let pop = generate_proof_of_possession(&authority_keypair, account_address);
                let validator_info = GenesisValidatorInfo {
                    info: iota_genesis_builder::validator_info::ValidatorInfo {
                        name,
                        authority_key: authority_keypair.public().into(),
                        protocol_key: protocol_keypair.public().clone(),
                        account_address,
                        network_key: network_keypair.public().clone(),
                        gas_price: iota_config::node::DEFAULT_VALIDATOR_GAS_PRICE,
                        commission_rate: iota_config::node::DEFAULT_COMMISSION_RATE,
                        network_address: Multiaddr::try_from(format!(
                            "/dns/{host_name}/tcp/8080/http"
                        ))?,
                        p2p_address: Multiaddr::try_from(format!("/dns/{host_name}/udp/8084"))?,
                        primary_address: Multiaddr::try_from(format!("/dns/{host_name}/udp/8081"))?,
                        description,
                        image_url,
                        project_url,
                    },
                    proof_of_possession: pop,
                };
                // TODO set key files permission
                let validator_info_file_name = dir.join("validator.info");
                let validator_info_bytes = serde_yaml::to_string(&validator_info)?;
                fs::write(validator_info_file_name.clone(), validator_info_bytes)?;
                println!("Generated validator info file: {validator_info_file_name:?}.");
                IotaValidatorCommandResponse::MakeValidatorInfo
            }
            IotaValidatorCommand::BecomeCandidate { file, gas_budget } => {
                let gas_budget = gas_budget.unwrap_or(DEFAULT_GAS_BUDGET);
                let validator_info_bytes = fs::read(file)?;
                // Note: we should probably rename the struct or evolve it accordingly.
                let validator_info: GenesisValidatorInfo =
                    serde_yaml::from_slice(&validator_info_bytes)?;
                let validator = validator_info.info;

                let args = vec![
                    CallArg::pure(&AuthorityPublicKeyBytes::from_bytes(
                        validator.authority_key().as_bytes(),
                    )?),
                    CallArg::pure(&validator.network_key().as_bytes().to_vec()),
                    CallArg::pure(&validator.protocol_key().as_bytes().to_vec()),
                    CallArg::pure(&validator_info.proof_of_possession.as_ref().to_vec()),
                    CallArg::pure(&validator.name().to_owned().into_bytes()),
                    CallArg::pure(&validator.description.clone().into_bytes()),
                    CallArg::pure(&validator.image_url.clone().into_bytes()),
                    CallArg::pure(&validator.project_url.clone().into_bytes()),
                    CallArg::pure(validator.network_address()),
                    CallArg::pure(validator.p2p_address()),
                    CallArg::pure(validator.primary_address()),
                    CallArg::pure(&validator.gas_price()),
                    CallArg::pure(&validator.commission_rate()),
                ];
                let response =
                    call_0x5(context, "request_add_validator_candidate", args, gas_budget).await?;
                IotaValidatorCommandResponse::BecomeCandidate(response)
            }

            IotaValidatorCommand::JoinValidators { gas_budget } => {
                let gas_budget = gas_budget.unwrap_or(DEFAULT_GAS_BUDGET);
                let response =
                    call_0x5(context, "request_add_validator", vec![], gas_budget).await?;
                IotaValidatorCommandResponse::JoinValidators(response)
            }

            IotaValidatorCommand::LeaveValidators { gas_budget } => {
                let _status = check_status(
                    context,
                    HashSet::from([ValidatorStatus::Active, ValidatorStatus::CommitteeMember]),
                )
                .await?;
                let gas_budget = gas_budget.unwrap_or(DEFAULT_GAS_BUDGET);
                let response =
                    call_0x5(context, "request_remove_validator", vec![], gas_budget).await?;
                IotaValidatorCommandResponse::LeaveValidators(response)
            }

            IotaValidatorCommand::DisplayMetadata { validator_address } => {
                let validator_address = validator_address.unwrap_or(context.active_address()?);
                // Default display with json serialization for better UX.
                let grpc = context.grpc_client().await?;
                let resp = display_metadata(&grpc, validator_address, json).await?;
                IotaValidatorCommandResponse::DisplayMetadata(resp)
            }

            IotaValidatorCommand::UpdateMetadata {
                metadata,
                gas_budget,
            } => {
                let gas_budget = gas_budget.unwrap_or(DEFAULT_GAS_BUDGET);
                let resp = update_metadata(context, metadata, gas_budget).await?;
                IotaValidatorCommandResponse::UpdateMetadata(resp)
            }

            IotaValidatorCommand::ReportValidator {
                operation_cap_id,
                reportee_address,
                undo_report,
                gas_budget,
            } => {
                let gas_budget = gas_budget.unwrap_or(DEFAULT_GAS_BUDGET);
                let undo_report = undo_report.unwrap_or(false);
                let resp = report_validator(
                    context,
                    reportee_address,
                    operation_cap_id,
                    undo_report,
                    gas_budget,
                )
                .await?;
                IotaValidatorCommandResponse::ReportValidator(resp)
            }

            IotaValidatorCommand::SerializePayloadForPoP {
                account_address,
                authority_public_key,
            } => {
                let mut msg: Vec<u8> = Vec::new();
                msg.extend_from_slice(authority_public_key.as_bytes());
                msg.extend_from_slice(account_address.as_ref());
                let mut intent_msg_bytes = bcs::to_bytes(&IntentMessage::new(
                    Intent::iota_app(IntentScope::ProofOfPossession),
                    msg,
                ))
                .expect("Message serialization should not fail");
                DEFAULT_EPOCH_ID.write(&mut intent_msg_bytes);
                IotaValidatorCommandResponse::SerializedPayload(Base64::encode(&intent_msg_bytes))
            }
            IotaValidatorCommand::List => {
                let mut builder = Builder::default();

                builder.set_header([
                    "iota address",
                    "name",
                    "staking pool balance",
                    "pending stake",
                    "committee member",
                ]);

                let grpc = context.grpc_client().await?;

                let iota_system_state = get_iota_system_state_summary(&grpc).await?;
                let (active_validators, committee_members) = match iota_system_state {
                    IotaSystemStateSummary::V1(v1) => (v1.active_validators, None),
                    IotaSystemStateSummary::V2(v2) => {
                        (v2.active_validators, Some(v2.committee_members))
                    }
                    _ => bail!(
                        "Unsupported IotaSystemStateSummary found. You may need to upgrade your iota binary."
                    ),
                };

                let mut entries = Vec::new();
                for (
                    index,
                    IotaValidatorSummary {
                        iota_address,
                        name,
                        staking_pool_iota_balance,
                        pending_stake,
                        ..
                    },
                ) in active_validators.into_iter().enumerate()
                {
                    let committee_member = committee_members
                        .as_ref()
                        .map(|members| members.contains(&(index as u64)))
                        // There was no committee in IotaSystemStateSummary::V1, so for consistency
                        // in the table we just add all validators.
                        .unwrap_or(true);
                    builder.push_record([
                        iota_address.to_string(),
                        name.clone(),
                        staking_pool_iota_balance.to_string(),
                        pending_stake.to_string(),
                        if committee_member { "✓" } else { "" }.to_string(),
                    ]);
                    entries.push(serde_json::json!({
                        "iota_address": iota_address.to_string(),
                        "name": name,
                        "staking_pool_balance": staking_pool_iota_balance.to_string(),
                        "pending_stake": pending_stake.to_string(),
                        "committee_member": committee_member,
                    }));
                }

                let resp = if json {
                    serde_json::to_string_pretty(&entries)?
                } else {
                    builder
                        .build()
                        .with(Style::rounded())
                        .with(Modify::new(Columns::new(2..=3)).with(Alignment::right()))
                        .with(Modify::new(Column::from(4)).with(Alignment::center()))
                        .to_string()
                };

                IotaValidatorCommandResponse::List(resp)
            }
        });
        ret
    }
}

/// Fetch the latest system state summary over gRPC by deserializing the
/// epoch's BCS-encoded system state.
async fn get_iota_system_state_summary(grpc: &Client) -> Result<IotaSystemStateSummary> {
    let epoch = grpc
        .get_epoch(None, Some(ReadMask::from(EpochField::BCS_SYSTEM_STATE)))
        .await
        .map_err(|e| anyhow!("{e}"))?;
    let system_state: IotaSystemState = epoch
        .body()
        .bcs_system_state
        .as_ref()
        .ok_or_else(|| anyhow!("node did not return the system state"))?
        .deserialize()
        .map_err(|e| anyhow!("{e}"))?;
    Ok(system_state.into_iota_system_state_summary())
}

/// Fetch a Move object's BCS-encoded contents over gRPC. Errors if the object
/// does not exist or is not a Move struct.
async fn get_move_object_contents(grpc: &Client, object_id: ObjectId) -> Result<Vec<u8>> {
    Ok(get_object(grpc, object_id)
        .await?
        .as_struct_opt()
        .ok_or_else(|| anyhow!("object {object_id} is not a Move struct"))?
        .contents()
        .to_vec())
}

/// Fetch a single object over gRPC. Errors if it does not exist.
async fn get_object(grpc: &Client, object_id: ObjectId) -> Result<Object> {
    let objects = grpc
        .get_objects(&[(object_id, None)], None)
        .await
        .map_err(|e| anyhow!("{e}"))?;
    Ok(objects
        .body()
        .first()
        .ok_or_else(|| anyhow!("object {object_id} not found"))?
        .object()
        .map_err(|e| anyhow!("{e}"))?
        .into())
}

/// List the object ids of a dynamic-field table's entries over gRPC.
async fn list_dynamic_field_ids(grpc: &Client, parent: ObjectId) -> Result<Vec<ObjectId>> {
    let fields = grpc
        .list_dynamic_fields(parent, None, None, None)
        .collect(None)
        .await
        .map_err(|e| anyhow!("{e}"))?;
    fields
        .body()
        .iter()
        .map(|field| {
            ObjectId::try_from(
                field
                    .field_id
                    .as_ref()
                    .ok_or_else(|| anyhow!("dynamic field is missing its field_id"))?,
            )
            .map_err(|e| anyhow!("{e}"))
        })
        .collect()
}

async fn get_cap_object_ref(
    context: &mut WalletContext,
    operation_cap_id: Option<ObjectId>,
) -> Result<(ValidatorStatus, IotaValidatorSummary, ObjectRef)> {
    let grpc = context.grpc_client().await?;
    if let Some(operation_cap_id) = operation_cap_id {
        let (status, summary) = get_validator_summary_from_cap_id(&grpc, operation_cap_id).await?;
        let cap_obj_ref = get_object(&grpc, summary.operation_cap_id)
            .await?
            .object_ref();
        Ok::<(ValidatorStatus, IotaValidatorSummary, ObjectRef), anyhow::Error>((
            status,
            summary,
            cap_obj_ref,
        ))
    } else {
        // Sender is Reporter Validator itself.
        let validator_address = context.active_address()?;
        let (status, summary) = get_validator_summary(&grpc, validator_address)
            .await?
            .ok_or_else(|| anyhow::anyhow!("{validator_address} is not a validator."))?;
        // TODO we should allow validator to perform this operation even though the Cap
        // is not at hand. But for now we need to make sure the cap is owned by
        // the sender.
        let cap_object_id = summary.operation_cap_id;
        let cap_object = get_object(&grpc, cap_object_id).await?;
        let owner = *cap_object.owner();
        let cap_obj_ref = cap_object.object_ref();
        if owner != Owner::Address(context.active_address()?) {
            anyhow::bail!(
                "OperationCap {} is not owned by the sender address {} but {:?}",
                summary.operation_cap_id,
                validator_address,
                owner
            );
        }
        Ok((status, summary, cap_obj_ref))
    }
}

async fn report_validator(
    context: &mut WalletContext,
    reportee_address: Address,
    operation_cap_id: Option<ObjectId>,
    undo_report: bool,
    gas_budget: u64,
) -> Result<IotaTransactionBlockResponse> {
    let (status, summary, cap_obj_ref) = get_cap_object_ref(context, operation_cap_id).await?;

    let validator_address = summary.iota_address;
    // Only committee members can report/un-report.
    if !matches!(status, ValidatorStatus::CommitteeMember) {
        anyhow::bail!(
            "Only committee members can report/un-report Validators, but {validator_address} is {status:?}."
        );
    }
    let args = vec![
        CallArg::ImmutableOrOwned(cap_obj_ref),
        CallArg::pure(&reportee_address),
    ];
    let function_name = if undo_report {
        "undo_report_validator"
    } else {
        "report_validator"
    };
    call_0x5(context, function_name, args, gas_budget).await
}

async fn get_validator_summary_from_cap_id(
    grpc: &Client,
    operation_cap_id: ObjectId,
) -> anyhow::Result<(ValidatorStatus, IotaValidatorSummary)> {
    let bcs = get_move_object_contents(grpc, operation_cap_id).await?;
    let cap = bcs::from_bytes::<UnverifiedValidatorOperationCap>(&bcs).map_err(|e| {
        anyhow::anyhow!(
            "Can't convert bcs bytes of object {operation_cap_id} to UnverifiedValidatorOperationCapV1: {e}")
    })?;
    let validator_address = cap.authorizer_validator_address;
    let (status, summary) = get_validator_summary(grpc, validator_address)
        .await?
        .ok_or_else(|| anyhow::anyhow!("{validator_address} is not a validator"))?;
    if summary.operation_cap_id != operation_cap_id {
        anyhow::bail!(
            "Validator {}'s current operation cap id is {}",
            validator_address,
            summary.operation_cap_id
        );
    }
    Ok((status, summary))
}

async fn construct_unsigned_0x5_txn(
    context: &mut WalletContext,
    sender: Address,
    function: &'static str,
    call_args: Vec<CallArg>,
    gas_budget: u64,
) -> anyhow::Result<TransactionData> {
    let mut args = vec![CallArg::IOTA_SYSTEM_MUTABLE];
    args.extend(call_args);
    let rgp = context.get_reference_gas_price().await?;

    let gas_obj_ref = get_gas_obj_ref(context, sender, gas_budget).await?;
    TransactionData::new_move_call(
        sender,
        ObjectId::SYSTEM,
        Identifier::IOTA_SYSTEM_MODULE,
        Identifier::from_static(function),
        vec![],
        gas_obj_ref,
        args,
        gas_budget,
        rgp,
    )
}

async fn call_0x5(
    context: &mut WalletContext,
    function: &'static str,
    call_args: Vec<CallArg>,
    gas_budget: u64,
) -> anyhow::Result<IotaTransactionBlockResponse> {
    let sender = context.active_address()?;
    let tx_data =
        construct_unsigned_0x5_txn(context, sender, function, call_args, gas_budget).await?;

    let signature = sign_transaction(context, &tx_data, &tx_data.sender(), None).await?;
    let transaction = Transaction::from_generic_sig_data(tx_data, vec![signature]);

    context.execute_transaction_may_fail(transaction).await
}

impl PrintableResult for IotaValidatorCommandResponse {
    // pretty is unused here, as this is handled for each command separately
    fn print(&self, _pretty: bool) {
        println!("{self}");
    }
}

impl Display for IotaValidatorCommandResponse {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        let mut writer = String::new();
        match self {
            IotaValidatorCommandResponse::MakeValidatorInfo => {}
            IotaValidatorCommandResponse::DisplayMetadata(resp)
            | IotaValidatorCommandResponse::List(resp) => {
                write!(writer, "{resp}")?;
            }
            IotaValidatorCommandResponse::BecomeCandidate(resp)
            | IotaValidatorCommandResponse::JoinValidators(resp)
            | IotaValidatorCommandResponse::LeaveValidators(resp)
            | IotaValidatorCommandResponse::UpdateMetadata(resp)
            | IotaValidatorCommandResponse::ReportValidator(resp) => {
                write!(writer, "{}", write_transaction_response(resp)?)?;
            }
            IotaValidatorCommandResponse::SerializedPayload(response) => {
                write!(writer, "Serialized payload: {response}")?;
            }
        }
        write!(f, "{}", writer.trim_end_matches('\n'))
    }
}

pub fn write_transaction_response(
    response: &IotaTransactionBlockResponse,
) -> Result<String, fmt::Error> {
    // we requested with for full_content, so the following content should be
    // available.
    let success = response.status_ok().unwrap();
    let lines = vec![
        String::from("----- Transaction Digest ----"),
        response.digest.to_string(),
        String::from("\n----- Transaction Data ----"),
        response.transaction.as_ref().unwrap().to_string(),
        String::from("----- Transaction Effects ----"),
        response.effects.as_ref().unwrap().to_string(),
    ];
    let mut writer = String::new();
    for line in lines {
        let colorized_line = if success { line.green() } else { line.red() };
        writeln!(writer, "{colorized_line}")?;
    }
    Ok(writer)
}

impl Debug for IotaValidatorCommandResponse {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        let string = serde_json::to_string_pretty(self);
        let s = match string {
            Ok(s) => s,
            Err(err) => format!("{err}").red().to_string(),
        };
        write!(f, "{s}")
    }
}

#[derive(Debug, Hash, PartialEq, Eq)]
pub enum ValidatorStatus {
    Active,
    CommitteeMember,
    Candidate,
    Inactive,
    Pending,
}

pub async fn get_validator_summary(
    grpc: &Client,
    validator_address: Address,
) -> anyhow::Result<Option<(ValidatorStatus, IotaValidatorSummary)>> {
    let iota_system_state = get_iota_system_state_summary(grpc).await?;
    let (
        committee_members,
        active_validators,
        pending_active_validators_id,
        validator_candidates_id,
        inactive_pools_id,
        protocol_version,
    ) = match iota_system_state {
        IotaSystemStateSummary::V1(v1) => (
            None,
            v1.active_validators,
            v1.pending_active_validators_id,
            v1.validator_candidates_id,
            v1.inactive_pools_id,
            v1.protocol_version,
        ),
        IotaSystemStateSummary::V2(v2) => (
            Some(v2.committee_members),
            v2.active_validators,
            v2.pending_active_validators_id,
            v2.validator_candidates_id,
            v2.inactive_pools_id,
            v2.protocol_version,
        ),
        _ => bail!(
            "Unsupported IotaSystemStateSummary found. You may need to upgrade your iota binary."
        ),
    };

    let mut active_validators = active_validators
        .into_iter()
        .enumerate()
        .map(|(index, summary)| {
            let committee_member = committee_members
                .as_ref()
                .map(|members| members.contains(&(index as u64)))
                // There was no committee in IotaSystemStateSummary::V1, so for consistency
                // we just set all validators also as committee_member.
                .unwrap_or(true);
            (summary.iota_address, (summary, committee_member))
        })
        .collect::<BTreeMap<_, _>>();

    // Check active and committee members
    if let Some((validator_summary, committee_member)) =
        active_validators.remove(&validator_address)
    {
        let status = if committee_member {
            ValidatorStatus::CommitteeMember
        } else {
            ValidatorStatus::Active
        };
        return Ok(Some((status, validator_summary)));
    }

    // Check pending validators
    let pending_validator_summary =
        get_pending_candidate_summary(validator_address, grpc, pending_active_validators_id)
            .await?
            .map(|v| v.into_iota_validator_summary(Some(protocol_version)));

    if let Some(pending_validator_summary) = pending_validator_summary {
        return Ok(Some((ValidatorStatus::Pending, pending_validator_summary)));
    }

    // Check candidates. The candidate is stored under a dynamic field of the
    // candidates table keyed by the validator address; a missing field means the
    // address is not a candidate.
    let candidate_field_id = derive_dynamic_field_id(
        validator_candidates_id,
        &TypeTag::Address,
        &bcs::to_bytes(&validator_address)?,
    )?;
    if get_object(grpc, candidate_field_id).await.is_ok() {
        let validator_summary = get_validator_summary_from_validator_wrapper(
            grpc,
            candidate_field_id,
            Some(protocol_version),
        )
        .await?;
        return Ok(Some((ValidatorStatus::Candidate, validator_summary)));
    };

    // Check inactive
    for field_id in list_dynamic_field_ids(grpc, inactive_pools_id).await? {
        let validator_summary =
            get_validator_summary_from_validator_wrapper(grpc, field_id, Some(protocol_version))
                .await?;
        if validator_summary.iota_address == validator_address {
            return Ok(Some((ValidatorStatus::Inactive, validator_summary)));
        }
    }

    Ok(None)
}

async fn get_validator_summary_from_validator_wrapper(
    grpc: &Client,
    validator_object_id: ObjectId,
    protocol_version: Option<u64>,
) -> anyhow::Result<IotaValidatorSummary> {
    let contents = get_move_object_contents(grpc, validator_object_id).await?;
    let validator = bcs::from_bytes::<Field<Address, Validator>>(&contents)?;

    let object_id = derive_dynamic_field_id(
        *validator.value.inner.id.object_id(),
        &TypeTag::U64,
        &bcs::to_bytes(&1u64)?,
    )?;
    let contents = get_move_object_contents(grpc, object_id).await?;
    let validator = bcs::from_bytes::<Field<u64, ValidatorV1>>(&contents)?;

    Ok(validator
        .value
        .into_iota_validator_summary(protocol_version))
}

async fn display_metadata(
    grpc: &Client,
    validator_address: Address,
    json: bool,
) -> anyhow::Result<String> {
    Ok(
        match get_validator_summary(grpc, validator_address).await? {
            None => format!("{validator_address} is not a validator"),
            Some((status, metadata)) => {
                if json {
                    let obj = serde_json::json!({
                        "status": format!("{status:?}"),
                        "metadata": metadata
                    });
                    serde_json::to_string_pretty(&obj)?
                } else {
                    let mut result = format!("{validator_address}'s validator status: {status:?}");
                    if let serde_json::Value::Object(map) = serde_json::to_value(&metadata).unwrap()
                    {
                        for (key, value) in map {
                            write!(result, "\n{key}: {value}").unwrap();
                        }
                    }
                    result
                }
            }
        },
    )
}

async fn get_pending_candidate_summary(
    validator_address: Address,
    grpc: &Client,
    pending_active_validators_id: ObjectId,
) -> anyhow::Result<Option<ValidatorV1>> {
    for object_id in list_dynamic_field_ids(grpc, pending_active_validators_id).await? {
        let bcs = get_move_object_contents(grpc, object_id).await?;
        let field = bcs::from_bytes::<Field<u64, ValidatorV1>>(&bcs).map_err(|e| {
            anyhow::anyhow!(
                "Can't convert bcs bytes of object {object_id} to Field<u64, ValidatorV1>: {e}",
            )
        })?;
        if field.value.verified_metadata().iota_address == validator_address {
            return Ok(Some(field.value));
        }
    }
    Ok(None)
}

#[derive(Subcommand)]
pub enum MetadataUpdate {
    /// Update name. Effectuate immediately.
    Name { name: String },
    /// Update description. Effectuate immediately.
    Description { description: String },
    /// Update Image URL. Effectuate immediately.
    ImageUrl { image_url: String },
    /// Update Project URL. Effectuate immediately.
    ProjectUrl { project_url: String },
    /// Update Network Address. Effectuate from next epoch.
    NetworkAddress { network_address: Multiaddr },
    /// Update Primary Address. Effectuate from next epoch.
    PrimaryAddress { primary_address: Multiaddr },
    /// Update P2P Address. Effectuate from next epoch.
    P2pAddress { p2p_address: Multiaddr },
    /// Update Network Public Key. Effectuate from next epoch.
    NetworkPubKey {
        #[arg(name = "network-key-path")]
        file: PathBuf,
    },
    /// Update Protocol Public Key. Effectuate from next epoch.
    ProtocolPubKey {
        #[arg(name = "protocol-key-path")]
        file: PathBuf,
    },
    /// Update Authority Public Key and Proof and Possession. Effectuate from
    /// next epoch.
    AuthorityPubKey {
        #[arg(name = "authority-key-path")]
        file: PathBuf,
    },
}

async fn update_metadata(
    context: &mut WalletContext,
    metadata: MetadataUpdate,
    gas_budget: u64,
) -> anyhow::Result<IotaTransactionBlockResponse> {
    match metadata {
        MetadataUpdate::Name { name } => {
            let args = vec![CallArg::pure(&name.into_bytes())];
            call_0x5(context, "update_validator_name", args, gas_budget).await
        }
        MetadataUpdate::Description { description } => {
            let args = vec![CallArg::pure(&description.into_bytes())];
            call_0x5(context, "update_validator_description", args, gas_budget).await
        }
        MetadataUpdate::ImageUrl { image_url } => {
            let args = vec![CallArg::pure(&image_url.into_bytes())];
            call_0x5(context, "update_validator_image_url", args, gas_budget).await
        }
        MetadataUpdate::ProjectUrl { project_url } => {
            let args = vec![CallArg::pure(&project_url.into_bytes())];
            call_0x5(context, "update_validator_project_url", args, gas_budget).await
        }
        MetadataUpdate::NetworkAddress { network_address } => {
            // Check the network address to be in TCP.
            if !network_address.is_loosely_valid_tcp_addr() {
                bail!("Network address must be a TCP address");
            }
            can_validator_mutate_all_data(context).await?;
            let args = vec![CallArg::pure(&network_address)];
            call_0x5(
                context,
                "update_validator_next_epoch_network_address",
                args,
                gas_budget,
            )
            .await
        }
        MetadataUpdate::PrimaryAddress { primary_address } => {
            primary_address.to_anemo_address().map_err(|_| {
                anyhow!("Invalid primary address, it must look like `/[ip4,ip6,dns]/.../udp/port`")
            })?;
            can_validator_mutate_all_data(context).await?;
            let args = vec![CallArg::pure(&primary_address)];
            call_0x5(
                context,
                "update_validator_next_epoch_primary_address",
                args,
                gas_budget,
            )
            .await
        }
        MetadataUpdate::P2pAddress { p2p_address } => {
            p2p_address.to_anemo_address().map_err(|_| {
                anyhow!("Invalid p2p address, it must look like `/[ip4,ip6,dns]/.../udp/port`")
            })?;
            can_validator_mutate_all_data(context).await?;
            let args = vec![CallArg::pure(&p2p_address)];
            call_0x5(
                context,
                "update_validator_next_epoch_p2p_address",
                args,
                gas_budget,
            )
            .await
        }
        MetadataUpdate::NetworkPubKey { file } => {
            can_validator_mutate_all_data(context).await?;
            let network_pub_key: NetworkPublicKey =
                read_network_keypair_from_file(file)?.public().clone();
            let args = vec![CallArg::pure(&network_pub_key.as_bytes().to_vec())];
            call_0x5(
                context,
                "update_validator_next_epoch_network_pubkey",
                args,
                gas_budget,
            )
            .await
        }
        MetadataUpdate::ProtocolPubKey { file } => {
            can_validator_mutate_all_data(context).await?;
            let protocol_pub_key: NetworkPublicKey =
                read_network_keypair_from_file(file)?.public().clone();
            let args = vec![CallArg::pure(&protocol_pub_key.as_bytes().to_vec())];
            call_0x5(
                context,
                "update_validator_next_epoch_protocol_pubkey",
                args,
                gas_budget,
            )
            .await
        }
        MetadataUpdate::AuthorityPubKey { file } => {
            can_validator_mutate_all_data(context).await?;
            let iota_address = context.active_address()?;
            let authority_key_pair: AuthorityKeyPair = read_authority_keypair_from_file(file)?;
            let authority_pub_key: AuthorityPublicKey = authority_key_pair.public().clone();
            let pop = generate_proof_of_possession(&authority_key_pair, iota_address);
            let args = vec![
                CallArg::pure(&AuthorityPublicKeyBytes::from_bytes(
                    authority_pub_key.as_bytes(),
                )?),
                CallArg::pure(&pop.as_ref().to_vec()),
            ];
            call_0x5(
                context,
                "update_validator_next_epoch_authority_pubkey",
                args,
                gas_budget,
            )
            .await
        }
    }
}

async fn check_status(
    context: &mut WalletContext,
    allowed_status: HashSet<ValidatorStatus>,
) -> Result<ValidatorStatus> {
    let grpc = context.grpc_client().await?;
    let validator_address = context.active_address()?;
    let summary = get_validator_summary(&grpc, validator_address).await?;
    if summary.is_none() {
        bail!("{validator_address} is not a Validator.");
    }
    let (status, _summary) = summary.unwrap();
    if allowed_status.contains(&status) {
        return Ok(status);
    }
    bail!(
        "Validator {validator_address} is {status:?}, this operation is not supported in this tool or prohibited."
    )
}

async fn can_validator_mutate_all_data(context: &mut WalletContext) -> Result<()> {
    let _status = check_status(
        context,
        HashSet::from([
            ValidatorStatus::Pending,
            ValidatorStatus::Active,
            ValidatorStatus::CommitteeMember,
        ]),
    )
    .await?;
    Ok(())
}

async fn get_gas_obj_ref(
    context: &WalletContext,
    iota_address: Address,
    minimal_gas_balance: u64,
) -> anyhow::Result<ObjectRef> {
    context
        .gas_for_owner_budget(
            iota_address,
            minimal_gas_balance,
            std::collections::BTreeSet::new(),
        )
        .await
        .map(|(_, data)| data.object_ref())
        .map_err(|e| {
            anyhow!("Validator doesn't have enough IOTA coins to cover transaction fees: {e}")
        })
}
