{
 "title": "Iota Validators - low level metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Environment", "label": "Datasource", "query": "prometheus" },
   { "name": "network", "label": "Network", "query": { "query": "label_values(uptime,network)" } },
   { "name": "validator", "label": "Job", "query": { "query": "label_values(host)" } }
  ]
 },
 "panels": [
  {
   "title": "Current epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(current_epoch{network=\"$network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gas rewards",
   "type": "stat",
   "description": "Prev epoch gas rewards (IOTA)",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(epoch_total_gas_reward{network=\"$network\"}) / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prev epoch duration (sec)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(epoch_total_duration{network=\"$network\"}) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Pod Versions (and uptime, in seconds)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{network=\"$network\"}",
     "legendFormat": "{{pod}} {{version}}"
    }
   ]
  },
  { "title": "Hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Usage (absolute core)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(host) (irate(node_cpu_seconds_total{host=\"$validator\", mode=\"system\", network=\"$network\"}[$__rate_interval]))",
     "legendFormat": "{{host}} Busy System"
    },
    {
     "expr": "sum by(host) (irate(node_cpu_seconds_total{host=~\"$validator\", mode=\"user\", network=\"$network\"}[$__rate_interval])) ",
     "legendFormat": "{{host}} Busy User"
    },
    {
     "expr": "sum by(host) (irate(node_cpu_seconds_total{host=~\"$validator\",mode=\"iowait\", network=\"$network\"}[$__rate_interval])) ",
     "legendFormat": "{{host}} Busy Iowait"
    },
    {
     "expr": "sum by(host) (irate(node_cpu_seconds_total{host=~\"$validator\", mode=~\".*irq\", network=\"$network\"}[$__rate_interval])) ",
     "legendFormat": "{{host}} Busy IRQs"
    },
    {
     "expr": "sum by(host) (irate(node_cpu_seconds_total{host=~\"$validator\", mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq', network=\"$network\"}[$__rate_interval])) ",
     "legendFormat": "{{host}} Busy Other"
    },
    {
     "expr": "sum by(host) (irate(node_cpu_seconds_total{host=~\"$host\", mode=\"idle\", network=\"$network\"}[$__rate_interval])) ",
     "legendFormat": "{{host}} Idle"
    }
   ]
  },
  {
   "title": "CPU Usage (percentage)",
   "type": "timeseries",
   "description": "Basic CPU info (this chart does not work with more than 1 host variant)\n",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(host) (irate(node_cpu_seconds_total{host=~\"$validator\", mode=\"system\", network=\"$network\"}[5m])) / on(instance) group_left sum by (host)((irate(node_cpu_seconds_total{host=~\"$validator\", network=\"$network\"}[5m])))",
     "legendFormat": "{{host}} Busy System"
    },
    {
     "expr": "sum by(host) (irate(node_cpu_seconds_total{host=~\"$validator\", mode=\"user\", network=\"$network\"}[5m])) / on(instance) group_left sum by (host)((irate(node_cpu_seconds_total{host=~\"$validator\", network=\"$network\"}[5m])))",
     "legendFormat": "{{host}} Busy User"
    },
    {
     "expr": "sum by(host) (irate(node_cpu_seconds_total{host=~\"$validator\",mode=\"iowait\", network=\"$network\"}[5m])) / on(instance) group_left sum by (host)((irate(node_cpu_seconds_total{host=~\"$validator\", network=\"$network\"}[5m])))",
     "legendFormat": "{{host}} Busy Iowait"
    },
    {
     "expr": "sum by(host) (irate(node_cpu_seconds_total{host=~\"$validator\", mode=~\".*irq\", network=\"$network\"}[5m])) / on(instance) group_left sum by (host)((irate(node_cpu_seconds_total{host=~\"$validator\", network=\"$network\"}[5m])))",
     "legendFormat": "{{host}} Busy IRQs"
    },
    {
     "expr": "sum by(host) (irate(node_cpu_seconds_total{host=~\"$validator\", mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq', network=\"$network\"}[5m])) / on(instance) group_left sum by (host)((irate(node_cpu_seconds_total{host=~\"$host\", network=\"$network\"}[5m])))",
     "legendFormat": "{{host}} Busy Other"
    },
    {
     "expr": "sum by(host) (irate(node_cpu_seconds_total{host=~\"$validator\", mode=\"idle\", network=\"$network\"}[5m])) / on(host) group_left sum by (host)((irate(node_cpu_seconds_total{host=~\"$validator\", network=\"$network\"}[5m])))",
     "legendFormat": "{{host}} Idle"
    }
   ]
  },
  {
   "title": "Memory in use",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (host) (node_memory_MemTotal_bytes{host=~\"$validator\", network=\"$network\"} - node_memory_MemFree_bytes{host=~\"$validator\", network=\"$network\"} - (node_memory_Cached_bytes{host=~\"$validator\", network=\"$network\"} + node_memory_Buffers_bytes{host=~\"$validator\", network=\"$network\"} + node_memory_SReclaimable_bytes{host=~\"$validator\", network=\"$network\"}))",
     "legendFormat": "{{host}} Used"
    },
    {
     "expr": "sum by (host) (node_memory_Active_bytes{host=~\"$validator\", network=\"$network\"})",
     "legendFormat": "{{host}} Active"
    }
   ]
  },
  {
   "title": "Disk used",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{host=~\"$validator\", device!~'rootfs', network=\"$network\"} * 100) / node_filesystem_size_bytes{host=~\"$validator\", device!~'rootfs', network=\"$network\"})",
     "legendFormat": "{{host}} {{device}} {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{host=~\"$validator\", network=\"$network\"}[$__rate_interval])*8",
     "legendFormat": "{{host}} recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{host=~\"$validator\", network=\"$network\"}[$__rate_interval])*8",
     "legendFormat": "{{host}} trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk reads",
   "type": "timeseries",
   "description": "Cumulative count of bytes read.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{network=\"$network\", host=~\"$validator\"}[5m])) by (host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rate of # of Open Sockets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(node_sockstat_sockets_used{host=~\"$validator\", network=\"$network\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of Open Sockets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "node_sockstat_sockets_used{host=~\"$validator\", network=\"$network\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk writes",
   "type": "timeseries",
   "description": "Cumulative count of bytes written.\n",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{host=~\"$validator\", network=\"$network\"}[5m])) by (host)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "QPS - Transaction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum by (statefulset_kubernetes_io_pod_name) (rate(total_transaction_orders{app=~\".*validator.*\", network=\"$network\"}[5m]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (statefulset_kubernetes_io_pod_name) (rate(total_transaction_orders{job=~\".*iotaval.*\", network=\"$network\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host) (rate(total_transaction_orders{host!=\"\", host!~\".*iotafn.*\", network=\"$network\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finalized Tx QPS - Single Writer Transaction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "expr": "sum by (statefulset_kubernetes_io_pod_name) (rate(total_transaction_certificates{app=~\".*validator.*\", network=\"$network\"}[5m])) - sum by (statefulset_kubernetes_io_pod_name) (rate(num_shared_obj_tx{app=~\".*validator.*\", network=\"$network\"}[5m]))"
    },
    {
     "expr": "sum by (statefulset_kubernetes_io_pod_name) (rate(total_transaction_certificates{job=~\".*iotaval.*\", network=\"$network\"}[5m])) - sum by (statefulset_kubernetes_io_pod_name) (rate(num_shared_obj_tx{job=~\".*iotaval.*\", network=\"$network\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host) (rate(total_transaction_certificates{host!=\"\", network=\"$network\"}[5m])) - sum by (host) (rate(num_shared_obj_tx{host!=\"\", network=\"$network\"}[5m]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Finalized Tx QPS - Consensus Transaction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "targets": [
    {
     "expr": "sum by (statefulset_kubernetes_io_pod_name) (rate(num_shared_obj_tx{app=~\".*validator.*\", network=\"$network\"}[5m]))"
    },
    {
     "expr": "sum by (statefulset_kubernetes_io_pod_name) (rate(num_shared_obj_tx{job=~\".*iotaval.*\", network=\"$network\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host) (rate(num_shared_obj_tx{host!=\"\", network=\"$network\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fullnode Connectivities (RPC Error Per Sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum by (name) (rate(total_rpc_err{network=\"$network\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "handle_certificate p50",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "validator_service_handle_certificate_non_consensus_latency{network=\"$network\", pct=\"50\"} / 1000",
     "legendFormat": "{{host}} single writer tx"
    },
    {
     "expr": "validator_service_handle_certificate_consensus_latency{network=\"$network\", pct=\"50\"} / 1000",
     "legendFormat": "{{host}} shared obj tx"
    }
   ]
  },
  {
   "title": "handle_certificatep95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "validator_service_handle_certificate_non_consensus_latency{network=\"$network\", pct=\"95\"} / 1000",
     "legendFormat": "{{host}} single writer tx"
    },
    {
     "expr": "validator_service_handle_certificate_consensus_latency{network=\"$network\", pct=\"95\"} / 1000",
     "legendFormat": "{{host}} shared obj tx"
    }
   ]
  },
  {
   "title": "Transaction Manager - executing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum by(host) (transaction_manager_num_executing_certificates{network=\"$network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Manager - pending",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 63 },
   "targets": [
    {
     "expr": "sum by(host) (transaction_manager_num_pending_certificates{network=\"$network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution Driver - executed transactions per sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 63 },
   "targets": [
    {
     "expr": "sum by(host) (rate(execution_driver_executed_transactions{network=\"$network\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction manager execution queue age",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "transaction_manager_transaction_queue_age{network=\"$network\", pct=\"95\", role=\"validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending certificates to sequence",
   "type": "timeseries",
   "description": "The number of certificates that are pending for sequencing in an authority. A high number of inflight certificates shows a pathogen in the system as an authority is waiting for a certificate to get sequenced and it does not in time.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 72 },
   "targets": [
    {
     "expr": "sum by(host) (sequencing_certificate_inflight{network=\"$network\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Pending Futures and Tasks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 72 },
   "targets": [
    {
     "expr": "sum by (host) (monitored_futures{host=~\"$validator\", network=\"$network\"})",
     "legendFormat": "{{host}} futures"
    },
    {
     "expr": "sum by (host) (monitored_tasks{host=~\"$validator\", network=\"$network\"})",
     "legendFormat": "{{host}} tasks"
    }
   ]
  }
 ]
}