processed 12 tasks

init:
A: object(0,0)

task 1 'publish'. lines 7-35:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7881200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 37-37:
created: object(2,0), object(2,1), object(2,2), object(2,3)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7273200,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'view-object'. lines 39-39:
Owner: Object ID: ( fake(2,1) )
Version: 3
Contents: iota::dynamic_field::Field<iota::dynamic_object_field::Wrapper<u64>, iota::object::ID> {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}, name: iota::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: iota::object::ID {bytes: fake(2,2)}}

task 4 'view-object'. lines 41-41:
Owner: Account Address ( fake(2,3) )
Version: 3
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,1)}}, value: 0u64}

task 5 'view-object'. lines 43-43:
Owner: Object ID: ( fake(2,0) )
Version: 3
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,2)}}, value: 0u64}

task 6 'view-object'. lines 45-45:
Owner: Shared
Version: 3
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,3)}}, value: 0u64}

task 7 'run'. lines 47-47:
Error: Error checking transaction input objects: IncorrectUserSignature { error: "Object object(2,1) is owned by account address object(2,3), but given owner/signer address is 0x4c291487b3b40954aa87f79cde3cb2e11e346b23828c746b7016f933dacf0a82" }

task 8 'view-object'. lines 49-49:
Owner: Object ID: ( fake(2,1) )
Version: 3
Contents: iota::dynamic_field::Field<iota::dynamic_object_field::Wrapper<u64>, iota::object::ID> {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}, name: iota::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: iota::object::ID {bytes: fake(2,2)}}

task 9 'view-object'. lines 51-51:
Owner: Account Address ( fake(2,3) )
Version: 3
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,1)}}, value: 0u64}

task 10 'view-object'. lines 53-53:
Owner: Object ID: ( fake(2,0) )
Version: 3
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,2)}}, value: 0u64}

task 11 'view-object'. lines 55-55:
Owner: Shared
Version: 3
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,3)}}, value: 0u64}
