// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2024 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Ampli - A strong typed wrapper for your Analytics
 *
 * This file is generated by Amplitude.
 * To update run 'ampli pull web'
 *
 * Required dependencies: @amplitude/analytics-browser@^1.3.0
 * Tracking Plan Version: 3
 * Build: 1.0.0
 * Runtime: browser:typescript-ampli-v2
 *
 * [View Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest)
 *
 * [Full Setup Instructions](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/implementation/web)
 */

import * as amplitude from '@amplitude/analytics-browser';

export type Environment = 'iotawallet';

export const ApiKey: Record<Environment, string> = {
    iotawallet: '2a5d35822a1bab41835813f0223f319e',
};

/**
 * Default Amplitude configuration options. Contains tracking plan information.
 */
export const DefaultConfiguration: BrowserOptions = {
    plan: {
        version: '3',
        branch: 'main',
        source: 'web',
        versionId: '41c28342-e260-4c3e-8465-6618203f115a',
    },
    ...{
        ingestionMetadata: {
            sourceName: 'browser-typescript-ampli',
            sourceVersion: '2.0.0',
        },
    },
    serverZone: amplitude.Types.ServerZone.EU,
};

export interface LoadOptionsBase {
    disabled?: boolean;
}

export type LoadOptionsWithEnvironment = LoadOptionsBase & {
    environment: Environment;
    client?: { configuration?: BrowserOptions };
};
export type LoadOptionsWithApiKey = LoadOptionsBase & {
    client: { apiKey: string; configuration?: BrowserOptions };
};
export type LoadOptionsWithClientInstance = LoadOptionsBase & {
    client: { instance: BrowserClient };
};

export type LoadOptions =
    | LoadOptionsWithEnvironment
    | LoadOptionsWithApiKey
    | LoadOptionsWithClientInstance;

export interface IdentifyProperties {
    network?: string;
}

export interface AccountCreationStartedProperties {
    accountOrigin?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    accountType?: string;
    isFirstAccount?: boolean;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    sourceFlow?: string;
}

export interface AccountDeletedProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    accountType?: string;
}

export interface AccountKeysExportedProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    accountType?: string;
}

export interface AccountsAddedProperties {
    accountOrigin?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    accountType?: string;
    isFirstAccount?: boolean;
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    numberOfAccounts?: number;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    sourceFlow?: string;
}

export interface ApplicationDisconnectedProperties {
    applicationName?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    applicationUrl?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    disconnectedAccounts?: number;
    partial?: boolean;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    sourceFlow?: string;
}

export interface ApplicationOpenedProperties {
    applicationName?: string;
}

export interface AppsBannerCtaClickedProperties {
    bannerUrl?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    sourceFlow?: string;
}

export interface AutoLockUpdatedProperties {
    autoLock: boolean;
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    lockTimeSeconds: number;
}

export interface BalanceFinderUsedProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    accountType?: string;
}

export interface ClickedUnstakeIotaProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    stakedAmount?: number;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    validatorAddress?: string;
}

export interface CoinPinnedProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    coinType?: string;
}

export interface CoinSelectedProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    coinType?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    totalBalance?: number;
}

export interface CoinUnpinnedProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    coinType?: string;
}

export interface CoinsSentProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    amount?: number;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    coinType?: string;
}

export interface CollectibleCardClickedProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    collectibleType?: string;
}

export interface CollectibleHiddenProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    collectibleType?: string;
}

export interface CollectibleSentProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    collectibleType?: string;
}

export interface CollectibleUnHiddenProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    collectibleType?: string;
}

export interface DappConnectStartedProperties {
    applicationName?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    applicationUrl?: string;
}

export interface ElementCopiedProperties {
    type: string;
}

export interface ExternalLinkOpenedProperties {
    type: string;
}

export interface IotaStakedProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    stakedAmount?: number;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    validatorAddress?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    validatorAPY?: number;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    validatorName?: string;
}

export interface IotaUnstakedProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    rewards?: number;
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    stakedAmount?: number;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    validatorAddress?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    validatorName?: string;
}

export interface NetworkSwitchedProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    toNetwork?: string;
}

export interface RespondedToConnectionRequestProperties {
    applicationName?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    applicationUrl?: string;
    approvedConnection?: boolean;
}

export interface RespondedToTransactionRequestProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    applicationUrl?: string;
    approvedTransaction?: boolean;
    receivedFailureWarning?: boolean;
}

export interface SidePanelChangedProperties {
    enabled: boolean;
}

export interface StakeClickedProperties {
    isCurrentlyStaking?: boolean;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    sourceFlow?: string;
}

export interface ThemeChangedProperties {
    theme: string;
}

export interface TransactionOpenedProperties {
    success?: boolean;
    transactionType?: string;
}

export interface ValidatorSelectedProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    validatorAddress?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    validatorAPY?: number;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    validatorName?: string;
}

export class Identify implements BaseEvent {
    event_type = amplitude.Types.SpecialEventType.IDENTIFY;

    constructor(public event_properties?: IdentifyProperties) {
        this.event_properties = event_properties;
    }
}

export class AccountCreationStarted implements BaseEvent {
    event_type = 'account creation started';

    constructor(public event_properties?: AccountCreationStartedProperties) {
        this.event_properties = event_properties;
    }
}

export class AccountDeleted implements BaseEvent {
    event_type = 'account deleted';

    constructor(public event_properties?: AccountDeletedProperties) {
        this.event_properties = event_properties;
    }
}

export class AccountKeysExported implements BaseEvent {
    event_type = 'account keys exported';

    constructor(public event_properties?: AccountKeysExportedProperties) {
        this.event_properties = event_properties;
    }
}

export class AccountRenamed implements BaseEvent {
    event_type = 'account renamed';
}

export class AccountsAdded implements BaseEvent {
    event_type = 'accounts added';

    constructor(public event_properties?: AccountsAddedProperties) {
        this.event_properties = event_properties;
    }
}

export class ApplicationDisconnected implements BaseEvent {
    event_type = 'application disconnected';

    constructor(public event_properties?: ApplicationDisconnectedProperties) {
        this.event_properties = event_properties;
    }
}

export class ApplicationOpened implements BaseEvent {
    event_type = 'application opened';

    constructor(public event_properties?: ApplicationOpenedProperties) {
        this.event_properties = event_properties;
    }
}

export class AppsBannerCtaClicked implements BaseEvent {
    event_type = 'apps banner cta clicked';

    constructor(public event_properties?: AppsBannerCtaClickedProperties) {
        this.event_properties = event_properties;
    }
}

export class AutoLockUpdated implements BaseEvent {
    event_type = 'auto lock updated';

    constructor(public event_properties: AutoLockUpdatedProperties) {
        this.event_properties = event_properties;
    }
}

export class BalanceFinderUsed implements BaseEvent {
    event_type = 'balance finder used';

    constructor(public event_properties?: BalanceFinderUsedProperties) {
        this.event_properties = event_properties;
    }
}

export class ClickedUnstakeIota implements BaseEvent {
    event_type = 'clicked unstake IOTA';

    constructor(public event_properties?: ClickedUnstakeIotaProperties) {
        this.event_properties = event_properties;
    }
}

export class CoinPinned implements BaseEvent {
    event_type = 'coin pinned';

    constructor(public event_properties?: CoinPinnedProperties) {
        this.event_properties = event_properties;
    }
}

export class CoinSelected implements BaseEvent {
    event_type = 'coin selected';

    constructor(public event_properties?: CoinSelectedProperties) {
        this.event_properties = event_properties;
    }
}

export class CoinUnpinned implements BaseEvent {
    event_type = 'coin unpinned';

    constructor(public event_properties?: CoinUnpinnedProperties) {
        this.event_properties = event_properties;
    }
}

export class CoinsSent implements BaseEvent {
    event_type = 'coins sent';

    constructor(public event_properties?: CoinsSentProperties) {
        this.event_properties = event_properties;
    }
}

export class CollectibleCardClicked implements BaseEvent {
    event_type = 'collectible card clicked';

    constructor(public event_properties?: CollectibleCardClickedProperties) {
        this.event_properties = event_properties;
    }
}

export class CollectibleHidden implements BaseEvent {
    event_type = 'collectible hidden';

    constructor(public event_properties?: CollectibleHiddenProperties) {
        this.event_properties = event_properties;
    }
}

export class CollectibleSent implements BaseEvent {
    event_type = 'collectible sent';

    constructor(public event_properties?: CollectibleSentProperties) {
        this.event_properties = event_properties;
    }
}

export class CollectibleUnHidden implements BaseEvent {
    event_type = 'collectible un-hidden';

    constructor(public event_properties?: CollectibleUnHiddenProperties) {
        this.event_properties = event_properties;
    }
}

export class DappConnectStarted implements BaseEvent {
    event_type = 'dapp connect started';

    constructor(public event_properties?: DappConnectStartedProperties) {
        this.event_properties = event_properties;
    }
}

export class ElementCopied implements BaseEvent {
    event_type = 'element copied';

    constructor(public event_properties: ElementCopiedProperties) {
        this.event_properties = event_properties;
    }
}

export class ExternalLinkOpened implements BaseEvent {
    event_type = 'external link opened';

    constructor(public event_properties: ExternalLinkOpenedProperties) {
        this.event_properties = event_properties;
    }
}

export class IotaStaked implements BaseEvent {
    event_type = 'iota staked';

    constructor(public event_properties?: IotaStakedProperties) {
        this.event_properties = event_properties;
    }
}

export class IotaUnstaked implements BaseEvent {
    event_type = 'iota unstaked';

    constructor(public event_properties?: IotaUnstakedProperties) {
        this.event_properties = event_properties;
    }
}

export class NetworkSwitched implements BaseEvent {
    event_type = 'network switched';

    constructor(public event_properties?: NetworkSwitchedProperties) {
        this.event_properties = event_properties;
    }
}

export class RespondedToConnectionRequest implements BaseEvent {
    event_type = 'responded to connection request';

    constructor(public event_properties?: RespondedToConnectionRequestProperties) {
        this.event_properties = event_properties;
    }
}

export class RespondedToTransactionRequest implements BaseEvent {
    event_type = 'responded to transaction request';

    constructor(public event_properties?: RespondedToTransactionRequestProperties) {
        this.event_properties = event_properties;
    }
}

export class SidePanelChanged implements BaseEvent {
    event_type = 'side panel changed';

    constructor(public event_properties: SidePanelChangedProperties) {
        this.event_properties = event_properties;
    }
}

export class StakeClicked implements BaseEvent {
    event_type = 'stake clicked';

    constructor(public event_properties?: StakeClickedProperties) {
        this.event_properties = event_properties;
    }
}

export class ThemeChanged implements BaseEvent {
    event_type = 'theme changed';

    constructor(public event_properties: ThemeChangedProperties) {
        this.event_properties = event_properties;
    }
}

export class TransactionOpened implements BaseEvent {
    event_type = 'transaction opened';

    constructor(public event_properties?: TransactionOpenedProperties) {
        this.event_properties = event_properties;
    }
}

export class ValidatorSelected implements BaseEvent {
    event_type = 'validator selected';

    constructor(public event_properties?: ValidatorSelectedProperties) {
        this.event_properties = event_properties;
    }
}

export class WalletReset implements BaseEvent {
    event_type = 'wallet reset';
}

export type PromiseResult<T> = { promise: Promise<T | void> };

const getVoidPromiseResult = () => ({ promise: Promise.resolve() });

// prettier-ignore
export class Ampli {
  private disabled: boolean = false;
  private amplitude?: BrowserClient;

  get client(): BrowserClient {
    this.isInitializedAndEnabled();
    return this.amplitude!;
  }

  get isLoaded(): boolean {
    return this.amplitude != null;
  }

  private isInitializedAndEnabled(): boolean {
    if (!this.amplitude) {
      console.error('ERROR: Ampli is not yet initialized. Have you called ampli.load() on app start?');
      return false;
    }
    return !this.disabled;
  }

  /**
   * Initialize the Ampli SDK. Call once when your application starts.
   *
   * @param options Configuration options to initialize the Ampli SDK with.
   */
  load(options: LoadOptions): PromiseResult<void> {
    this.disabled = options.disabled ?? false;

    if (this.amplitude) {
      console.warn('WARNING: Ampli is already initialized. Ampli.load() should be called once at application startup.');
      return getVoidPromiseResult();
    }

    let apiKey: string | null = null;
    if (options.client && 'apiKey' in options.client) {
      apiKey = options.client.apiKey;
    } else if ('environment' in options) {
      apiKey = ApiKey[options.environment];
    }

    if (options.client && 'instance' in options.client) {
      this.amplitude = options.client.instance;
    } else if (apiKey) {
      this.amplitude = amplitude.createInstance();
      const configuration = (options.client && 'configuration' in options.client) ? options.client.configuration : {};
      return this.amplitude.init(apiKey, undefined, { ...DefaultConfiguration, ...configuration });
    } else {
      console.error("ERROR: ampli.load() requires 'environment', 'client.apiKey', or 'client.instance'");
    }

    return getVoidPromiseResult();
  }

  /**
   * Identify a user and set user properties.
   *
   * @param userId The user's id.
   * @param properties The user properties.
   * @param options Optional event options.
   */
  identify(
    userId: string | undefined,
    properties?: IdentifyProperties,
    options?: EventOptions,
  ): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    if (userId) {
      options = {...options,  user_id: userId};
    }

    const amplitudeIdentify = new amplitude.Identify();
    const eventProperties = properties;
    if (eventProperties != null) {
      for (const [key, value] of Object.entries(eventProperties)) {
        amplitudeIdentify.set(key, value);
      }
    }
    return this.amplitude!.identify(
      amplitudeIdentify,
      options,
    );
  }

 /**
  * Flush the event.
  */
  flush() : PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.flush();
  }

  /**
   * Track event
   *
   * @param event The event to track.
   * @param options Optional event options.
   */
  track(event: Event, options?: EventOptions): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.track(event, undefined, options);
  }

  /**
   * account creation started
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/account%20creation%20started)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. accountOrigin)
   * @param options Amplitude event options.
   */
  accountCreationStarted(
    properties?: AccountCreationStartedProperties,
    options?: EventOptions,
  ) {
    return this.track(new AccountCreationStarted(properties), options);
  }

  /**
   * account deleted
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/account%20deleted)
   *
   * Fires when the user clicks on the “Delete” option on one of his accounts.
   *
   * @param properties The event's properties (e.g. accountType)
   * @param options Amplitude event options.
   */
  accountDeleted(
    properties?: AccountDeletedProperties,
    options?: EventOptions,
  ) {
    return this.track(new AccountDeleted(properties), options);
  }

  /**
   * account keys exported
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/account%20keys%20exported)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. accountType)
   * @param options Amplitude event options.
   */
  accountKeysExported(
    properties?: AccountKeysExportedProperties,
    options?: EventOptions,
  ) {
    return this.track(new AccountKeysExported(properties), options);
  }

  /**
   * account renamed
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/account%20renamed)
   *
   * Event has no description in tracking plan.
   *
   * @param options Amplitude event options.
   */
  accountRenamed(
    options?: EventOptions,
  ) {
    return this.track(new AccountRenamed(), options);
  }

  /**
   * accounts added
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/accounts%20added)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. accountOrigin)
   * @param options Amplitude event options.
   */
  accountsAdded(
    properties?: AccountsAddedProperties,
    options?: EventOptions,
  ) {
    return this.track(new AccountsAdded(properties), options);
  }

  /**
   * application disconnected
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/application%20disconnected)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. applicationName)
   * @param options Amplitude event options.
   */
  applicationDisconnected(
    properties?: ApplicationDisconnectedProperties,
    options?: EventOptions,
  ) {
    return this.track(new ApplicationDisconnected(properties), options);
  }

  /**
   * application opened
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/application%20opened)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. applicationName)
   * @param options Amplitude event options.
   */
  applicationOpened(
    properties?: ApplicationOpenedProperties,
    options?: EventOptions,
  ) {
    return this.track(new ApplicationOpened(properties), options);
  }

  /**
   * apps banner cta clicked
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/apps%20banner%20cta%20clicked)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. bannerUrl)
   * @param options Amplitude event options.
   */
  appsBannerCtaClicked(
    properties?: AppsBannerCtaClickedProperties,
    options?: EventOptions,
  ) {
    return this.track(new AppsBannerCtaClicked(properties), options);
  }

  /**
   * auto lock updated
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/auto%20lock%20updated)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. autoLock)
   * @param options Amplitude event options.
   */
  autoLockUpdated(
    properties: AutoLockUpdatedProperties,
    options?: EventOptions,
  ) {
    return this.track(new AutoLockUpdated(properties), options);
  }

  /**
   * balance finder used
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/balance%20finder%20used)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. accountType)
   * @param options Amplitude event options.
   */
  balanceFinderUsed(
    properties?: BalanceFinderUsedProperties,
    options?: EventOptions,
  ) {
    return this.track(new BalanceFinderUsed(properties), options);
  }

  /**
   * clicked unstake IOTA
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/clicked%20unstake%20IOTA)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. stakedAmount)
   * @param options Amplitude event options.
   */
  clickedUnstakeIota(
    properties?: ClickedUnstakeIotaProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickedUnstakeIota(properties), options);
  }

  /**
   * coin pinned
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/coin%20pinned)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. coinType)
   * @param options Amplitude event options.
   */
  coinPinned(
    properties?: CoinPinnedProperties,
    options?: EventOptions,
  ) {
    return this.track(new CoinPinned(properties), options);
  }

  /**
   * coin selected
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/coin%20selected)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. coinType)
   * @param options Amplitude event options.
   */
  coinSelected(
    properties?: CoinSelectedProperties,
    options?: EventOptions,
  ) {
    return this.track(new CoinSelected(properties), options);
  }

  /**
   * coin unpinned
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/coin%20unpinned)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. coinType)
   * @param options Amplitude event options.
   */
  coinUnpinned(
    properties?: CoinUnpinnedProperties,
    options?: EventOptions,
  ) {
    return this.track(new CoinUnpinned(properties), options);
  }

  /**
   * coins sent
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/coins%20sent)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. amount)
   * @param options Amplitude event options.
   */
  coinsSent(
    properties?: CoinsSentProperties,
    options?: EventOptions,
  ) {
    return this.track(new CoinsSent(properties), options);
  }

  /**
   * collectible card clicked
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/collectible%20card%20clicked)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. collectibleType)
   * @param options Amplitude event options.
   */
  collectibleCardClicked(
    properties?: CollectibleCardClickedProperties,
    options?: EventOptions,
  ) {
    return this.track(new CollectibleCardClicked(properties), options);
  }

  /**
   * collectible hidden
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/collectible%20hidden)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. collectibleType)
   * @param options Amplitude event options.
   */
  collectibleHidden(
    properties?: CollectibleHiddenProperties,
    options?: EventOptions,
  ) {
    return this.track(new CollectibleHidden(properties), options);
  }

  /**
   * collectible sent
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/collectible%20sent)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. collectibleType)
   * @param options Amplitude event options.
   */
  collectibleSent(
    properties?: CollectibleSentProperties,
    options?: EventOptions,
  ) {
    return this.track(new CollectibleSent(properties), options);
  }

  /**
   * collectible un-hidden
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/collectible%20un-hidden)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. collectibleType)
   * @param options Amplitude event options.
   */
  collectibleUnHidden(
    properties?: CollectibleUnHiddenProperties,
    options?: EventOptions,
  ) {
    return this.track(new CollectibleUnHidden(properties), options);
  }

  /**
   * dapp connect started
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/dapp%20connect%20started)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. applicationName)
   * @param options Amplitude event options.
   */
  dappConnectStarted(
    properties?: DappConnectStartedProperties,
    options?: EventOptions,
  ) {
    return this.track(new DappConnectStarted(properties), options);
  }

  /**
   * element copied
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/element%20copied)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. type)
   * @param options Amplitude event options.
   */
  elementCopied(
    properties: ElementCopiedProperties,
    options?: EventOptions,
  ) {
    return this.track(new ElementCopied(properties), options);
  }

  /**
   * external link opened
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/external%20link%20opened)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. type)
   * @param options Amplitude event options.
   */
  externalLinkOpened(
    properties: ExternalLinkOpenedProperties,
    options?: EventOptions,
  ) {
    return this.track(new ExternalLinkOpened(properties), options);
  }

  /**
   * iota staked
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/iota%20staked)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. stakedAmount)
   * @param options Amplitude event options.
   */
  iotaStaked(
    properties?: IotaStakedProperties,
    options?: EventOptions,
  ) {
    return this.track(new IotaStaked(properties), options);
  }

  /**
   * iota unstaked
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/iota%20unstaked)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. rewards)
   * @param options Amplitude event options.
   */
  iotaUnstaked(
    properties?: IotaUnstakedProperties,
    options?: EventOptions,
  ) {
    return this.track(new IotaUnstaked(properties), options);
  }

  /**
   * network switched
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/network%20switched)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. toNetwork)
   * @param options Amplitude event options.
   */
  networkSwitched(
    properties?: NetworkSwitchedProperties,
    options?: EventOptions,
  ) {
    return this.track(new NetworkSwitched(properties), options);
  }

  /**
   * responded to connection request
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/responded%20to%20connection%20request)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. applicationName)
   * @param options Amplitude event options.
   */
  respondedToConnectionRequest(
    properties?: RespondedToConnectionRequestProperties,
    options?: EventOptions,
  ) {
    return this.track(new RespondedToConnectionRequest(properties), options);
  }

  /**
   * responded to transaction request
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/responded%20to%20transaction%20request)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. applicationUrl)
   * @param options Amplitude event options.
   */
  respondedToTransactionRequest(
    properties?: RespondedToTransactionRequestProperties,
    options?: EventOptions,
  ) {
    return this.track(new RespondedToTransactionRequest(properties), options);
  }

  /**
   * side panel changed
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/side%20panel%20changed)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. enabled)
   * @param options Amplitude event options.
   */
  sidePanelChanged(
    properties: SidePanelChangedProperties,
    options?: EventOptions,
  ) {
    return this.track(new SidePanelChanged(properties), options);
  }

  /**
   * stake clicked
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/stake%20clicked)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. isCurrentlyStaking)
   * @param options Amplitude event options.
   */
  stakeClicked(
    properties?: StakeClickedProperties,
    options?: EventOptions,
  ) {
    return this.track(new StakeClicked(properties), options);
  }

  /**
   * theme changed
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/theme%20changed)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. theme)
   * @param options Amplitude event options.
   */
  themeChanged(
    properties: ThemeChangedProperties,
    options?: EventOptions,
  ) {
    return this.track(new ThemeChanged(properties), options);
  }

  /**
   * transaction opened
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/transaction%20opened)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. success)
   * @param options Amplitude event options.
   */
  transactionOpened(
    properties?: TransactionOpenedProperties,
    options?: EventOptions,
  ) {
    return this.track(new TransactionOpened(properties), options);
  }

  /**
   * validator selected
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/validator%20selected)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. validatorAddress)
   * @param options Amplitude event options.
   */
  validatorSelected(
    properties?: ValidatorSelectedProperties,
    options?: EventOptions,
  ) {
    return this.track(new ValidatorSelected(properties), options);
  }

  /**
   * wallet reset
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/wallet%20reset)
   *
   * Event has no description in tracking plan.
   *
   * @param options Amplitude event options.
   */
  walletReset(
    options?: EventOptions,
  ) {
    return this.track(new WalletReset(), options);
  }
}

export const ampli = new Ampli();

// BASE TYPES
type BrowserOptions = amplitude.Types.BrowserOptions;

export type BrowserClient = amplitude.Types.BrowserClient;
export type BaseEvent = amplitude.Types.BaseEvent;
export type IdentifyEvent = amplitude.Types.IdentifyEvent;
export type GroupEvent = amplitude.Types.GroupIdentifyEvent;
export type Event = amplitude.Types.Event;
export type EventOptions = amplitude.Types.EventOptions;
export type Result = amplitude.Types.Result;
