[package]
name = "time_locked"
edition = "2024"

[dependencies]
Iota = { local = "../../../crates/iota-framework/packages/iota-framework" }
iotaccount = { local = "../iotaccount" }

[addresses]
time_locked = "0x0"

[dev-dependencies]

[dev-addresses]
