// Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

use std::sync::Arc;

use futures::stream::BoxStream;
use iota_grpc_types::v0::checkpoints as grpc_checkpoints;
use tokio_util::sync::CancellationToken;
use tonic::{Request, Response, Status};
use tracing::debug;

use crate::types::*;

pub struct CheckpointGrpcService {
    pub reader: Arc<GrpcReader>,
    pub checkpoint_summary_broadcaster: GrpcCheckpointSummaryBroadcaster,
    pub checkpoint_data_broadcaster: GrpcCheckpointDataBroadcaster,
    pub cancellation_token: CancellationToken,
}

impl CheckpointGrpcService {
    /// Create a new CheckpointGrpcService with a GrpcReader
    pub fn new(
        reader: Arc<GrpcReader>,
        checkpoint_summary_broadcaster: GrpcCheckpointSummaryBroadcaster,
        checkpoint_data_broadcaster: GrpcCheckpointDataBroadcaster,
        cancellation_token: CancellationToken,
    ) -> Self {
        Self {
            reader,
            checkpoint_summary_broadcaster,
            checkpoint_data_broadcaster,
            cancellation_token,
        }
    }
}

impl CheckpointGrpcService {
    fn stream_checkpoint_data(
        &self,
        start_sequence_number: Option<u64>,
        end_sequence_number: Option<u64>,
    ) -> impl futures::Stream<Item = CheckpointStreamResult> + Send {
        let rx = self.checkpoint_data_broadcaster.subscribe();
        self.reader.create_checkpoint_data_stream(
            rx,
            start_sequence_number,
            end_sequence_number,
            self.cancellation_token.clone(),
        )
    }

    fn stream_checkpoint_summary(
        &self,
        start_sequence_number: Option<u64>,
        end_sequence_number: Option<u64>,
    ) -> impl futures::Stream<Item = CheckpointStreamResult> + Send {
        let rx = self.checkpoint_summary_broadcaster.subscribe();
        self.reader.create_checkpoint_summary_stream(
            rx,
            start_sequence_number,
            end_sequence_number,
            self.cancellation_token.clone(),
        )
    }
}

// The `CheckpointService` is the auto-generated trait from the protobuf
// definition. It's generated by tonic/protobuf and defines the interface that
// any gRPC checkpoint service must implement.
#[tonic::async_trait]
impl grpc_checkpoints::checkpoint_service_server::CheckpointService for CheckpointGrpcService {
    type StreamCheckpointsStream = BoxStream<'static, Result<grpc_checkpoints::Checkpoint, Status>>;

    async fn stream_checkpoints(
        &self,
        request: Request<grpc_checkpoints::CheckpointStreamRequest>,
    ) -> Result<Response<Self::StreamCheckpointsStream>, Status> {
        let req = request.into_inner();
        let start_sequence_number = req.start_sequence_number;
        let end_sequence_number = req.end_sequence_number;
        let full = req.full;

        let stream: Self::StreamCheckpointsStream = if full {
            Box::pin(self.stream_checkpoint_data(start_sequence_number, end_sequence_number))
        } else {
            Box::pin(self.stream_checkpoint_summary(start_sequence_number, end_sequence_number))
        };
        Ok(Response::new(stream))
    }

    async fn get_epoch_first_checkpoint_sequence_number(
        &self,
        request: Request<grpc_checkpoints::EpochRequest>,
    ) -> Result<Response<grpc_checkpoints::CheckpointSequenceNumberResponse>, Status> {
        let epoch = request.into_inner().epoch;
        debug!(
            "get_epoch_first_checkpoint_sequence_number called for epoch {}",
            epoch
        );

        let sequence_number = if epoch == 0 {
            // Genesis epoch starts at checkpoint 0
            0
        } else {
            // Get the last checkpoint of the previous epoch
            match self.reader.get_epoch_last_checkpoint(epoch - 1) {
                Ok(Some(last_checkpoint)) => {
                    // First checkpoint of current epoch is the next one
                    *last_checkpoint.sequence_number() + 1
                }
                Ok(None) => {
                    return Err(Status::not_found(format!(
                        "No checkpoints found for previous epoch {}",
                        epoch - 1
                    )));
                }
                Err(e) => {
                    return Err(Status::internal(format!(
                        "Failed to get last checkpoint for epoch {}: {}",
                        epoch - 1,
                        e
                    )));
                }
            }
        };

        debug!("First checkpoint for epoch {epoch}: seq={sequence_number}");

        Ok(Response::new(
            grpc_checkpoints::CheckpointSequenceNumberResponse { sequence_number },
        ))
    }

    async fn get_latest_checkpoint(
        &self,
        request: Request<grpc_checkpoints::GetLatestCheckpointRequest>,
    ) -> Result<Response<grpc_checkpoints::Checkpoint>, Status> {
        let req = request.into_inner();

        // Get the latest checkpoint sequence number
        let sequence_number = self
            .reader
            .get_latest_checkpoint_sequence_number()
            .ok_or_else(|| Status::not_found("No checkpoints available"))?;

        // Create checkpoint response using the same structure as checkpoint streaming
        let checkpoint = if req.full {
            // Get full checkpoint data
            if let Some(data) = self.reader.get_full_checkpoint_data(sequence_number) {
                let grpc_data = iota_grpc_types::checkpoints::CheckpointData::from(data);
                grpc_checkpoints::Checkpoint {
                    sequence_number,
                    is_full: true,
                    bcs_data: Some(
                        iota_grpc_types::v0::common::BcsData::serialize_from(&grpc_data).map_err(
                            |e| Status::internal(format!("BCS serialization failed: {e}")),
                        )?,
                    ),
                }
            } else {
                return Err(Status::not_found("Checkpoint data not found"));
            }
        } else {
            // Get checkpoint summary
            if let Some(summary) = self.reader.get_checkpoint_summary(sequence_number) {
                let grpc_summary =
                    iota_grpc_types::checkpoints::CertifiedCheckpointSummary::from(summary);
                grpc_checkpoints::Checkpoint {
                    sequence_number,
                    is_full: false,
                    bcs_data: Some(
                        iota_grpc_types::v0::common::BcsData::serialize_from(&grpc_summary)
                            .map_err(|e| {
                                Status::internal(format!("BCS serialization failed: {e}"))
                            })?,
                    ),
                }
            } else {
                return Err(Status::not_found("Checkpoint summary not found"));
            }
        };

        debug!("Latest checkpoint: {sequence_number}");

        Ok(Response::new(checkpoint))
    }
}
