// Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

use std::{pin::Pin, sync::Arc};

use iota_grpc_types::v0::ledger_service as grpc_ledger_service;
use tokio_util::sync::CancellationToken;
use tonic::Response;
use tracing::info;

use crate::types::*;

pub struct LedgerService {
    pub reader: Arc<GrpcReader>,
    pub checkpoint_summary_broadcaster: GrpcCheckpointSummaryBroadcaster,
    pub checkpoint_data_broadcaster: GrpcCheckpointDataBroadcaster,
    pub cancellation_token: CancellationToken,
}

impl LedgerService {
    /// Create a new CheckpointGrpcService with a GrpcReader
    pub fn new(
        reader: Arc<GrpcReader>,
        checkpoint_summary_broadcaster: GrpcCheckpointSummaryBroadcaster,
        checkpoint_data_broadcaster: GrpcCheckpointDataBroadcaster,
        cancellation_token: CancellationToken,
    ) -> Self {
        Self {
            reader,
            checkpoint_summary_broadcaster,
            checkpoint_data_broadcaster,
            cancellation_token,
        }
    }
}

impl LedgerService {
    fn stream_checkpoint_data(
        &self,
        start_sequence_number: Option<u64>,
        end_sequence_number: Option<u64>,
    ) -> impl futures::Stream<Item = CheckpointStreamResult> + Send {
        let rx = self.checkpoint_data_broadcaster.subscribe();
        self.reader.create_checkpoint_data_stream(
            rx,
            start_sequence_number,
            end_sequence_number,
            self.cancellation_token.clone(),
        )
    }
}

// The `CheckpointService` is the auto-generated trait from the protobuf
// definition. It's generated by tonic/protobuf and defines the interface that
// any gRPC checkpoint service must implement.
#[tonic::async_trait]
impl grpc_ledger_service::ledger_service_server::LedgerService for LedgerService {
    type GetObjectsStream = Pin<Box<dyn futures::Stream<Item = ObjectsStreamResult> + Send>>;
    type GetTransactionsStream =
        Pin<Box<dyn futures::Stream<Item = TransactionsStreamResult> + Send>>;
    type GetCheckpointDataStream =
        Pin<Box<dyn futures::Stream<Item = CheckpointStreamResult> + Send>>;
    type StreamCheckpointDataStream =
        Pin<Box<dyn futures::Stream<Item = CheckpointStreamResult> + Send>>;

    /// Query the service for general information about its current state.
    async fn get_service_info(
        &self,
        _request: tonic::Request<grpc_ledger_service::GetServiceInfoRequest>,
    ) -> std::result::Result<
        tonic::Response<grpc_ledger_service::GetServiceInfoResponse>,
        tonic::Status,
    > {
        info!("[grpc][ledger] GetServiceInfo called");
        let response = grpc_ledger_service::GetServiceInfoResponse {
            chain_id: None,
            chain: None,
            epoch: None,
            executed_checkpoint_height: None,
            executed_checkpoint_timestamp: None,
            lowest_available_checkpoint: None,
            lowest_available_checkpoint_objects: None,
            server: None,
        };
        Ok(Response::new(response))
    }

    async fn get_objects(
        &self,
        _request: tonic::Request<grpc_ledger_service::GetObjectsRequest>,
    ) -> std::result::Result<tonic::Response<Self::GetObjectsStream>, tonic::Status> {
        // not implemented - return empty stream
        let stream = futures::stream::empty();
        let stream: Self::GetObjectsStream = Box::pin(stream);
        Ok(Response::new(stream))
    }

    async fn get_transactions(
        &self,
        _request: tonic::Request<grpc_ledger_service::GetTransactionsRequest>,
    ) -> std::result::Result<tonic::Response<Self::GetTransactionsStream>, tonic::Status> {
        // not implemented - return empty stream
        let stream = futures::stream::empty();
        let stream: Self::GetTransactionsStream = Box::pin(stream);
        Ok(Response::new(stream))
    }

    /// Checkpoint operations
    async fn get_checkpoint_data(
        &self,
        _request: tonic::Request<grpc_ledger_service::GetCheckpointDataRequest>,
    ) -> std::result::Result<tonic::Response<Self::StreamCheckpointDataStream>, tonic::Status> {
        let stream = async_stream::try_stream! {
            // not implemented
            yield grpc_ledger_service::CheckpointData {
                payload: None,
            };
        };

        // not implemented
        Ok(Response::new(
            Box::pin(stream) as Self::StreamCheckpointDataStream
        ))
    }

    async fn stream_checkpoint_data(
        &self,
        request: tonic::Request<grpc_ledger_service::CheckpointDataStreamRequest>,
    ) -> std::result::Result<tonic::Response<Self::StreamCheckpointDataStream>, tonic::Status> {
        let req = request.into_inner();
        let start_sequence_number = req.start_sequence_number;
        let end_sequence_number = req.end_sequence_number;

        let stream = self.stream_checkpoint_data(start_sequence_number, end_sequence_number);
        Ok(Response::new(
            Box::pin(stream) as Self::StreamCheckpointDataStream
        ))
    }

    async fn get_epoch(
        &self,
        _request: tonic::Request<grpc_ledger_service::GetEpochRequest>,
    ) -> std::result::Result<tonic::Response<grpc_ledger_service::GetEpochResponse>, tonic::Status>
    {
        // not implemented
        Ok(Response::new(grpc_ledger_service::GetEpochResponse {
            epoch: None,
        }))
    }
}
