// Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

use std::sync::Arc;

use iota_grpc_types::v0::{common as grpc_common, read as grpc_read};
use iota_metrics::spawn_monitored_task;
use iota_types::{
    base_types::{ObjectID, ObjectType},
    object::{ObjectRead, Owner},
};
use tonic::{Request, Response, Status};
use tracing::{debug, instrument, warn};

use crate::GrpcReader;

pub struct ReadGrpcService {
    pub grpc_reader: Arc<GrpcReader>,
}

impl ReadGrpcService {
    pub fn new(grpc_reader: Arc<GrpcReader>) -> Self {
        Self { grpc_reader }
    }
}

// The `ReadService` is the auto-generated trait from the protobuf definition.
// It's generated by tonic/protobuf and defines the interface that any gRPC read
// service must implement.
#[tonic::async_trait]
impl grpc_read::read_service_server::ReadService for ReadGrpcService {
    #[instrument(skip(self))]
    async fn get_object(
        &self,
        request: Request<grpc_read::GetObjectRequest>,
    ) -> Result<Response<grpc_read::GetObjectResponse>, Status> {
        let req = request.into_inner();

        // Extract object ID from gRPC request
        let object_id = parse_object_id(&req.object_id)?;

        // Get ObjectRead from storage
        let grpc_reader = self.grpc_reader.clone();
        let object_read = spawn_monitored_task!(async move {
            grpc_reader.get_object_read(&object_id).map_err(|e| {
                warn!(?object_id, "Failed to get object: {:?}", e);
                Status::internal(format!("Failed to read object from storage: {e}"))
            })
        })
        .await
        .map_err(|e| Status::internal(format!("Task execution failed: {e}")))??;

        // Convert to proto response
        let response = convert_object_read_to_proto(object_read)?;

        debug!("Object retrieved successfully");
        Ok(Response::new(response))
    }
}

/// Convert ObjectRead to proto GetObjectResponse
fn convert_object_read_to_proto(
    object_read: ObjectRead,
) -> Result<grpc_read::GetObjectResponse, Status> {
    let result = match object_read {
        ObjectRead::NotExists(object_id) => {
            grpc_read::get_object_response::Result::NotExists(grpc_read::NotExists {
                object_id: Some(grpc_common::Address {
                    address: object_id.into_bytes().to_vec(),
                }),
            })
        }
        ObjectRead::Exists(object_ref, object, layout) => {
            let obj_inner = object.into_inner();

            // Get the object type
            let object_type = obj_inner
                .data
                .type_()
                .map(|t| ObjectType::Struct(t.clone()))
                .unwrap_or(ObjectType::Package);

            // BCS-encode the entire object data
            let data_bcs = bcs::to_bytes(&obj_inner.data)
                .map_err(|e| Status::internal(format!("Failed to serialize object data: {e}")))?;

            // Convert owner to proto Owner message
            let owner = Some(convert_owner_to_proto(&obj_inner.owner)?);

            grpc_read::get_object_response::Result::Exists(grpc_read::Exists {
                // Object type
                object_type: object_type.to_string(),
                // Object reference
                object_ref: Some(grpc_common::ObjectRef {
                    object_id: Some(grpc_common::Address {
                        address: object_ref.0.into_bytes().to_vec(),
                    }),
                    version: object_ref.1.value(),
                    digest: Some(grpc_common::Digest {
                        digest: object_ref.2.into_inner().to_vec(),
                    }),
                }),
                // Object data (BCS-encoded)
                data: Some(grpc_common::BcsData { data: data_bcs }),
                // Owner
                owner,
                // Object metadata
                previous_transaction: Some(grpc_common::Digest {
                    digest: obj_inner.previous_transaction.into_inner().to_vec(),
                }),
                storage_rebate: obj_inner.storage_rebate,
                // Optional layout
                move_structure_layout: layout
                    .map(|l| {
                        bcs::to_bytes(&l)
                            .map(|data| grpc_common::BcsData { data })
                            .map_err(|e| {
                                Status::internal(format!("Failed to serialize layout: {e}"))
                            })
                    })
                    .transpose()?,
            })
        }
        ObjectRead::Deleted(object_ref) => {
            grpc_read::get_object_response::Result::Deleted(grpc_read::Deleted {
                object_ref: Some(grpc_common::ObjectRef {
                    object_id: Some(grpc_common::Address {
                        address: object_ref.0.into_bytes().to_vec(),
                    }),
                    version: object_ref.1.value(),
                    digest: Some(grpc_common::Digest {
                        digest: object_ref.2.into_inner().to_vec(),
                    }),
                }),
            })
        }
    };

    Ok(grpc_read::GetObjectResponse {
        result: Some(result),
    })
}

/// Convert Owner to proto Owner message
fn convert_owner_to_proto(owner: &Owner) -> Result<grpc_common::Owner, Status> {
    let owner_oneof = match owner {
        Owner::AddressOwner(addr) => {
            grpc_common::owner::Owner::AddressOwner(grpc_common::Address {
                address: addr.to_vec(),
            })
        }
        Owner::ObjectOwner(addr) => grpc_common::owner::Owner::ObjectOwner(grpc_common::Address {
            address: addr.to_vec(),
        }),
        Owner::Shared {
            initial_shared_version,
        } => grpc_common::owner::Owner::Shared(grpc_common::SharedOwner {
            initial_shared_version: initial_shared_version.value(),
        }),
        Owner::Immutable => grpc_common::owner::Owner::Immutable(grpc_common::ImmutableOwner {}),
    };

    Ok(grpc_common::Owner {
        owner: Some(owner_oneof),
    })
}

/// Parse object ID from protobuf Address
fn parse_object_id(address: &Option<grpc_common::Address>) -> Result<ObjectID, Status> {
    let address = address
        .as_ref()
        .ok_or_else(|| Status::invalid_argument("Object ID is required"))?;

    if address.address.len() != 32 {
        return Err(Status::invalid_argument(format!(
            "Object ID must be 32 bytes, got {}",
            address.address.len()
        )));
    }

    let mut bytes = [0u8; 32];
    bytes.copy_from_slice(&address.address);
    ObjectID::from_bytes(bytes)
        .map_err(|e| Status::invalid_argument(format!("Invalid object ID: {e}")))
}
