processed 5 tasks

task 1, lines 7-29:
//# run-graphql
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "8i3pje74LEzqRfEbUkc7dMovgFtz1qNr7tAkyJijb6es",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "8i3pje74LEzqRfEbUkc7dMovgFtz1qNr7tAkyJijb6es",
        "sequenceNumber": 0
      }
    },
    "first": {
      "digest": "8i3pje74LEzqRfEbUkc7dMovgFtz1qNr7tAkyJijb6es",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "8i3pje74LEzqRfEbUkc7dMovgFtz1qNr7tAkyJijb6es",
      "sequenceNumber": 0
    }
  }
}

task 2, line 31:
//# create-checkpoint
Checkpoint created: 1

task 3, line 34:
//# create-checkpoint
Checkpoint created: 2

task 4, lines 37-59:
//# run-graphql
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "8i3pje74LEzqRfEbUkc7dMovgFtz1qNr7tAkyJijb6es",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "BmNP1C2r6FoopNbkJxthWjVBstBFsB6AQ5G3qkTY9TxE",
        "sequenceNumber": 2
      }
    },
    "first": {
      "digest": "8i3pje74LEzqRfEbUkc7dMovgFtz1qNr7tAkyJijb6es",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "BmNP1C2r6FoopNbkJxthWjVBstBFsB6AQ5G3qkTY9TxE",
      "sequenceNumber": 2
    }
  }
}
