processed 5 tasks

task 1, lines 7-29:
//# run-graphql
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "6wyR7YkwtD7gdqVAWA8mLEepj8hTFdapsBmXcTvEFFaw",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "6wyR7YkwtD7gdqVAWA8mLEepj8hTFdapsBmXcTvEFFaw",
        "sequenceNumber": 0
      }
    },
    "first": {
      "digest": "6wyR7YkwtD7gdqVAWA8mLEepj8hTFdapsBmXcTvEFFaw",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "6wyR7YkwtD7gdqVAWA8mLEepj8hTFdapsBmXcTvEFFaw",
      "sequenceNumber": 0
    }
  }
}

task 2, line 31:
//# create-checkpoint
Checkpoint created: 1

task 3, line 34:
//# create-checkpoint
Checkpoint created: 2

task 4, lines 37-59:
//# run-graphql
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "6wyR7YkwtD7gdqVAWA8mLEepj8hTFdapsBmXcTvEFFaw",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "5XTBMhyKNhY27jFhTi3EJhkTWthMSNh6ToneogvZzUwc",
        "sequenceNumber": 2
      }
    },
    "first": {
      "digest": "6wyR7YkwtD7gdqVAWA8mLEepj8hTFdapsBmXcTvEFFaw",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "5XTBMhyKNhY27jFhTi3EJhkTWthMSNh6ToneogvZzUwc",
      "sequenceNumber": 2
    }
  }
}
