processed 25 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 7-28:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 5791200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 30:
//# create-checkpoint
Checkpoint created: 1

task 3, line 32:
//# run Test::M1::create --args 0 @B --sender A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4, line 34:
//# run Test::M1::create --args 1 @B --sender A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 5, line 36:
//# run Test::M1::create --args 2 @B --sender A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 6, line 38:
//# run Test::M1::create --args 3 @B --sender A
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 7, line 40:
//# run Test::M1::create --args 4 @B --sender A
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 8, line 42:
//# create-checkpoint
Checkpoint created: 2

task 9, line 44:
//# run Test::M1::create --args 100 @B --sender A
created: object(9,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 10, line 46:
//# run Test::M1::create --args 101 @B --sender A
created: object(10,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 11, line 48:
//# run Test::M1::create --args 102 @B --sender A
created: object(11,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 12, line 50:
//# run Test::M1::create --args 103 @B --sender A
created: object(12,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 13, line 52:
//# run Test::M1::create --args 104 @B --sender A
created: object(13,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 14, line 54:
//# create-checkpoint
Checkpoint created: 3

task 15, lines 56-75:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": false,
        "endCursor": "eyJjIjozLCJ0IjoxMSwiaSI6ZmFsc2V9",
        "startCursor": "eyJjIjozLCJ0IjoyLCJpIjpmYWxzZX0"
      },
      "nodes": [
        {
          "digest": "EbDGGG7J7UrDdsn6F1C8puthPhTAyCbP8zJamEmXrvH4",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "ovzzHxewTojtxtEmjJNWFJZuD8MuP6NDxUafmf4z8tf",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "3EEE6qLkWUHTKao12yX2Z5Wa24xpArFuXXdxUm8bACqf",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "F7z3hxsjWK8Rwh1ATL55HLJE6K3vS2V8n2JipmXGiu8d",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "J7DwztQx1iKJdpmaSjt2PEJCM8VZXJMxVFpTcLPyCE8q",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "7ef7k6w9ML8t4ifRD9eMNoDGbFxRqsGttupE3opzkKjM",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "7XbbNMaQUR1R3ZujV2LKJA73HpBG8s9vAy2JTXRMgcxe",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "FUioT54RTwJ3UbXfUF9TTZFDU7PsuNzZsBH7Z9egjNg4",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "GPUnTY7eUNa6Uopm6oqtwuRAjNV4JyBPwGT61U6dK8A6",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "2vpWJcdbASSzWB5febpoC9Qi6kX9fF2rHJCsnzzgs6sN",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        }
      ]
    }
  }
}

task 16, lines 77-96:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": false,
        "endCursor": "eyJjIjozLCJ0IjoxMSwiaSI6ZmFsc2V9",
        "startCursor": "eyJjIjozLCJ0IjoyLCJpIjpmYWxzZX0"
      },
      "nodes": [
        {
          "digest": "EbDGGG7J7UrDdsn6F1C8puthPhTAyCbP8zJamEmXrvH4",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "ovzzHxewTojtxtEmjJNWFJZuD8MuP6NDxUafmf4z8tf",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "3EEE6qLkWUHTKao12yX2Z5Wa24xpArFuXXdxUm8bACqf",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "F7z3hxsjWK8Rwh1ATL55HLJE6K3vS2V8n2JipmXGiu8d",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "J7DwztQx1iKJdpmaSjt2PEJCM8VZXJMxVFpTcLPyCE8q",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "7ef7k6w9ML8t4ifRD9eMNoDGbFxRqsGttupE3opzkKjM",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "7XbbNMaQUR1R3ZujV2LKJA73HpBG8s9vAy2JTXRMgcxe",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "FUioT54RTwJ3UbXfUF9TTZFDU7PsuNzZsBH7Z9egjNg4",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "GPUnTY7eUNa6Uopm6oqtwuRAjNV4JyBPwGT61U6dK8A6",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "2vpWJcdbASSzWB5febpoC9Qi6kX9fF2rHJCsnzzgs6sN",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        }
      ]
    }
  }
}

task 17, lines 98-117:
//# run-graphql
Response: {
  "data": null,
  "errors": [
    {
      "message": "A scan limit must be specified for the given filter combination",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "transactionBlocks"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 18, lines 119-138:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": false,
        "endCursor": "eyJjIjozLCJ0IjoxMSwiaSI6dHJ1ZX0",
        "startCursor": "eyJjIjozLCJ0IjoyLCJpIjp0cnVlfQ"
      },
      "nodes": [
        {
          "digest": "EbDGGG7J7UrDdsn6F1C8puthPhTAyCbP8zJamEmXrvH4",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "ovzzHxewTojtxtEmjJNWFJZuD8MuP6NDxUafmf4z8tf",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "3EEE6qLkWUHTKao12yX2Z5Wa24xpArFuXXdxUm8bACqf",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "F7z3hxsjWK8Rwh1ATL55HLJE6K3vS2V8n2JipmXGiu8d",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "J7DwztQx1iKJdpmaSjt2PEJCM8VZXJMxVFpTcLPyCE8q",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "7ef7k6w9ML8t4ifRD9eMNoDGbFxRqsGttupE3opzkKjM",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "7XbbNMaQUR1R3ZujV2LKJA73HpBG8s9vAy2JTXRMgcxe",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "FUioT54RTwJ3UbXfUF9TTZFDU7PsuNzZsBH7Z9egjNg4",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "GPUnTY7eUNa6Uopm6oqtwuRAjNV4JyBPwGT61U6dK8A6",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "2vpWJcdbASSzWB5febpoC9Qi6kX9fF2rHJCsnzzgs6sN",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        }
      ]
    }
  }
}

task 19, lines 140-159:
//# run-graphql
Response: {
  "data": null,
  "errors": [
    {
      "message": "A scan limit must be specified for the given filter combination",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "transactionBlocks"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 20, lines 161-180:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": false,
        "endCursor": "eyJjIjozLCJ0IjoxMSwiaSI6dHJ1ZX0",
        "startCursor": "eyJjIjozLCJ0IjoyLCJpIjp0cnVlfQ"
      },
      "nodes": [
        {
          "digest": "EbDGGG7J7UrDdsn6F1C8puthPhTAyCbP8zJamEmXrvH4",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "ovzzHxewTojtxtEmjJNWFJZuD8MuP6NDxUafmf4z8tf",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "3EEE6qLkWUHTKao12yX2Z5Wa24xpArFuXXdxUm8bACqf",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "F7z3hxsjWK8Rwh1ATL55HLJE6K3vS2V8n2JipmXGiu8d",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "J7DwztQx1iKJdpmaSjt2PEJCM8VZXJMxVFpTcLPyCE8q",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "7ef7k6w9ML8t4ifRD9eMNoDGbFxRqsGttupE3opzkKjM",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "7XbbNMaQUR1R3ZujV2LKJA73HpBG8s9vAy2JTXRMgcxe",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "FUioT54RTwJ3UbXfUF9TTZFDU7PsuNzZsBH7Z9egjNg4",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "GPUnTY7eUNa6Uopm6oqtwuRAjNV4JyBPwGT61U6dK8A6",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "2vpWJcdbASSzWB5febpoC9Qi6kX9fF2rHJCsnzzgs6sN",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        }
      ]
    }
  }
}

task 21, lines 182-201:
//# run-graphql
Response: {
  "data": null,
  "errors": [
    {
      "message": "A scan limit must be specified for the given filter combination",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "transactionBlocks"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 22, lines 203-222:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": false,
        "endCursor": "eyJjIjozLCJ0IjoxMSwiaSI6dHJ1ZX0",
        "startCursor": "eyJjIjozLCJ0IjoyLCJpIjp0cnVlfQ"
      },
      "nodes": []
    }
  }
}

task 23, lines 225-244:
//# run-graphql
Response: {
  "data": null,
  "errors": [
    {
      "message": "A scan limit must be specified for the given filter combination",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "transactionBlocks"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 24, lines 246-270:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": false,
        "startCursor": "eyJjIjozLCJ0IjoyLCJpIjp0cnVlfQ",
        "endCursor": "eyJjIjozLCJ0IjoxMSwiaSI6dHJ1ZX0"
      },
      "edges": [
        {
          "cursor": "eyJjIjozLCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "digest": "EbDGGG7J7UrDdsn6F1C8puthPhTAyCbP8zJamEmXrvH4",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        }
      ]
    }
  }
}
