processed 25 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 7-28:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 5791200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 30:
//# create-checkpoint
Checkpoint created: 1

task 3, line 32:
//# run Test::M1::create --args 0 @B --sender A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4, line 34:
//# run Test::M1::create --args 1 @B --sender A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 5, line 36:
//# run Test::M1::create --args 2 @B --sender A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 6, line 38:
//# run Test::M1::create --args 3 @B --sender A
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 7, line 40:
//# run Test::M1::create --args 4 @B --sender A
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 8, line 42:
//# create-checkpoint
Checkpoint created: 2

task 9, line 44:
//# run Test::M1::create --args 100 @B --sender A
created: object(9,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 10, line 46:
//# run Test::M1::create --args 101 @B --sender A
created: object(10,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 11, line 48:
//# run Test::M1::create --args 102 @B --sender A
created: object(11,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 12, line 50:
//# run Test::M1::create --args 103 @B --sender A
created: object(12,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 13, line 52:
//# run Test::M1::create --args 104 @B --sender A
created: object(13,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 14, line 54:
//# create-checkpoint
Checkpoint created: 3

task 15, lines 56-75:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": false,
        "endCursor": "eyJjIjozLCJ0IjoxMSwiaSI6ZmFsc2V9",
        "startCursor": "eyJjIjozLCJ0IjoyLCJpIjpmYWxzZX0"
      },
      "nodes": [
        {
          "digest": "6CL5E7h4RHP1MRgX9acbMzmBFybseF93LxTn2oQiVQcp",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "GXCLARdo6guVFbLJmtXgqh9fPqmE8krxRAH3bDriCve5",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "Fw76Wncg9MW6W3fYeuokRgRPm9ke5H8vDYjARkDU5cp2",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "DuP6u1Z8xj4TXcSXEAcb1nwTpEbnAkRPFdEpobcb9agd",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "GuJZ9SjVVazudEcttJdnD1nsB2vQzNhpxZQBcTwGWu7w",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "6rCNxHfx6j5c5Kai7gZkgUm3AvpQ2mRa8vu7xSHmSwe3",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "CWetyb6ZVviXP3fKGV6YQJCzr6sx3aT26naNxWoRfZUb",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "4JBaU5UuoF3F1hWxHFPRU9i7ENtCpQSc4k3sXj4b5xkk",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "BHxM7udenkZ3xPX1F9CrhxNfhnFb19ysgZvopcJ2MAnE",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "7RHuhCSwq5PNpTquLsXnjXA3h23Ziv7uLLAncyiinzHp",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        }
      ]
    }
  }
}

task 16, lines 77-96:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": false,
        "endCursor": "eyJjIjozLCJ0IjoxMSwiaSI6ZmFsc2V9",
        "startCursor": "eyJjIjozLCJ0IjoyLCJpIjpmYWxzZX0"
      },
      "nodes": [
        {
          "digest": "6CL5E7h4RHP1MRgX9acbMzmBFybseF93LxTn2oQiVQcp",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "GXCLARdo6guVFbLJmtXgqh9fPqmE8krxRAH3bDriCve5",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "Fw76Wncg9MW6W3fYeuokRgRPm9ke5H8vDYjARkDU5cp2",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "DuP6u1Z8xj4TXcSXEAcb1nwTpEbnAkRPFdEpobcb9agd",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "GuJZ9SjVVazudEcttJdnD1nsB2vQzNhpxZQBcTwGWu7w",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "6rCNxHfx6j5c5Kai7gZkgUm3AvpQ2mRa8vu7xSHmSwe3",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "CWetyb6ZVviXP3fKGV6YQJCzr6sx3aT26naNxWoRfZUb",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "4JBaU5UuoF3F1hWxHFPRU9i7ENtCpQSc4k3sXj4b5xkk",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "BHxM7udenkZ3xPX1F9CrhxNfhnFb19ysgZvopcJ2MAnE",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "7RHuhCSwq5PNpTquLsXnjXA3h23Ziv7uLLAncyiinzHp",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        }
      ]
    }
  }
}

task 17, lines 98-117:
//# run-graphql
Response: {
  "data": null,
  "errors": [
    {
      "message": "A scan limit must be specified for the given filter combination",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "transactionBlocks"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 18, lines 119-138:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": false,
        "endCursor": "eyJjIjozLCJ0IjoxMSwiaSI6dHJ1ZX0",
        "startCursor": "eyJjIjozLCJ0IjoyLCJpIjp0cnVlfQ"
      },
      "nodes": [
        {
          "digest": "6CL5E7h4RHP1MRgX9acbMzmBFybseF93LxTn2oQiVQcp",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "GXCLARdo6guVFbLJmtXgqh9fPqmE8krxRAH3bDriCve5",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "Fw76Wncg9MW6W3fYeuokRgRPm9ke5H8vDYjARkDU5cp2",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "DuP6u1Z8xj4TXcSXEAcb1nwTpEbnAkRPFdEpobcb9agd",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "GuJZ9SjVVazudEcttJdnD1nsB2vQzNhpxZQBcTwGWu7w",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "6rCNxHfx6j5c5Kai7gZkgUm3AvpQ2mRa8vu7xSHmSwe3",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "CWetyb6ZVviXP3fKGV6YQJCzr6sx3aT26naNxWoRfZUb",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "4JBaU5UuoF3F1hWxHFPRU9i7ENtCpQSc4k3sXj4b5xkk",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "BHxM7udenkZ3xPX1F9CrhxNfhnFb19ysgZvopcJ2MAnE",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "7RHuhCSwq5PNpTquLsXnjXA3h23Ziv7uLLAncyiinzHp",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        }
      ]
    }
  }
}

task 19, lines 140-159:
//# run-graphql
Response: {
  "data": null,
  "errors": [
    {
      "message": "A scan limit must be specified for the given filter combination",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "transactionBlocks"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 20, lines 161-180:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": false,
        "endCursor": "eyJjIjozLCJ0IjoxMSwiaSI6dHJ1ZX0",
        "startCursor": "eyJjIjozLCJ0IjoyLCJpIjp0cnVlfQ"
      },
      "nodes": [
        {
          "digest": "6CL5E7h4RHP1MRgX9acbMzmBFybseF93LxTn2oQiVQcp",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "GXCLARdo6guVFbLJmtXgqh9fPqmE8krxRAH3bDriCve5",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "Fw76Wncg9MW6W3fYeuokRgRPm9ke5H8vDYjARkDU5cp2",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "DuP6u1Z8xj4TXcSXEAcb1nwTpEbnAkRPFdEpobcb9agd",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "GuJZ9SjVVazudEcttJdnD1nsB2vQzNhpxZQBcTwGWu7w",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "6rCNxHfx6j5c5Kai7gZkgUm3AvpQ2mRa8vu7xSHmSwe3",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "CWetyb6ZVviXP3fKGV6YQJCzr6sx3aT26naNxWoRfZUb",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "4JBaU5UuoF3F1hWxHFPRU9i7ENtCpQSc4k3sXj4b5xkk",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "BHxM7udenkZ3xPX1F9CrhxNfhnFb19ysgZvopcJ2MAnE",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        },
        {
          "digest": "7RHuhCSwq5PNpTquLsXnjXA3h23Ziv7uLLAncyiinzHp",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 3
            }
          }
        }
      ]
    }
  }
}

task 21, lines 182-201:
//# run-graphql
Response: {
  "data": null,
  "errors": [
    {
      "message": "A scan limit must be specified for the given filter combination",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "transactionBlocks"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 22, lines 203-222:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": false,
        "endCursor": "eyJjIjozLCJ0IjoxMSwiaSI6dHJ1ZX0",
        "startCursor": "eyJjIjozLCJ0IjoyLCJpIjp0cnVlfQ"
      },
      "nodes": []
    }
  }
}

task 23, lines 225-244:
//# run-graphql
Response: {
  "data": null,
  "errors": [
    {
      "message": "A scan limit must be specified for the given filter combination",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "transactionBlocks"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 24, lines 246-270:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": false,
        "startCursor": "eyJjIjozLCJ0IjoyLCJpIjp0cnVlfQ",
        "endCursor": "eyJjIjozLCJ0IjoxMSwiaSI6dHJ1ZX0"
      },
      "edges": [
        {
          "cursor": "eyJjIjozLCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "digest": "6CL5E7h4RHP1MRgX9acbMzmBFybseF93LxTn2oQiVQcp",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        }
      ]
    }
  }
}
