[package]
name = "iota-genesis-builder"
version.workspace = true
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[lints]
workspace = true

[dependencies]
# external dependencies
anyhow.workspace = true
bcs.workspace = true
camino.workspace = true
fastcrypto.workspace = true
serde.workspace = true
serde_with.workspace = true
serde_yaml.workspace = true
tracing.workspace = true

# internal dependencies
iota-config.workspace = true
iota-execution.workspace = true
iota-framework.workspace = true
iota-framework-snapshot.workspace = true
iota-genesis-common.workspace = true
iota-multiaddr.workspace = true
iota-protocol-config.workspace = true
iota-sdk-ext = { workspace = true, features = ["types"] }
iota-types.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true
prometheus-filtered.workspace = true

[dev-dependencies]
# external dependencies
rand = { workspace = true, features = ["std_rng"] }
tempfile.workspace = true

# internal dependencies
iota-swarm-config.workspace = true
