[package]
name = "lean_imt_account"
edition = "2024"

[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "framework/devnet" }

[addresses]
lean_imt_account = "0x0"
