// Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

use std::{str::FromStr, sync::Arc};

use futures::StreamExt;
use iota_json_rpc_types::{EventFilter, IotaEvent};
use iota_types::{
    base_types::{IotaAddress, ObjectID},
    digests::TransactionDigest,
};
use move_core_types::{identifier::Identifier, language_storage::StructTag};
use tokio_util::sync::CancellationToken;
use tonic::{Request, Response, Status};
use tracing::debug;

use crate::{
    events::{Event, EventId, EventStreamRequest, event_service_server::EventService},
    types::EventSubscriber,
};

pub struct EventGrpcService {
    pub event_subscriber: Arc<dyn EventSubscriber>,
    pub cancellation_token: CancellationToken,
}

impl EventGrpcService {
    pub fn new(
        event_subscriber: Arc<dyn EventSubscriber>,
        cancellation_token: CancellationToken,
    ) -> Self {
        Self {
            event_subscriber,
            cancellation_token,
        }
    }
}

// The `EventService` is the auto-generated trait from the protobuf
// definition. It's generated by tonic/protobuf and defines the interface that
// any gRPC event service must implement.
#[tonic::async_trait]
impl EventService for EventGrpcService {
    type StreamEventsStream =
        std::pin::Pin<Box<dyn futures::Stream<Item = Result<Event, Status>> + Send>>;

    async fn stream_events(
        &self,
        request: Request<EventStreamRequest>,
    ) -> Result<Response<Self::StreamEventsStream>, Status> {
        let proto_filter = request
            .into_inner()
            .filter
            .ok_or_else(|| Status::invalid_argument("Filter is required"))?;

        let event_filter = create_event_filter(&proto_filter)?;
        debug!("New gRPC client subscribed with filter: {event_filter:?}");

        // Subscribe to events using the EventSubscriber trait
        let event_stream = self.event_subscriber.subscribe_events(event_filter);
        let cancellation_token = self.cancellation_token.clone();

        let stream = async_stream::try_stream! {
            // Pin the stream for use with .next() and tokio::select!
            // Safe because the stream has Unpin bound
            let mut pinned_stream = std::pin::Pin::new(event_stream);

            loop {
                let event_result = tokio::select! {
                    event_option = pinned_stream.next() => event_option,
                    _ = cancellation_token.cancelled() => {
                        debug!("Event stream cancelled");
                        None
                    }
                };

                match event_result {
                    Some(event) => {
                        debug!(
                            "Event matched filter: TX: {}, Type: {}, Sender: {}",
                            event.id.tx_digest,
                            event.type_.name.as_ident_str(),
                            event.sender
                        );

                        // Convert to protobuf Event
                        let proto_event = Event::from(&event);

                        yield proto_event;
                    }
                    None => {
                        // Stream ended or cancellation occurred
                        debug!("Event stream ended");
                        break;
                    }
                }
            }
        };

        Ok(Response::new(Box::pin(stream)))
    }
}

/// Convert protobuf EventFilter to iota_json_rpc_types::EventFilter
fn create_event_filter(proto_filter: &crate::events::EventFilter) -> Result<EventFilter, Status> {
    use crate::events::event_filter::Filter;

    match &proto_filter.filter {
        Some(Filter::All(_)) => Ok(EventFilter::All(vec![])),
        Some(Filter::Sender(f)) => {
            let sender = parse_iota_address(&f.sender, "Sender address")?;
            Ok(EventFilter::Sender(sender))
        }
        Some(Filter::Transaction(f)) => {
            let tx_digest = parse_tx_digest(&f.tx_digest, "Transaction digest")?;
            Ok(EventFilter::Transaction(tx_digest))
        }
        Some(Filter::MoveModule(f)) => {
            let package_id = parse_object_id(&f.package_id, "Package ID")?;
            Ok(EventFilter::MoveModule {
                package: package_id,
                module: parse_identifier(&f.module, "module name")?,
            })
        }
        Some(Filter::MoveEventType(f)) => {
            let object_id = parse_object_id(&f.package_id, "Package ID")?;
            let struct_tag = StructTag {
                address: *object_id,
                module: parse_identifier(&f.module, "module name")?,
                name: parse_identifier(&f.name, "event name")?,
                type_params: vec![],
            };
            Ok(EventFilter::MoveEventType(struct_tag))
        }
        Some(Filter::MoveEventModule(f)) => {
            let package_id = parse_object_id(&f.package_id, "Package ID")?;
            Ok(EventFilter::MoveEventModule {
                package: package_id,
                module: parse_identifier(&f.module, "module name")?,
            })
        }
        Some(Filter::TimeRange(f)) => Ok(EventFilter::TimeRange {
            start_time: f.start_time,
            end_time: f.end_time,
        }),
        None => Ok(EventFilter::All(vec![])),
    }
}

// Helper functions to reduce repetition and improve error messages
fn parse_object_id(
    address: &Option<crate::common::Address>,
    field_name: &str,
) -> Result<ObjectID, Status> {
    let address = address
        .as_ref()
        .ok_or_else(|| Status::invalid_argument(format!("{field_name} is required")))?;
    ObjectID::from_bytes(&address.address)
        .map_err(|e| Status::invalid_argument(format!("Invalid {field_name}: {e}")))
}

fn parse_identifier(id_str: &str, field_name: &str) -> Result<Identifier, Status> {
    Identifier::from_str(id_str)
        .map_err(|e| Status::invalid_argument(format!("Invalid {field_name} '{id_str}': {e}")))
}

fn parse_iota_address(
    address: &Option<crate::common::Address>,
    field_name: &str,
) -> Result<IotaAddress, Status> {
    let address = address
        .as_ref()
        .ok_or_else(|| Status::invalid_argument(format!("{field_name} is required")))?;
    IotaAddress::from_bytes(&address.address)
        .map_err(|e| Status::invalid_argument(format!("Invalid {field_name}: {e}")))
}

fn parse_tx_digest(
    digest: &Option<crate::common::TransactionDigest>,
    field_name: &str,
) -> Result<TransactionDigest, Status> {
    let digest = digest
        .as_ref()
        .ok_or_else(|| Status::invalid_argument(format!("{field_name} is required")))?;
    TransactionDigest::try_from(digest.digest.as_slice())
        .map_err(|e| Status::invalid_argument(format!("Invalid {field_name}: {e}")))
}

// Convert IotaEvent to protobuf Event
impl From<&IotaEvent> for Event {
    fn from(event: &IotaEvent) -> Self {
        Event {
            event_id: Some(EventId {
                event_seq: event.id.event_seq,
                tx_digest: Some(crate::common::TransactionDigest {
                    digest: event.id.tx_digest.into_inner().to_vec(),
                }),
            }),
            package_id: Some(crate::common::Address {
                address: event.package_id.to_vec(),
            }),
            transaction_module: event.transaction_module.to_string(),
            sender: Some(crate::common::Address {
                address: event.sender.to_vec(),
            }),
            type_name: event.type_.to_string(),
            parsed_json: event.parsed_json.to_string(),
            timestamp_ms: event.timestamp_ms,
            event_data: Some(crate::common::BcsData {
                data: event.bcs.bytes().to_vec(),
            }),
        }
    }
}
