// Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

use std::sync::Arc;

use futures::{StreamExt, stream::BoxStream};
use iota_core::subscription_handler::SubscriptionHandler;
use iota_grpc_types::{
    transactions::{IotaTransactionKind, TransactionFilter},
    v0::{common as grpc_common, transactions as grpc_transactions},
};
use iota_types::{
    base_types::{IotaAddress, ObjectID},
    effects::TransactionEffectsAPI,
};
use tokio_util::sync::CancellationToken;
use tonic::{Request, Response, Status};
use tracing::debug;

pub struct TransactionGrpcService {
    pub event_subscriber: Arc<SubscriptionHandler>,
    pub cancellation_token: CancellationToken,
}

impl TransactionGrpcService {
    pub fn new(
        event_subscriber: Arc<SubscriptionHandler>,
        cancellation_token: CancellationToken,
    ) -> Self {
        Self {
            event_subscriber,
            cancellation_token,
        }
    }
}

// The `TransactionService` is the auto-generated trait from the protobuf
// definition. It's generated by tonic/protobuf and defines the interface that
// any gRPC transaction service must implement.
#[tonic::async_trait]
impl grpc_transactions::transaction_service_server::TransactionService for TransactionGrpcService {
    type StreamTransactionsStream =
        BoxStream<'static, Result<grpc_transactions::Transaction, Status>>;

    async fn stream_transactions(
        &self,
        request: Request<grpc_transactions::TransactionStreamRequest>,
    ) -> Result<Response<Self::StreamTransactionsStream>, Status> {
        let proto_filter = request
            .into_inner()
            .filter
            .ok_or_else(|| Status::invalid_argument("Filter is required"))?;

        let transaction_filter = create_transaction_filter(&proto_filter)?;
        debug!("New gRPC client subscribed with filter: {transaction_filter:?}");

        // Subscribe to transactions using the gRPC subscription method
        let mut transaction_stream = self
            .event_subscriber
            .subscribe_transactions_grpc(transaction_filter);
        let cancellation_token = self.cancellation_token.clone();

        let stream = async_stream::stream! {
            loop {
                let transaction_result = tokio::select! {
                    transaction_option = transaction_stream.next() => transaction_option,
                    _ = cancellation_token.cancelled() => {
                        debug!("Transaction stream cancelled");
                        None
                    }
                };

                match transaction_result {
                    Some(transaction_effects) => {
                        // Get transaction digest from effects
                        let tx_digest = transaction_effects.transaction_digest();

                        debug!("Transaction matched filter: TX: {}", tx_digest);

                        // Serialize to BCS
                        let data = match bcs::to_bytes(&transaction_effects) {
                            Ok(data) => data,
                            Err(e) => {
                                yield Err(Status::internal(format!("Failed to serialize transaction effects: {e}")));
                                continue;
                            }
                        };

                        yield Ok(grpc_transactions::Transaction {
                            bcs_data: Some(grpc_common::BcsData { data })
                        });
                    }
                    None => {
                        // Stream ended or cancellation occurred
                        debug!("Transaction stream ended");
                        break;
                    }
                }
            }
        };

        Ok(Response::new(Box::pin(stream)))
    }
}

/// Convert protobuf TransactionFilter to iota_grpc_types::TransactionFilter
fn create_transaction_filter(
    proto_filter: &grpc_transactions::TransactionFilter,
) -> Result<TransactionFilter, Status> {
    use grpc_transactions::transaction_filter::Filter;

    match &proto_filter.filter {
        Some(Filter::All(_)) => {
            // For "All" transactions, include all possible transaction kinds
            Ok(TransactionFilter::TransactionKindIn(vec![
                IotaTransactionKind::SystemTransaction,
                IotaTransactionKind::ProgrammableTransaction,
                IotaTransactionKind::Genesis,
                IotaTransactionKind::ConsensusCommitPrologueV1,
                IotaTransactionKind::AuthenticatorStateUpdateV1,
                IotaTransactionKind::RandomnessStateUpdate,
                IotaTransactionKind::EndOfEpochTransaction,
            ]))
        }
        Some(Filter::Checkpoint(_)) => Err(Status::invalid_argument(
            "Checkpoint filter not supported for streaming",
        )),
        Some(Filter::MoveFunction(f)) => {
            let package_id = parse_object_id(&f.package_id, "Package ID")?;
            Ok(TransactionFilter::MoveFunction {
                package: package_id,
                module: f.module.clone(),
                function: f.function.clone(),
            })
        }
        Some(Filter::InputObject(f)) => {
            let object_id = parse_object_id(&f.object_id, "Object ID")?;
            Ok(TransactionFilter::InputObject(object_id))
        }
        Some(Filter::ChangedObject(f)) => {
            let object_id = parse_object_id(&f.object_id, "Object ID")?;
            Ok(TransactionFilter::ChangedObject(object_id))
        }
        Some(Filter::FromAddress(f)) => {
            let address = parse_iota_address(&f.address, "From address")?;
            Ok(TransactionFilter::FromAddress(address))
        }
        Some(Filter::ToAddress(f)) => {
            let address = parse_iota_address(&f.address, "To address")?;
            Ok(TransactionFilter::ToAddress(address))
        }
        Some(Filter::FromAndToAddress(f)) => {
            let from_address = parse_iota_address(&f.from_address, "From address")?;
            let to_address = parse_iota_address(&f.to_address, "To address")?;
            Ok(TransactionFilter::FromAndToAddress {
                from: from_address,
                to: to_address,
            })
        }
        Some(Filter::FromOrToAddress(f)) => {
            let address = parse_iota_address(&f.address, "From or to address")?;
            Ok(TransactionFilter::FromOrToAddress { addr: address })
        }
        Some(Filter::TransactionKind(f)) => {
            let kind = convert_transaction_kind(f.kind)?;
            Ok(TransactionFilter::TransactionKind(kind))
        }
        Some(Filter::TransactionKindIn(f)) => {
            let kinds = f
                .kinds
                .iter()
                .map(|k| convert_transaction_kind(*k))
                .collect::<Result<Vec<_>, _>>()?;
            Ok(TransactionFilter::TransactionKindIn(kinds))
        }
        None => {
            // Default to all transaction types
            Ok(TransactionFilter::TransactionKindIn(vec![
                IotaTransactionKind::SystemTransaction,
                IotaTransactionKind::ProgrammableTransaction,
                IotaTransactionKind::Genesis,
                IotaTransactionKind::ConsensusCommitPrologueV1,
                IotaTransactionKind::AuthenticatorStateUpdateV1,
                IotaTransactionKind::RandomnessStateUpdate,
                IotaTransactionKind::EndOfEpochTransaction,
            ]))
        }
    }
}

// Helper functions to reduce repetition and improve error messages
fn parse_object_id(
    address: &Option<grpc_common::Address>,
    field_name: &str,
) -> Result<ObjectID, Status> {
    let address = address
        .as_ref()
        .ok_or_else(|| Status::invalid_argument(format!("{field_name} is required")))?;
    ObjectID::from_bytes(&address.address)
        .map_err(|e| Status::invalid_argument(format!("Invalid {field_name}: {e}")))
}

fn parse_iota_address(
    address: &Option<grpc_common::Address>,
    field_name: &str,
) -> Result<IotaAddress, Status> {
    let address = address
        .as_ref()
        .ok_or_else(|| Status::invalid_argument(format!("{field_name} is required")))?;
    IotaAddress::from_bytes(&address.address)
        .map_err(|e| Status::invalid_argument(format!("Invalid {field_name}: {e}")))
}

fn convert_transaction_kind(kind: i32) -> Result<IotaTransactionKind, Status> {
    match grpc_transactions::TransactionKind::try_from(kind) {
        Ok(grpc_transactions::TransactionKind::SystemTransaction) => {
            Ok(IotaTransactionKind::SystemTransaction)
        }
        Ok(grpc_transactions::TransactionKind::ProgrammableTransaction) => {
            Ok(IotaTransactionKind::ProgrammableTransaction)
        }
        Ok(grpc_transactions::TransactionKind::Genesis) => Ok(IotaTransactionKind::Genesis),
        Ok(grpc_transactions::TransactionKind::ConsensusCommitPrologueV1) => {
            Ok(IotaTransactionKind::ConsensusCommitPrologueV1)
        }
        Ok(grpc_transactions::TransactionKind::AuthenticatorStateUpdateV1) => {
            Ok(IotaTransactionKind::AuthenticatorStateUpdateV1)
        }
        Ok(grpc_transactions::TransactionKind::RandomnessStateUpdate) => {
            Ok(IotaTransactionKind::RandomnessStateUpdate)
        }
        Ok(grpc_transactions::TransactionKind::EndOfEpochTransaction) => {
            Ok(IotaTransactionKind::EndOfEpochTransaction)
        }
        Err(_) => Err(Status::invalid_argument("Invalid transaction kind")),
    }
}
