processed 35 tasks

init:
A: object(0,0)

task 1, lines 13-83:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 11012400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 85-87:
//# programmable --sender A --inputs @A 42
//> 0: Test::M1::parent(Input(0));
//> 1: Test::M1::child(Input(0));
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3549200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 89:
//# view-object 2,1
Owner: Account Address ( A )
Version: 2
Contents: Test::M1::Parent {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 4, line 91:
//# view-object 2,0
Owner: Account Address ( A )
Version: 2
Contents: Test::M1::Child {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 0u64,
}

task 5, lines 93-95:
//# programmable --sender A --inputs object(2,1) object(2,0) 420
//> Test::M1::add_child(Input(0), Input(1), Input(2));
//> Test::M1::mutate_child_via_parent(Input(0), Input(2));
created: object(5,0)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 6004000,  storage_rebate: 3549200, non_refundable_storage_fee: 0

task 6, line 97:
//# view-object 2,1
Owner: Account Address ( A )
Version: 3
Contents: Test::M1::Parent {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 7, line 99:
//# view-object 2,0
Owner: Object ID: ( fake(5,0) )
Version: 3
Contents: Test::M1::Child {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 1u64,
}

task 8, line 101:
//# create-checkpoint
Checkpoint created: 1

task 9, lines 103-165:
//# run-graphql
Response: {
  "data": {
    "parent_version_2_no_dof": {
      "address": "0x9330e8430f55caa7778062fd88f139709b4452f60aa30115543e4cb46ea2bd4b",
      "dynamicFields": {
        "edges": []
      }
    },
    "parent_version_3_has_dof": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IP4C5WDg6e2AZTBSICpv6UIMrz/BpjaQWGg4FgTr0eMXAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x4fc1596c74d0f05a45fb272a50cd87b87d8028acfd14324af4d6f7f606a31939",
                    "count": "1"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "child_version_2_no_parent": {
      "address": "0x4fc1596c74d0f05a45fb272a50cd87b87d8028acfd14324af4d6f7f606a31939",
      "owner": {}
    },
    "child_version_3_has_parent": {
      "owner": {
        "parent": {
          "address": "0xfe02e560e0e9ed80653052202a6fe9420caf3fc1a636905868381604ebd1e317"
        }
      }
    }
  }
}

task 10, lines 167-169:
//# programmable --sender A --inputs object(2,1) 420
//> Test::M1::mutate_child_via_parent(Input(0), Input(1));
//> Test::M1::add_df(Input(0));
created: object(10,0), object(10,1), object(10,2)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 9910400,  storage_rebate: 3549200, non_refundable_storage_fee: 0

task 11, line 171:
//# view-object 2,1
Owner: Account Address ( A )
Version: 4
Contents: Test::M1::Parent {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 12, line 173:
//# view-object 2,0
Owner: Object ID: ( fake(5,0) )
Version: 4
Contents: Test::M1::Child {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 2u64,
}

task 13, line 175:
//# create-checkpoint
Checkpoint created: 2

task 14, lines 177-237:
//# run-graphql --cursors @{obj_5_0,1} @{obj_5_0,2}
Response: {
  "data": {
    "parent_version_4_show_dof_and_dfs": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "ICoDlrtr0wdGbAyetBpRobV0BnadgYiBG7whmWlpwknUAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "IJoz998oOiy3+iA5xNgn46nWqGzlmApgkSwZa+CH3FXNAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "INbPWtvp9mYpkP1811SrnecveSdOHwxArqJGFwqcHLrfAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "IP4C5WDg6e2AZTBSICpv6UIMrz/BpjaQWGg4FgTr0eMXAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x4fc1596c74d0f05a45fb272a50cd87b87d8028acfd14324af4d6f7f606a31939",
                    "count": "2"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "parent_version_3_only_dof": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IP4C5WDg6e2AZTBSICpv6UIMrz/BpjaQWGg4FgTr0eMXAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x4fc1596c74d0f05a45fb272a50cd87b87d8028acfd14324af4d6f7f606a31939",
                    "count": "1"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "use_dof_version_3_cursor_at_parent_version_4": {
      "dynamicFields": {
        "edges": []
      }
    },
    "use_dof_version_4_cursor_at_parent_version_4": {
      "dynamicFields": {
        "edges": []
      }
    },
    "use_dof_version_3_cursor_at_parent_version_3": {
      "dynamicFields": {
        "edges": []
      }
    },
    "use_dof_version_4_cursor_at_version_3": {
      "dynamicFields": {
        "edges": []
      }
    }
  }
}

task 15, lines 239-276:
//# run-graphql
Response: {
  "data": {
    "parent_version_3": {
      "dynamicObjectField": {
        "name": {
          "bcs": "pAEAAAAAAAA=",
          "type": {
            "repr": "u64"
          }
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x4fc1596c74d0f05a45fb272a50cd87b87d8028acfd14324af4d6f7f606a31939",
              "count": "1"
            }
          }
        }
      },
      "dfNotAvailableYet": null
    },
    "parent_version_4": {
      "dynamicObjectField": {
        "name": {
          "bcs": "pAEAAAAAAAA=",
          "type": {
            "repr": "u64"
          }
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x4fc1596c74d0f05a45fb272a50cd87b87d8028acfd14324af4d6f7f606a31939",
              "count": "2"
            }
          }
        }
      },
      "dfAddedHere": {
        "name": {
          "bcs": "A2RmMQ==",
          "type": {
            "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
          }
        },
        "value": {
          "json": "df1"
        }
      }
    }
  }
}

task 16, lines 279-280:
//# programmable --sender A --inputs object(2,1)
//> Test::M1::add_more_df(Input(0));
created: object(16,0), object(16,1), object(16,2)
mutated: object(0,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 8603200,  storage_rebate: 2242000, non_refundable_storage_fee: 0

task 17, line 282:
//# view-object 2,1
Owner: Account Address ( A )
Version: 5
Contents: Test::M1::Parent {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 18, line 284:
//# view-object 2,0
Owner: Object ID: ( fake(5,0) )
Version: 4
Contents: Test::M1::Child {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 2u64,
}

task 19, line 286:
//# create-checkpoint
Checkpoint created: 3

task 20, lines 288-338:
//# run-graphql --cursors @{obj_5_0,2} @{obj_5_0,3}
Response: {
  "data": {
    "parent_version_4_has_4_children": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "ICoDlrtr0wdGbAyetBpRobV0BnadgYiBG7whmWlpwknUAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "IJoz998oOiy3+iA5xNgn46nWqGzlmApgkSwZa+CH3FXNAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "INbPWtvp9mYpkP1811SrnecveSdOHwxArqJGFwqcHLrfAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "IP4C5WDg6e2AZTBSICpv6UIMrz/BpjaQWGg4FgTr0eMXAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x4fc1596c74d0f05a45fb272a50cd87b87d8028acfd14324af4d6f7f606a31939",
                    "count": "2"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "parent_version_4_paginated_on_dof_consistent": {
      "dynamicFields": {
        "edges": []
      }
    },
    "parent_version_5_has_7_children": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IBMu2Y0auTWpC3F/vKnoovIyXzXTIP91IcgHPkbCPwtMAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "ICoDlrtr0wdGbAyetBpRobV0BnadgYiBG7whmWlpwknUAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "IDtIk2Duq9xXLM2yULkdvPo23/wDngCY/j8RgBQy21uAAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IJoz998oOiy3+iA5xNgn46nWqGzlmApgkSwZa+CH3FXNAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "INbPWtvp9mYpkP1811SrnecveSdOHwxArqJGFwqcHLrfAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "IPy62mZtW7QLaRH0M4ty5kx2lcC/WrzKayrn5dWXGJ2MAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "IP4C5WDg6e2AZTBSICpv6UIMrz/BpjaQWGg4FgTr0eMXAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x4fc1596c74d0f05a45fb272a50cd87b87d8028acfd14324af4d6f7f606a31939",
                    "count": "2"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "parent_version_5_paginated_on_dof_consistent": {
      "dynamicFields": {
        "edges": []
      }
    }
  }
}

task 21, lines 340-341:
//# programmable --sender A --inputs object(2,1) 420
//> Test::M1::remove_df(Input(0));
mutated: object(0,0), object(2,1)
deleted: object(10,0), object(10,1), object(10,2)
gas summary: computation_cost: 1000000, storage_cost: 2242000,  storage_rebate: 8603200, non_refundable_storage_fee: 0

task 22, line 343:
//# view-object 2,1
Owner: Account Address ( A )
Version: 6
Contents: Test::M1::Parent {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 23, line 345:
//# view-object 2,0
Owner: Object ID: ( fake(5,0) )
Version: 4
Contents: Test::M1::Child {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 2u64,
}

task 24, line 347:
//# create-checkpoint
Checkpoint created: 4

task 25, lines 349-399:
//# run-graphql --cursors @{obj_5_0,2} @{obj_5_0,4}
Response: {
  "data": {
    "parent_version_4_has_df1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "ICoDlrtr0wdGbAyetBpRobV0BnadgYiBG7whmWlpwknUBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "IJoz998oOiy3+iA5xNgn46nWqGzlmApgkSwZa+CH3FXNBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "INbPWtvp9mYpkP1811SrnecveSdOHwxArqJGFwqcHLrfBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "IP4C5WDg6e2AZTBSICpv6UIMrz/BpjaQWGg4FgTr0eMXBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x4fc1596c74d0f05a45fb272a50cd87b87d8028acfd14324af4d6f7f606a31939",
                    "count": "2"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "parent_version_4_paginated_on_dof_consistent": {
      "dynamicFields": {
        "edges": []
      }
    },
    "parent_version_6_no_df_1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IBMu2Y0auTWpC3F/vKnoovIyXzXTIP91IcgHPkbCPwtMBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IDtIk2Duq9xXLM2yULkdvPo23/wDngCY/j8RgBQy21uABAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IPy62mZtW7QLaRH0M4ty5kx2lcC/WrzKayrn5dWXGJ2MBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "IP4C5WDg6e2AZTBSICpv6UIMrz/BpjaQWGg4FgTr0eMXBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x4fc1596c74d0f05a45fb272a50cd87b87d8028acfd14324af4d6f7f606a31939",
                    "count": "2"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "parent_version_6_paginated_no_df_1_2_3": {
      "dynamicFields": {
        "edges": []
      }
    }
  }
}

task 26, lines 401-432:
//# run-graphql
Response: {
  "data": {
    "parent_version_4": {
      "dfAtParentVersion4": {
        "name": {
          "bcs": "A2RmMQ==",
          "type": {
            "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
          }
        },
        "value": {
          "json": "df1"
        }
      }
    },
    "parent_version_6": {
      "dfAtParentVersion6": null
    }
  }
}

task 28, line 436:
//# create-checkpoint
Checkpoint created: 5

task 30, line 440:
//# create-checkpoint
Checkpoint created: 6

task 31, line 442:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 5
Objects snapshot updated to [0 to 5)

task 32, line 444:
//# create-checkpoint
Checkpoint created: 7

task 33, lines 446-496:
//# run-graphql --cursors @{obj_5_0,2} @{obj_5_0,4}
Response: {
  "data": {
    "parent_version_4_outside_consistent_range": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IP4C5WDg6e2AZTBSICpv6UIMrz/BpjaQWGg4FgTr0eMXBwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x4fc1596c74d0f05a45fb272a50cd87b87d8028acfd14324af4d6f7f606a31939",
                    "count": "2"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "parent_version_4_paginated_outside_consistent_range": null,
    "parent_version_6_no_df_1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IBMu2Y0auTWpC3F/vKnoovIyXzXTIP91IcgHPkbCPwtMBwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IDtIk2Duq9xXLM2yULkdvPo23/wDngCY/j8RgBQy21uABwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IPy62mZtW7QLaRH0M4ty5kx2lcC/WrzKayrn5dWXGJ2MBwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "IP4C5WDg6e2AZTBSICpv6UIMrz/BpjaQWGg4FgTr0eMXBwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x4fc1596c74d0f05a45fb272a50cd87b87d8028acfd14324af4d6f7f606a31939",
                    "count": "2"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "parent_version_6_paginated_no_df_1_2_3": {
      "dynamicFields": {
        "edges": []
      }
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 34,
          "column": 5
        }
      ],
      "path": [
        "parent_version_4_paginated_outside_consistent_range",
        "dynamicFields"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 34, lines 498-529:
//# run-graphql
Response: {
  "data": {
    "parent_version_4": {
      "dfAtParentVersion4_outside_range": {
        "name": {
          "bcs": "A2RmMQ==",
          "type": {
            "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
          }
        },
        "value": {
          "json": "df1"
        }
      }
    },
    "parent_version_6": {
      "dfAtParentVersion6": null
    }
  }
}
