processed 35 tasks

init:
A: object(0,0)

task 1, lines 13-83:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 11004800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 85-87:
//# programmable --sender A --inputs @A 42
//> 0: Test::M1::parent(Input(0));
//> 1: Test::M1::child(Input(0));
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3526400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 89:
//# view-object 2,1
Owner: Account Address ( A )
Version: 2
Contents: Test::M1::Parent {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 4, line 91:
//# view-object 2,0
Owner: Account Address ( A )
Version: 2
Contents: Test::M1::Child {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 0u64,
}

task 5, lines 93-95:
//# programmable --sender A --inputs object(2,1) object(2,0) 420
//> Test::M1::add_child(Input(0), Input(1), Input(2));
//> Test::M1::mutate_child_via_parent(Input(0), Input(2));
created: object(5,0)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 5973600,  storage_rebate: 3526400, non_refundable_storage_fee: 0

task 6, line 97:
//# view-object 2,1
Owner: Account Address ( A )
Version: 3
Contents: Test::M1::Parent {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 7, line 99:
//# view-object 2,0
Owner: Object ID: ( fake(5,0) )
Version: 3
Contents: Test::M1::Child {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 1u64,
}

task 8, line 101:
//# create-checkpoint
Checkpoint created: 1

task 9, lines 103-165:
//# run-graphql
Response: {
  "data": {
    "parent_version_2_no_dof": {
      "address": "0x3032a2236c5e2f122808bbce3c329dbafcb39669c85a9958c311869729e2f432",
      "dynamicFields": {
        "edges": []
      }
    },
    "parent_version_3_has_dof": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IDeK+yIQ6ezeNidvyctps/7HlB909dxow89/ZxAfA6XQAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x9eb2d1215c4ef76a4b584e00d44448e44db829b6596f03d9d97e92d6e4067585",
                    "count": "1"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "child_version_2_no_parent": {
      "address": "0x9eb2d1215c4ef76a4b584e00d44448e44db829b6596f03d9d97e92d6e4067585",
      "owner": {}
    },
    "child_version_3_has_parent": {
      "owner": {
        "parent": {
          "address": "0x378afb2210e9ecde36276fc9cb69b3fec7941f74f5dc68c3cf7f67101f03a5d0"
        }
      }
    }
  }
}

task 10, lines 167-169:
//# programmable --sender A --inputs object(2,1) 420
//> Test::M1::mutate_child_via_parent(Input(0), Input(1));
//> Test::M1::add_df(Input(0));
created: object(10,0), object(10,1), object(10,2)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 9864800,  storage_rebate: 3526400, non_refundable_storage_fee: 0

task 11, line 171:
//# view-object 2,1
Owner: Account Address ( A )
Version: 4
Contents: Test::M1::Parent {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 12, line 173:
//# view-object 2,0
Owner: Object ID: ( fake(5,0) )
Version: 4
Contents: Test::M1::Child {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 2u64,
}

task 13, line 175:
//# create-checkpoint
Checkpoint created: 2

task 14, lines 177-237:
//# run-graphql --cursors @{obj_5_0,1} @{obj_5_0,2}
Response: {
  "data": {
    "parent_version_4_show_dof_and_dfs": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "ICxurO1XBMm2muGLkO8P4RqREILGj31n+0dReoVuveKNAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "IDeK+yIQ6ezeNidvyctps/7HlB909dxow89/ZxAfA6XQAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x9eb2d1215c4ef76a4b584e00d44448e44db829b6596f03d9d97e92d6e4067585",
                    "count": "2"
                  }
                }
              }
            }
          },
          {
            "cursor": "IDgdCSQ+Fs+dyDxVRbf4I9n8txhmJ3RdTEsd0VH0x0gCAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IPONIqKbjdt5uGk3lOP5NIhQrAQ887iwBRV4quT3MHeSAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          }
        ]
      }
    },
    "parent_version_3_only_dof": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IDeK+yIQ6ezeNidvyctps/7HlB909dxow89/ZxAfA6XQAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x9eb2d1215c4ef76a4b584e00d44448e44db829b6596f03d9d97e92d6e4067585",
                    "count": "1"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "use_dof_version_3_cursor_at_parent_version_4": {
      "dynamicFields": {
        "edges": []
      }
    },
    "use_dof_version_4_cursor_at_parent_version_4": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IDgdCSQ+Fs+dyDxVRbf4I9n8txhmJ3RdTEsd0VH0x0gCAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IPONIqKbjdt5uGk3lOP5NIhQrAQ887iwBRV4quT3MHeSAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          }
        ]
      }
    },
    "use_dof_version_3_cursor_at_parent_version_3": {
      "dynamicFields": {
        "edges": []
      }
    },
    "use_dof_version_4_cursor_at_version_3": {
      "dynamicFields": {
        "edges": []
      }
    }
  }
}

task 15, lines 239-276:
//# run-graphql
Response: {
  "data": {
    "parent_version_3": {
      "dynamicObjectField": {
        "name": {
          "bcs": "pAEAAAAAAAA=",
          "type": {
            "repr": "u64"
          }
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x9eb2d1215c4ef76a4b584e00d44448e44db829b6596f03d9d97e92d6e4067585",
              "count": "1"
            }
          }
        }
      },
      "dfNotAvailableYet": null
    },
    "parent_version_4": {
      "dynamicObjectField": {
        "name": {
          "bcs": "pAEAAAAAAAA=",
          "type": {
            "repr": "u64"
          }
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x9eb2d1215c4ef76a4b584e00d44448e44db829b6596f03d9d97e92d6e4067585",
              "count": "2"
            }
          }
        }
      },
      "dfAddedHere": {
        "name": {
          "bcs": "A2RmMQ==",
          "type": {
            "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
          }
        },
        "value": {
          "json": "df1"
        }
      }
    }
  }
}

task 16, lines 279-280:
//# programmable --sender A --inputs object(2,1)
//> Test::M1::add_more_df(Input(0));
created: object(16,0), object(16,1), object(16,2)
mutated: object(0,0), object(2,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 8565200,  storage_rebate: 2226800, non_refundable_storage_fee: 0

task 17, line 282:
//# view-object 2,1
Owner: Account Address ( A )
Version: 5
Contents: Test::M1::Parent {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 18, line 284:
//# view-object 2,0
Owner: Object ID: ( fake(5,0) )
Version: 4
Contents: Test::M1::Child {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 2u64,
}

task 19, line 286:
//# create-checkpoint
Checkpoint created: 3

task 20, lines 288-338:
//# run-graphql --cursors @{obj_5_0,2} @{obj_5_0,3}
Response: {
  "data": {
    "parent_version_4_has_4_children": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "ICxurO1XBMm2muGLkO8P4RqREILGj31n+0dReoVuveKNAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "IDeK+yIQ6ezeNidvyctps/7HlB909dxow89/ZxAfA6XQAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x9eb2d1215c4ef76a4b584e00d44448e44db829b6596f03d9d97e92d6e4067585",
                    "count": "2"
                  }
                }
              }
            }
          },
          {
            "cursor": "IDgdCSQ+Fs+dyDxVRbf4I9n8txhmJ3RdTEsd0VH0x0gCAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IPONIqKbjdt5uGk3lOP5NIhQrAQ887iwBRV4quT3MHeSAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          }
        ]
      }
    },
    "parent_version_4_paginated_on_dof_consistent": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IDgdCSQ+Fs+dyDxVRbf4I9n8txhmJ3RdTEsd0VH0x0gCAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IPONIqKbjdt5uGk3lOP5NIhQrAQ887iwBRV4quT3MHeSAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          }
        ]
      }
    },
    "parent_version_5_has_7_children": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "ICxurO1XBMm2muGLkO8P4RqREILGj31n+0dReoVuveKNAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "IDeK+yIQ6ezeNidvyctps/7HlB909dxow89/ZxAfA6XQAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x9eb2d1215c4ef76a4b584e00d44448e44db829b6596f03d9d97e92d6e4067585",
                    "count": "2"
                  }
                }
              }
            }
          },
          {
            "cursor": "IDgdCSQ+Fs+dyDxVRbf4I9n8txhmJ3RdTEsd0VH0x0gCAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IG6kCifeAtk2miLE24gnlF8GahfH0qaoukLEnwTWk1KlAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IKGQXOLV4kLWhlqin5NpKhOnEfeTCsR490LS93AhCLgAAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "IPNMwJLkql332rR0Zix83pAMKKkvhpNjSbtEvADTLRk4AwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IPONIqKbjdt5uGk3lOP5NIhQrAQ887iwBRV4quT3MHeSAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          }
        ]
      }
    },
    "parent_version_5_paginated_on_dof_consistent": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IDgdCSQ+Fs+dyDxVRbf4I9n8txhmJ3RdTEsd0VH0x0gCAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IG6kCifeAtk2miLE24gnlF8GahfH0qaoukLEnwTWk1KlAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IKGQXOLV4kLWhlqin5NpKhOnEfeTCsR490LS93AhCLgAAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "IPNMwJLkql332rR0Zix83pAMKKkvhpNjSbtEvADTLRk4AwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IPONIqKbjdt5uGk3lOP5NIhQrAQ887iwBRV4quT3MHeSAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          }
        ]
      }
    }
  }
}

task 21, lines 340-341:
//# programmable --sender A --inputs object(2,1) 420
//> Test::M1::remove_df(Input(0));
mutated: object(0,0), object(2,1)
deleted: object(10,0), object(10,1), object(10,2)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2226800,  storage_rebate: 8565200, non_refundable_storage_fee: 0

task 22, line 343:
//# view-object 2,1
Owner: Account Address ( A )
Version: 6
Contents: Test::M1::Parent {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 23, line 345:
//# view-object 2,0
Owner: Object ID: ( fake(5,0) )
Version: 4
Contents: Test::M1::Child {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 2u64,
}

task 24, line 347:
//# create-checkpoint
Checkpoint created: 4

task 25, lines 349-399:
//# run-graphql --cursors @{obj_5_0,2} @{obj_5_0,4}
Response: {
  "data": {
    "parent_version_4_has_df1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "ICxurO1XBMm2muGLkO8P4RqREILGj31n+0dReoVuveKNBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "IDeK+yIQ6ezeNidvyctps/7HlB909dxow89/ZxAfA6XQBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x9eb2d1215c4ef76a4b584e00d44448e44db829b6596f03d9d97e92d6e4067585",
                    "count": "2"
                  }
                }
              }
            }
          },
          {
            "cursor": "IDgdCSQ+Fs+dyDxVRbf4I9n8txhmJ3RdTEsd0VH0x0gCBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IPONIqKbjdt5uGk3lOP5NIhQrAQ887iwBRV4quT3MHeSBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          }
        ]
      }
    },
    "parent_version_4_paginated_on_dof_consistent": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IDgdCSQ+Fs+dyDxVRbf4I9n8txhmJ3RdTEsd0VH0x0gCAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IPONIqKbjdt5uGk3lOP5NIhQrAQ887iwBRV4quT3MHeSAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          }
        ]
      }
    },
    "parent_version_6_no_df_1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IDeK+yIQ6ezeNidvyctps/7HlB909dxow89/ZxAfA6XQBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x9eb2d1215c4ef76a4b584e00d44448e44db829b6596f03d9d97e92d6e4067585",
                    "count": "2"
                  }
                }
              }
            }
          },
          {
            "cursor": "IG6kCifeAtk2miLE24gnlF8GahfH0qaoukLEnwTWk1KlBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IKGQXOLV4kLWhlqin5NpKhOnEfeTCsR490LS93AhCLgABAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "IPNMwJLkql332rR0Zix83pAMKKkvhpNjSbtEvADTLRk4BAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          }
        ]
      }
    },
    "parent_version_6_paginated_no_df_1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IG6kCifeAtk2miLE24gnlF8GahfH0qaoukLEnwTWk1KlBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IKGQXOLV4kLWhlqin5NpKhOnEfeTCsR490LS93AhCLgABAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "IPNMwJLkql332rR0Zix83pAMKKkvhpNjSbtEvADTLRk4BAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          }
        ]
      }
    }
  }
}

task 26, lines 401-432:
//# run-graphql
Response: {
  "data": {
    "parent_version_4": {
      "dfAtParentVersion4": {
        "name": {
          "bcs": "A2RmMQ==",
          "type": {
            "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
          }
        },
        "value": {
          "json": "df1"
        }
      }
    },
    "parent_version_6": {
      "dfAtParentVersion6": null
    }
  }
}

task 28, line 436:
//# create-checkpoint
Checkpoint created: 5

task 30, line 440:
//# create-checkpoint
Checkpoint created: 6

task 31, line 442:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 5
Objects snapshot updated to [0 to 5)

task 32, line 444:
//# create-checkpoint
Checkpoint created: 7

task 33, lines 446-496:
//# run-graphql --cursors @{obj_5_0,2} @{obj_5_0,4}
Response: {
  "data": {
    "parent_version_4_outside_consistent_range": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IDeK+yIQ6ezeNidvyctps/7HlB909dxow89/ZxAfA6XQBwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x9eb2d1215c4ef76a4b584e00d44448e44db829b6596f03d9d97e92d6e4067585",
                    "count": "2"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "parent_version_4_paginated_outside_consistent_range": null,
    "parent_version_6_no_df_1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IDeK+yIQ6ezeNidvyctps/7HlB909dxow89/ZxAfA6XQBwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x9eb2d1215c4ef76a4b584e00d44448e44db829b6596f03d9d97e92d6e4067585",
                    "count": "2"
                  }
                }
              }
            }
          },
          {
            "cursor": "IG6kCifeAtk2miLE24gnlF8GahfH0qaoukLEnwTWk1KlBwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IKGQXOLV4kLWhlqin5NpKhOnEfeTCsR490LS93AhCLgABwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "IPNMwJLkql332rR0Zix83pAMKKkvhpNjSbtEvADTLRk4BwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          }
        ]
      }
    },
    "parent_version_6_paginated_no_df_1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IG6kCifeAtk2miLE24gnlF8GahfH0qaoukLEnwTWk1KlBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IKGQXOLV4kLWhlqin5NpKhOnEfeTCsR490LS93AhCLgABAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "IPNMwJLkql332rR0Zix83pAMKKkvhpNjSbtEvADTLRk4BAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          }
        ]
      }
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 34,
          "column": 5
        }
      ],
      "path": [
        "parent_version_4_paginated_outside_consistent_range",
        "dynamicFields"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 34, lines 498-529:
//# run-graphql
Response: {
  "data": {
    "parent_version_4": {
      "dfAtParentVersion4_outside_range": {
        "name": {
          "bcs": "A2RmMQ==",
          "type": {
            "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
          }
        },
        "value": {
          "json": "df1"
        }
      }
    },
    "parent_version_6": {
      "dfAtParentVersion6": null
    }
  }
}
