processed 17 tasks

init:
A: object(0,0)

task 1, lines 25-76:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 8952800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 78:
//# run Test::M1::parent --sender A --args @A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 80:
//# run Test::M1::child --sender A --args @A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2280000,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 4, line 82:
//# run Test::M1::child --sender A --args @A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2280000,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 5, line 84:
//# run Test::M1::add_child --sender A --args object(2,0) object(3,0) 42
created: object(5,0)
mutated: object(0,0), object(2,0), object(3,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 6034400,  storage_rebate: 3587200, non_refundable_storage_fee: 0

task 6, line 86:
//# run Test::M1::add_nested_child --sender A --args object(2,0) 42 object(4,0) 420
created: object(6,0)
mutated: object(0,0), object(2,0), object(4,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 6034400,  storage_rebate: 3587200, non_refundable_storage_fee: 0

task 7, line 88:
//# run Test::M1::mutate_child_on_parent --sender A --args object(2,0) 42
mutated: object(0,0), object(2,0), object(3,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3587200,  storage_rebate: 3587200, non_refundable_storage_fee: 0

task 8, line 90:
//# run Test::M1::mutate_nested_child_on_parent --sender A --args object(2,0) 42 420
mutated: object(0,0), object(2,0), object(4,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3587200,  storage_rebate: 3587200, non_refundable_storage_fee: 0

task 9, line 92:
//# create-checkpoint
Checkpoint created: 1

task 10, lines 94-124:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0xde9667a98c2e9acdd09a31fd1157568060373645c655b1242a69f2e013001780",
              "version": 5,
              "contents": {
                "json": {
                  "id": "0xde9667a98c2e9acdd09a31fd1157568060373645c655b1242a69f2e013001780",
                  "count": "0"
                }
              },
              "dynamicFields": {
                "nodes": []
              }
            }
          }
        ]
      }
    }
  }
}

task 11, lines 126-156:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0xde9667a98c2e9acdd09a31fd1157568060373645c655b1242a69f2e013001780",
              "version": 5,
              "contents": {
                "json": {
                  "id": "0xde9667a98c2e9acdd09a31fd1157568060373645c655b1242a69f2e013001780",
                  "count": "0"
                }
              },
              "dynamicFields": {
                "nodes": [
                  {
                    "value": {
                      "address": "0x9305144f32b0377871fd89a33c04b9cac3cf03239cc9dc7be13aa7da12751634",
                      "version": 6,
                      "contents": {
                        "json": {
                          "id": "0x9305144f32b0377871fd89a33c04b9cac3cf03239cc9dc7be13aa7da12751634",
                          "count": "0"
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}

task 12, lines 158-188:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0xde9667a98c2e9acdd09a31fd1157568060373645c655b1242a69f2e013001780",
              "version": 7,
              "contents": {
                "json": {
                  "id": "0xde9667a98c2e9acdd09a31fd1157568060373645c655b1242a69f2e013001780",
                  "count": "1"
                }
              },
              "dynamicFields": {
                "nodes": [
                  {
                    "value": {
                      "address": "0x9305144f32b0377871fd89a33c04b9cac3cf03239cc9dc7be13aa7da12751634",
                      "version": 6,
                      "contents": {
                        "json": {
                          "id": "0x9305144f32b0377871fd89a33c04b9cac3cf03239cc9dc7be13aa7da12751634",
                          "count": "0"
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}

task 13, lines 190-220:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0xde9667a98c2e9acdd09a31fd1157568060373645c655b1242a69f2e013001780",
              "version": 7,
              "contents": {
                "json": {
                  "id": "0xde9667a98c2e9acdd09a31fd1157568060373645c655b1242a69f2e013001780",
                  "count": "1"
                }
              },
              "dynamicFields": {
                "nodes": [
                  {
                    "value": {
                      "address": "0x9305144f32b0377871fd89a33c04b9cac3cf03239cc9dc7be13aa7da12751634",
                      "version": 8,
                      "contents": {
                        "json": {
                          "id": "0x9305144f32b0377871fd89a33c04b9cac3cf03239cc9dc7be13aa7da12751634",
                          "count": "1"
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}

task 14, lines 222-239:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": []
      }
    }
  }
}

task 15, lines 241-258:
//# run-graphql
Response: {
  "data": {
    "object": null
  }
}

task 16, lines 260-277:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x9305144f32b0377871fd89a33c04b9cac3cf03239cc9dc7be13aa7da12751634",
              "version": 6,
              "contents": {
                "json": {
                  "id": "0x9305144f32b0377871fd89a33c04b9cac3cf03239cc9dc7be13aa7da12751634",
                  "count": "0"
                }
              }
            }
          }
        ]
      }
    }
  }
}
