{
 "title": "testbed",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "[Aggregated] TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(latency_s_count[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "[Aggregated] Avg Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(latency_s_sum/latency_s_count)"
    }
   ]
  },
  {
   "title": "[Aggregated] P50 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.5, sum by(le) (rate(latency_s_bucket[$__rate_interval]))))"
    }
   ]
  },
  {
   "title": "[Aggregated] P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.95, sum by(le) (rate(latency_s_bucket[$__rate_interval]))))"
    }
   ]
  },
  {
   "title": "[Individual] TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(latency_s_count[$__rate_interval])"
    }
   ]
  },
  {
   "title": "[Individual] Avg Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "latency_s_sum/latency_s_count" }
   ]
  },
  {
   "title": "[Individual] P50 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(latency_s_bucket{job=\"client-0\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(latency_s_bucket{job=\"client-1\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(latency_s_bucket{job=\"client-2\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(latency_s_bucket{job=\"client-3\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(latency_s_bucket{job=\"client-4\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(latency_s_bucket{job=\"client-5\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(latency_s_bucket{job=\"client-6\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(latency_s_bucket{job=\"client-7\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(latency_s_bucket{job=\"client-8\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(latency_s_bucket{job=\"client-9\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "[Individual] P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(latency_s_bucket{job=\"client-0\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(latency_s_bucket{job=\"client-1\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(latency_s_bucket{job=\"client-2\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(latency_s_bucket{job=\"client-3\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(latency_s_bucket{job=\"client-4\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(latency_s_bucket{job=\"client-5\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(latency_s_bucket{job=\"client-6\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(latency_s_bucket{job=\"client-7\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(latency_s_bucket{job=\"client-8\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(latency_s_bucket{job=\"client-9\"}[$__rate_interval])))"
    },
    {}
   ]
  }
 ]
}