#!/bin/bash
set -euo pipefail

# Downloads the IOTA SDK API reference markdown for every binding language.
#
# The tarballs are generated by the Reference Docs workflow in the
# iota-rust-sdk repository (scripts/reference-docs/generate.sh) and published
# as assets of its `docs-references` release. Each tarball contains
# docs/<language>/** which is copied to content/developer/iota-sdk/references/.
BASE_URL="https://github.com/iotaledger/iota-rust-sdk/releases/download/docs-references"

# Create temporary directory to work in
mkdir -p tmp
cd tmp || exit

process() {
    local language="$1"
    echo "Processing ${language} SDK reference..."
    curl -sfL "${BASE_URL}/${language}.tar.gz" | tar xz

    mkdir -p "../../content/developer/iota-sdk/references/"
    cp -R "docs/${language}" "../../content/developer/iota-sdk/references/"

    # Clean up for the next iteration
    rm -rf docs
}

process "python"
process "go"
process "kotlin"
process "csharp"
process "swift"

# Return to root and cleanup
cd - || exit
rm -rf tmp
