processed 21 tasks

init:
A: object(0,0)

task 1, lines 7-17:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6315600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 19:
//# create-checkpoint
Checkpoint created: 1

task 3, lines 21-200:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "AF9NExKic6MFUb7uv21hYnfdnXDXX4Tv8VHdFmNdbLpR",
          "sender": {
            "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
          },
          "signatures": [
            "AHXKweJHLP+QwKrtBRk+elknl3cX7xSfVknpPwxMbtPE5iUAY0otQhjW6Fsv/uimI4V+BQcfIu24N4QtXWRusA5/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x6e4f51e9a082897fb23e23a699deed7fed0f08579c9ed0bd483ed086f87a1e29"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "jMpOHOC6WQTOph35JC2i99KePvMo+37AfAhrO/R8pho="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "__typename": "PublishTransaction",
                    "modules": [
                      "oRzrCwYAAAAIAQAGAgYMAxIKBRwRBy0wCF1ACp0BCQymAQ8ABAEGAQcAAAwAAQIEAAIBAgAABQABAAEFAwQAAgoDBwgCAQgAAAEHCAIBCAEDRm9vCVR4Q29udGV4dANVSUQCaWQBbQNuZXcGb2JqZWN0CnR4X2NvbnRleHQCeHMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAICAwgBCAoDAAEAAAIFCwERAQsAEgACAA=="
                    ],
                    "dependencies": [
                      "0x0000000000000000000000000000000000000000000000000000000000000001",
                      "0x0000000000000000000000000000000000000000000000000000000000000002"
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoxfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 0,
                        "ix": null
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 0
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "9BoMRiBUPt96jz6BzVBdZMrLXSpZNBqjApaZy2wNaQu8"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
                  },
                  "amount": "-7315600",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x3d33853fc90b1fe007987920ff48ffc0f5860a46392981422c186bbc07b93e12",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x3d33853fc90b1fe007987920ff48ffc0f5860a46392981422c186bbc07b93e12",
                    "digest": "DYWs8UVPBrjsrjaq7WS2axTJdtQad4Job4fVAW9Kppa4"
                  }
                },
                {
                  "address": "0x6e4f51e9a082897fb23e23a699deed7fed0f08579c9ed0bd483ed086f87a1e29",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x6e4f51e9a082897fb23e23a699deed7fed0f08579c9ed0bd483ed086f87a1e29",
                    "digest": "Fc3ZyBhtgXCZpoaGpWFA7gP7jRLR3FjFTfv72TtFhfQb"
                  }
                },
                {
                  "address": "0xbd2cbb515d07f0f685a51cb83c4da64e8e8779744e0758ab3e95db7fed20ea06",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xbd2cbb515d07f0f685a51cb83c4da64e8e8779744e0758ab3e95db7fed20ea06",
                    "digest": "CX9AgVAQDmKZnD9t7yA28HpWpeWFs5eih8r9ff93YixW"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x6e4f51e9a082897fb23e23a699deed7fed0f08579c9ed0bd483ed086f87a1e29"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6315600",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "AF9NExKic6MFUb7uv21hYnfdnXDXX4Tv8VHdFmNdbLpR"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 4, lines 202-217:
//# upgrade --package P0 --upgrade-capability 1,0 --sender A
created: object(4,0)
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 6589200,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 5, line 219:
//# create-checkpoint
Checkpoint created: 2

task 6, lines 221-400:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "DxXm2H8hyxbdNEDPPVt9QmihGmURQE7E4ehJa28RUe3G",
          "sender": {
            "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
          },
          "signatures": [
            "ALHDWDdpPpeT+cQW5ipx6zJTcLLOf9BBUVADWDRC4MPs1pbUp6o6n/fiz6SZUd7AxOteCiq/LQ15PYb9lQ2HJAd/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x6e4f51e9a082897fb23e23a699deed7fed0f08579c9ed0bd483ed086f87a1e29"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "OwnedOrImmutable",
                    "address": "0xbd2cbb515d07f0f685a51cb83c4da64e8e8779744e0758ab3e95db7fed20ea06",
                    "version": 2,
                    "digest": "CX9AgVAQDmKZnD9t7yA28HpWpeWFs5eih8r9ff93YixW",
                    "object": {
                      "address": "0xbd2cbb515d07f0f685a51cb83c4da64e8e8779744e0758ab3e95db7fed20ea06",
                      "version": 2,
                      "digest": "CX9AgVAQDmKZnD9t7yA28HpWpeWFs5eih8r9ff93YixW",
                      "asMoveObject": {
                        "contents": {
                          "type": {
                            "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                          },
                          "json": {
                            "id": "0xbd2cbb515d07f0f685a51cb83c4da64e8e8779744e0758ab3e95db7fed20ea06",
                            "package": "0x3d33853fc90b1fe007987920ff48ffc0f5860a46392981422c186bbc07b93e12",
                            "version": "1",
                            "policy": 0
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoyfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "AA=="
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjoyfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "IKtSxFg0BLyRn8vrtIRqeqpsihVPvPFxPFBg5s0K+UqS"
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "module": "package",
                    "functionName": "authorize_upgrade",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Input",
                        "ix": 1
                      },
                      {
                        "__typename": "Input",
                        "ix": 2
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                        },
                        {
                          "repr": "u8"
                        },
                        {
                          "repr": "vector<u8>"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeTicket"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoyfQ",
                  "node": {
                    "__typename": "UpgradeTransaction",
                    "modules": [
                      "oRzrCwYAAAAIAQAGAgYMAxIUBSYRBzc8CHNACrMBCQy8AR0ABgEIAQkAAAwAAQIEAAIBAgAABwABAAADAQIAAQQEAgABBwMEAAIKAwcIAgEIAAABBwgCAQgBA0ZvbwlUeENvbnRleHQDVUlEBGJ1cm4GZGVsZXRlAmlkAW0DbmV3Bm9iamVjdAp0eF9jb250ZXh0AnhzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgACAgUIAQoKAwABAAACBQsBEQMLABIAAgEBAAACBQsAEwABEQICAA=="
                    ],
                    "dependencies": [
                      "0x0000000000000000000000000000000000000000000000000000000000000001",
                      "0x0000000000000000000000000000000000000000000000000000000000000002"
                    ],
                    "currentPackage": "0x3d33853fc90b1fe007987920ff48ffc0f5860a46392981422c186bbc07b93e12",
                    "upgradeTicket": {
                      "__typename": "Result",
                      "cmd": 0,
                      "ix": null
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjoyfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "module": "package",
                    "functionName": "commit_upgrade",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Result",
                        "cmd": 1,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                        },
                        {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeReceipt"
                        }
                      ],
                      "return": []
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 3,
            "dependencies": {
              "nodes": [
                {
                  "digest": "9BoMRiBUPt96jz6BzVBdZMrLXSpZNBqjApaZy2wNaQu8"
                },
                {
                  "digest": "AF9NExKic6MFUb7uv21hYnfdnXDXX4Tv8VHdFmNdbLpR"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
                  },
                  "amount": "-4967200",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x6e4f51e9a082897fb23e23a699deed7fed0f08579c9ed0bd483ed086f87a1e29",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x6e4f51e9a082897fb23e23a699deed7fed0f08579c9ed0bd483ed086f87a1e29",
                    "digest": "DAeq4atqtmRqBygsEip3dw7YQwe5Ha6Mxap5aUbxm96c"
                  }
                },
                {
                  "address": "0x77c4e897e28607c7608cda4288bd4dc973ff969797baff733fd416f41c2e08ec",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x77c4e897e28607c7608cda4288bd4dc973ff969797baff733fd416f41c2e08ec",
                    "digest": "9aMq4zYQj6KrFaLqTMYVpTTWZsB7SCHbq4M2BrPb7zYi"
                  }
                },
                {
                  "address": "0xbd2cbb515d07f0f685a51cb83c4da64e8e8779744e0758ab3e95db7fed20ea06",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xbd2cbb515d07f0f685a51cb83c4da64e8e8779744e0758ab3e95db7fed20ea06",
                    "digest": "3rUM1KZay3Us6LnPaw1uFMLVB1BbHbFdf3b5uFNJwy2F"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x6e4f51e9a082897fb23e23a699deed7fed0f08579c9ed0bd483ed086f87a1e29"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6589200",
                "storageRebate": "2622000",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "DxXm2H8hyxbdNEDPPVt9QmihGmURQE7E4ehJa28RUe3G"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 7, lines 402-405:
//# programmable --sender A --inputs 41u64 @A
//> 0: MakeMoveVec<u64>([Input(0)]);
//> 1: P0::m::new(Result(0));
//> iota::transfer::public_transfer<P0::m::Foo>(Result(1), Input(1))
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2280000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 8, lines 407-416:
//# programmable --sender A --inputs 42u64 43u64 1000 @A
//> 0: MakeMoveVec<u64>([Input(0), Input(1)]);
//> 1: MakeMoveVec<u64>([]);
//> 2: SplitCoins(Gas, [Input(2), Input(2)]);
//> 3: P0::m::new(Result(0));
//> 4: TransferObjects([Result(3)], Input(3));
//> 5: P0::m::new(Result(1));
//> 6: P0::m::burn(Result(5));
//> 7: MergeCoins(NestedResult(2,0), [NestedResult(2,1)]);
//> TransferObjects([NestedResult(2,0)], Input(3))
created: object(8,0), object(8,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3328800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 9, line 418:
//# create-checkpoint
Checkpoint created: 3

task 10, lines 420-608:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "12o1SohLNmesXKTkAyswjc3oRNWiRtAxwbM57zyMju4o",
          "sender": {
            "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
          },
          "signatures": [
            "AIgrzXMg1+xTqYiNXmcYXSf5vXjFdZPTOE+0HB1wUZn6jpskE1yf66iu2cseTyppv5o8WE3VSiQXBCEH8HLsWgF/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x6e4f51e9a082897fb23e23a699deed7fed0f08579c9ed0bd483ed086f87a1e29"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "KgAAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "KwAAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "6AMAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "jMpOHOC6WQTOph35JC2i99KePvMo+37AfAhrO/R8pho="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjozfQ",
                  "node": {
                    "__typename": "MakeMoveVecTransaction",
                    "type": {
                      "repr": "u64"
                    },
                    "elements": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Input",
                        "ix": 1
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjozfQ",
                  "node": {
                    "__typename": "MakeMoveVecTransaction",
                    "type": {
                      "repr": "u64"
                    },
                    "elements": []
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjozfQ",
                  "node": {
                    "__typename": "SplitCoinsTransaction",
                    "coin": {
                      "__typename": "GasCoin"
                    },
                    "amounts": [
                      {
                        "__typename": "Input",
                        "ix": 2
                      },
                      {
                        "__typename": "Input",
                        "ix": 2
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x77c4e897e28607c7608cda4288bd4dc973ff969797baff733fd416f41c2e08ec",
                    "module": "m",
                    "functionName": "new",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 0,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "vector<u64>"
                        },
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x3d33853fc90b1fe007987920ff48ffc0f5860a46392981422c186bbc07b93e12::m::Foo"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo0LCJjIjozfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 3,
                        "ix": null
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 3
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo1LCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x77c4e897e28607c7608cda4288bd4dc973ff969797baff733fd416f41c2e08ec",
                    "module": "m",
                    "functionName": "new",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 1,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "vector<u64>"
                        },
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x3d33853fc90b1fe007987920ff48ffc0f5860a46392981422c186bbc07b93e12::m::Foo"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo2LCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x77c4e897e28607c7608cda4288bd4dc973ff969797baff733fd416f41c2e08ec",
                    "module": "m",
                    "functionName": "burn",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 5,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "0x3d33853fc90b1fe007987920ff48ffc0f5860a46392981422c186bbc07b93e12::m::Foo"
                        }
                      ],
                      "return": []
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo3LCJjIjozfQ",
                  "node": {
                    "__typename": "MergeCoinsTransaction",
                    "coin": {
                      "__typename": "Result",
                      "cmd": 2,
                      "ix": 0
                    },
                    "coins": [
                      {
                        "__typename": "Result",
                        "cmd": 2,
                        "ix": 1
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjo4LCJjIjozfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 2,
                        "ix": 0
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 3
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 5,
            "dependencies": {
              "nodes": [
                {
                  "digest": "DxXm2H8hyxbdNEDPPVt9QmihGmURQE7E4ehJa28RUe3G"
                },
                {
                  "digest": "EcWN1mWuprv7AecrzEsoPzogdw5JiX7HL4zRiZaeLfv4"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
                  },
                  "amount": "-3340800",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x27f342242a7008f97c9697ccf81de94a28f61cabc1eb9baf9ff7705392c3f052",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x27f342242a7008f97c9697ccf81de94a28f61cabc1eb9baf9ff7705392c3f052",
                    "digest": "6v5rNqmUixUg2mCubmBgricHzFENFhd1s8zUmcdznfc",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x3d33853fc90b1fe007987920ff48ffc0f5860a46392981422c186bbc07b93e12::m::Foo"
                        },
                        "json": {
                          "id": "0x27f342242a7008f97c9697ccf81de94a28f61cabc1eb9baf9ff7705392c3f052",
                          "xs": [
                            "42",
                            "43"
                          ]
                        }
                      }
                    }
                  }
                },
                {
                  "address": "0x6e4f51e9a082897fb23e23a699deed7fed0f08579c9ed0bd483ed086f87a1e29",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x6e4f51e9a082897fb23e23a699deed7fed0f08579c9ed0bd483ed086f87a1e29",
                    "digest": "7HTAszG9EiDFFnbQwaqmbEfg4fbZ5iKEue1hnnxqcVZo",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x6e4f51e9a082897fb23e23a699deed7fed0f08579c9ed0bd483ed086f87a1e29",
                          "balance": {
                            "value": "299999982082400"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "address": "0xab4b1d7f165aa39f8df4168708f46be2f46a8d8ff693943d9163f3d1c7221a99",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xab4b1d7f165aa39f8df4168708f46be2f46a8d8ff693943d9163f3d1c7221a99",
                    "digest": "4jGHjp1krmxyfe3U5J1fsRKExNACABuALSiTsQ8QuMNi",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0xab4b1d7f165aa39f8df4168708f46be2f46a8d8ff693943d9163f3d1c7221a99",
                          "balance": {
                            "value": "2000"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x6e4f51e9a082897fb23e23a699deed7fed0f08579c9ed0bd483ed086f87a1e29"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "3328800",
                "storageRebate": "988000",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 3
            },
            "transactionBlock": {
              "digest": "12o1SohLNmesXKTkAyswjc3oRNWiRtAxwbM57zyMju4o"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 11, lines 610-611:
//# programmable --sender A --inputs 1000
//> SplitCoins(Gas, [Input(0)])
Error: Transaction Effects Status: Unused result without the drop ability. Command result 0, return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: UnusedValueWithoutDrop { result_idx: 0, secondary_idx: 0 }, source: None, command: None } }

task 12, line 613:
//# create-checkpoint
Checkpoint created: 4

task 13, lines 615-794:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "Go6crQdwiUPoE16vDM4Pt8DPByaTFQUDrB63L76MwZPs",
          "sender": {
            "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
          },
          "signatures": [
            "APx0NoPztpHyNJ165goCeQ//uldYc+bqmwE6sxt6o2w0OOgKmOip8ZFu7sqcr1GaRmr/38DbCZyC5o4cfgJRTQV/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x6e4f51e9a082897fb23e23a699deed7fed0f08579c9ed0bd483ed086f87a1e29"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjo0fQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "6AMAAAAAAAA="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjo0fQ",
                  "node": {
                    "__typename": "SplitCoinsTransaction",
                    "coin": {
                      "__typename": "GasCoin"
                    },
                    "amounts": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      }
                    ]
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "FAILURE",
            "errors": "Unused result without the drop ability. Command result 0, return value 0",
            "lamportVersion": 6,
            "dependencies": {
              "nodes": [
                {
                  "digest": "12o1SohLNmesXKTkAyswjc3oRNWiRtAxwbM57zyMju4o"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
                  },
                  "amount": "-1000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x6e4f51e9a082897fb23e23a699deed7fed0f08579c9ed0bd483ed086f87a1e29",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x6e4f51e9a082897fb23e23a699deed7fed0f08579c9ed0bd483ed086f87a1e29",
                    "digest": "139qhCEA7ufah3QsM8GPwU2iXmhYAPzygtiBCTYeG8vE"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x6e4f51e9a082897fb23e23a699deed7fed0f08579c9ed0bd483ed086f87a1e29"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "988000",
                "storageRebate": "988000",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 4
            },
            "transactionBlock": {
              "digest": "Go6crQdwiUPoE16vDM4Pt8DPByaTFQUDrB63L76MwZPs"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 14, lines 796-806:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjowLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "GenesisTransaction"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoxLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo1LCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        }
      ]
    }
  }
}

task 15, lines 808-818:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjowLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "GenesisTransaction"
            }
          }
        }
      ]
    }
  }
}

task 16, lines 820-830:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoxLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo1LCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        }
      ]
    }
  }
}

task 17, lines 832-839:
//# run-graphql
Response: {
  "data": {
    "address": {
      "transactionBlocks": {
        "nodes": []
      }
    }
  }
}

task 18, lines 841-846:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0"
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0"
        }
      ]
    }
  }
}

task 19, lines 848-853:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0"
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJpIjpmYWxzZX0"
        }
      ]
    }
  }
}

task 20, lines 855-865:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0"
        }
      ]
    }
  }
}
