processed 21 tasks

init:
A: object(0,0)

task 1, lines 7-17:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 6300400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 19:
//# create-checkpoint
Checkpoint created: 1

task 3, lines 21-200:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "DStVeow9xBNhy4nZWSiMP4WZGsNaNFZQhWUzPHGnynyo",
          "sender": {
            "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
          },
          "signatures": [
            "ACWH/ZLI0uFUs4vyM4EJzhNIis0YFhMKDXsnOs0nUaywj7aPjj0udDW6A6IbAaJDeDsr9qrR6ZtcLNT5amXATgJ/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x18a5cb688685554c4b370c3f551466dba6fb25390920fa5836812a9fb66500c4"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "jMpOHOC6WQTOph35JC2i99KePvMo+37AfAhrO/R8pho="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "__typename": "PublishTransaction",
                    "modules": [
                      "oRzrCwYAAAAIAQAGAgYMAxIKBRwRBy0wCF1ACp0BCQymAQ8ABAEGAQcAAAwAAQIEAAIBAgAABQABAAEFAwQAAgoDBwgCAQgAAAEHCAIBCAEDRm9vCVR4Q29udGV4dANVSUQCaWQBbQNuZXcGb2JqZWN0CnR4X2NvbnRleHQCeHMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAICAwgBCAoDAAEAAAIFCwERAQsAEgACAA=="
                    ],
                    "dependencies": [
                      "0x0000000000000000000000000000000000000000000000000000000000000001",
                      "0x0000000000000000000000000000000000000000000000000000000000000002"
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoxfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 0,
                        "ix": null
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 0
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "HMpUemPGq81ZKbabWFBBberZ97ZQzZyd2ufocFpgaKxF"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
                  },
                  "amount": "-7300400",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x18a5cb688685554c4b370c3f551466dba6fb25390920fa5836812a9fb66500c4",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x18a5cb688685554c4b370c3f551466dba6fb25390920fa5836812a9fb66500c4",
                    "digest": "9et93fzXWULZboG1jbmPUY4Pjy5fdzYkXbZ2Tk3fff3Q"
                  }
                },
                {
                  "address": "0xa76aca10126d5d229060b1363c338e695a191c318bbbf54007151d6918134d65",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xa76aca10126d5d229060b1363c338e695a191c318bbbf54007151d6918134d65",
                    "digest": "2dSPbPpCYNgxAwhN35rNfZveTSjKRJiS7ndDWm3AsuRd"
                  }
                },
                {
                  "address": "0xfa4b58cc517cbb110c3ff16e66b45e273d0d9c63ef70c5e7981a74b505136c1c",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xfa4b58cc517cbb110c3ff16e66b45e273d0d9c63ef70c5e7981a74b505136c1c",
                    "digest": "6SGX3tGkm1Mwo6XTCqAEyubcGgkfqvmqXYMq8XTxT5vu"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x18a5cb688685554c4b370c3f551466dba6fb25390920fa5836812a9fb66500c4"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6300400",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "DStVeow9xBNhy4nZWSiMP4WZGsNaNFZQhWUzPHGnynyo"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 4, lines 202-217:
//# upgrade --package P0 --upgrade-capability 1,0 --sender A
created: object(4,0)
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 6574000,  storage_rebate: 2606800, non_refundable_storage_fee: 0

task 5, line 219:
//# create-checkpoint
Checkpoint created: 2

task 6, lines 221-400:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "AgriF36Cqis1HgoJTfpiCufw2R3cadyZaXqJiqWDhLzL",
          "sender": {
            "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
          },
          "signatures": [
            "AAYhpMoy694z8sKoB9lcxyPQqdxC9/T2Qe5F93FMA5HmjXHjn3drH+xngIIMqxWsqulu9VXnV300w+C7L7+IjA5/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x18a5cb688685554c4b370c3f551466dba6fb25390920fa5836812a9fb66500c4"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "OwnedOrImmutable",
                    "address": "0xfa4b58cc517cbb110c3ff16e66b45e273d0d9c63ef70c5e7981a74b505136c1c",
                    "version": 2,
                    "digest": "6SGX3tGkm1Mwo6XTCqAEyubcGgkfqvmqXYMq8XTxT5vu",
                    "object": {
                      "address": "0xfa4b58cc517cbb110c3ff16e66b45e273d0d9c63ef70c5e7981a74b505136c1c",
                      "version": 2,
                      "digest": "6SGX3tGkm1Mwo6XTCqAEyubcGgkfqvmqXYMq8XTxT5vu",
                      "asMoveObject": {
                        "contents": {
                          "type": {
                            "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                          },
                          "json": {
                            "id": "0xfa4b58cc517cbb110c3ff16e66b45e273d0d9c63ef70c5e7981a74b505136c1c",
                            "package": "0xa76aca10126d5d229060b1363c338e695a191c318bbbf54007151d6918134d65",
                            "version": "1",
                            "policy": 0
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoyfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "AA=="
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjoyfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "IKtSxFg0BLyRn8vrtIRqeqpsihVPvPFxPFBg5s0K+UqS"
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "module": "package",
                    "functionName": "authorize_upgrade",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Input",
                        "ix": 1
                      },
                      {
                        "__typename": "Input",
                        "ix": 2
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                        },
                        {
                          "repr": "u8"
                        },
                        {
                          "repr": "vector<u8>"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeTicket"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoyfQ",
                  "node": {
                    "__typename": "UpgradeTransaction",
                    "modules": [
                      "oRzrCwYAAAAIAQAGAgYMAxIUBSYRBzc8CHNACrMBCQy8AR0ABgEIAQkAAAwAAQIEAAIBAgAABwABAAADAQIAAQQEAgABBwMEAAIKAwcIAgEIAAABBwgCAQgBA0ZvbwlUeENvbnRleHQDVUlEBGJ1cm4GZGVsZXRlAmlkAW0DbmV3Bm9iamVjdAp0eF9jb250ZXh0AnhzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgACAgUIAQoKAwABAAACBQsBEQMLABIAAgEBAAACBQsAEwABEQICAA=="
                    ],
                    "dependencies": [
                      "0x0000000000000000000000000000000000000000000000000000000000000001",
                      "0x0000000000000000000000000000000000000000000000000000000000000002"
                    ],
                    "currentPackage": "0xa76aca10126d5d229060b1363c338e695a191c318bbbf54007151d6918134d65",
                    "upgradeTicket": {
                      "__typename": "Result",
                      "cmd": 0,
                      "ix": null
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjoyfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "module": "package",
                    "functionName": "commit_upgrade",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Result",
                        "cmd": 1,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                        },
                        {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeReceipt"
                        }
                      ],
                      "return": []
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 3,
            "dependencies": {
              "nodes": [
                {
                  "digest": "DStVeow9xBNhy4nZWSiMP4WZGsNaNFZQhWUzPHGnynyo"
                },
                {
                  "digest": "HMpUemPGq81ZKbabWFBBberZ97ZQzZyd2ufocFpgaKxF"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
                  },
                  "amount": "-4967200",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x18a5cb688685554c4b370c3f551466dba6fb25390920fa5836812a9fb66500c4",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x18a5cb688685554c4b370c3f551466dba6fb25390920fa5836812a9fb66500c4",
                    "digest": "8c2bwMXrgv7wXFLN16zvdAdzsUffBb5UmP1cyfzswLu6"
                  }
                },
                {
                  "address": "0x92307478b83faee47dae9846622016f8c5d86bec5d72333b5d75c739b986c025",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x92307478b83faee47dae9846622016f8c5d86bec5d72333b5d75c739b986c025",
                    "digest": "RnXt4c1zEop2mo3eGaCVVYqJmNBvXLSsa5cozxAnnWY"
                  }
                },
                {
                  "address": "0xfa4b58cc517cbb110c3ff16e66b45e273d0d9c63ef70c5e7981a74b505136c1c",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xfa4b58cc517cbb110c3ff16e66b45e273d0d9c63ef70c5e7981a74b505136c1c",
                    "digest": "D6bV2KX6nqdty574rDYjKoigVfDB7UUPGqd4mCLV4WXD"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x18a5cb688685554c4b370c3f551466dba6fb25390920fa5836812a9fb66500c4"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6574000",
                "storageRebate": "2606800",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "AgriF36Cqis1HgoJTfpiCufw2R3cadyZaXqJiqWDhLzL"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 7, lines 402-405:
//# programmable --sender A --inputs 41u64 @A
//> 0: MakeMoveVec<u64>([Input(0)]);
//> 1: P0::m::new(Result(0));
//> iota::transfer::public_transfer<P0::m::Foo>(Result(1), Input(1))
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2264800,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 8, lines 407-416:
//# programmable --sender A --inputs 42u64 43u64 1000 @A
//> 0: MakeMoveVec<u64>([Input(0), Input(1)]);
//> 1: MakeMoveVec<u64>([]);
//> 2: SplitCoins(Gas, [Input(2), Input(2)]);
//> 3: P0::m::new(Result(0));
//> 4: TransferObjects([Result(3)], Input(3));
//> 5: P0::m::new(Result(1));
//> 6: P0::m::burn(Result(5));
//> 7: MergeCoins(NestedResult(2,0), [NestedResult(2,1)]);
//> TransferObjects([NestedResult(2,0)], Input(3))
created: object(8,0), object(8,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3306000,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 9, line 418:
//# create-checkpoint
Checkpoint created: 3

task 10, lines 420-608:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "72hb62Xx8UCvvfvsDpQntCUnr9EGFPHUVohx8YpN5iGS",
          "sender": {
            "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
          },
          "signatures": [
            "AME48u1BDowW3Jv0BjdpKnIe1a7m2cGL5B4Ig7E25EQ0FoH+8jF4k6qzPHTn9+Et1gbTLBJ9MAE2JWPmbhHaEAV/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x18a5cb688685554c4b370c3f551466dba6fb25390920fa5836812a9fb66500c4"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "KgAAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "KwAAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "6AMAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "jMpOHOC6WQTOph35JC2i99KePvMo+37AfAhrO/R8pho="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjozfQ",
                  "node": {
                    "__typename": "MakeMoveVecTransaction",
                    "type": {
                      "repr": "u64"
                    },
                    "elements": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Input",
                        "ix": 1
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjozfQ",
                  "node": {
                    "__typename": "MakeMoveVecTransaction",
                    "type": {
                      "repr": "u64"
                    },
                    "elements": []
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjozfQ",
                  "node": {
                    "__typename": "SplitCoinsTransaction",
                    "coin": {
                      "__typename": "GasCoin"
                    },
                    "amounts": [
                      {
                        "__typename": "Input",
                        "ix": 2
                      },
                      {
                        "__typename": "Input",
                        "ix": 2
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x92307478b83faee47dae9846622016f8c5d86bec5d72333b5d75c739b986c025",
                    "module": "m",
                    "functionName": "new",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 0,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "vector<u64>"
                        },
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0xa76aca10126d5d229060b1363c338e695a191c318bbbf54007151d6918134d65::m::Foo"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo0LCJjIjozfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 3,
                        "ix": null
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 3
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo1LCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x92307478b83faee47dae9846622016f8c5d86bec5d72333b5d75c739b986c025",
                    "module": "m",
                    "functionName": "new",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 1,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "vector<u64>"
                        },
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0xa76aca10126d5d229060b1363c338e695a191c318bbbf54007151d6918134d65::m::Foo"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo2LCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x92307478b83faee47dae9846622016f8c5d86bec5d72333b5d75c739b986c025",
                    "module": "m",
                    "functionName": "burn",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 5,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "0xa76aca10126d5d229060b1363c338e695a191c318bbbf54007151d6918134d65::m::Foo"
                        }
                      ],
                      "return": []
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo3LCJjIjozfQ",
                  "node": {
                    "__typename": "MergeCoinsTransaction",
                    "coin": {
                      "__typename": "Result",
                      "cmd": 2,
                      "ix": 0
                    },
                    "coins": [
                      {
                        "__typename": "Result",
                        "cmd": 2,
                        "ix": 1
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjo4LCJjIjozfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 2,
                        "ix": 0
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 3
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 5,
            "dependencies": {
              "nodes": [
                {
                  "digest": "8yToACVC5ZQqVbjeTvjwSMugbuw1gBbngHmVcJiy6Wfh"
                },
                {
                  "digest": "AgriF36Cqis1HgoJTfpiCufw2R3cadyZaXqJiqWDhLzL"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
                  },
                  "amount": "-3325600",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x04df2cc664f044d04926fdd64a874053746e122278680308150f60b567b20940",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x04df2cc664f044d04926fdd64a874053746e122278680308150f60b567b20940",
                    "digest": "2xZhu1r8zVrrjx6dTGmhyd3hUspYCmLURzNT9vGGM5nC",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x04df2cc664f044d04926fdd64a874053746e122278680308150f60b567b20940",
                          "balance": {
                            "value": "2000"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "address": "0x18a5cb688685554c4b370c3f551466dba6fb25390920fa5836812a9fb66500c4",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x18a5cb688685554c4b370c3f551466dba6fb25390920fa5836812a9fb66500c4",
                    "digest": "BvV2DJy7JAHKjTFgTFri7GrHN6GnEEjZovCBMpdGuMXC",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x18a5cb688685554c4b370c3f551466dba6fb25390920fa5836812a9fb66500c4",
                          "balance": {
                            "value": "299999982120400"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "address": "0x223be7efd160093e62a1b704b39bf7c0b99ef9a213eb12766693c18829eb8358",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x223be7efd160093e62a1b704b39bf7c0b99ef9a213eb12766693c18829eb8358",
                    "digest": "n1Vsn9aEWScvXM5LdPHt5i4x9dz27TND53bvgVvZP8g",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xa76aca10126d5d229060b1363c338e695a191c318bbbf54007151d6918134d65::m::Foo"
                        },
                        "json": {
                          "id": "0x223be7efd160093e62a1b704b39bf7c0b99ef9a213eb12766693c18829eb8358",
                          "xs": [
                            "42",
                            "43"
                          ]
                        }
                      }
                    }
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x18a5cb688685554c4b370c3f551466dba6fb25390920fa5836812a9fb66500c4"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "3306000",
                "storageRebate": "980400",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 3
            },
            "transactionBlock": {
              "digest": "72hb62Xx8UCvvfvsDpQntCUnr9EGFPHUVohx8YpN5iGS"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 11, lines 610-611:
//# programmable --sender A --inputs 1000
//> SplitCoins(Gas, [Input(0)])
Error: Transaction Effects Status: Unused result without the drop ability. Command result 0, return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: UnusedValueWithoutDrop { result_idx: 0, secondary_idx: 0 }, source: None, command: None } }

task 12, line 613:
//# create-checkpoint
Checkpoint created: 4

task 13, lines 615-794:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "Ffp1DhEFmSMobvN7x83LN18dsj4qH8Tv6f74vqntrA32",
          "sender": {
            "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
          },
          "signatures": [
            "ALH9L5nJjP7Cz9X1aqT2ZsV1Ry2wZ7+0bhQFcAm3OB8dLGtEu75zArMTz/28KfjFC5tzJ86m/vO2T+nXaaly3Qh/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x18a5cb688685554c4b370c3f551466dba6fb25390920fa5836812a9fb66500c4"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjo0fQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "6AMAAAAAAAA="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjo0fQ",
                  "node": {
                    "__typename": "SplitCoinsTransaction",
                    "coin": {
                      "__typename": "GasCoin"
                    },
                    "amounts": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      }
                    ]
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "FAILURE",
            "errors": "Unused result without the drop ability. Command result 0, return value 0",
            "lamportVersion": 6,
            "dependencies": {
              "nodes": [
                {
                  "digest": "72hb62Xx8UCvvfvsDpQntCUnr9EGFPHUVohx8YpN5iGS"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
                  },
                  "amount": "-1000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x18a5cb688685554c4b370c3f551466dba6fb25390920fa5836812a9fb66500c4",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x18a5cb688685554c4b370c3f551466dba6fb25390920fa5836812a9fb66500c4",
                    "digest": "5ysmth2HaqLv1xLbCMQUnhd8qVZtEvyhRZ4M8mPMF9qc"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x18a5cb688685554c4b370c3f551466dba6fb25390920fa5836812a9fb66500c4"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "980400",
                "storageRebate": "980400",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 4
            },
            "transactionBlock": {
              "digest": "Ffp1DhEFmSMobvN7x83LN18dsj4qH8Tv6f74vqntrA32"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 14, lines 796-806:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjowLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "GenesisTransaction"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoxLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo1LCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        }
      ]
    }
  }
}

task 15, lines 808-818:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjowLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "GenesisTransaction"
            }
          }
        }
      ]
    }
  }
}

task 16, lines 820-830:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoxLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo1LCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        }
      ]
    }
  }
}

task 17, lines 832-839:
//# run-graphql
Response: {
  "data": {
    "address": {
      "transactionBlocks": {
        "nodes": []
      }
    }
  }
}

task 18, lines 841-846:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0"
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0"
        }
      ]
    }
  }
}

task 19, lines 848-853:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0"
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJpIjpmYWxzZX0"
        }
      ]
    }
  }
}

task 20, lines 855-865:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0"
        }
      ]
    }
  }
}
