processed 7 tasks

task 1, line 7:
//# create-checkpoint
Checkpoint created: 1

task 2, line 9:
//# advance-epoch --create-random-state
Epoch advanced: 0

task 3, lines 11-47:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "protocolConfigs": {
        "protocolVersion": 1,
        "randomBeacon": {
          "value": true
        }
      }
    },
    "object": {
      "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
      "version": 2,
      "asMoveObject": {
        "contents": {
          "type": {
            "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::random::Random"
          },
          "json": {
            "id": "0x0000000000000000000000000000000000000000000000000000000000000008",
            "inner": {
              "id": "0xc49abd697d24213bff4f8af15914659874e4aeec04425b0797e4d175c4f838a7",
              "version": "1"
            }
          }
        }
      }
    },
    "transactionBlocks": {
      "nodes": [
        {
          "kind": {
            "__typename": "EndOfEpochTransaction",
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "RandomnessStateCreateTransaction"
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoyfQ",
                  "node": {
                    "__typename": "ChangeEpochTransaction"
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 5, line 53:
//# create-checkpoint
Checkpoint created: 3

task 6, lines 55-70:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "kind": {
            "__typename": "RandomnessStateUpdateTransaction",
            "epoch": {
              "epochId": 0
            },
            "randomnessRound": 0,
            "randomBytes": "SGVsbG8gU3Vp",
            "randomnessObjInitialSharedVersion": 2
          }
        }
      ]
    }
  }
}
