processed 7 tasks

task 1, lines 7-23:
//# publish
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 6847600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 25-26:
//# programmable --inputs immshared(1,0)
//> 0: P0::m::get(Input(0))
mutated: object(0,0)
unchanged_shared: object(1,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 980400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 3, lines 28-29:
//# programmable --inputs object(1,0)
//> 0: P0::m::inc(Input(0))
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2257200,  storage_rebate: 2257200, non_refundable_storage_fee: 0

task 4, lines 31-33:
//# programmable --inputs object(1,0)
//> 0: P0::m::get(Input(0));
//> P0::m::inc(Input(0))
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2257200,  storage_rebate: 2257200, non_refundable_storage_fee: 0

task 5, line 35:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 37-85:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0xda23edc8f3c411902de45523348680cbd78852c2d4ba0e639fcf4a65ba69b789",
                  "module": "m",
                  "functionName": "get"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": [
                {
                  "__typename": "SharedObjectRead",
                  "address": "0xd205ddf04fa3d256aab875ced8dd3d8c4655281555ce5159724709f67e011283",
                  "version": 2,
                  "digest": "4iZxLS8NS4np1Dz6Qwnfpg188QiE2qRYQwfWks1ZFNbE",
                  "object": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xda23edc8f3c411902de45523348680cbd78852c2d4ba0e639fcf4a65ba69b789::m::Foo"
                        },
                        "json": {
                          "id": "0xd205ddf04fa3d256aab875ced8dd3d8c4655281555ce5159724709f67e011283",
                          "x": "0"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0xda23edc8f3c411902de45523348680cbd78852c2d4ba0e639fcf4a65ba69b789",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": []
            }
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0xda23edc8f3c411902de45523348680cbd78852c2d4ba0e639fcf4a65ba69b789",
                  "module": "m",
                  "functionName": "get"
                },
                {
                  "package": "0xda23edc8f3c411902de45523348680cbd78852c2d4ba0e639fcf4a65ba69b789",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": []
            }
          }
        }
      ]
    }
  }
}
