processed 7 tasks

task 1, lines 7-23:
//# publish
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 6847600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 25-26:
//# programmable --inputs immshared(1,0)
//> 0: P0::m::get(Input(0))
mutated: object(0,0)
unchanged_shared: object(1,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 980400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 3, lines 28-29:
//# programmable --inputs object(1,0)
//> 0: P0::m::inc(Input(0))
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2257200,  storage_rebate: 2257200, non_refundable_storage_fee: 0

task 4, lines 31-33:
//# programmable --inputs object(1,0)
//> 0: P0::m::get(Input(0));
//> P0::m::inc(Input(0))
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2257200,  storage_rebate: 2257200, non_refundable_storage_fee: 0

task 5, line 35:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 37-85:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0x8dd0c56b9c27ce853f4ca3ecc4a39d46c1e25b732f0624e4af73d36d20710049",
                  "module": "m",
                  "functionName": "get"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": [
                {
                  "__typename": "SharedObjectRead",
                  "address": "0x04ffb98f823667ce5d04dd68b2f9f670ce232160f2fc88451968dd83b7986d59",
                  "version": 2,
                  "digest": "HiS1Et2aru3emf35aRPcHe8BCuseebf3SFc8sJRZht2S",
                  "object": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x8dd0c56b9c27ce853f4ca3ecc4a39d46c1e25b732f0624e4af73d36d20710049::m::Foo"
                        },
                        "json": {
                          "id": "0x04ffb98f823667ce5d04dd68b2f9f670ce232160f2fc88451968dd83b7986d59",
                          "x": "0"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0x8dd0c56b9c27ce853f4ca3ecc4a39d46c1e25b732f0624e4af73d36d20710049",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": []
            }
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0x8dd0c56b9c27ce853f4ca3ecc4a39d46c1e25b732f0624e4af73d36d20710049",
                  "module": "m",
                  "functionName": "get"
                },
                {
                  "package": "0x8dd0c56b9c27ce853f4ca3ecc4a39d46c1e25b732f0624e4af73d36d20710049",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": []
            }
          }
        }
      ]
    }
  }
}
