processed 8 tasks

task 1, lines 9-103:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "DM8s3w94vDvcB9H2nJYXm5kggS9TUfDUXyMERw5up2ii",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "GenesisTransaction",
            "objects": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzcyIsImMiOjB9",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYXNjaWkiLCJjIjowfQ",
                            "node": {
                              "name": "ascii"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNzIiwiYyI6MH0",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYml0X3ZlY3RvciIsImMiOjB9",
                            "node": {
                              "name": "bit_vector"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGVidWciLCJjIjowfQ",
                            "node": {
                              "name": "debug"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZml4ZWRfcG9pbnQzMiIsImMiOjB9",
                            "node": {
                              "name": "fixed_point32"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaGFzaCIsImMiOjB9",
                            "node": {
                              "name": "hash"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWFjcm9zIiwiYyI6MH0",
                            "node": {
                              "name": "macros"
                            }
                          },
                          {
                            "cursor": "eyJuIjoib3B0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "option"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RyaW5nIiwiYyI6MH0",
                            "node": {
                              "name": "string"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidHlwZV9uYW1lIiwiYyI6MH0",
                            "node": {
                              "name": "type_name"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTEyOCIsImMiOjB9",
                            "node": {
                              "name": "u128"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTE2IiwiYyI6MH0",
                            "node": {
                              "name": "u16"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTI1NiIsImMiOjB9",
                            "node": {
                              "name": "u256"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTMyIiwiYyI6MH0",
                            "node": {
                              "name": "u32"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTY0IiwiYyI6MH0",
                            "node": {
                              "name": "u64"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTgiLCJjIjowfQ",
                            "node": {
                              "name": "u8"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmVjdG9yIiwiYyI6MH0",
                            "node": {
                              "name": "vector"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzcyIsImMiOjB9",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYXV0aGVudGljYXRvcl9zdGF0ZSIsImMiOjB9",
                            "node": {
                              "name": "authenticator_state"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFnIiwiYyI6MH0",
                            "node": {
                              "name": "bag"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFsYW5jZSIsImMiOjB9",
                            "node": {
                              "name": "balance"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNzIiwiYyI6MH0",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmxzMTIzODEiLCJjIjowfQ",
                            "node": {
                              "name": "bls12381"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYm9ycm93IiwiYyI6MH0",
                            "node": {
                              "name": "borrow"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2xvY2siLCJjIjowfQ",
                            "node": {
                              "name": "clock"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29pbiIsImMiOjB9",
                            "node": {
                              "name": "coin"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29pbl9tYW5hZ2VyIiwiYyI6MH0",
                            "node": {
                              "name": "coin_manager"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29uZmlnIiwiYyI6MH0",
                            "node": {
                              "name": "config"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGVueV9saXN0IiwiYyI6MH0",
                            "node": {
                              "name": "deny_list"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGlzcGxheSIsImMiOjB9",
                            "node": {
                              "name": "display"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZHluYW1pY19maWVsZCIsImMiOjB9",
                            "node": {
                              "name": "dynamic_field"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZHluYW1pY19vYmplY3RfZmllbGQiLCJjIjowfQ",
                            "node": {
                              "name": "dynamic_object_field"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWNkc2FfazEiLCJjIjowfQ",
                            "node": {
                              "name": "ecdsa_k1"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWNkc2FfcjEiLCJjIjowfQ",
                            "node": {
                              "name": "ecdsa_r1"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWN2cmYiLCJjIjowfQ",
                            "node": {
                              "name": "ecvrf"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWQyNTUxOSIsImMiOjB9",
                            "node": {
                              "name": "ed25519"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZXZlbnQiLCJjIjowfQ",
                            "node": {
                              "name": "event"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiZ2VuZXNpcyIsImMiOjB9",
                            "node": {
                              "name": "genesis"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaW90YV9zeXN0ZW0iLCJjIjowfQ",
                            "node": {
                              "name": "iota_system"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaW90YV9zeXN0ZW1fc3RhdGVfaW5uZXIiLCJjIjowfQ",
                            "node": {
                              "name": "iota_system_state_inner"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3Rha2luZ19wb29sIiwiYyI6MH0",
                            "node": {
                              "name": "staking_pool"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RvcmFnZV9mdW5kIiwiYyI6MH0",
                            "node": {
                              "name": "storage_fund"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidGltZWxvY2tlZF9zdGFraW5nIiwiYyI6MH0",
                            "node": {
                              "name": "timelocked_staking"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yIiwiYyI6MH0",
                            "node": {
                              "name": "validator"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX2NhcCIsImMiOjB9",
                            "node": {
                              "name": "validator_cap"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX3NldCIsImMiOjB9",
                            "node": {
                              "name": "validator_set"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX3dyYXBwZXIiLCJjIjowfQ",
                            "node": {
                              "name": "validator_wrapper"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidm90aW5nX3Bvd2VyIiwiYyI6MH0",
                            "node": {
                              "name": "voting_power"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::iota_system::IotaSystemState"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000005",
                          "version": "1"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo0LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::clock::Clock"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000006",
                          "timestamp_ms": "0"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo1LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::random::Random"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000008",
                          "inner": {
                            "id": "0x70a869c04b1d6bdcfd8c37981621f7788492e47b287a43f7196d17cf1ef5c3f7",
                            "version": "1"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo2LCJjIjowfQ",
                  "node": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYnJpZGdlIiwiYyI6MH0",
                            "node": {
                              "name": "bridge"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2hhaW5faWRzIiwiYyI6MH0",
                            "node": {
                              "name": "chain_ids"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29tbWl0dGVlIiwiYyI6MH0",
                            "node": {
                              "name": "committee"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3J5cHRvIiwiYyI6MH0",
                            "node": {
                              "name": "crypto"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibGltaXRlciIsImMiOjB9",
                            "node": {
                              "name": "limiter"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWVzc2FnZSIsImMiOjB9",
                            "node": {
                              "name": "message"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWVzc2FnZV90eXBlcyIsImMiOjB9",
                            "node": {
                              "name": "message_types"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidHJlYXN1cnkiLCJjIjowfQ",
                            "node": {
                              "name": "treasury"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo3LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::deny_list::DenyList"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000403",
                          "lists": {
                            "id": "0x69c34f6a614f0498500ffd4ef8082972e583f727372176809c47e9ca6998112c",
                            "size": "0"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo4LCJjIjowfQ",
                  "node": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000107a",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzc191bmxvY2tfY29uZGl0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "address_unlock_condition"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYWxpYXMiLCJjIjowfQ",
                            "node": {
                              "name": "alias"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYWxpYXNfb3V0cHV0IiwiYyI6MH0",
                            "node": {
                              "name": "alias_output"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFzaWNfb3V0cHV0IiwiYyI6MH0",
                            "node": {
                              "name": "basic_output"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZXhwaXJhdGlvbl91bmxvY2tfY29uZGl0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "expiration_unlock_condition"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaXJjMjciLCJjIjowfQ",
                            "node": {
                              "name": "irc27"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibmZ0IiwiYyI6MH0",
                            "node": {
                              "name": "nft"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibmZ0X291dHB1dCIsImMiOjB9",
                            "node": {
                              "name": "nft_output"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RhcmR1c3RfdXBncmFkZV9sYWJlbCIsImMiOjB9",
                            "node": {
                              "name": "stardust_upgrade_label"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RvcmFnZV9kZXBvc2l0X3JldHVybl91bmxvY2tfY29uZGl0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "storage_deposit_return_unlock_condition"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidGltZWxvY2tfdW5sb2NrX2NvbmRpdGlvbiIsImMiOjB9",
                            "node": {
                              "name": "timelock_unlock_condition"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidXRpbGl0aWVzIiwiYyI6MH0",
                            "node": {
                              "name": "utilities"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo5LCJjIjowfQ",
                  "node": {
                    "address": "0x1b76eddabed888c32f0c34e18cf456261a73cdce0ca31fbd3ae4993de951e583",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<0x0000000000000000000000000000000000000000000000000000000000000002::object::ID,address>"
                        },
                        "json": {
                          "id": "0x1b76eddabed888c32f0c34e18cf456261a73cdce0ca31fbd3ae4993de951e583",
                          "name": "0x58ea53883616547594ad2fd555be66a6ca7978ec1cff4b90afe01402fa7b59a8",
                          "value": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMCwiYyI6MH0",
                  "node": {
                    "address": "0x3b4c3fd6d41fd8781719db66dc06c7269b12e8ff81d28a4b0ac477f972ac98d7",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::display::Display<0x000000000000000000000000000000000000000000000000000000000000107a::nft::Nft>"
                        },
                        "json": {
                          "id": "0x3b4c3fd6d41fd8781719db66dc06c7269b12e8ff81d28a4b0ac477f972ac98d7",
                          "fields": {
                            "contents": [
                              {
                                "key": "name",
                                "value": "{immutable_metadata.name}"
                              },
                              {
                                "key": "image_url",
                                "value": "{immutable_metadata.uri}"
                              },
                              {
                                "key": "description",
                                "value": "{immutable_metadata.description}"
                              },
                              {
                                "key": "creator",
                                "value": "{immutable_metadata.issuer_name}"
                              },
                              {
                                "key": "version",
                                "value": "{immutable_metadata.version}"
                              },
                              {
                                "key": "media_type",
                                "value": "{immutable_metadata.media_type}"
                              },
                              {
                                "key": "collection_name",
                                "value": "{immutable_metadata.collection_name}"
                              },
                              {
                                "key": "immutable_issuer",
                                "value": "{immutable_issuer}"
                              }
                            ]
                          },
                          "version": 1
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMSwiYyI6MH0",
                  "node": {
                    "address": "0x5d6c6bd30a14b60130e825dc9173c566a212328537a93c8a708b862c46fe6159",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000002::random::RandomInner>"
                        },
                        "json": {
                          "id": "0x5d6c6bd30a14b60130e825dc9173c566a212328537a93c8a708b862c46fe6159",
                          "name": "1",
                          "value": {
                            "version": "1",
                            "epoch": "0",
                            "randomness_round": "0",
                            "random_bytes": []
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMiwiYyI6MH0",
                  "node": {
                    "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::iota_system_state_inner::IotaSystemStateV1>"
                        },
                        "json": {
                          "id": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                          "name": "1",
                          "value": {
                            "epoch": "0",
                            "protocol_version": "3",
                            "system_state_version": "1",
                            "iota_treasury_cap": {
                              "inner": {
                                "id": "0xaa575580b9541e44baba2462a349cb51ee84ea9c7cf9130d012bfefa335a0174",
                                "total_supply": {
                                  "value": "31800000000000000"
                                }
                              }
                            },
                            "validators": {
                              "total_stake": "1500000000000000",
                              "active_validators": [
                                {
                                  "metadata": {
                                    "iota_address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80",
                                    "authority_pubkey_bytes": [
                                      168,
                                      10,
                                      113,
                                      148,
                                      146,
                                      18,
                                      4,
                                      206,
                                      160,
                                      17,
                                      65,
                                      3,
                                      192,
                                      72,
                                      69,
                                      3,
                                      34,
                                      62,
                                      177,
                                      119,
                                      149,
                                      119,
                                      28,
                                      226,
                                      120,
                                      84,
                                      208,
                                      34,
                                      33,
                                      221,
                                      215,
                                      26,
                                      19,
                                      43,
                                      135,
                                      198,
                                      111,
                                      189,
                                      25,
                                      213,
                                      111,
                                      170,
                                      66,
                                      24,
                                      110,
                                      12,
                                      78,
                                      20,
                                      10,
                                      27,
                                      128,
                                      57,
                                      246,
                                      144,
                                      114,
                                      82,
                                      79,
                                      96,
                                      215,
                                      59,
                                      240,
                                      247,
                                      211,
                                      18,
                                      143,
                                      1,
                                      109,
                                      137,
                                      179,
                                      82,
                                      215,
                                      118,
                                      63,
                                      135,
                                      18,
                                      31,
                                      123,
                                      40,
                                      235,
                                      25,
                                      153,
                                      189,
                                      81,
                                      129,
                                      128,
                                      219,
                                      99,
                                      215,
                                      146,
                                      145,
                                      113,
                                      132,
                                      99,
                                      76,
                                      126,
                                      246
                                    ],
                                    "network_pubkey_bytes": [
                                      222,
                                      193,
                                      56,
                                      253,
                                      223,
                                      140,
                                      108,
                                      228,
                                      161,
                                      246,
                                      151,
                                      172,
                                      42,
                                      190,
                                      219,
                                      243,
                                      212,
                                      210,
                                      59,
                                      152,
                                      5,
                                      6,
                                      236,
                                      134,
                                      82,
                                      53,
                                      90,
                                      224,
                                      105,
                                      93,
                                      152,
                                      85
                                    ],
                                    "protocol_pubkey_bytes": [
                                      172,
                                      116,
                                      152,
                                      220,
                                      228,
                                      127,
                                      173,
                                      148,
                                      84,
                                      44,
                                      112,
                                      162,
                                      74,
                                      125,
                                      50,
                                      95,
                                      124,
                                      147,
                                      55,
                                      36,
                                      241,
                                      143,
                                      223,
                                      60,
                                      129,
                                      224,
                                      221,
                                      102,
                                      15,
                                      35,
                                      217,
                                      101
                                    ],
                                    "proof_of_possession": [
                                      146,
                                      189,
                                      89,
                                      74,
                                      29,
                                      175,
                                      203,
                                      128,
                                      64,
                                      181,
                                      156,
                                      97,
                                      250,
                                      67,
                                      71,
                                      1,
                                      183,
                                      54,
                                      131,
                                      205,
                                      9,
                                      153,
                                      183,
                                      92,
                                      197,
                                      160,
                                      192,
                                      111,
                                      216,
                                      8,
                                      35,
                                      211,
                                      26,
                                      222,
                                      255,
                                      142,
                                      137,
                                      6,
                                      130,
                                      140,
                                      153,
                                      155,
                                      252,
                                      79,
                                      139,
                                      240,
                                      222,
                                      153
                                    ],
                                    "name": "validator-0",
                                    "description": "",
                                    "image_url": {
                                      "url": ""
                                    },
                                    "project_url": {
                                      "url": ""
                                    },
                                    "net_address": "/ip4/127.0.0.1/tcp/8000/http",
                                    "p2p_address": "/ip4/127.0.0.1/udp/8001/http",
                                    "primary_address": "/ip4/127.0.0.1/udp/8003/http",
                                    "next_epoch_authority_pubkey_bytes": null,
                                    "next_epoch_proof_of_possession": null,
                                    "next_epoch_network_pubkey_bytes": null,
                                    "next_epoch_protocol_pubkey_bytes": null,
                                    "next_epoch_net_address": null,
                                    "next_epoch_p2p_address": null,
                                    "next_epoch_primary_address": null,
                                    "extra_fields": {
                                      "id": "0xd0192b72f78399e5866f56c7de77585a7e2548fefd4781428e18748f11f87761",
                                      "size": "0"
                                    }
                                  },
                                  "voting_power": "10000",
                                  "operation_cap_id": "0xd144ccfadfa9c328e7d47aad3d89e33053d0d37593c226c118767c2f14245398",
                                  "gas_price": "1000",
                                  "staking_pool": {
                                    "id": "0x58ea53883616547594ad2fd555be66a6ca7978ec1cff4b90afe01402fa7b59a8",
                                    "activation_epoch": "0",
                                    "deactivation_epoch": null,
                                    "iota_balance": "1500000000000000",
                                    "rewards_pool": {
                                      "value": "0"
                                    },
                                    "pool_token_balance": "1500000000000000",
                                    "exchange_rates": {
                                      "id": "0x92570afcd26cb5dac0d9282654203870594dd25d1d4c5e5f21fed081184129a6",
                                      "size": "1"
                                    },
                                    "pending_stake": "0",
                                    "pending_total_iota_withdraw": "0",
                                    "pending_pool_token_withdraw": "0",
                                    "extra_fields": {
                                      "id": "0x9f281c098a8aba454ede1aea3a641c61cf020283c8d8fb636c9ec2a9227daf74",
                                      "size": "0"
                                    }
                                  },
                                  "commission_rate": "200",
                                  "next_epoch_stake": "1500000000000000",
                                  "next_epoch_gas_price": "1000",
                                  "next_epoch_commission_rate": "200",
                                  "extra_fields": {
                                    "id": "0xdfc66ccb8340689003eb02186e844cea5d8177da3cc55c3664d697e818ead945",
                                    "size": "0"
                                  }
                                }
                              ],
                              "pending_active_validators": {
                                "contents": {
                                  "id": "0xc65b4a4f3989041172bdd0acb669a4bd05e86518f4147523ac705092941811bd",
                                  "size": "0"
                                }
                              },
                              "pending_removals": [],
                              "staking_pool_mappings": {
                                "id": "0x6af0a0e1c3ac8187a6d2343d91cdee3abb85143f289638eff8e8fce30d21d5fd",
                                "size": "1"
                              },
                              "inactive_validators": {
                                "id": "0xce59007c6d03fb9cae7f924ffcfe253b482f72726fb0abec764586d5d42cadfb",
                                "size": "0"
                              },
                              "validator_candidates": {
                                "id": "0xdc53bd0eab4f4aaa4e476daa09df703a9da1030b4bfdf1c7aee6e600dd5f65f3",
                                "size": "0"
                              },
                              "at_risk_validators": {
                                "contents": []
                              },
                              "extra_fields": {
                                "id": "0x643b34810511a72b6c64950390c18dba848a26807710f265cf7357cd5ce7c9a6",
                                "size": "0"
                              }
                            },
                            "storage_fund": {
                              "total_object_storage_rebates": {
                                "value": "0"
                              },
                              "non_refundable_balance": {
                                "value": "0"
                              }
                            },
                            "parameters": {
                              "epoch_duration_ms": "86400000",
                              "min_validator_count": "4",
                              "max_validator_count": "150",
                              "min_validator_joining_stake": "2000000000000000",
                              "validator_low_stake_threshold": "1500000000000000",
                              "validator_very_low_stake_threshold": "1000000000000000",
                              "validator_low_stake_grace_period": "7",
                              "extra_fields": {
                                "id": "0x810389c8037e0c61c2abf623d9dfa0c1e682c6b00d7c949d88e042bf125041cc",
                                "size": "0"
                              }
                            },
                            "iota_system_admin_cap": {
                              "dummy_field": false
                            },
                            "reference_gas_price": "1000",
                            "validator_report_records": {
                              "contents": []
                            },
                            "safe_mode": false,
                            "safe_mode_storage_charges": {
                              "value": "0"
                            },
                            "safe_mode_computation_rewards": {
                              "value": "0"
                            },
                            "safe_mode_storage_rebates": "0",
                            "safe_mode_non_refundable_storage_fee": "0",
                            "epoch_start_timestamp_ms": "0",
                            "extra_fields": {
                              "id": "0xb9dbecacf735eb1f6da7d56ff861393282816856a610d7d9f72ffe2aee4b79ea",
                              "size": "0"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMywiYyI6MH0",
                  "node": {
                    "address": "0x956a7277b7da881360721a4d9fc12cee12e509dbf2c10c0fcf7664fbbc67fcd8",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x956a7277b7da881360721a4d9fc12cee12e509dbf2c10c0fcf7664fbbc67fcd8",
                          "balance": {
                            "value": "30000000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNCwiYyI6MH0",
                  "node": {
                    "address": "0x9c1d6aa32c63a2dcb3bab3eacc66a926310b03a0e524bd5e3332cfc71fc13150",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x9c1d6aa32c63a2dcb3bab3eacc66a926310b03a0e524bd5e3332cfc71fc13150",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNSwiYyI6MH0",
                  "node": {
                    "address": "0xad0a037077ae89bff3bf8c2b9e1c06bfc6dd381bf8d11cdeebff6f936f2e0911",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::PoolTokenExchangeRate>"
                        },
                        "json": {
                          "id": "0xad0a037077ae89bff3bf8c2b9e1c06bfc6dd381bf8d11cdeebff6f936f2e0911",
                          "name": "0",
                          "value": {
                            "iota_amount": "0",
                            "pool_token_amount": "0"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNiwiYyI6MH0",
                  "node": {
                    "address": "0xd144ccfadfa9c328e7d47aad3d89e33053d0d37593c226c118767c2f14245398",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::validator_cap::UnverifiedValidatorOperationCap"
                        },
                        "json": {
                          "id": "0xd144ccfadfa9c328e7d47aad3d89e33053d0d37593c226c118767c2f14245398",
                          "authorizer_validator_address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNywiYyI6MH0",
                  "node": {
                    "address": "0xe8953fea75f6fcb0e3846ce5a62297b5c534f097edc88fee4dd26959a232b100",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::CoinMetadata<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0xe8953fea75f6fcb0e3846ce5a62297b5c534f097edc88fee4dd26959a232b100",
                          "decimals": 9,
                          "name": "IOTA",
                          "symbol": "IOTA",
                          "description": "The main (gas)token of the IOTA Network.",
                          "icon_url": {
                            "url": "https://iota.org/logo.png"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxOCwiYyI6MH0",
                  "node": {
                    "address": "0xfad19a2e4d65c8f07f42f1fbeee8c5d1eb00fb1ef394c3e75cc77f1a3c545c99",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::StakedIota"
                        },
                        "json": {
                          "id": "0xfad19a2e4d65c8f07f42f1fbeee8c5d1eb00fb1ef394c3e75cc77f1a3c545c99",
                          "pool_id": "0x58ea53883616547594ad2fd555be66a6ca7978ec1cff4b90afe01402fa7b59a8",
                          "stake_activation_epoch": "0",
                          "principal": {
                            "value": "1500000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 1,
            "dependencies": {
              "nodes": []
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
                  },
                  "amount": "30000000000000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  }
                },
                {
                  "owner": {
                    "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
                  },
                  "amount": "300000000000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "digest": "6FjzxvV1e6w47kRPBMrkuKscqJAHL7fVDAMPLhpv6PiW"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "digest": "84Gw4reeyTNa8NWRVhDbwjhAVzxidLdY2ApoqFwgvd1j"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "digest": "4tV1xTniredGZqwVTEJiHURgzMukFF5AXPQMaNfjXv5r"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "digest": "Fupk6BKk2udFazjUUD8ebB2en5gigSKwsmDMieXhw16K"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "AAF2gTEdEcLSidn8p3J4VdMQW9dfvyd5Es1VZR5ME4Fh"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                    "digest": "2kXp5MexhBkX2EBiLvgkFP4DwitTUAPnKNVDqggDND6A"
                  }
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                    "digest": "8gVHgq5M2kAssHMLUC1BxtHzAPbzXN1VtH8pgK39Vx7a"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                    "digest": "F8PCw5NbtxYVBBHEvKg2U9PdnqnomoWEmuAY5GDjhLkm"
                  }
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000107a",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000107a",
                    "digest": "FqKdrgn31Urw9oVqmdy4m88tSjUcVaqF2LzCX5mE5b8D"
                  }
                },
                {
                  "address": "0x1b76eddabed888c32f0c34e18cf456261a73cdce0ca31fbd3ae4993de951e583",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x1b76eddabed888c32f0c34e18cf456261a73cdce0ca31fbd3ae4993de951e583",
                    "digest": "4aMZXyTHWAYfPLEXQRsH4nGTncJukszdmZ8nvpCqSnfv"
                  }
                },
                {
                  "address": "0x3b4c3fd6d41fd8781719db66dc06c7269b12e8ff81d28a4b0ac477f972ac98d7",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x3b4c3fd6d41fd8781719db66dc06c7269b12e8ff81d28a4b0ac477f972ac98d7",
                    "digest": "3tNFuNhQr2j69UPMfdPnL4euTJJJYH8uorxxTYocNAru"
                  }
                },
                {
                  "address": "0x5d6c6bd30a14b60130e825dc9173c566a212328537a93c8a708b862c46fe6159",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x5d6c6bd30a14b60130e825dc9173c566a212328537a93c8a708b862c46fe6159",
                    "digest": "2naQYUXnBXg3LAi51F6Pz3S4jNJWokvafKtzoWTx8Lgw"
                  }
                },
                {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                    "digest": "Ga9TLZpqHmBwRcbH1k41kJLjzoo1nCgEVMsiSuyu5pKn"
                  }
                },
                {
                  "address": "0x956a7277b7da881360721a4d9fc12cee12e509dbf2c10c0fcf7664fbbc67fcd8",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x956a7277b7da881360721a4d9fc12cee12e509dbf2c10c0fcf7664fbbc67fcd8",
                    "digest": "5cypRnfFbMBSWbziVyXGbd7ywXLQdHKG9wggfqRkPZR5"
                  }
                },
                {
                  "address": "0x9c1d6aa32c63a2dcb3bab3eacc66a926310b03a0e524bd5e3332cfc71fc13150",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x9c1d6aa32c63a2dcb3bab3eacc66a926310b03a0e524bd5e3332cfc71fc13150",
                    "digest": "Cc6JJBQJwgtJZQEWhnUWHxCTLKnUV8QBUhyjQ8N6QQpT"
                  }
                },
                {
                  "address": "0xad0a037077ae89bff3bf8c2b9e1c06bfc6dd381bf8d11cdeebff6f936f2e0911",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xad0a037077ae89bff3bf8c2b9e1c06bfc6dd381bf8d11cdeebff6f936f2e0911",
                    "digest": "D985e9P89t3PxFhdYgxKMFxEkmAn2D3BSt3DQhoid19M"
                  }
                },
                {
                  "address": "0xd144ccfadfa9c328e7d47aad3d89e33053d0d37593c226c118767c2f14245398",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xd144ccfadfa9c328e7d47aad3d89e33053d0d37593c226c118767c2f14245398",
                    "digest": "HiB1n7gXxwY9KvmLNcsme6YTZA2F9APTZL7hcQ5QdNod"
                  }
                },
                {
                  "address": "0xe8953fea75f6fcb0e3846ce5a62297b5c534f097edc88fee4dd26959a232b100",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xe8953fea75f6fcb0e3846ce5a62297b5c534f097edc88fee4dd26959a232b100",
                    "digest": "7amDa28Hm32diBJJn1GvwREf3M1pACT41op2th4izV7v"
                  }
                },
                {
                  "address": "0xfad19a2e4d65c8f07f42f1fbeee8c5d1eb00fb1ef394c3e75cc77f1a3c545c99",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xfad19a2e4d65c8f07f42f1fbeee8c5d1eb00fb1ef394c3e75cc77f1a3c545c99",
                    "digest": "DBvYLNoLKb3c86CeMhYDzQLxwVRCsMsj1wFXhYUedZmK"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 0
            },
            "transactionBlock": {
              "digest": "DM8s3w94vDvcB9H2nJYXm5kggS9TUfDUXyMERw5up2ii"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 3, line 107:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 109-184:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "83hbgTuUUsGBjrUDigjrfebf2U8Ue1gBFGL87mzYe2fK",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 0
            },
            "round": 0,
            "commitTimestamp": "1970-01-01T00:00:42Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "DM8s3w94vDvcB9H2nJYXm5kggS9TUfDUXyMERw5up2ii"
                }
              ]
            },
            "balanceChanges": {
              "nodes": []
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "FQsvyRc9HAiReCY3aNX4CwyAZujqeWGhZDYddNsuL8NT"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:42Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "83hbgTuUUsGBjrUDigjrfebf2U8Ue1gBFGL87mzYe2fK"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 6, line 188:
//# advance-epoch
Epoch advanced: 0

task 7, lines 190-277:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "9ADUBQmAfCGqabFJTzw3VsybLPe28j7QTZ84xqbDRiVd",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "EndOfEpochTransaction",
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "ChangeEpochTransaction",
                    "epoch": null,
                    "protocolVersion": 3,
                    "storageCharge": "0",
                    "computationCharge": "0",
                    "storageRebate": "0",
                    "nonRefundableStorageFee": "0",
                    "startTimestamp": "1970-01-01T00:01:25Z"
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "DM8s3w94vDvcB9H2nJYXm5kggS9TUfDUXyMERw5up2ii"
                }
              ]
            },
            "balanceChanges": {
              "nodes": []
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "digest": "6XciTcJGe1ojLheRewNPp2BBdt5CCUSzbMyhowmrG9tN"
                  }
                },
                {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                    "digest": "GV5GCBKBTGCbLKFCDCcz7YtmSR59WmzV3YJNpwD1ykH5"
                  }
                },
                {
                  "address": "0x77ebd13ca27a089fcdfecdafe7a0e66e6e5e6778aa19d2f6f7bc94ec170ac35e",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x77ebd13ca27a089fcdfecdafe7a0e66e6e5e6778aa19d2f6f7bc94ec170ac35e",
                    "digest": "3D2bB5LAxX3Vzvpmbc9Kgd7exrK8qj64EJYpeKNbFCQX"
                  }
                },
                {
                  "address": "0x9dbebe911330dc625cbe53a5e622b1bd42ef09d76122ca2df36a84781322d204",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x9dbebe911330dc625cbe53a5e622b1bd42ef09d76122ca2df36a84781322d204",
                    "digest": "EoxJUkMfjHpikqDVgh88BxJJLNLEuWwyjnyXNfYHcd8B"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:01:25Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "9ADUBQmAfCGqabFJTzw3VsybLPe28j7QTZ84xqbDRiVd"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}
