processed 8 tasks

task 1, lines 9-103:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "HuAtfgjw2KZbZmqq1mc5UFVX3paqR1W6K4XZN4faNaNo",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "GenesisTransaction",
            "objects": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzcyIsImMiOjB9",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYXNjaWkiLCJjIjowfQ",
                            "node": {
                              "name": "ascii"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNzIiwiYyI6MH0",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYml0X3ZlY3RvciIsImMiOjB9",
                            "node": {
                              "name": "bit_vector"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGVidWciLCJjIjowfQ",
                            "node": {
                              "name": "debug"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZml4ZWRfcG9pbnQzMiIsImMiOjB9",
                            "node": {
                              "name": "fixed_point32"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaGFzaCIsImMiOjB9",
                            "node": {
                              "name": "hash"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWFjcm9zIiwiYyI6MH0",
                            "node": {
                              "name": "macros"
                            }
                          },
                          {
                            "cursor": "eyJuIjoib3B0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "option"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RyaW5nIiwiYyI6MH0",
                            "node": {
                              "name": "string"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidHlwZV9uYW1lIiwiYyI6MH0",
                            "node": {
                              "name": "type_name"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTEyOCIsImMiOjB9",
                            "node": {
                              "name": "u128"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTE2IiwiYyI6MH0",
                            "node": {
                              "name": "u16"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTI1NiIsImMiOjB9",
                            "node": {
                              "name": "u256"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTMyIiwiYyI6MH0",
                            "node": {
                              "name": "u32"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTY0IiwiYyI6MH0",
                            "node": {
                              "name": "u64"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTgiLCJjIjowfQ",
                            "node": {
                              "name": "u8"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmVjdG9yIiwiYyI6MH0",
                            "node": {
                              "name": "vector"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzcyIsImMiOjB9",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYXV0aGVudGljYXRvcl9zdGF0ZSIsImMiOjB9",
                            "node": {
                              "name": "authenticator_state"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFnIiwiYyI6MH0",
                            "node": {
                              "name": "bag"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFsYW5jZSIsImMiOjB9",
                            "node": {
                              "name": "balance"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNzIiwiYyI6MH0",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmxzMTIzODEiLCJjIjowfQ",
                            "node": {
                              "name": "bls12381"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYm9ycm93IiwiYyI6MH0",
                            "node": {
                              "name": "borrow"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2xvY2siLCJjIjowfQ",
                            "node": {
                              "name": "clock"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29pbiIsImMiOjB9",
                            "node": {
                              "name": "coin"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29pbl9tYW5hZ2VyIiwiYyI6MH0",
                            "node": {
                              "name": "coin_manager"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29uZmlnIiwiYyI6MH0",
                            "node": {
                              "name": "config"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGVueV9saXN0IiwiYyI6MH0",
                            "node": {
                              "name": "deny_list"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGlzcGxheSIsImMiOjB9",
                            "node": {
                              "name": "display"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZHluYW1pY19maWVsZCIsImMiOjB9",
                            "node": {
                              "name": "dynamic_field"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZHluYW1pY19vYmplY3RfZmllbGQiLCJjIjowfQ",
                            "node": {
                              "name": "dynamic_object_field"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWNkc2FfazEiLCJjIjowfQ",
                            "node": {
                              "name": "ecdsa_k1"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWNkc2FfcjEiLCJjIjowfQ",
                            "node": {
                              "name": "ecdsa_r1"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWN2cmYiLCJjIjowfQ",
                            "node": {
                              "name": "ecvrf"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWQyNTUxOSIsImMiOjB9",
                            "node": {
                              "name": "ed25519"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZXZlbnQiLCJjIjowfQ",
                            "node": {
                              "name": "event"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiZ2VuZXNpcyIsImMiOjB9",
                            "node": {
                              "name": "genesis"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaW90YV9zeXN0ZW0iLCJjIjowfQ",
                            "node": {
                              "name": "iota_system"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaW90YV9zeXN0ZW1fc3RhdGVfaW5uZXIiLCJjIjowfQ",
                            "node": {
                              "name": "iota_system_state_inner"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3Rha2luZ19wb29sIiwiYyI6MH0",
                            "node": {
                              "name": "staking_pool"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RvcmFnZV9mdW5kIiwiYyI6MH0",
                            "node": {
                              "name": "storage_fund"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidGltZWxvY2tlZF9zdGFraW5nIiwiYyI6MH0",
                            "node": {
                              "name": "timelocked_staking"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yIiwiYyI6MH0",
                            "node": {
                              "name": "validator"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX2NhcCIsImMiOjB9",
                            "node": {
                              "name": "validator_cap"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX3NldCIsImMiOjB9",
                            "node": {
                              "name": "validator_set"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX3dyYXBwZXIiLCJjIjowfQ",
                            "node": {
                              "name": "validator_wrapper"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidm90aW5nX3Bvd2VyIiwiYyI6MH0",
                            "node": {
                              "name": "voting_power"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::iota_system::IotaSystemState"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000005",
                          "version": "1"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo0LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::clock::Clock"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000006",
                          "timestamp_ms": "0"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo1LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::random::Random"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000008",
                          "inner": {
                            "id": "0x8eca4a8cc5f2340bbe739cb081757a3ffd3bc830e91971f7f96febbbfaeadf0c",
                            "version": "1"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo2LCJjIjowfQ",
                  "node": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYnJpZGdlIiwiYyI6MH0",
                            "node": {
                              "name": "bridge"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2hhaW5faWRzIiwiYyI6MH0",
                            "node": {
                              "name": "chain_ids"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29tbWl0dGVlIiwiYyI6MH0",
                            "node": {
                              "name": "committee"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3J5cHRvIiwiYyI6MH0",
                            "node": {
                              "name": "crypto"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibGltaXRlciIsImMiOjB9",
                            "node": {
                              "name": "limiter"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWVzc2FnZSIsImMiOjB9",
                            "node": {
                              "name": "message"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWVzc2FnZV90eXBlcyIsImMiOjB9",
                            "node": {
                              "name": "message_types"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidHJlYXN1cnkiLCJjIjowfQ",
                            "node": {
                              "name": "treasury"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo3LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::deny_list::DenyList"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000403",
                          "lists": {
                            "id": "0x8f84caa74fcc4af960e63e5650bfe8f579bcccfb5a44c7b545271f640a762ae3",
                            "size": "1"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo4LCJjIjowfQ",
                  "node": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000107a",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzc191bmxvY2tfY29uZGl0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "address_unlock_condition"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYWxpYXMiLCJjIjowfQ",
                            "node": {
                              "name": "alias"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYWxpYXNfb3V0cHV0IiwiYyI6MH0",
                            "node": {
                              "name": "alias_output"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFzaWNfb3V0cHV0IiwiYyI6MH0",
                            "node": {
                              "name": "basic_output"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZXhwaXJhdGlvbl91bmxvY2tfY29uZGl0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "expiration_unlock_condition"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaXJjMjciLCJjIjowfQ",
                            "node": {
                              "name": "irc27"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibmZ0IiwiYyI6MH0",
                            "node": {
                              "name": "nft"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibmZ0X291dHB1dCIsImMiOjB9",
                            "node": {
                              "name": "nft_output"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RhcmR1c3RfdXBncmFkZV9sYWJlbCIsImMiOjB9",
                            "node": {
                              "name": "stardust_upgrade_label"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RvcmFnZV9kZXBvc2l0X3JldHVybl91bmxvY2tfY29uZGl0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "storage_deposit_return_unlock_condition"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidGltZWxvY2tfdW5sb2NrX2NvbmRpdGlvbiIsImMiOjB9",
                            "node": {
                              "name": "timelock_unlock_condition"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidXRpbGl0aWVzIiwiYyI6MH0",
                            "node": {
                              "name": "utilities"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo5LCJjIjowfQ",
                  "node": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiY2xvYiIsImMiOjB9",
                            "node": {
                              "name": "clob"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2xvYl92MiIsImMiOjB9",
                            "node": {
                              "name": "clob_v2"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3JpdGJpdCIsImMiOjB9",
                            "node": {
                              "name": "critbit"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3VzdG9kaWFuIiwiYyI6MH0",
                            "node": {
                              "name": "custodian"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3VzdG9kaWFuX3YyIiwiYyI6MH0",
                            "node": {
                              "name": "custodian_v2"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWF0aCIsImMiOjB9",
                            "node": {
                              "name": "math"
                            }
                          },
                          {
                            "cursor": "eyJuIjoib3JkZXJfcXVlcnkiLCJjIjowfQ",
                            "node": {
                              "name": "order_query"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxMCwiYyI6MH0",
                  "node": {
                    "address": "0x3cb92a6b50e1223efc71be40e17dde09f380700b428e4caf7ef5392c3f64bb20",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::CoinMetadata<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x3cb92a6b50e1223efc71be40e17dde09f380700b428e4caf7ef5392c3f64bb20",
                          "decimals": 9,
                          "name": "IOTA",
                          "symbol": "IOTA",
                          "description": "The main (gas)token of the IOTA Network.",
                          "icon_url": {
                            "url": "https://iota.org/logo.png"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMSwiYyI6MH0",
                  "node": {
                    "address": "0x4a7e22fe45e8eaa4381e9335d0389c4af6b7b23e261612910fe69e40fef3a7bb",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<0x0000000000000000000000000000000000000000000000000000000000000002::object::ID,address>"
                        },
                        "json": {
                          "id": "0x4a7e22fe45e8eaa4381e9335d0389c4af6b7b23e261612910fe69e40fef3a7bb",
                          "name": "0x8447c4286c33e3898cf907c2c026e76aa9b003b5b734f8b055cbe47156f854db",
                          "value": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMiwiYyI6MH0",
                  "node": {
                    "address": "0x5a6383eb592bab4ff7c037a2118c514149ba9a86cf5a3b019c7034686365183f",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<vector<u8>,0x0000000000000000000000000000000000000000000000000000000000000002::timelock::SystemTimelockCap>"
                        },
                        "json": {
                          "id": "0x5a6383eb592bab4ff7c037a2118c514149ba9a86cf5a3b019c7034686365183f",
                          "name": [
                            115,
                            121,
                            115,
                            95,
                            116,
                            105,
                            109,
                            101,
                            108,
                            111,
                            99,
                            107,
                            95,
                            99,
                            97,
                            112
                          ],
                          "value": {
                            "dummy_field": false
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMywiYyI6MH0",
                  "node": {
                    "address": "0x67a3749049e3768f64a7ce583ec5db5b3295859e1169d70ce5fee7a133156329",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x67a3749049e3768f64a7ce583ec5db5b3295859e1169d70ce5fee7a133156329",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNCwiYyI6MH0",
                  "node": {
                    "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::iota_system_state_inner::IotaSystemStateInner>"
                        },
                        "json": {
                          "id": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                          "name": "1",
                          "value": {
                            "epoch": "0",
                            "protocol_version": "1",
                            "system_state_version": "1",
                            "iota_treasury_cap": {
                              "inner": {
                                "id": "0x69c20b09723a6e65713b18f79ee3af5b910254e9b88956f8eb4575b46c0f1972",
                                "total_supply": {
                                  "value": "31800000000000000"
                                }
                              }
                            },
                            "validators": {
                              "total_stake": "1500000000000000",
                              "active_validators": [
                                {
                                  "metadata": {
                                    "iota_address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80",
                                    "protocol_pubkey_bytes": [
                                      168,
                                      10,
                                      113,
                                      148,
                                      146,
                                      18,
                                      4,
                                      206,
                                      160,
                                      17,
                                      65,
                                      3,
                                      192,
                                      72,
                                      69,
                                      3,
                                      34,
                                      62,
                                      177,
                                      119,
                                      149,
                                      119,
                                      28,
                                      226,
                                      120,
                                      84,
                                      208,
                                      34,
                                      33,
                                      221,
                                      215,
                                      26,
                                      19,
                                      43,
                                      135,
                                      198,
                                      111,
                                      189,
                                      25,
                                      213,
                                      111,
                                      170,
                                      66,
                                      24,
                                      110,
                                      12,
                                      78,
                                      20,
                                      10,
                                      27,
                                      128,
                                      57,
                                      246,
                                      144,
                                      114,
                                      82,
                                      79,
                                      96,
                                      215,
                                      59,
                                      240,
                                      247,
                                      211,
                                      18,
                                      143,
                                      1,
                                      109,
                                      137,
                                      179,
                                      82,
                                      215,
                                      118,
                                      63,
                                      135,
                                      18,
                                      31,
                                      123,
                                      40,
                                      235,
                                      25,
                                      153,
                                      189,
                                      81,
                                      129,
                                      128,
                                      219,
                                      99,
                                      215,
                                      146,
                                      145,
                                      113,
                                      132,
                                      99,
                                      76,
                                      126,
                                      246
                                    ],
                                    "network_pubkey_bytes": [
                                      222,
                                      193,
                                      56,
                                      253,
                                      223,
                                      140,
                                      108,
                                      228,
                                      161,
                                      246,
                                      151,
                                      172,
                                      42,
                                      190,
                                      219,
                                      243,
                                      212,
                                      210,
                                      59,
                                      152,
                                      5,
                                      6,
                                      236,
                                      134,
                                      82,
                                      53,
                                      90,
                                      224,
                                      105,
                                      93,
                                      152,
                                      85
                                    ],
                                    "worker_pubkey_bytes": [
                                      172,
                                      116,
                                      152,
                                      220,
                                      228,
                                      127,
                                      173,
                                      148,
                                      84,
                                      44,
                                      112,
                                      162,
                                      74,
                                      125,
                                      50,
                                      95,
                                      124,
                                      147,
                                      55,
                                      36,
                                      241,
                                      143,
                                      223,
                                      60,
                                      129,
                                      224,
                                      221,
                                      102,
                                      15,
                                      35,
                                      217,
                                      101
                                    ],
                                    "proof_of_possession": [
                                      146,
                                      189,
                                      89,
                                      74,
                                      29,
                                      175,
                                      203,
                                      128,
                                      64,
                                      181,
                                      156,
                                      97,
                                      250,
                                      67,
                                      71,
                                      1,
                                      183,
                                      54,
                                      131,
                                      205,
                                      9,
                                      153,
                                      183,
                                      92,
                                      197,
                                      160,
                                      192,
                                      111,
                                      216,
                                      8,
                                      35,
                                      211,
                                      26,
                                      222,
                                      255,
                                      142,
                                      137,
                                      6,
                                      130,
                                      140,
                                      153,
                                      155,
                                      252,
                                      79,
                                      139,
                                      240,
                                      222,
                                      153
                                    ],
                                    "name": "validator-0",
                                    "description": "",
                                    "image_url": {
                                      "url": ""
                                    },
                                    "project_url": {
                                      "url": ""
                                    },
                                    "net_address": "/ip4/127.0.0.1/tcp/8000/http",
                                    "p2p_address": "/ip4/127.0.0.1/udp/8001/http",
                                    "primary_address": "/ip4/127.0.0.1/udp/8004/http",
                                    "worker_address": "/ip4/127.0.0.1/udp/8005/http",
                                    "next_epoch_protocol_pubkey_bytes": null,
                                    "next_epoch_proof_of_possession": null,
                                    "next_epoch_network_pubkey_bytes": null,
                                    "next_epoch_worker_pubkey_bytes": null,
                                    "next_epoch_net_address": null,
                                    "next_epoch_p2p_address": null,
                                    "next_epoch_primary_address": null,
                                    "next_epoch_worker_address": null,
                                    "extra_fields": {
                                      "id": "0xc43fcd3f4c8c01f33327b95a264cf58191dbcabdf600f88f664ae7838640d188",
                                      "size": "0"
                                    }
                                  },
                                  "voting_power": "10000",
                                  "operation_cap_id": "0x8e48c4b079dba007e62560607ad5b6c8e53b51f57acf3ae9de5f6fcb832a3886",
                                  "gas_price": "1000",
                                  "staking_pool": {
                                    "id": "0x8447c4286c33e3898cf907c2c026e76aa9b003b5b734f8b055cbe47156f854db",
                                    "activation_epoch": "0",
                                    "deactivation_epoch": null,
                                    "iota_balance": "1500000000000000",
                                    "rewards_pool": {
                                      "value": "0"
                                    },
                                    "pool_token_balance": "1500000000000000",
                                    "exchange_rates": {
                                      "id": "0xb38c5751ecb4f75ba417235d1cafce4225041a4b7d7477af393f9b18558dd70f",
                                      "size": "1"
                                    },
                                    "pending_stake": "0",
                                    "pending_total_iota_withdraw": "0",
                                    "pending_pool_token_withdraw": "0",
                                    "extra_fields": {
                                      "id": "0xbb3756987ff0c90ef649c28b3d5c44098bfafe9b4f8ffbbdc503182cae8214f2",
                                      "size": "0"
                                    }
                                  },
                                  "commission_rate": "200",
                                  "next_epoch_stake": "1500000000000000",
                                  "next_epoch_gas_price": "1000",
                                  "next_epoch_commission_rate": "200",
                                  "extra_fields": {
                                    "id": "0xc1a364bc4239969d3e02b55a232aab6b0bf58466555a5d0955bd385080aebe1e",
                                    "size": "0"
                                  }
                                }
                              ],
                              "pending_active_validators": {
                                "contents": {
                                  "id": "0x7235db8ea069b994752e7b09c69cc80c736315c737bf7e84a37b9825ce75458e",
                                  "size": "0"
                                }
                              },
                              "pending_removals": [],
                              "staking_pool_mappings": {
                                "id": "0x731677d45aa5b871a3f0948e7138b70b14b101ee5bda1796154c608f551aa108",
                                "size": "1"
                              },
                              "inactive_validators": {
                                "id": "0x07f89355f86acf1e2771dad1b1a643b180fc77187e2720f873478bf11fc4a5ec",
                                "size": "0"
                              },
                              "validator_candidates": {
                                "id": "0xe37cf932f52055f750e8943d483fe40a579cbc1837734d17c9968e6656717cb4",
                                "size": "0"
                              },
                              "at_risk_validators": {
                                "contents": []
                              },
                              "extra_fields": {
                                "id": "0x8038e4e8a7a882598c9c72d3c52279020e69617c521dade2aca99ef244442b93",
                                "size": "0"
                              }
                            },
                            "storage_fund": {
                              "total_object_storage_rebates": {
                                "value": "0"
                              },
                              "non_refundable_balance": {
                                "value": "0"
                              }
                            },
                            "parameters": {
                              "epoch_duration_ms": "86400000",
                              "max_validator_count": "150",
                              "min_validator_joining_stake": "2000000000000000",
                              "validator_low_stake_threshold": "1500000000000000",
                              "validator_very_low_stake_threshold": "1000000000000000",
                              "validator_low_stake_grace_period": "7",
                              "extra_fields": {
                                "id": "0xc16dc8a3a0bec5e696c255cfd887c69858223cef015220b7606501871c474f95",
                                "size": "0"
                              }
                            },
                            "reference_gas_price": "1000",
                            "validator_report_records": {
                              "contents": []
                            },
                            "safe_mode": false,
                            "safe_mode_storage_charges": {
                              "value": "0"
                            },
                            "safe_mode_computation_rewards": {
                              "value": "0"
                            },
                            "safe_mode_storage_rebates": "0",
                            "safe_mode_non_refundable_storage_fee": "0",
                            "epoch_start_timestamp_ms": "0",
                            "extra_fields": {
                              "id": "0x0ba9030fc643a0df3ed801db1c3a08e1dcb86fdd4e2d63dee4873f15544d1627",
                              "size": "0"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNSwiYyI6MH0",
                  "node": {
                    "address": "0x8e48c4b079dba007e62560607ad5b6c8e53b51f57acf3ae9de5f6fcb832a3886",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::validator_cap::UnverifiedValidatorOperationCap"
                        },
                        "json": {
                          "id": "0x8e48c4b079dba007e62560607ad5b6c8e53b51f57acf3ae9de5f6fcb832a3886",
                          "authorizer_validator_address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNiwiYyI6MH0",
                  "node": {
                    "address": "0x8f33081bee57361fef574265f881dfe188f09ce847f4f7f244b611c2fa7e7c64",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x8f33081bee57361fef574265f881dfe188f09ce847f4f7f244b611c2fa7e7c64",
                          "balance": {
                            "value": "30000000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNywiYyI6MH0",
                  "node": {
                    "address": "0xa073dccbe8f0521980f2b732e980c3948cd1264216afbf019c2cf9491bfef679",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::PoolTokenExchangeRate>"
                        },
                        "json": {
                          "id": "0xa073dccbe8f0521980f2b732e980c3948cd1264216afbf019c2cf9491bfef679",
                          "name": "0",
                          "value": {
                            "iota_amount": "0",
                            "pool_token_amount": "0"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxOCwiYyI6MH0",
                  "node": {
                    "address": "0xbec524b158cbe21ffb36a46de10c17f55205b9599a0973a1bcbba961cd83e008",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000002::random::RandomInner>"
                        },
                        "json": {
                          "id": "0xbec524b158cbe21ffb36a46de10c17f55205b9599a0973a1bcbba961cd83e008",
                          "name": "1",
                          "value": {
                            "version": "1",
                            "epoch": "0",
                            "randomness_round": "0",
                            "random_bytes": []
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxOSwiYyI6MH0",
                  "node": {
                    "address": "0xbec6bd8bdd4e7f0933edb6d0363d26d46151d8ca8cba1d7dcc5036b4c6cc17cd",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000002::deny_list::PerTypeList>"
                        },
                        "json": {
                          "id": "0xbec6bd8bdd4e7f0933edb6d0363d26d46151d8ca8cba1d7dcc5036b4c6cc17cd",
                          "name": "0",
                          "value": {
                            "id": "0x80add617af7314a0f4c5b70ef131ccb286dbf0bd1b4b516b0af7ba43a9f54df4",
                            "denied_count": {
                              "id": "0x472ecf1f5b53e22fd4aee9c7313914cd025b18cb298c0472db9aa91506878dca",
                              "size": "0"
                            },
                            "denied_addresses": {
                              "id": "0x292222b1134c7fe0513db2baa523577280a63b6740c2ed632c0e217422f5c4b6",
                              "size": "0"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 1,
            "dependencies": {
              "nodes": []
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
                  },
                  "amount": "30000000000000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  }
                },
                {
                  "owner": {
                    "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
                  },
                  "amount": "300000000000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "digest": "JBJkSwhqnjk2cMqgi4D3THnbpYEjyKzKrXg8Uroz3P9i"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "digest": "8nLny7EG9bAZrQs3FNNWNWxCskkYigd8umYeMoB8tVC"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "digest": "ENEpL5igE44NEtPqbBsyy3T5hHhfpe49R1vCcZvEDqx4"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "digest": "7icYXb3Z2NRwtFeweYweT5V5gLWoh3NmWWRoLJnrLzDA"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "7h6CtbidsbneCMhougpoumLcVNkj2ezvZCSGYV3KsYMa"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                    "digest": "337qLfRcpqQjnyKd39keLaGhfLEQy5enjXJqpA9SRkPw"
                  }
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                    "digest": "6EEFL4sQY1S6p65rCEGwauenFWMYgXazVeR7QvGzT96D"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                    "digest": "CTiRGwmCK3QFUPwUnRMUVwxkKXjXzvsbwfQNg8XMcVhP"
                  }
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000107a",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000107a",
                    "digest": "AzRX1DTctNaMxFwRxwfoyFBU9whmepG5CWcHmnGuHWbU"
                  }
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                    "digest": "8QKFCVY2W8x85EF4EvPPuQmQHtbs7avPrin1TzCnXB1k"
                  }
                },
                {
                  "address": "0x3cb92a6b50e1223efc71be40e17dde09f380700b428e4caf7ef5392c3f64bb20",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x3cb92a6b50e1223efc71be40e17dde09f380700b428e4caf7ef5392c3f64bb20",
                    "digest": "3F29Hmc587VaX9zBTNhz7u4zCYxiATRjFd8Ur92jmgDn"
                  }
                },
                {
                  "address": "0x4a7e22fe45e8eaa4381e9335d0389c4af6b7b23e261612910fe69e40fef3a7bb",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x4a7e22fe45e8eaa4381e9335d0389c4af6b7b23e261612910fe69e40fef3a7bb",
                    "digest": "PJhqZ7tHTyaYSmu6NstE9wHszriw9hi935GLc2kRsoE"
                  }
                },
                {
                  "address": "0x5a6383eb592bab4ff7c037a2118c514149ba9a86cf5a3b019c7034686365183f",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x5a6383eb592bab4ff7c037a2118c514149ba9a86cf5a3b019c7034686365183f",
                    "digest": "F3rjnSJNQm9i7ufJ25CJgs2Wvd4v48PRBYqnqyQU1AJf"
                  }
                },
                {
                  "address": "0x67a3749049e3768f64a7ce583ec5db5b3295859e1169d70ce5fee7a133156329",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x67a3749049e3768f64a7ce583ec5db5b3295859e1169d70ce5fee7a133156329",
                    "digest": "5kTaofD1wLjJH8fvA2nTHEJog4siV9bKfbrbUCLSUdxk"
                  }
                },
                {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                    "digest": "CiaTwsVHPaRjoodSMGjCmM2T5rCzEiTTiR83ox1LCmVF"
                  }
                },
                {
                  "address": "0x8e48c4b079dba007e62560607ad5b6c8e53b51f57acf3ae9de5f6fcb832a3886",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x8e48c4b079dba007e62560607ad5b6c8e53b51f57acf3ae9de5f6fcb832a3886",
                    "digest": "FRaw6qha6aD7LkwTcyFBPYUGBME7SranZRYKRus4Pkj7"
                  }
                },
                {
                  "address": "0x8f33081bee57361fef574265f881dfe188f09ce847f4f7f244b611c2fa7e7c64",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x8f33081bee57361fef574265f881dfe188f09ce847f4f7f244b611c2fa7e7c64",
                    "digest": "9f4N2NQf27fQRgVP3rsb7ZWkMSi4kHzWScaPtyT7SkBF"
                  }
                },
                {
                  "address": "0xa073dccbe8f0521980f2b732e980c3948cd1264216afbf019c2cf9491bfef679",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xa073dccbe8f0521980f2b732e980c3948cd1264216afbf019c2cf9491bfef679",
                    "digest": "9ZdJvxB2wn4vHDxy2BJJAsT9PwGaBd423ENWGEd6s8zA"
                  }
                },
                {
                  "address": "0xbec524b158cbe21ffb36a46de10c17f55205b9599a0973a1bcbba961cd83e008",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xbec524b158cbe21ffb36a46de10c17f55205b9599a0973a1bcbba961cd83e008",
                    "digest": "FNCEggtTGYcfPonqZaZci3vwqmRTmxEFLy6zy4CjFvi8"
                  }
                },
                {
                  "address": "0xbec6bd8bdd4e7f0933edb6d0363d26d46151d8ca8cba1d7dcc5036b4c6cc17cd",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xbec6bd8bdd4e7f0933edb6d0363d26d46151d8ca8cba1d7dcc5036b4c6cc17cd",
                    "digest": "EL8giqg7S1wiyiYfky1zLf95H6UyNL8LrAU6bZ9HVk1o"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 0
            },
            "transactionBlock": {
              "digest": "HuAtfgjw2KZbZmqq1mc5UFVX3paqR1W6K4XZN4faNaNo"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 3, line 107:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 109-184:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "DPq7c2A5SyX36jGrNW6QNstAzSxtFPai1SZj4eF7oFDR",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 0
            },
            "round": 0,
            "commitTimestamp": "1970-01-01T00:00:42Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "HuAtfgjw2KZbZmqq1mc5UFVX3paqR1W6K4XZN4faNaNo"
                }
              ]
            },
            "balanceChanges": {
              "nodes": []
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "Dbu2swR7jSwhxcjbyL1iGCuQPSrKR7Kyp8PEbKxsd9Uq"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:42Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "DPq7c2A5SyX36jGrNW6QNstAzSxtFPai1SZj4eF7oFDR"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 6, line 188:
//# advance-epoch
Epoch advanced: 0

task 7, lines 190-277:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "9wzczqe1Bo9cEqU8tzwRse5EMHSQg5VVqrT6MxwtkDuL",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "EndOfEpochTransaction",
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "ChangeEpochTransaction",
                    "epoch": null,
                    "protocolVersion": 1,
                    "storageCharge": "0",
                    "computationCharge": "0",
                    "storageRebate": "0",
                    "nonRefundableStorageFee": "0",
                    "startTimestamp": "1970-01-01T00:01:25Z"
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "HuAtfgjw2KZbZmqq1mc5UFVX3paqR1W6K4XZN4faNaNo"
                }
              ]
            },
            "balanceChanges": {
              "nodes": []
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "digest": "BC4MegdKK2GkresPULRoV8aHyMrSLiKn4wgt5gza28aa"
                  }
                },
                {
                  "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                    "digest": "8tnw1giJTJDnNYsKkAtp259DgDcpWPywqyBuCC7mzA3Q"
                  }
                },
                {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "idCreated": false,
                  "idDeleted": true,
                  "outputState": null
                },
                {
                  "address": "0xc20b92046489912b155a245895fea5f8bced00b279fa3e21f17aaee10160b80a",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xc20b92046489912b155a245895fea5f8bced00b279fa3e21f17aaee10160b80a",
                    "digest": "AduAw5t2crQFnRjBdaBmUKKHUUA3kjXpWjXkRwKcMUcN"
                  }
                },
                {
                  "address": "0xd37e55b63c3df289e533d790078a12b60df27d3ba11d425425e18a53bdcf49ec",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xd37e55b63c3df289e533d790078a12b60df27d3ba11d425425e18a53bdcf49ec",
                    "digest": "CxAWd6e8rVGrX4R82Q2gHoNvmChMkJjG5gHejjYtd1Dk"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:01:25Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "9wzczqe1Bo9cEqU8tzwRse5EMHSQg5VVqrT6MxwtkDuL"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}
