processed 11 tasks

init:
A: object(0,0)

task 1 'publish'. lines 7-37:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7835600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 39-39:
created: object(2,0), object(2,1)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3541600,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'view-object'. lines 41-41:
Owner: Account Address ( fake(2,1) )
Version: 3
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}, value: 0u64}

task 4 'view-object'. lines 43-43:
Owner: Account Address ( _ )
Version: 3
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,1)}}, value: 0u64}

task 5 'run'. lines 45-45:
Error: Error checking transaction input objects: IncorrectUserSignature { error: "Object object(2,0) is owned by account address object(2,1), but given owner/signer address is 0x4c291487b3b40954aa87f79cde3cb2e11e346b23828c746b7016f933dacf0a82" }

task 6 'view-object'. lines 47-47:
Owner: Account Address ( fake(2,1) )
Version: 3
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}, value: 0u64}

task 7 'view-object'. lines 49-49:
Owner: Account Address ( _ )
Version: 3
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,1)}}, value: 0u64}

task 8 'view-object'. lines 51-51:
Error: task 8, lines 51-51. Unbound fake id 5,0

task 9 'view-object'. lines 53-53:
Error: task 9, lines 53-53. Unbound fake id 5,1

task 10 'view-object'. lines 55-55:
Error: task 10, lines 55-55. Unbound fake id 5,2
