// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CheckpointStreamRequest {
    #[prost(uint64, optional, tag = "1")]
    pub start_sequence_number: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "2")]
    pub end_sequence_number: ::core::option::Option<u64>,
    /// If true, stream the full CheckpointData (not just the summary).
    #[prost(bool, tag = "3")]
    pub full: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct EpochRequest {
    #[prost(uint64, tag = "1")]
    pub epoch: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CheckpointSequenceNumberResponse {
    #[prost(uint64, tag = "1")]
    pub sequence_number: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Checkpoint {
    #[prost(uint64, tag = "1")]
    pub sequence_number: u64,
    /// Indicates whether bcs_data contains full CheckpointData (true) or just CertifiedCheckpointSummary (false)
    #[prost(bool, tag = "2")]
    pub is_full: bool,
    /// BCS-encoded CertifiedCheckpointSummary (default) or CheckpointData (if full=true)
    #[prost(message, optional, tag = "3")]
    pub bcs_data: ::core::option::Option<super::common::BcsData>,
}
/// Generated client implementations.
pub mod checkpoint_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct CheckpointServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl CheckpointServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> CheckpointServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> CheckpointServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            CheckpointServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Checkpoint operations
        pub async fn stream_checkpoints(
            &mut self,
            request: impl tonic::IntoRequest<super::CheckpointStreamRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::Checkpoint>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/iota.grpc.v0.checkpoints.CheckpointService/StreamCheckpoints",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "iota.grpc.v0.checkpoints.CheckpointService",
                        "StreamCheckpoints",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn get_epoch_first_checkpoint_sequence_number(
            &mut self,
            request: impl tonic::IntoRequest<super::EpochRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CheckpointSequenceNumberResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/iota.grpc.v0.checkpoints.CheckpointService/GetEpochFirstCheckpointSequenceNumber",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "iota.grpc.v0.checkpoints.CheckpointService",
                        "GetEpochFirstCheckpointSequenceNumber",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod checkpoint_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with CheckpointServiceServer.
    #[async_trait]
    pub trait CheckpointService: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the StreamCheckpoints method.
        type StreamCheckpointsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::Checkpoint, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Checkpoint operations
        async fn stream_checkpoints(
            &self,
            request: tonic::Request<super::CheckpointStreamRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamCheckpointsStream>,
            tonic::Status,
        >;
        async fn get_epoch_first_checkpoint_sequence_number(
            &self,
            request: tonic::Request<super::EpochRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CheckpointSequenceNumberResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct CheckpointServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> CheckpointServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for CheckpointServiceServer<T>
    where
        T: CheckpointService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/iota.grpc.v0.checkpoints.CheckpointService/StreamCheckpoints" => {
                    #[allow(non_camel_case_types)]
                    struct StreamCheckpointsSvc<T: CheckpointService>(pub Arc<T>);
                    impl<
                        T: CheckpointService,
                    > tonic::server::ServerStreamingService<
                        super::CheckpointStreamRequest,
                    > for StreamCheckpointsSvc<T> {
                        type Response = super::Checkpoint;
                        type ResponseStream = T::StreamCheckpointsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CheckpointStreamRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CheckpointService>::stream_checkpoints(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamCheckpointsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/iota.grpc.v0.checkpoints.CheckpointService/GetEpochFirstCheckpointSequenceNumber" => {
                    #[allow(non_camel_case_types)]
                    struct GetEpochFirstCheckpointSequenceNumberSvc<
                        T: CheckpointService,
                    >(
                        pub Arc<T>,
                    );
                    impl<
                        T: CheckpointService,
                    > tonic::server::UnaryService<super::EpochRequest>
                    for GetEpochFirstCheckpointSequenceNumberSvc<T> {
                        type Response = super::CheckpointSequenceNumberResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::EpochRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CheckpointService>::get_epoch_first_checkpoint_sequence_number(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetEpochFirstCheckpointSequenceNumberSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for CheckpointServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "iota.grpc.v0.checkpoints.CheckpointService";
    impl<T> tonic::server::NamedService for CheckpointServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
