// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// This file is @generated by prost-build.
/// BCS-serialized data container
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BcsData {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// 32-byte address type for IOTA addresses, object IDs, package IDs, etc.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Address {
    #[prost(bytes = "vec", tag = "1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
}
/// 32-byte Transaction digest
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TransactionDigest {
    #[prost(bytes = "vec", tag = "1")]
    pub digest: ::prost::alloc::vec::Vec<u8>,
}
