// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventStreamRequest {
    #[prost(message, optional, tag = "1")]
    pub filter: ::core::option::Option<EventFilter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    #[prost(message, optional, tag = "1")]
    pub event_id: ::core::option::Option<EventId>,
    #[prost(message, optional, tag = "2")]
    pub package_id: ::core::option::Option<super::common::Address>,
    #[prost(string, tag = "3")]
    pub transaction_module: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub sender: ::core::option::Option<super::common::Address>,
    #[prost(string, tag = "5")]
    pub type_name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub parsed_json: ::prost::alloc::string::String,
    #[prost(uint64, optional, tag = "7")]
    pub timestamp_ms: ::core::option::Option<u64>,
    #[prost(message, optional, tag = "8")]
    pub event_data: ::core::option::Option<super::common::BcsData>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventId {
    #[prost(uint64, tag = "1")]
    pub event_seq: u64,
    #[prost(message, optional, tag = "2")]
    pub tx_digest: ::core::option::Option<super::common::TransactionDigest>,
}
/// Rich event filter that supports gRPC event filtering
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventFilter {
    #[prost(oneof = "event_filter::Filter", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub filter: ::core::option::Option<event_filter::Filter>,
}
/// Nested message and enum types in `EventFilter`.
pub mod event_filter {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Filter {
        #[prost(message, tag = "1")]
        All(super::AllFilter),
        #[prost(message, tag = "2")]
        Sender(super::SenderFilter),
        #[prost(message, tag = "3")]
        Transaction(super::TransactionFilter),
        #[prost(message, tag = "4")]
        MoveModule(super::MoveModuleFilter),
        #[prost(message, tag = "5")]
        MoveEventType(super::MoveEventTypeFilter),
        #[prost(message, tag = "6")]
        MoveEventModule(super::MoveEventModuleFilter),
        #[prost(message, tag = "7")]
        TimeRange(super::TimeRangeFilter),
    }
}
/// Match all events (catch-all filter)
///
/// Empty - matches all events
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AllFilter {}
/// Filter by sender address
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SenderFilter {
    /// Sender address
    #[prost(message, optional, tag = "1")]
    pub sender: ::core::option::Option<super::common::Address>,
}
/// Filter by transaction digest
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionFilter {
    /// Transaction digest
    #[prost(message, optional, tag = "1")]
    pub tx_digest: ::core::option::Option<super::common::TransactionDigest>,
}
/// Filter by transaction execution module (different from event definition module)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MoveModuleFilter {
    /// Package ID
    #[prost(message, optional, tag = "1")]
    pub package_id: ::core::option::Option<super::common::Address>,
    /// Module name
    #[prost(string, tag = "2")]
    pub module: ::prost::alloc::string::String,
}
/// Filter by Move event type (package::module::event_name)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MoveEventTypeFilter {
    /// Package ID
    #[prost(message, optional, tag = "1")]
    pub package_id: ::core::option::Option<super::common::Address>,
    /// Module name (e.g., "request")
    #[prost(string, tag = "2")]
    pub module: ::prost::alloc::string::String,
    /// Event name (e.g., "RequestEvent")
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
}
/// Filter by package and module
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MoveEventModuleFilter {
    /// Package ID
    #[prost(message, optional, tag = "1")]
    pub package_id: ::core::option::Option<super::common::Address>,
    /// Module name
    #[prost(string, tag = "2")]
    pub module: ::prost::alloc::string::String,
}
/// Filter by timestamp range
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TimeRangeFilter {
    /// Start time in milliseconds since epoch (inclusive)
    #[prost(uint64, tag = "1")]
    pub start_time: u64,
    /// End time in milliseconds since epoch (exclusive)
    #[prost(uint64, tag = "2")]
    pub end_time: u64,
}
/// Generated client implementations.
pub mod event_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct EventServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl EventServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> EventServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> EventServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            EventServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn stream_events(
            &mut self,
            request: impl tonic::IntoRequest<super::EventStreamRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::Event>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/iota.grpc.v0.events.EventService/StreamEvents",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("iota.grpc.v0.events.EventService", "StreamEvents"),
                );
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod event_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with EventServiceServer.
    #[async_trait]
    pub trait EventService: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the StreamEvents method.
        type StreamEventsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::Event, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn stream_events(
            &self,
            request: tonic::Request<super::EventStreamRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamEventsStream>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct EventServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> EventServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for EventServiceServer<T>
    where
        T: EventService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/iota.grpc.v0.events.EventService/StreamEvents" => {
                    #[allow(non_camel_case_types)]
                    struct StreamEventsSvc<T: EventService>(pub Arc<T>);
                    impl<
                        T: EventService,
                    > tonic::server::ServerStreamingService<super::EventStreamRequest>
                    for StreamEventsSvc<T> {
                        type Response = super::Event;
                        type ResponseStream = T::StreamEventsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::EventStreamRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as EventService>::stream_events(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamEventsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for EventServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "iota.grpc.v0.events.EventService";
    impl<T> tonic::server::NamedService for EventServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
