name: Ledgernano End-to-end Tests

on: workflow_call

concurrency:
  group: ledgernano-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

jobs:
  ledgernano:
    name: Ledgernano
    runs-on: self-hosted-x64
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Install Nodejs
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Pull speculos docker image
        run: docker pull ghcr.io/ledgerhq/speculos

      - name: Download ledgernano binary
        run: |
          curl -L -o nanox.tar.gz https://github.com/iotaledger/ledger-app-iota/releases/download/ledger-app-iota-v1.0.0/nanox.tar.gz
          tar -xvf nanox.tar.gz
          mv nanox/iota sdk/ledgerjs-hw-app-iota/tests/iota

      - name: Start speculos simulator
        run: |
          # Start the container in detached mode and capture its ID
          container_id=$(docker run --rm -d -p 5000:5000 -v $(pwd)/sdk/ledgerjs-hw-app-iota/tests:/app ghcr.io/ledgerhq/speculos --api-port 5000 --display headless /app/iota)

          # Print logs for 5 seconds
          timeout 5 docker logs -f $container_id || true

      - name: Run TS SDK ledgernano tests
        run: pnpm --filter @iota/ledgerjs-hw-app-iota test
