name: Rust lints

on:
  workflow_call:
    inputs:
      isRust:
        type: boolean
      isRustExample:
        type: boolean
      isNightly:
        type: boolean
        default: false

concurrency:
  group: rust-lints-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: "error"
  # Don't emit giant backtraces in the CI logs.
  RUST_BACKTRACE: short
  # Disable incremental compilation.
  #
  # Incremental compilation is useful as part of an edit-build-test-edit cycle,
  # as it lets the compiler avoid recompiling code that hasn't changed. However,
  # on CI, we're not making small edits; we're almost always building the entire
  # project from scratch. Thus, incremental compilation on CI actually
  # introduces *additional* overhead to support making future builds
  # faster...but no future builds will ever occur in any given CI environment.
  #
  # See https://matklad.github.io/2021/09/04/fast-rust-builds.html#ci-workflow
  # for details.
  CARGO_INCREMENTAL: 0
  # Allow more retries for network requests in cargo (downloading crates) and
  # rustup (installing toolchains). This should help to reduce flaky CI failures
  # from transient network timeouts or other issues.
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:
  rustfmt:
    if: (!cancelled() && inputs.isRust)
    runs-on: [self-hosted-x64]
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Check Rust formatting
        run: cargo +nightly-2026-01-07 ci-fmt

  rustfmt-cancel:
    needs: [rustfmt]
    if: failure() && !inputs.isNightly
    runs-on: ubuntu-latest
    steps:
      - name: Cancel workflow run
        run: gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}

  cargo-sort:
    if: (!cancelled() && inputs.isRust)
    runs-on: [self-hosted-x64]
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Check Cargo.toml format and sorting and consolidate dependencies
        run: |
          pushd "scripts/cargo_sort"
          ./run_consolidate.sh --skip-dprint
          popd
      - name: Check Cargo.toml diffs after formatting
        run: |
          if git status --porcelain | grep -q "Cargo.toml"; then
            echo "Cargo.toml files not formatted and/or sorted properly, or dependencies not consolidated! Please run the 'scripts/cargo_sort/run_consolidate.sh' script."
            git diff  # Show the actual diffs
            exit 1    # Fail the workflow
          fi

  cargo-sort-cancel:
    needs: [cargo-sort]
    if: failure() && !inputs.isNightly
    runs-on: ubuntu-latest
    steps:
      - name: Cancel workflow run
        run: gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}

  examples:
    if: (!cancelled() && inputs.isRustExample)
    uses: ./.github/workflows/_rust_examples.yml
    with:
      isNightly: ${{ inputs.isNightly }}

  clippy:
    if: (!cancelled() && !failure() && inputs.isRust)
    needs:
      - rustfmt
    runs-on: [self-hosted-x64]
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      # See '.cargo/config' for list of enabled/disabled clippy lints
      - name: Check Clippy Lints
        run: cargo ci-clippy

      - name: Check Clippy Lints with msim
        run: |
          git clean -fd
          ./scripts/simtest/clippy.sh

  clippy-cancel:
    needs: [clippy]
    if: failure() && !inputs.isNightly
    runs-on: ubuntu-latest
    steps:
      - name: Cancel workflow run
        run: gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}
