name: Typos

on: workflow_call

concurrency:
  group: typos-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    if: (!cancelled() && !failure())
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check spelling
        uses: crate-ci/typos@cf5f1c29a8ac336af8568821ec41919923b05a83 # v1.45.1
        with:
          config: ./.typos.toml
