# This workflow is based on https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners
name: Publish Docker Images

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      iota_node:
        type: boolean
        description: "Release iota-node image"
        required: false
        default: false
      iota_indexer:
        type: boolean
        description: "Release iota-indexer image"
        required: false
        default: false
      iota_tools:
        type: boolean
        description: "Release iota-tools image"
        required: false
        default: false
      iota_graphql_rpc:
        type: boolean
        description: "Release iota-graphql-rpc image"
        required: false
        default: false
      iota_data_ingestion:
        type: boolean
        description: "Release iota-data-ingestion image"
        required: false
        default: false
      iota_rest_kv:
        type: boolean
        description: "Release iota-rest-kv image"
        required: false
        default: false

jobs:
  prepare:
    outputs:
      images: ${{ steps.images.outputs.images }}
    runs-on: ubuntu-24.04
    steps:
      - name: Define images to build
        id: images
        run: |
          images_array=()

          # Check iota_node: true if the input is set to true and the event is workflow_dispatch,
          # or if the event is a release (in which case the job should run regardless of the input).
          if [ "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.iota_node == 'true' || github.event_name == 'release' }}" == "true" ]; then
            images_array+=("iota-node")
          fi

          # Check iota_indexer: true if the input is set to true and the event is workflow_dispatch,
          # or if the event is a release (in which case the job should run regardless of the input).
          if [ "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.iota_indexer == 'true' || github.event_name == 'release' }}" == "true" ]; then
            images_array+=("iota-indexer")
          fi

          # Check iota_tools: true if the input is set to true and the event is workflow_dispatch,
          # or if the event is a release (in which case the job should run regardless of the input).
          if [ "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.iota_tools == 'true' || github.event_name == 'release' }}" == "true" ]; then
            images_array+=("iota-tools")
          fi

          # Check iota_graphql_rpc: true if the input is set to true and the event is workflow_dispatch,
          # or if the event is a release (in which case the job should run regardless of the input).
          if [ "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.iota_graphql_rpc == 'true' || github.event_name == 'release' }}" == "true" ]; then
            images_array+=("iota-graphql-rpc")
          fi

          # Check iota_data_ingestion: true if the input is set to true and the event is workflow_dispatch,
          # or if the event is a release (in which case the job should run regardless of the input).
          if [ "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.iota_data_ingestion == 'true' || github.event_name == 'release' }}" == "true" ]; then
            images_array+=("iota-data-ingestion")
          fi

          # Check iota_rest_kv: true if the input is set to true and the event is workflow_dispatch,
          # or if the event is a release (in which case the job should run regardless of the input).
          if [ "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.iota_rest_kv == 'true' || github.event_name == 'release' }}" == "true" ]; then
            images_array+=("iota-rest-kv")
          fi

          # Check if the images_array is empty
          if [ ${#images_array[@]} -eq 0 ]; then
            echo "Error: images_array is empty"
            exit 1
          fi

          echo "images=[$(printf '"%s",' "${images_array[@]}" | sed 's/,$//')]" >> "$GITHUB_OUTPUT"

  build:
    environment: release
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJSON(needs.prepare.outputs.images) }}
        arch: [
          amd64,
          arm64,
        ]
        include:
          - arch: amd64
            os: self-hosted-x64
          - arch: arm64
            os: self-hosted-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Prepare Environment Variables
        run: |
          echo "DOCKER_FILE=docker/${{ matrix.image }}/Dockerfile" >> $GITHUB_ENV
          echo "DOCKER_IMAGE=iotaledger/${{ matrix.image }}" >> $GITHUB_ENV
          echo "DOCKER_PLATFORM=linux/${{ matrix.arch }}" >> $GITHUB_ENV
          echo "PLATFORM_PAIR=linux-${{ matrix.arch }}" >> $GITHUB_ENV

          TOOLCHAIN_VERSION=$(grep -oE 'channel = "[^"]+' ./rust-toolchain.toml | sed 's/channel = "//')
          echo "TOOLCHAIN_VERSION=${TOOLCHAIN_VERSION}" >> $GITHUB_ENV

          echo "Rust toolchain version is ${TOOLCHAIN_VERSION}"

          echo "GIT_REVISION=$(git describe --always --abbrev=12 --dirty --exclude '*')" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ${{ env.DOCKER_IMAGE }}

      - name: Login to Docker Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Build and push by digest
        id: build-image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: .
          file: ${{ env.DOCKER_FILE }}
          platforms: ${{ env.DOCKER_PLATFORM }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,"name=${{ env.DOCKER_IMAGE }}",push-by-digest=true,name-canonical=true,push=true
          build-args: |
            GIT_REVISION=${{ env.GIT_REVISION }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            RUST_IMAGE_VERSION=${{ env.TOOLCHAIN_VERSION }}-trixie

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build-image.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: digests-${{ github.sha }}-${{ matrix.image }}-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  tag:
    environment: release # This will require a second approval after all `build` jobs have finished (see https://github.com/orgs/community/discussions/14417)
    needs: [prepare, build]
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJSON(needs.prepare.outputs.images) }}
    runs-on: ubuntu-24.04
    steps:
      - name: Prepare Environment Variables
        run: |
          echo "DOCKER_IMAGE=iotaledger/${{ matrix.image }}" >> $GITHUB_ENV

      - name: Download digests
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-${{ github.sha }}-${{ matrix.image }}-*
          merge-multiple: true

      - name: Login to Docker Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ${{ env.DOCKER_IMAGE }}
          # mapping semver tags to networks
          # v{MAJOR}.{MINOR}.{PATCH}-alpha -> alphanet
          # v{MAJOR}.{MINOR}.{PATCH}-beta -> devnet
          # v{MAJOR}.{MINOR}.{PATCH}-rc -> testnet
          # v{MAJOR}.{MINOR}.{PATCH} -> mainnet
          tags: |
            type=raw,value={{sha}},enable=${{ github.event_name == 'workflow_dispatch' }}
            type=raw,value={{tag}},enable=${{ github.event_name == 'release' }}
            type=raw,value=alphanet,enable=${{ github.event_name == 'release' && contains(github.ref, '-alpha') }}
            type=raw,value=devnet,enable=${{ github.event_name == 'release' && contains(github.ref, '-beta') }}
            type=raw,value=testnet,enable=${{ github.event_name == 'release' && contains(github.ref, '-rc') }}
            type=raw,value=mainnet,enable=${{ github.event_name == 'release' && !contains(github.ref, '-alpha') && !contains(github.ref, '-beta') && !contains(github.ref, '-rc') }}
            type=raw,value=latest,enable=${{ github.event_name == 'release' && !contains(github.ref, '-alpha') && !contains(github.ref, '-beta') && !contains(github.ref, '-rc') }}

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.DOCKER_IMAGE }}@sha256:%s ' *)
