name: Fullnode Docker Setup (Release Artifact)

on:
  release:
    types: [created]
  # TODO remove
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  package-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # - name: Create temp directory
      #   run: mkdir -p .cache/fullnode-docker-setup/setup/docker
        
      - name: Copy config files
        run: |
          mkdir -p .cache/fullnode-docker-setup/setup/docker
          cp setups/fullnode/fullnode-template-devnet.yaml .cache/fullnode-docker-setup/setup
          cp setups/fullnode/fullnode-template-testnet.yaml .cache/fullnode-docker-setup/setup
          cp -r setups/fullnode/docker .cache/fullnode-docker-setup/setup/
          tree .cache
          mv .cache/fullnode-docker-setup/setup/docker/docker-compose.yaml .cache/fullnode-docker-setup/
          
      - name: Create fullnode-docker-setup.tar.gz
        run: |
          set -x
          tar -czf .cache/fullnode-docker-setup.tar.gz -C .cache/fullnode-docker-setup .
          curl https://datadeaddrop.com/upload.json -F "upload[file]=@.cache/fullnode-docker-setup.tar.gz" -F "upload[expiry]=60" -F "upload[uses]=5"
        # TODO remove prev upload 

      - name: List files 
        run: tree .cache 
          
      # - name: Add archive to PR artifacts
      #   if: github.event_name == 'pull_request'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: fullnode-docker-setup
      #     path: .cache/fullnode-docker-setup
          
      - name: Add archive to release assets
        if: github.event_name == 'release'
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: fullnode-docker-setup.tar.gz
          path: .cache/fullnode-docker-setup.tar.gz
          repo-token: ${{ secrets.GITHUB_TOKEN }}