name: Fullnode Docker Setup (Release Artifact)

on:
  release:
    types: [created]
  # TODO remove
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  package-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create temp directory
        run: mkdir -p .cache/fullnode-docker-setup
        
      - name: Copy config files
        run: |
          cp setups/fullnode/fullnode-template-devnet.yaml .cache/fullnode-docker-setup/
          cp setups/fullnode/fullnode-template-testnet.yaml .cache/fullnode-docker-setup/
          cp -r setups/fullnode/docker/* .cache/fullnode-docker-setup/
          
      - name: Create fullnode-docker-setup.tar.gz
        if: github.event_name == 'release'
        uses: ihiroky/archive-action@v1
        with:
          root_dir: .cache/fullnode-docker-setup
          file_path: .cache/fullnode-docker-setup_${{ github.ref_name }}.tar.gz

      - name: List files
        run: ls -la .cache/
          
      - name: Upload PR artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: fullnode-docker-setup-${{ github.ref_name }}.tar.gz
          path: .cache/fullnode-docker-setup_${{ github.ref_name }}.tar.gz
          
      - name: Upload fullnode-docker-setup.tar.gz
        if: github.event_name == 'release'
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: fullnode-docker-setup_${{ github.ref_name }}.tar.gz
          path: .cache/fullnode-docker-setup_${{ github.ref_name }}.tar.gz
          repo-token: ${{ secrets.GITHUB_TOKEN }}