name: Upload Docs to S3

on:
  push:
    branches:
      - devnet
      - testnet
      - mainnet

jobs:
  build-and-upload-docs:
    runs-on: ubuntu-latest
    env:
      S3_BUCKET: files.iota.org/iota-wiki/iota

    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build Rust documentation
        run: UPDATE=1 cargo test --manifest-path crates/iota-framework/Cargo.toml

      # ----------- Build TypeScript and GraphQL Docs with pnpm -----------
      - name: Set up Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24"

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@10.30.0 --activate

      - name: Install dependencies
        run: pnpm install

      - name: Generate GraphQl docs
        run: pnpm --filter iota-docs generate-graphql-docs

      - name: Compress generated docs
        run: |
          tar czvf ${{ github.ref_name }}.tar.gz docs/generated-docs/*

      # ----------- Configure AWS Credentials -----------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_IOTA_WIKI }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_IOTA_WIKI }}
          aws-region: eu-central-1 # Change if needed

      # ----------- Upload Docs to S3 -----------
      - name: Upload Rust docs to S3
        run: aws s3 cp ${{ github.ref_name }}.tar.gz s3://$S3_BUCKET/${{ github.ref_name }}.tar.gz --acl public-read
