processed 14 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 13-35:
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 18316000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'view-object'. lines 37-37:
Owner: Account Address ( A )
Version: 2
Contents: iota::coin::Coin<test::regulated_coin::REGULATED_COIN> {id: iota::object::UID {id: iota::object::ID {bytes: fake(1,0)}}, balance: iota::balance::Balance<test::regulated_coin::REGULATED_COIN> {value: 10000u64}}

task 3 'view-object'. lines 39-39:
Owner: Immutable
Version: 2
Contents: iota::coin::CoinMetadata<test::regulated_coin::REGULATED_COIN> {id: iota::object::UID {id: iota::object::ID {bytes: fake(1,1)}}, decimals: 9u8, name: std::string::String {bytes: vector[82u8, 69u8, 71u8, 85u8, 76u8, 65u8, 84u8, 69u8, 68u8, 95u8, 67u8, 79u8, 73u8, 78u8]}, symbol: std::ascii::String {bytes: vector[82u8, 67u8]}, description: std::string::String {bytes: vector[65u8, 32u8, 110u8, 101u8, 119u8, 32u8, 114u8, 101u8, 103u8, 117u8, 108u8, 97u8, 116u8, 101u8, 100u8, 32u8, 99u8, 111u8, 105u8, 110u8]}, icon_url: std::option::Option<iota::url::Url> {vec: vector[]}}

task 4 'view-object'. lines 41-41:
Owner: Account Address ( A )
Version: 2
Contents: iota::coin::DenyCap<test::regulated_coin::REGULATED_COIN> {id: iota::object::UID {id: iota::object::ID {bytes: fake(1,2)}}}

task 5 'view-object'. lines 43-43:
Owner: Immutable
Version: 2
Contents: iota::coin::RegulatedCoinMetadata<test::regulated_coin::REGULATED_COIN> {id: iota::object::UID {id: iota::object::ID {bytes: fake(1,3)}}, coin_metadata_object: iota::object::ID {bytes: fake(1,1)}, deny_cap_object: iota::object::ID {bytes: fake(1,2)}}

task 6 'view-object'. lines 45-45:
Owner: Immutable
Version: 2
Contents: iota::coin::TreasuryCap<test::regulated_coin::REGULATED_COIN> {id: iota::object::UID {id: iota::object::ID {bytes: fake(1,4)}}, total_supply: iota::balance::Supply<test::regulated_coin::REGULATED_COIN> {value: 10000u64}}

task 7 'view-object'. lines 47-49:
1,5::regulated_coin

task 8 'run'. lines 50-52:
Error: Transaction Effects Status: Invalid command argument at 0. Immutable objects cannot be passed by mutable reference, &mut.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: InvalidObjectByMutRef }, source: None, command: Some(0) } }

task 9 'run'. lines 53-55:
Error: Transaction Effects Status: Invalid command argument at 1. Immutable objects cannot be passed by mutable reference, &mut.
Debug of error: CommandArgumentError { arg_idx: 1, kind: InvalidObjectByMutRef } at command Some(0)

task 10 'transfer-object'. lines 56-58:
Error: INVALID TEST. Unknown object, object(8,0)

task 11 'run'. lines 59-61:
Error: INVALID TEST. Unknown object, object(8,0)

task 12 'run'. lines 62-64:
Error: Transaction Effects Status: Invalid command argument at 1. Immutable objects cannot be passed by mutable reference, &mut.
Debug of error: CommandArgumentError { arg_idx: 1, kind: InvalidObjectByMutRef } at command Some(0)

task 13 'transfer-object'. lines 65-65:
Error: INVALID TEST. Unknown object, object(8,0)
