processed 4 tasks

init:
A: object(0,0)

task 1, lines 7-34:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 15618000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 36:
//# create-checkpoint
Checkpoint created: 1

task 3, lines 38-86:
//# run-graphql
Response: {
  "data": {
    "iotaCoins": {
      "edges": [
        {
          "cursor": "IB0/qkQzMX2AxpPurkhHoUma4VW5VOspMYccsPSRHNHvAQAAAAAAAAA=",
          "node": {
            "coinBalance": "299999983382000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
              }
            }
          }
        },
        {
          "cursor": "IHOSqmieO2R6ihgrpQdDhTcPhdO2AcQGExoFs96exsLDAQAAAAAAAAA=",
          "node": {
            "coinBalance": "300000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
              }
            }
          }
        },
        {
          "cursor": "IMY5je+p7h8C1fguAS9nYVZbcDcHIQbm3Jnx/rQBLz51AQAAAAAAAAA=",
          "node": {
            "coinBalance": "30000000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
              }
            }
          }
        }
      ]
    },
    "fakeCoins": {
      "edges": [
        {
          "cursor": "ILd2RJLgdtiYBFgjwDyuq3o7Z+tii5/oR4Y5vQOm8QT4AQAAAAAAAAA=",
          "node": {
            "coinBalance": "3",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x9cb8c8840a91bca3ed02497c7167370b24d586d0af48f4d34766d46012856574::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "IMDMCeR+pUOk5zmRomgOL6qB0T59SeEDA4XXRR7aYQlWAQAAAAAAAAA=",
          "node": {
            "coinBalance": "2",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x9cb8c8840a91bca3ed02497c7167370b24d586d0af48f4d34766d46012856574::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "IM3U2nyGhel4LbwDU9H48DXL4/HhQlYbXL7bLAYcIVEbAQAAAAAAAAA=",
          "node": {
            "coinBalance": "1",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x9cb8c8840a91bca3ed02497c7167370b24d586d0af48f4d34766d46012856574::fake::FAKE>"
              }
            }
          }
        }
      ]
    },
    "address": {
      "coins": {
        "edges": [
          {
            "cursor": "IB0/qkQzMX2AxpPurkhHoUma4VW5VOspMYccsPSRHNHvAQAAAAAAAAA=",
            "node": {
              "coinBalance": "299999983382000",
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                }
              }
            }
          }
        ]
      },
      "allBalances": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjppb3RhOjpJT1RBIiwiYyI6MX0",
            "node": {
              "coinType": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
              },
              "coinObjectCount": 1,
              "totalBalance": "299999983382000"
            }
          },
          {
            "cursor": "eyJ0IjoiMHg5Y2I4Yzg4NDBhOTFiY2EzZWQwMjQ5N2M3MTY3MzcwYjI0ZDU4NmQwYWY0OGY0ZDM0NzY2ZDQ2MDEyODU2NTc0OjpmYWtlOjpGQUtFIiwiYyI6MX0",
            "node": {
              "coinType": {
                "repr": "0x9cb8c8840a91bca3ed02497c7167370b24d586d0af48f4d34766d46012856574::fake::FAKE"
              },
              "coinObjectCount": 3,
              "totalBalance": "6"
            }
          }
        ]
      },
      "firstBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjppb3RhOjpJT1RBIiwiYyI6MX0"
          }
        ]
      },
      "lastBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHg5Y2I4Yzg4NDBhOTFiY2EzZWQwMjQ5N2M3MTY3MzcwYjI0ZDU4NmQwYWY0OGY0ZDM0NzY2ZDQ2MDEyODU2NTc0OjpmYWtlOjpGQUtFIiwiYyI6MX0"
          }
        ]
      }
    }
  }
}
