processed 4 tasks

init:
A: object(0,0)

task 1, lines 7-34:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 15618000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 36:
//# create-checkpoint
Checkpoint created: 1

task 3, lines 38-86:
//# run-graphql
Response: {
  "data": {
    "iotaCoins": {
      "edges": [
        {
          "cursor": "IEXvSXvT/hOb0qlwwa/HxLDkzqli7t2EjLLP9Y1niYjHAQAAAAAAAAA=",
          "node": {
            "coinBalance": "300000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
              }
            }
          }
        },
        {
          "cursor": "IILIjQW/1QuKy7P2EpDR6uwjNNGigCUJ49EjW02peyPxAQAAAAAAAAA=",
          "node": {
            "coinBalance": "30000000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
              }
            }
          }
        },
        {
          "cursor": "IJIVAZcNXGC3IXZ48ZeGOHajJTv4YDv4lsFEqh0N+jj8AQAAAAAAAAA=",
          "node": {
            "coinBalance": "299999983382000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
              }
            }
          }
        }
      ]
    },
    "fakeCoins": {
      "edges": [
        {
          "cursor": "IHKO75J8YCqmNZ67aqkJHyLNKCQucJNTSjDEqwCO9N8xAQAAAAAAAAA=",
          "node": {
            "coinBalance": "2",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x82d0c29f1a7108b4a4f2e2c49592c67ee05fbade3568e274a88d0612d0e59ee7::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "IJlWYVFwa/vVCUmDMeYyY1X1Donl9e47jNPtuUp7wsHUAQAAAAAAAAA=",
          "node": {
            "coinBalance": "3",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x82d0c29f1a7108b4a4f2e2c49592c67ee05fbade3568e274a88d0612d0e59ee7::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "IL5JK31UHMXzSFKK4Q7qbL9rO1Gx5xlMnq3S7G353NpyAQAAAAAAAAA=",
          "node": {
            "coinBalance": "1",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x82d0c29f1a7108b4a4f2e2c49592c67ee05fbade3568e274a88d0612d0e59ee7::fake::FAKE>"
              }
            }
          }
        }
      ]
    },
    "address": {
      "coins": {
        "edges": [
          {
            "cursor": "IJIVAZcNXGC3IXZ48ZeGOHajJTv4YDv4lsFEqh0N+jj8AQAAAAAAAAA=",
            "node": {
              "coinBalance": "299999983382000",
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                }
              }
            }
          }
        ]
      },
      "allBalances": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjppb3RhOjpJT1RBIiwiYyI6MX0",
            "node": {
              "coinType": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
              },
              "coinObjectCount": 1,
              "totalBalance": "299999983382000"
            }
          },
          {
            "cursor": "eyJ0IjoiMHg4MmQwYzI5ZjFhNzEwOGI0YTRmMmUyYzQ5NTkyYzY3ZWUwNWZiYWRlMzU2OGUyNzRhODhkMDYxMmQwZTU5ZWU3OjpmYWtlOjpGQUtFIiwiYyI6MX0",
            "node": {
              "coinType": {
                "repr": "0x82d0c29f1a7108b4a4f2e2c49592c67ee05fbade3568e274a88d0612d0e59ee7::fake::FAKE"
              },
              "coinObjectCount": 3,
              "totalBalance": "6"
            }
          }
        ]
      },
      "firstBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjppb3RhOjpJT1RBIiwiYyI6MX0"
          }
        ]
      },
      "lastBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHg4MmQwYzI5ZjFhNzEwOGI0YTRmMmUyYzQ5NTkyYzY3ZWUwNWZiYWRlMzU2OGUyNzRhODhkMDYxMmQwZTU5ZWU3OjpmYWtlOjpGQUtFIiwiYyI6MX0"
          }
        ]
      }
    }
  }
}
