processed 5 tasks

init:
A: object(0,0)

task 1, lines 7-40:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 7615200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 42-44:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2895600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 3, line 46:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 48-69:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  69,
                                  239,
                                  73,
                                  123,
                                  211,
                                  254,
                                  19,
                                  155,
                                  210,
                                  169,
                                  112,
                                  193,
                                  175,
                                  199,
                                  196,
                                  176,
                                  228,
                                  206,
                                  169,
                                  98,
                                  238,
                                  221,
                                  132,
                                  140,
                                  178,
                                  207,
                                  245,
                                  141,
                                  103,
                                  137,
                                  136,
                                  199
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999988469600"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x45ef497bd3fe139bd2a970c1afc7c4b0e4cea962eedd848cb2cff58d678988c7",
                          "balance": {
                            "value": "299999988469600"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xf880fc9dfdeb4326feb85982ce29f0281304c77904e68a9fe9c0ad31143f1a83::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  221,
                                  78,
                                  131,
                                  83,
                                  102,
                                  226,
                                  63,
                                  60,
                                  227,
                                  30,
                                  193,
                                  79,
                                  253,
                                  170,
                                  47,
                                  146,
                                  187,
                                  124,
                                  64,
                                  94,
                                  160,
                                  32,
                                  174,
                                  41,
                                  80,
                                  8,
                                  154,
                                  227,
                                  13,
                                  92,
                                  14,
                                  212
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  221,
                                  78,
                                  131,
                                  83,
                                  102,
                                  226,
                                  63,
                                  60,
                                  227,
                                  30,
                                  193,
                                  79,
                                  253,
                                  170,
                                  47,
                                  146,
                                  187,
                                  124,
                                  64,
                                  94,
                                  160,
                                  32,
                                  174,
                                  41,
                                  80,
                                  8,
                                  154,
                                  227,
                                  13,
                                  92,
                                  14,
                                  212
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      221,
                                      78,
                                      131,
                                      83,
                                      102,
                                      226,
                                      63,
                                      60,
                                      227,
                                      30,
                                      193,
                                      79,
                                      253,
                                      170,
                                      47,
                                      146,
                                      187,
                                      124,
                                      64,
                                      94,
                                      160,
                                      32,
                                      174,
                                      41,
                                      80,
                                      8,
                                      154,
                                      227,
                                      13,
                                      92,
                                      14,
                                      212
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0xdd4e835366e23f3ce31ec14ffdaa2f92bb7c405ea020ae2950089ae30d5c0ed4",
                          "f0": "0xdd4e835366e23f3ce31ec14ffdaa2f92bb7c405ea020ae2950089ae30d5c0ed4",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0xdd4e835366e23f3ce31ec14ffdaa2f92bb7c405ea020ae2950089ae30d5c0ed4"
                          ],
                          "f7": 44
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
