processed 5 tasks

init:
A: object(0,0)

task 1, lines 7-40:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7622800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 42-44:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2910800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 46:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 48-69:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  117,
                                  9,
                                  112,
                                  32,
                                  243,
                                  71,
                                  170,
                                  59,
                                  128,
                                  105,
                                  46,
                                  206,
                                  96,
                                  187,
                                  16,
                                  44,
                                  80,
                                  233,
                                  134,
                                  149,
                                  39,
                                  52,
                                  172,
                                  2,
                                  238,
                                  109,
                                  218,
                                  104,
                                  54,
                                  215,
                                  44,
                                  207
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999988454400"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x75097020f347aa3b80692ece60bb102c50e986952734ac02ee6dda6836d72ccf",
                          "balance": {
                            "value": "299999988454400"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xd16e8ef94f83c572c6ab57588cd10319a28554b099042356c50a07aa725e929e::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  229,
                                  65,
                                  205,
                                  255,
                                  151,
                                  145,
                                  230,
                                  16,
                                  137,
                                  157,
                                  79,
                                  193,
                                  138,
                                  135,
                                  199,
                                  217,
                                  72,
                                  200,
                                  247,
                                  180,
                                  5,
                                  232,
                                  137,
                                  207,
                                  136,
                                  209,
                                  58,
                                  80,
                                  155,
                                  82,
                                  59,
                                  216
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  229,
                                  65,
                                  205,
                                  255,
                                  151,
                                  145,
                                  230,
                                  16,
                                  137,
                                  157,
                                  79,
                                  193,
                                  138,
                                  135,
                                  199,
                                  217,
                                  72,
                                  200,
                                  247,
                                  180,
                                  5,
                                  232,
                                  137,
                                  207,
                                  136,
                                  209,
                                  58,
                                  80,
                                  155,
                                  82,
                                  59,
                                  216
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      229,
                                      65,
                                      205,
                                      255,
                                      151,
                                      145,
                                      230,
                                      16,
                                      137,
                                      157,
                                      79,
                                      193,
                                      138,
                                      135,
                                      199,
                                      217,
                                      72,
                                      200,
                                      247,
                                      180,
                                      5,
                                      232,
                                      137,
                                      207,
                                      136,
                                      209,
                                      58,
                                      80,
                                      155,
                                      82,
                                      59,
                                      216
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0xe541cdff9791e610899d4fc18a87c7d948c8f7b405e889cf88d13a509b523bd8",
                          "f0": "0xe541cdff9791e610899d4fc18a87c7d948c8f7b405e889cf88d13a509b523bd8",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0xe541cdff9791e610899d4fc18a87c7d948c8f7b405e889cf88d13a509b523bd8"
                          ],
                          "f7": 44
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
