processed 5 tasks

init:
A: object(0,0)

task 1, lines 7-40:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7622800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 42-44:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2910800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 46:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 48-69:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x3d9ad79500d8da785bc76519a8a47bcaafc9e636c383e72ea01367fc31b6ab25::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  27,
                                  172,
                                  27,
                                  185,
                                  200,
                                  82,
                                  28,
                                  114,
                                  9,
                                  43,
                                  119,
                                  196,
                                  36,
                                  123,
                                  252,
                                  51,
                                  64,
                                  214,
                                  41,
                                  164,
                                  88,
                                  229,
                                  236,
                                  152,
                                  217,
                                  42,
                                  0,
                                  226,
                                  11,
                                  193,
                                  179,
                                  49
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  27,
                                  172,
                                  27,
                                  185,
                                  200,
                                  82,
                                  28,
                                  114,
                                  9,
                                  43,
                                  119,
                                  196,
                                  36,
                                  123,
                                  252,
                                  51,
                                  64,
                                  214,
                                  41,
                                  164,
                                  88,
                                  229,
                                  236,
                                  152,
                                  217,
                                  42,
                                  0,
                                  226,
                                  11,
                                  193,
                                  179,
                                  49
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      27,
                                      172,
                                      27,
                                      185,
                                      200,
                                      82,
                                      28,
                                      114,
                                      9,
                                      43,
                                      119,
                                      196,
                                      36,
                                      123,
                                      252,
                                      51,
                                      64,
                                      214,
                                      41,
                                      164,
                                      88,
                                      229,
                                      236,
                                      152,
                                      217,
                                      42,
                                      0,
                                      226,
                                      11,
                                      193,
                                      179,
                                      49
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x1bac1bb9c8521c72092b77c4247bfc3340d629a458e5ec98d92a00e20bc1b331",
                          "f0": "0x1bac1bb9c8521c72092b77c4247bfc3340d629a458e5ec98d92a00e20bc1b331",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0x1bac1bb9c8521c72092b77c4247bfc3340d629a458e5ec98d92a00e20bc1b331"
                          ],
                          "f7": 44
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  71,
                                  149,
                                  48,
                                  107,
                                  2,
                                  103,
                                  65,
                                  70,
                                  22,
                                  98,
                                  230,
                                  214,
                                  17,
                                  63,
                                  25,
                                  137,
                                  195,
                                  97,
                                  188,
                                  130,
                                  255,
                                  251,
                                  232,
                                  132,
                                  101,
                                  239,
                                  204,
                                  236,
                                  120,
                                  86,
                                  146,
                                  242
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999988454400"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x4795306b026741461662e6d6113f1989c361bc82fffbe88465efccec785692f2",
                          "balance": {
                            "value": "299999988454400"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
