processed 5 tasks

init:
A: object(0,0)

task 1, lines 7-55:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 10495600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 57-59:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3017200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 61:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 63-84:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x3709011389175c6e47609a2bd2af774b3b01ffbec237e5de649c88c2ea17a210::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  230,
                                  182,
                                  247,
                                  146,
                                  195,
                                  91,
                                  239,
                                  4,
                                  18,
                                  16,
                                  182,
                                  77,
                                  152,
                                  48,
                                  225,
                                  187,
                                  23,
                                  129,
                                  148,
                                  110,
                                  207,
                                  107,
                                  82,
                                  226,
                                  165,
                                  115,
                                  23,
                                  47,
                                  97,
                                  40,
                                  130,
                                  40
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  230,
                                  182,
                                  247,
                                  146,
                                  195,
                                  91,
                                  239,
                                  4,
                                  18,
                                  16,
                                  182,
                                  77,
                                  152,
                                  48,
                                  225,
                                  187,
                                  23,
                                  129,
                                  148,
                                  110,
                                  207,
                                  107,
                                  82,
                                  226,
                                  165,
                                  115,
                                  23,
                                  47,
                                  97,
                                  40,
                                  130,
                                  40
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      230,
                                      182,
                                      247,
                                      146,
                                      195,
                                      91,
                                      239,
                                      4,
                                      18,
                                      16,
                                      182,
                                      77,
                                      152,
                                      48,
                                      225,
                                      187,
                                      23,
                                      129,
                                      148,
                                      110,
                                      207,
                                      107,
                                      82,
                                      226,
                                      165,
                                      115,
                                      23,
                                      47,
                                      97,
                                      40,
                                      130,
                                      40
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            },
                            {
                              "name": "f8",
                              "value": {
                                "Variant": {
                                  "name": "A",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f9",
                              "value": {
                                "Variant": {
                                  "name": "B",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f10",
                              "value": {
                                "Variant": {
                                  "name": "C",
                                  "fields": [
                                    {
                                      "name": "pos0",
                                      "value": {
                                        "Number": "45"
                                      }
                                    }
                                  ]
                                }
                              }
                            },
                            {
                              "name": "f11",
                              "value": {
                                "Variant": {
                                  "name": "D",
                                  "fields": [
                                    {
                                      "name": "x",
                                      "value": {
                                        "Number": "46"
                                      }
                                    }
                                  ]
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0xe6b6f792c35bef041210b64d9830e1bb1781946ecf6b52e2a573172f61288228",
                          "f0": "0xe6b6f792c35bef041210b64d9830e1bb1781946ecf6b52e2a573172f61288228",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0xe6b6f792c35bef041210b64d9830e1bb1781946ecf6b52e2a573172f61288228"
                          ],
                          "f7": 44,
                          "f8": {
                            "A": {}
                          },
                          "f9": {
                            "B": {}
                          },
                          "f10": {
                            "C": {
                              "pos0": 45
                            }
                          },
                          "f11": {
                            "D": {
                              "x": "46"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  233,
                                  32,
                                  87,
                                  170,
                                  254,
                                  195,
                                  251,
                                  17,
                                  247,
                                  239,
                                  22,
                                  29,
                                  112,
                                  192,
                                  55,
                                  73,
                                  30,
                                  73,
                                  23,
                                  242,
                                  58,
                                  132,
                                  82,
                                  121,
                                  230,
                                  132,
                                  104,
                                  17,
                                  45,
                                  159,
                                  176,
                                  10
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999995982800"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0xe92057aafec3fb11f7ef161d70c037491e4917f23a845279e68468112d9fb00a",
                          "balance": {
                            "value": "299999995982800"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
