processed 5 tasks

init:
A: object(0,0)

task 1, lines 7-55:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 10510800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 57-59:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3032400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 61:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 63-84:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x9f246a2e7de3e176ab2bd7475e5cadf556ecd06b4ef381f1c82bcc9203316a17::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  95,
                                  172,
                                  221,
                                  100,
                                  149,
                                  13,
                                  177,
                                  80,
                                  49,
                                  99,
                                  228,
                                  15,
                                  218,
                                  16,
                                  225,
                                  55,
                                  223,
                                  17,
                                  214,
                                  92,
                                  114,
                                  204,
                                  250,
                                  0,
                                  168,
                                  246,
                                  60,
                                  141,
                                  182,
                                  142,
                                  55,
                                  161
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  95,
                                  172,
                                  221,
                                  100,
                                  149,
                                  13,
                                  177,
                                  80,
                                  49,
                                  99,
                                  228,
                                  15,
                                  218,
                                  16,
                                  225,
                                  55,
                                  223,
                                  17,
                                  214,
                                  92,
                                  114,
                                  204,
                                  250,
                                  0,
                                  168,
                                  246,
                                  60,
                                  141,
                                  182,
                                  142,
                                  55,
                                  161
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      95,
                                      172,
                                      221,
                                      100,
                                      149,
                                      13,
                                      177,
                                      80,
                                      49,
                                      99,
                                      228,
                                      15,
                                      218,
                                      16,
                                      225,
                                      55,
                                      223,
                                      17,
                                      214,
                                      92,
                                      114,
                                      204,
                                      250,
                                      0,
                                      168,
                                      246,
                                      60,
                                      141,
                                      182,
                                      142,
                                      55,
                                      161
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            },
                            {
                              "name": "f8",
                              "value": {
                                "Variant": {
                                  "name": "A",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f9",
                              "value": {
                                "Variant": {
                                  "name": "B",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f10",
                              "value": {
                                "Variant": {
                                  "name": "C",
                                  "fields": [
                                    {
                                      "name": "pos0",
                                      "value": {
                                        "Number": "45"
                                      }
                                    }
                                  ]
                                }
                              }
                            },
                            {
                              "name": "f11",
                              "value": {
                                "Variant": {
                                  "name": "D",
                                  "fields": [
                                    {
                                      "name": "x",
                                      "value": {
                                        "Number": "46"
                                      }
                                    }
                                  ]
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x5facdd64950db1503163e40fda10e137df11d65c72ccfa00a8f63c8db68e37a1",
                          "f0": "0x5facdd64950db1503163e40fda10e137df11d65c72ccfa00a8f63c8db68e37a1",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0x5facdd64950db1503163e40fda10e137df11d65c72ccfa00a8f63c8db68e37a1"
                          ],
                          "f7": 44,
                          "f8": {
                            "A": {}
                          },
                          "f9": {
                            "B": {}
                          },
                          "f10": {
                            "C": {
                              "pos0": 45
                            }
                          },
                          "f11": {
                            "D": {
                              "x": "46"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  117,
                                  9,
                                  112,
                                  32,
                                  243,
                                  71,
                                  170,
                                  59,
                                  128,
                                  105,
                                  46,
                                  206,
                                  96,
                                  187,
                                  16,
                                  44,
                                  80,
                                  233,
                                  134,
                                  149,
                                  39,
                                  52,
                                  172,
                                  2,
                                  238,
                                  109,
                                  218,
                                  104,
                                  54,
                                  215,
                                  44,
                                  207
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999995967600"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x75097020f347aa3b80692ece60bb102c50e986952734ac02ee6dda6836d72ccf",
                          "balance": {
                            "value": "299999995967600"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
