processed 5 tasks

init:
A: object(0,0)

task 1, lines 7-55:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 10495600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 57-59:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3017200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 61:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 63-84:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x29f6667cf78fdb44b9c18ddccc621754330ecb72dbbcbdb88a86041232100f30::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  13,
                                  8,
                                  82,
                                  129,
                                  242,
                                  27,
                                  231,
                                  36,
                                  28,
                                  194,
                                  22,
                                  41,
                                  181,
                                  121,
                                  79,
                                  27,
                                  93,
                                  247,
                                  233,
                                  190,
                                  202,
                                  228,
                                  244,
                                  153,
                                  25,
                                  107,
                                  75,
                                  194,
                                  131,
                                  106,
                                  215,
                                  25
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  13,
                                  8,
                                  82,
                                  129,
                                  242,
                                  27,
                                  231,
                                  36,
                                  28,
                                  194,
                                  22,
                                  41,
                                  181,
                                  121,
                                  79,
                                  27,
                                  93,
                                  247,
                                  233,
                                  190,
                                  202,
                                  228,
                                  244,
                                  153,
                                  25,
                                  107,
                                  75,
                                  194,
                                  131,
                                  106,
                                  215,
                                  25
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      13,
                                      8,
                                      82,
                                      129,
                                      242,
                                      27,
                                      231,
                                      36,
                                      28,
                                      194,
                                      22,
                                      41,
                                      181,
                                      121,
                                      79,
                                      27,
                                      93,
                                      247,
                                      233,
                                      190,
                                      202,
                                      228,
                                      244,
                                      153,
                                      25,
                                      107,
                                      75,
                                      194,
                                      131,
                                      106,
                                      215,
                                      25
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            },
                            {
                              "name": "f8",
                              "value": {
                                "Variant": {
                                  "name": "A",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f9",
                              "value": {
                                "Variant": {
                                  "name": "B",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f10",
                              "value": {
                                "Variant": {
                                  "name": "C",
                                  "fields": [
                                    {
                                      "name": "pos0",
                                      "value": {
                                        "Number": "45"
                                      }
                                    }
                                  ]
                                }
                              }
                            },
                            {
                              "name": "f11",
                              "value": {
                                "Variant": {
                                  "name": "D",
                                  "fields": [
                                    {
                                      "name": "x",
                                      "value": {
                                        "Number": "46"
                                      }
                                    }
                                  ]
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x0d085281f21be7241cc21629b5794f1b5df7e9becae4f499196b4bc2836ad719",
                          "f0": "0x0d085281f21be7241cc21629b5794f1b5df7e9becae4f499196b4bc2836ad719",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0x0d085281f21be7241cc21629b5794f1b5df7e9becae4f499196b4bc2836ad719"
                          ],
                          "f7": 44,
                          "f8": {
                            "A": {}
                          },
                          "f9": {
                            "B": {}
                          },
                          "f10": {
                            "C": {
                              "pos0": 45
                            }
                          },
                          "f11": {
                            "D": {
                              "x": "46"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  69,
                                  239,
                                  73,
                                  123,
                                  211,
                                  254,
                                  19,
                                  155,
                                  210,
                                  169,
                                  112,
                                  193,
                                  175,
                                  199,
                                  196,
                                  176,
                                  228,
                                  206,
                                  169,
                                  98,
                                  238,
                                  221,
                                  132,
                                  140,
                                  178,
                                  207,
                                  245,
                                  141,
                                  103,
                                  137,
                                  136,
                                  199
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999995982800"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x45ef497bd3fe139bd2a970c1afc7c4b0e4cea962eedd848cb2cff58d678988c7",
                          "balance": {
                            "value": "299999995982800"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
