processed 15 tasks

task 1, lines 7-20:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 5168000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 22-23:
//# run Test::M1::create --args 0 @A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 3, lines 25-26:
//# run Test::M1::create --args 1 @A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 4, lines 28-29:
//# run Test::M1::create --args 2 @A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 5, lines 31-32:
//# run Test::M1::create --args 3 @A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 6, lines 34-35:
//# run Test::M1::create --args 4 @A
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 7, line 37:
//# create-checkpoint
Checkpoint created: 1

task 8, lines 39-49:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "ICQ6bamiuRtEADjFXR+Q3zjniPY13gU7qp82fjffChPJAQAAAAAAAAA="
          },
          {
            "cursor": "ILBkiKFGvai64r9P92Exc6/OV73R/Cx24suo9vUQVhLLAQAAAAAAAAA="
          },
          {
            "cursor": "ILx1LJJHKQz7Yrn6su00tX4c31UI0tNs4/JHW2JCj7BnAQAAAAAAAAA="
          },
          {
            "cursor": "INzg4kDmBWuSiyWp3fx1Axd/EKhE5WZoJsHFMF0oxFt6AQAAAAAAAAA="
          },
          {
            "cursor": "IN4IiUzFMjHgEF0efQi1WmokhSvEYJqh85gaPPqLMQEZAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 9, lines 51-61:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "ICQ6bamiuRtEADjFXR+Q3zjniPY13gU7qp82fjffChPJAQAAAAAAAAA="
          },
          {
            "cursor": "ILBkiKFGvai64r9P92Exc6/OV73R/Cx24suo9vUQVhLLAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 10, lines 63-92:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "ICQ6bamiuRtEADjFXR+Q3zjniPY13gU7qp82fjffChPJAQAAAAAAAAA=",
            "node": {
              "address": "0x243a6da9a2b91b440038c55d1f90df38e788f635de053baa9f367e37df0a13c9"
            }
          },
          {
            "cursor": "ILBkiKFGvai64r9P92Exc6/OV73R/Cx24suo9vUQVhLLAQAAAAAAAAA=",
            "node": {
              "address": "0xb06488a146bda8bae2bf4ff7613173afce57bdd1fc2c76e2cba8f6f5105612cb"
            }
          },
          {
            "cursor": "ILx1LJJHKQz7Yrn6su00tX4c31UI0tNs4/JHW2JCj7BnAQAAAAAAAAA=",
            "node": {
              "address": "0xbc752c9247290cfb62b9fab2ed34b57e1cdf5508d2d36ce3f2475b62428fb067"
            }
          },
          {
            "cursor": "INzg4kDmBWuSiyWp3fx1Axd/EKhE5WZoJsHFMF0oxFt6AQAAAAAAAAA=",
            "node": {
              "address": "0xdce0e240e6056b928b25a9ddfc7503177f10a844e5666826c1c5305d28c45b7a"
            }
          },
          {
            "cursor": "IN4IiUzFMjHgEF0efQi1WmokhSvEYJqh85gaPPqLMQEZAQAAAAAAAAA=",
            "node": {
              "address": "0xde08894cc53231e0105d1e7d08b55a6a24852bc4609aa1f3981a3cfa8b310119"
            }
          }
        ]
      }
    },
    "obj_3_0": {
      "address": "0xde08894cc53231e0105d1e7d08b55a6a24852bc4609aa1f3981a3cfa8b310119"
    },
    "obj_5_0": {
      "address": "0x243a6da9a2b91b440038c55d1f90df38e788f635de053baa9f367e37df0a13c9"
    },
    "obj_6_0": {
      "address": "0xb06488a146bda8bae2bf4ff7613173afce57bdd1fc2c76e2cba8f6f5105612cb"
    },
    "obj_4_0": {
      "address": "0xbc752c9247290cfb62b9fab2ed34b57e1cdf5508d2d36ce3f2475b62428fb067"
    },
    "obj_2_0": {
      "address": "0xdce0e240e6056b928b25a9ddfc7503177f10a844e5666826c1c5305d28c45b7a"
    }
  }
}

task 11, lines 94-106:
//# run-graphql --cursors @{obj_5_0}
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "ILBkiKFGvai64r9P92Exc6/OV73R/Cx24suo9vUQVhLLAQAAAAAAAAA="
          },
          {
            "cursor": "ILx1LJJHKQz7Yrn6su00tX4c31UI0tNs4/JHW2JCj7BnAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 12, lines 108-118:
//# run-graphql --cursors @{obj_4_0}
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "INzg4kDmBWuSiyWp3fx1Axd/EKhE5WZoJsHFMF0oxFt6AQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 13, lines 120-130:
//# run-graphql --cursors @{obj_3_0}
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "ILx1LJJHKQz7Yrn6su00tX4c31UI0tNs4/JHW2JCj7BnAQAAAAAAAAA="
          },
          {
            "cursor": "INzg4kDmBWuSiyWp3fx1Axd/EKhE5WZoJsHFMF0oxFt6AQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 14, lines 132-144:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "INzg4kDmBWuSiyWp3fx1Axd/EKhE5WZoJsHFMF0oxFt6AQAAAAAAAAA=",
            "node": {
              "address": "0xdce0e240e6056b928b25a9ddfc7503177f10a844e5666826c1c5305d28c45b7a"
            }
          },
          {
            "cursor": "IN4IiUzFMjHgEF0efQi1WmokhSvEYJqh85gaPPqLMQEZAQAAAAAAAAA=",
            "node": {
              "address": "0xde08894cc53231e0105d1e7d08b55a6a24852bc4609aa1f3981a3cfa8b310119"
            }
          }
        ]
      }
    }
  }
}
