processed 15 tasks

task 1, lines 7-20:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 22-23:
//# run Test::M1::create --args 0 @A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, lines 25-26:
//# run Test::M1::create --args 1 @A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, lines 28-29:
//# run Test::M1::create --args 2 @A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 5, lines 31-32:
//# run Test::M1::create --args 3 @A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 6, lines 34-35:
//# run Test::M1::create --args 4 @A
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 7, line 37:
//# create-checkpoint
Checkpoint created: 1

task 8, lines 39-49:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IB6Y7SuOAn63q7oVsnfAsAkgLbfWPw5sH1Aas5+G6zUQAQAAAAAAAAA="
          },
          {
            "cursor": "ICJdqAl2L/vRwtY9nEE7oZM/RoQuZlYmDuQfJ9aJ2i68AQAAAAAAAAA="
          },
          {
            "cursor": "IH+kls8hxUu3dLRhr5dWydyXoA1r6TD7iZCTTwLB0AOFAQAAAAAAAAA="
          },
          {
            "cursor": "IJfmMk6Jnbl/JBrhchsmgc/mZe6CPznQPgyglNeWb8iFAQAAAAAAAAA="
          },
          {
            "cursor": "IKHdHaSQSuyldAptEPZW17vgxINsDqj3BxUmsKveY5IUAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 9, lines 51-61:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IB6Y7SuOAn63q7oVsnfAsAkgLbfWPw5sH1Aas5+G6zUQAQAAAAAAAAA="
          },
          {
            "cursor": "ICJdqAl2L/vRwtY9nEE7oZM/RoQuZlYmDuQfJ9aJ2i68AQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 10, lines 63-92:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IB6Y7SuOAn63q7oVsnfAsAkgLbfWPw5sH1Aas5+G6zUQAQAAAAAAAAA=",
            "node": {
              "address": "0x1e98ed2b8e027eb7abba15b277c0b009202db7d63f0e6c1f501ab39f86eb3510"
            }
          },
          {
            "cursor": "ICJdqAl2L/vRwtY9nEE7oZM/RoQuZlYmDuQfJ9aJ2i68AQAAAAAAAAA=",
            "node": {
              "address": "0x225da809762ffbd1c2d63d9c413ba1933f46842e6656260ee41f27d689da2ebc"
            }
          },
          {
            "cursor": "IH+kls8hxUu3dLRhr5dWydyXoA1r6TD7iZCTTwLB0AOFAQAAAAAAAAA=",
            "node": {
              "address": "0x7fa496cf21c54bb774b461af9756c9dc97a00d6be930fb8990934f02c1d00385"
            }
          },
          {
            "cursor": "IJfmMk6Jnbl/JBrhchsmgc/mZe6CPznQPgyglNeWb8iFAQAAAAAAAAA=",
            "node": {
              "address": "0x97e6324e899db97f241ae1721b2681cfe665ee823f39d03e0ca094d7966fc885"
            }
          },
          {
            "cursor": "IKHdHaSQSuyldAptEPZW17vgxINsDqj3BxUmsKveY5IUAQAAAAAAAAA=",
            "node": {
              "address": "0xa1dd1da4904aeca5740a6d10f656d7bbe0c4836c0ea8f7071526b0abde639214"
            }
          }
        ]
      }
    },
    "obj_3_0": {
      "address": "0xa1dd1da4904aeca5740a6d10f656d7bbe0c4836c0ea8f7071526b0abde639214"
    },
    "obj_5_0": {
      "address": "0x1e98ed2b8e027eb7abba15b277c0b009202db7d63f0e6c1f501ab39f86eb3510"
    },
    "obj_6_0": {
      "address": "0x7fa496cf21c54bb774b461af9756c9dc97a00d6be930fb8990934f02c1d00385"
    },
    "obj_4_0": {
      "address": "0x225da809762ffbd1c2d63d9c413ba1933f46842e6656260ee41f27d689da2ebc"
    },
    "obj_2_0": {
      "address": "0x97e6324e899db97f241ae1721b2681cfe665ee823f39d03e0ca094d7966fc885"
    }
  }
}

task 11, lines 94-106:
//# run-graphql --cursors @{obj_5_0}
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "ICJdqAl2L/vRwtY9nEE7oZM/RoQuZlYmDuQfJ9aJ2i68AQAAAAAAAAA="
          },
          {
            "cursor": "IH+kls8hxUu3dLRhr5dWydyXoA1r6TD7iZCTTwLB0AOFAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 12, lines 108-118:
//# run-graphql --cursors @{obj_4_0}
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IH+kls8hxUu3dLRhr5dWydyXoA1r6TD7iZCTTwLB0AOFAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 13, lines 120-130:
//# run-graphql --cursors @{obj_3_0}
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IH+kls8hxUu3dLRhr5dWydyXoA1r6TD7iZCTTwLB0AOFAQAAAAAAAAA="
          },
          {
            "cursor": "IJfmMk6Jnbl/JBrhchsmgc/mZe6CPznQPgyglNeWb8iFAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 14, lines 132-144:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IJfmMk6Jnbl/JBrhchsmgc/mZe6CPznQPgyglNeWb8iFAQAAAAAAAAA=",
            "node": {
              "address": "0x97e6324e899db97f241ae1721b2681cfe665ee823f39d03e0ca094d7966fc885"
            }
          },
          {
            "cursor": "IKHdHaSQSuyldAptEPZW17vgxINsDqj3BxUmsKveY5IUAQAAAAAAAAA=",
            "node": {
              "address": "0xa1dd1da4904aeca5740a6d10f656d7bbe0c4836c0ea8f7071526b0abde639214"
            }
          }
        ]
      }
    }
  }
}
