processed 15 tasks

task 1, lines 7-20:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 5168000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 22-23:
//# run Test::M1::create --args 0 @A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 3, lines 25-26:
//# run Test::M1::create --args 1 @A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 4, lines 28-29:
//# run Test::M1::create --args 2 @A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 5, lines 31-32:
//# run Test::M1::create --args 3 @A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 6, lines 34-35:
//# run Test::M1::create --args 4 @A
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 7, line 37:
//# create-checkpoint
Checkpoint created: 1

task 8, lines 39-49:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IBqMtOZAUnSpu9I5B9Lh7T2w/ciMiYku88mHKmPITv7NAQAAAAAAAAA="
          },
          {
            "cursor": "IKnVWZdy/wqKop9LnP6YugCz2St7sqrsQNgrI2+b0WbxAQAAAAAAAAA="
          },
          {
            "cursor": "IL/MdxPh4oeOdTS7gAIEV//bIxrw5IAk8E1Ob6NAgCZWAQAAAAAAAAA="
          },
          {
            "cursor": "IMcBUoV5yhFf+U11znlcMsZrcU3ofsYqQgtmqFrL9iegAQAAAAAAAAA="
          },
          {
            "cursor": "IP/+NRbI7vHQJVGOajHdwbC6zw162A/dXMleZsEUg8niAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 9, lines 51-61:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IBqMtOZAUnSpu9I5B9Lh7T2w/ciMiYku88mHKmPITv7NAQAAAAAAAAA="
          },
          {
            "cursor": "IKnVWZdy/wqKop9LnP6YugCz2St7sqrsQNgrI2+b0WbxAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 10, lines 63-92:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IBqMtOZAUnSpu9I5B9Lh7T2w/ciMiYku88mHKmPITv7NAQAAAAAAAAA=",
            "node": {
              "address": "0x1a8cb4e6405274a9bbd23907d2e1ed3db0fdc88c89892ef3c9872a63c84efecd"
            }
          },
          {
            "cursor": "IKnVWZdy/wqKop9LnP6YugCz2St7sqrsQNgrI2+b0WbxAQAAAAAAAAA=",
            "node": {
              "address": "0xa9d5599772ff0a8aa29f4b9cfe98ba00b3d92b7bb2aaec40d82b236f9bd166f1"
            }
          },
          {
            "cursor": "IL/MdxPh4oeOdTS7gAIEV//bIxrw5IAk8E1Ob6NAgCZWAQAAAAAAAAA=",
            "node": {
              "address": "0xbfcc7713e1e2878e7534bb80020457ffdb231af0e48024f04d4e6fa340802656"
            }
          },
          {
            "cursor": "IMcBUoV5yhFf+U11znlcMsZrcU3ofsYqQgtmqFrL9iegAQAAAAAAAAA=",
            "node": {
              "address": "0xc701528579ca115ff94d75ce795c32c66b714de87ec62a420b66a85acbf627a0"
            }
          },
          {
            "cursor": "IP/+NRbI7vHQJVGOajHdwbC6zw162A/dXMleZsEUg8niAQAAAAAAAAA=",
            "node": {
              "address": "0xfffe3516c8eef1d025518e6a31ddc1b0bacf0d7ad80fdd5cc95e66c11483c9e2"
            }
          }
        ]
      }
    },
    "obj_3_0": {
      "address": "0xc701528579ca115ff94d75ce795c32c66b714de87ec62a420b66a85acbf627a0"
    },
    "obj_5_0": {
      "address": "0xbfcc7713e1e2878e7534bb80020457ffdb231af0e48024f04d4e6fa340802656"
    },
    "obj_6_0": {
      "address": "0xa9d5599772ff0a8aa29f4b9cfe98ba00b3d92b7bb2aaec40d82b236f9bd166f1"
    },
    "obj_4_0": {
      "address": "0xfffe3516c8eef1d025518e6a31ddc1b0bacf0d7ad80fdd5cc95e66c11483c9e2"
    },
    "obj_2_0": {
      "address": "0x1a8cb4e6405274a9bbd23907d2e1ed3db0fdc88c89892ef3c9872a63c84efecd"
    }
  }
}

task 11, lines 94-106:
//# run-graphql --cursors @{obj_5_0}
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IMcBUoV5yhFf+U11znlcMsZrcU3ofsYqQgtmqFrL9iegAQAAAAAAAAA="
          },
          {
            "cursor": "IP/+NRbI7vHQJVGOajHdwbC6zw162A/dXMleZsEUg8niAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 12, lines 108-118:
//# run-graphql --cursors @{obj_4_0}
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": []
      }
    }
  }
}

task 13, lines 120-130:
//# run-graphql --cursors @{obj_3_0}
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IKnVWZdy/wqKop9LnP6YugCz2St7sqrsQNgrI2+b0WbxAQAAAAAAAAA="
          },
          {
            "cursor": "IL/MdxPh4oeOdTS7gAIEV//bIxrw5IAk8E1Ob6NAgCZWAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 14, lines 132-144:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IMcBUoV5yhFf+U11znlcMsZrcU3ofsYqQgtmqFrL9iegAQAAAAAAAAA=",
            "node": {
              "address": "0xc701528579ca115ff94d75ce795c32c66b714de87ec62a420b66a85acbf627a0"
            }
          },
          {
            "cursor": "IP/+NRbI7vHQJVGOajHdwbC6zw162A/dXMleZsEUg8niAQAAAAAAAAA=",
            "node": {
              "address": "0xfffe3516c8eef1d025518e6a31ddc1b0bacf0d7ad80fdd5cc95e66c11483c9e2"
            }
          }
        ]
      }
    }
  }
}
