processed 7 tasks

init:
C: object(0,0)

task 1, lines 7-32:
//# run-graphql
Response: {
  "data": {
    "objects": {
      "edges": [
        {
          "cursor": "IPI0OcNJaW2T/ka0ZV/nEY+HDnBLn7WV+GDGo0y6qtVgAAAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedIota": {
                "principal": "1500000000000000"
              }
            }
          }
        }
      ]
    },
    "address": {
      "stakedIotas": {
        "edges": []
      }
    }
  }
}

task 2, lines 34-36:
//# programmable --sender C --inputs 10000000000 @C
//> SplitCoins(Gas, [Input(0)]);
//> TransferObjects([Result(0)], Input(1))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 1960800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 38:
//# run 0x3::iota_system::request_add_stake --args object(0x5) object(2,0) @validator_0 --sender C
events: Event { package_id: iota_system, transaction_module: Identifier("iota_system"), sender: C, type_: StructTag { address: iota_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [19, 126, 221, 95, 147, 81, 130, 60, 220, 197, 145, 79, 94, 152, 178, 35, 110, 112, 94, 156, 230, 111, 152, 130, 196, 172, 144, 36, 43, 203, 118, 160, 175, 163, 158, 79, 0, 218, 226, 120, 249, 119, 199, 198, 147, 10, 94, 44, 118, 232, 93, 23, 165, 38, 215, 36, 187, 206, 15, 184, 31, 176, 125, 76, 140, 202, 78, 28, 224, 186, 89, 4, 206, 166, 29, 249, 36, 45, 162, 247, 210, 158, 62, 243, 40, 251, 126, 192, 124, 8, 107, 59, 244, 124, 166, 26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0] }
created: object(3,0)
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(2,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 14500800,  storage_rebate: 1960800, non_refundable_storage_fee: 0

task 4, line 40:
//# create-checkpoint
Checkpoint created: 1

task 5, line 42:
//# advance-epoch
Epoch advanced: 0

task 6, lines 44-70:
//# run-graphql
Response: {
  "data": {
    "objects": {
      "edges": [
        {
          "cursor": "IBRoODsinaSa4FR6ECYNlPAg85qVJE3d+HBEkymgWhy5AgAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedIota": {
                "principal": "15340000000000",
                "poolId": "0x137edd5f9351823cdcc5914f5e98b2236e705e9ce66f9882c4ac90242bcb76a0"
              }
            }
          }
        },
        {
          "cursor": "IL1jjmQAhidFpvcA6F2niX0/0s3ffWgzvSKzhsdstBbrAgAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedIota": {
                "principal": "10000000000",
                "poolId": "0x137edd5f9351823cdcc5914f5e98b2236e705e9ce66f9882c4ac90242bcb76a0"
              }
            }
          }
        },
        {
          "cursor": "IPI0OcNJaW2T/ka0ZV/nEY+HDnBLn7WV+GDGo0y6qtVgAgAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedIota": {
                "principal": "1500000000000000",
                "poolId": "0x137edd5f9351823cdcc5914f5e98b2236e705e9ce66f9882c4ac90242bcb76a0"
              }
            }
          }
        }
      ]
    },
    "address": {
      "stakedIotas": {
        "edges": [
          {
            "cursor": "IL1jjmQAhidFpvcA6F2niX0/0s3ffWgzvSKzhsdstBbrAgAAAAAAAAA=",
            "node": {
              "principal": "10000000000"
            }
          }
        ]
      }
    }
  }
}
